import 'package:fifa/values/club_names.dart';
import 'package:fifa/values/league_names.dart';


ClubName _name = ClubName();
LeagueOfficialNames leagueName = LeagueOfficialNames();

Map<String,dynamic> mapAfrica = {

  leagueName.egito : {
    2022.0: [_name.zamalek,_name.pyramids,_name.alahly,_name.future,_name.elgaish,_name.smouha,  ],
    2021.0: [_name.zamalek,_name.alahly,_name.pyramids,_name.smouha,_name.almasry,_name.enppi,   ],
    2020.0: [_name.alahly,_name.zamalek,_name.pyramids,],
    2019.0: [_name.alahly,_name.zamalek,_name.pyramids,],
    2018.0: [_name.alahly,_name.ismaily,_name.almasry,],
    2017.0: [_name.alahly,_name.makkasa,_name.zamalek,],
    2016.0: [_name.alahly,_name.zamalek,_name.smouha,],
    2015.0: [_name.zamalek,_name.alahly,_name.enppi,],
    2014.0: [_name.alahly,_name.smouha,_name.zamalek,],
    2013.0: [],
    2012.0: [],
    2011.0: [_name.alahly,_name.zamalek,_name.ismaily,],
    2010.0: [_name.alahly,_name.zamalek,_name.ismaily,],
    2009.0: [_name.alahly,_name.ismaily,_name.petrojet,],
    2008.0: [_name.alahly,_name.ismaily,_name.zamalek,],
    2007.0: [_name.alahly,_name.zamalek,_name.ismaily,],
    2006.0: [_name.alahly,_name.zamalek,_name.enppi,],
    2005.0: [_name.alahly,_name.enppi,_name.haras,],
    2004.0: [_name.zamalek,_name.alahly,_name.ismaily,],
    2003.0: [_name.zamalek,_name.alahly,_name.ismaily,],
    2002.0: [_name.ismaily,_name.alahly,_name.zamalek,],
    2001.0: [_name.zamalek,_name.alahly,_name.almasry,],
    2000.0: [_name.alahly,_name.ismaily,_name.zamalek,],
    1999.0: [_name.alahly,_name.zamalek,_name.ismaily,],
    1998.0: [_name.alahly,_name.zamalek,_name.almokawloon,],
    1997.0: [_name.alahly,_name.zamalek,_name.elmansoura,],
    1996.0: [_name.alahly,_name.zamalek,_name.ismaily,],
    1995.0: [_name.alahly,_name.zamalek,_name.ismaily,],
    1994.0: [_name.alahly,_name.ismaily,_name.zamalek,],
    1993.0: [_name.zamalek,_name.alahly,_name.ghazl,],
    1992.0: [_name.zamalek,_name.ismaily,_name.ghazl,],
    1991.0: [_name.ismaily,_name.alahly,_name.zamalek,],
    1990.0: [],
    1989.0: [_name.alahly,_name.zamalek,_name.ghazl,],
    1988.0: [_name.zamalek,_name.alahly,_name.ghazl,],
    1987.0: [_name.alahly,_name.zamalek,_name.tersana,],
    1986.0: [_name.alahly,_name.zamalek,_name.ismaily,],
    1985.0: [_name.alahly,_name.zamalek,_name.ismaily,],
    1984.0: [_name.zamalek,_name.alahly,_name.ismaily,],
    1983.0: [_name.almokawloon,_name.zamalek,_name.alahly,],
    1982.0: [_name.alahly,_name.zamalek,_name.alexandria],
    1981.0: [_name.alahly,_name.zamalek,_name.almasry,],
    1980.0: [_name.alahly,_name.zamalek,_name.almasry],
    1979.0: [_name.alahly,_name.zamalek,_name.ghazl,],
    1978.0: [_name.zamalek,_name.alahly,_name.elolympi],
    1977.0: [_name.alahly,_name.zamalek,_name.alexandria,],
    1976.0: [_name.alahly,_name.ghazl,_name.zamalek,],
    1975.0: [_name.alahly,_name.tersana,_name.ismaily,],
    1974.0: [],
    1973.0: [_name.ghazl,_name.zamalek,_name.ismaily,],
    1972.0: [],
    1971.0: [],
    1970.0: [],
    1969.0: [],
    1968.0: [],
    1967.0: [],
    1966.0: [],
    1965.0: [_name.zamalek,_name.ismaily,_name.tersana,],
    1964.0: [_name.zamalek,_name.ternana,_name.ismaily,],
    1963.0: [_name.tersana,_name.zamalek,_name.alahly,],
    1962.0: [_name.alahly,_name.zamalek,_name.tersana,],
    1961.0: [_name.alahly,_name.zamalek,_name.tersana,],
    1960.0: [_name.zamalek,_name.tersana,_name.alahly,],
  },

  leagueName.marrocos : {
    2022.0: [_name.wydad,_name.rajacasablanca,],
    2021.0: [_name.wydad,_name.rajacasablanca,_name.farRabat,_name.renBerkane,_name.moulodiaOujda,  ],
    2020.0: [_name.rajacasablanca,_name.wydad,_name.renBerkane,_name.fusRabat,_name.moulodiaOujda,  ],
    2019.0: [_name.wydad,_name.rajacasablanca,_name.hassaniaAgadir,_name.safi,_name.irTanger,       ],
    2018.0: [_name.irTanger,_name.wydad,_name.hassaniaAgadir,_name.fusRabat,_name.difaa,            ],
    2017.0: [_name.wydad,_name.difaa,_name.rajacasablanca,_name.renBerkane,_name.irTanger,          _name.farRabat,_name.fusRabat,_name.hassaniaAgadir,],
    2016.0: [_name.fusRabat,_name.wydad,_name.irTanger,_name.farRabat,_name.rajacasablanca,         _name.moghrebTetouan,_name.renBerkane,_name.hassaniaAgadir, ],
    2015.0: [_name.wydad,_name.khouribga,_name.kawkab,_name.moghrebTetouan,_name.fusRabat,          _name.hassaniaAgadir,_name.difaa,_name.rajacasablanca,],
    2014.0: [_name.moghrebTetouan,_name.rajacasablanca,_name.fusRabat,_name.kawkab,_name.difaa,     _name.wydad,_name.farRabat,_name.hassaniaAgadir,],
    2013.0: [_name.rajacasablanca,_name.farRabat,_name.maghreb,_name.wydad,_name.moghrebTetouan,    _name.fusRabat,_name.renBerkane,_name.chababRifHoceima,],
    2012.0: [_name.moghrebTetouan,_name.fusRabat,_name.wydad,_name.rajacasablanca,_name.difaa,      _name.maghreb,_name.farRabat,_name.safi,],
    2011.0: [_name.rajacasablanca,_name.maghreb,_name.wydad,_name.khouribga,_name.safi,             _name.farRabat,_name.fusRabat,_name.moghrebTetouan,],
    2010.0: [_name.wydad,_name.rajacasablanca,_name.difaa,_name.kawkab,_name.khouribga,             _name.hassaniaAgadir,_name.farRabat,_name.maghreb,],
    2009.0: [_name.rajacasablanca,_name.difaa,_name.farRabat,_name.wydad,_name.khouribga,           _name.moghrebTetouan,],
    2008.0: [_name.farRabat,_name.khemisset,_name.rajacasablanca,_name.hassaniaAgadir,_name.difaa,  ],
    2007.0: [_name.khouribga,_name.farRabat,_name.moghrebTetouan,_name.wydad,_name.difaa,           _name.kawkab,_name.khemisset,_name.jeunesseMassira,_name.hassaniaAgadir,_name.moulodiaOujda,   _name.rajacasablanca,_name.safi,],
    2006.0: [_name.wydad,_name.farRabat,_name.khouribga,_name.rajacasablanca,_name.hassaniaAgadir,  _name.meknes,_name.difaa,_name.khemisset,_name.sale,_name.safi,                                ],
    2005.0: [_name.farRabat,_name.rajacasablanca,_name.wydad,_name.safi,_name.jeunesseMassira,      _name.khemisset,_name.khouribga,],
    2004.0: [_name.rajacasablanca,_name.farRabat,_name.sale,_name.wydad,_name.khouribga,            _name.meknes,_name.moulodiaOujda,_name.maghreb,_name.hassaniaAgadir,_name.kawkab,              ],
    2003.0: [_name.hassaniaAgadir,_name.rajacasablanca,_name.wydad,_name.meknes,_name.maghreb,      _name.khouribga,_name.chababMohammedia,_name.jeunesseMassira,_name.farRabat,],
    2002.0: [_name.hassaniaAgadir,_name.wydad,_name.rajacasablanca,_name.maghreb,_name.khouribga,   _name.farRabat,],
    2001.0: [_name.rajacasablanca,_name.fusRabat,_name.maghreb,_name.settat,_name.khouribga,        _name.kawkab,_name.wydad,_name.khemisset,],
    2000.0: [_name.rajacasablanca,_name.wydad,],
    1999.0: [_name.rajacasablanca,_name.kawkab,],
    1998.0: [_name.rajacasablanca,_name.kawkab,],
    1997.0: [_name.rajacasablanca,_name.wydad,],
    1996.0: [_name.rajacasablanca,_name.khouribga,],
    1995.0: [_name.meknes,_name.oCasablanca,],
    1994.0: [_name.oCasablanca,_name.wydad,],
    1993.0: [_name.wydad,_name.rajacasablanca,],
    1992.0: [_name.kawkab,_name.rajacasablanca,],
    1991.0: [_name.wydad,_name.farRabat,],
    1990.0: [_name.wydad,_name.irTanger,],
    1989.0: [_name.farRabat,_name.maghreb,],
    1988.0: [_name.rajacasablanca,_name.kawkab,],
    1987.0: [_name.farRabat,_name.kawkab,],
    1986.0: [_name.wydad,_name.rajacasablanca,],
    1985.0: [_name.maghreb,_name.kenitra],
    1984.0: [_name.farRabat,_name.khouribga,],
    1983.0: [_name.maghreb,_name.renBerkane,],
    1982.0: [_name.kenitra,_name.wydad,],
    1981.0: [_name.kenitra,_name.fusRabat,],
    1980.0: [_name.chababMohammedia,_name.wydad,],
    1979.0: [_name.maghreb,_name.kenitra,],
    1978.0: [_name.wydad,_name.maghreb,],
    1977.0: [_name.wydad,_name.moulodiaOujda,],
    1976.0: [_name.wydad,_name.difaa,],
    1975.0: [_name.moulodiaOujda,_name.maghreb,],
    1974.0: [_name.beniMellal,_name.rajacasablanca,],
    1973.0: [_name.kenitra,_name.fusRabat,],
    1972.0: [_name.racingCasablanca,_name.wydad,],
    1971.0: [_name.settat,_name.farRabat,],
    1970.0: [_name.farRabat,],
    1969.0: [_name.wydad,_name.maghreb,],
    1968.0: [_name.farRabat,_name.settat,],
    1967.0: [_name.farRabat,_name.settat,],
    1966.0: [_name.wydad,_name.rajacasablanca,],
    1965.0: [_name.maghreb,_name.racingCasablanca,],
    1964.0: [_name.farRabat,],
    1963.0: [_name.farRabat,_name.kawkab,],
    1962.0: [_name.farRabat,_name.racingCasablanca,],
    1961.0: [_name.farRabat,_name.maghreb,],
    1960.0: [_name.kenitra,_name.farRabat,],
  },

  leagueName.tunisia : {
    2022.0: [_name.esperance,_name.monastir,],
    2021.0: [_name.esperance,_name.etoilesahel,],
    2020.0: [_name.esperance,_name.sfaxien,],
    2019.0: [_name.esperance,_name.etoilesahel,],
    2018.0: [_name.esperance,_name.clubAfricain,],
    2017.0: [_name.esperance,_name.etoilesahel,],
    2016.0: [_name.etoilesahel,_name.esperance,],
    2015.0: [_name.clubAfricain,_name.etoilesahel,],
    2014.0: [_name.esperance,_name.sfaxien,],
    2013.0: [_name.sfaxien,_name.esperance,],
    2012.0: [_name.esperance,_name.bizertin,],
    2011.0: [_name.esperance,_name.etoilesahel,],
    2010.0: [_name.esperance,_name.clubAfricain,],
    2009.0: [_name.esperance,_name.clubAfricain,],
    2008.0: [_name.clubAfricain,_name.etoilesahel,],
    2007.0: [_name.etoilesahel,_name.clubAfricain,],
    2006.0: [_name.esperance,_name.etoilesahel,],
    2005.0: [_name.sfaxien,_name.etoilesahel,],
    2004.0: [_name.esperance,_name.etoilesahel,],
    2003.0: [_name.esperance,_name.etoilesahel,],
    2002.0: [_name.esperance,_name.etoilesahel,],
    2001.0: [_name.esperance,_name.etoilesahel,],
    2000.0: [_name.esperance,_name.etoilesahel,],
    1999.0: [_name.esperance,_name.bizertin,],
    1998.0: [_name.esperance,_name.clubAfricain,],
    1997.0: [_name.etoilesahel,_name.esperance,],
    1996.0: [_name.clubAfricain,_name.etoilesahel,],
    1995.0: [_name.sfaxien,_name.esperance,],
    1994.0: [_name.esperance,_name.etoilesahel,],
    1993.0: [_name.esperance,_name.jskairouan,],
    1992.0: [_name.clubAfricain,_name.bizertin,],
    1991.0: [_name.esperance,_name.clubAfricain,],
    1990.0: [_name.clubAfricain,_name.esperance,],
    1989.0: [_name.esperance,_name.clubAfricain,],
    1988.0: [_name.esperance,_name.transports,],
    1987.0: [_name.etoilesahel,_name.clubAfricain,],
    1986.0: [_name.etoilesahel,_name.esperance,],
    1985.0: [_name.esperance,_name.clubAfricain,],
    1984.0: [_name.bizertin,_name.stadeTunisien,],
    1983.0: [_name.sfaxien,_name.clubAfricain,],
    1982.0: [_name.esperance,_name.clubAfricain,],
    1981.0: [_name.sfaxien,_name.clubAfricain,],
    1980.0: [_name.clubAfricain,_name.esperance,],
    1979.0: [_name.clubAfricain,_name.stadeTunisien,],
    1978.0: [_name.sfaxien,_name.clubAfricain,],
    1977.0: [_name.jskairouan,_name.clubAfricain,],
    1976.0: [_name.esperance,_name.etoilesahel,],
    1975.0: [_name.esperance,_name.clubAfricain,],
    1974.0: [_name.clubAfricain,_name.esperance,],
    1973.0: [_name.clubAfricain,_name.etoilesahel,],
    1972.0: [_name.etoilesahel,_name.clubAfricain,],
    1971.0: [_name.sfaxien,_name.clubAfricain,],
    1970.0: [_name.esperance,_name.clubAfricain,],
    1969.0: [_name.sfaxien,_name.clubAfricain,],
    1968.0: [_name.sfax,_name.clubAfricain,],
    1967.0: [_name.clubAfricain,_name.etoilesahel,],
    1966.0: [_name.etoilesahel,_name.sfaxien,],
    1965.0: [_name.stadeTunisien,_name.clubAfricain,],
    1964.0: [_name.clubAfricain,_name.esperance,],
    1963.0: [_name.etoilesahel,_name.stadeTunisien,],
    1962.0: [_name.stadeTunisien,],
    1961.0: [_name.stadeTunisien,_name.esperance,],
    1960.0: [_name.esperance,_name.stadeTunisien,],
  },

  leagueName.africaSul : {
    2022.0: [_name.mamelodi,_name.capetown,_name.royalAM,_name.stellenbosch,_name.kaizer,            _name.orlandopirates,_name.amazulu,_name.supersport,_name.goldenarrows,_name.marumo,      _name.sekhukhune,_name.maritzburg,_name.tsgalaxy,_name.chippa,_name.morokaSwallows,_name.baroka],
    2021.0: [_name.mamelodi,_name.amazulu,_name.orlandopirates,_name.goldenarrows,_name.supersport,  _name.morokaSwallows,_name.capetown,_name.kaizer,_name.tsgalaxy,_name.baroka,             _name.royalAM,_name.marumo,_name.maritzburg,_name.stellenbosch,_name.chippa,_name.blackLeopards],
    2020.0: [_name.mamelodi,_name.kaizer,_name.orlandopirates,_name.bidvestWits,_name.supersport,    _name.capetown,_name.maritzburg,_name.royalAM,_name.highlandspark,_name.stellenbosch,     _name.chippa,_name.goldenarrows,_name.amazulu,_name.baroka,_name.blackLeopards,_name.polokwane],
    2019.0: [_name.mamelodi,_name.orlandopirates,_name.bidvestWits,_name.capetown,_name.polokwane,   _name.supersport,_name.highlandspark,_name.royalAM,_name.kaizer,_name.goldenarrows,       _name.amazulu,_name.chippa,_name.blackLeopards,_name.baroka,_name.maritzburg,_name.freestate],
    2018.0: [_name.mamelodi,_name.orlandopirates,_name.kaizer,_name.maritzburg,_name.capetown,       _name.freestate,_name.supersport,_name.goldenarrows,_name.amazulu,_name.chippa,                _name.royalAM,_name.polokwane,_name.bidvestWits,_name.baroka,_name.platinumAFS,_name.capetownAjax],
    2017.0: [_name.bidvestWits,_name.mamelodi,_name.capetown,_name.supersport,_name.kaizer,          _name.polokwane,_name.maritzburg,_name.capetownAjax,_name.goldenarrows,_name.orlandopirates,   _name.platinumAFS,_name.royalAM,_name.freestate,_name.highlandspark,_name.chippa,_name.baroka],
    2016.0: [_name.mamelodi,_name.bidvestWits,_name.platinumAFS,_name.kaizer,_name.mpulamanga,       _name.orlandopirates,_name.chippa,_name.supersport,_name.goldenarrows,_name.capetownAjax, _name.freestate,_name.royalAM,_name.polokwane,],
    2015.0: [_name.kaizer,_name.mamelodi,_name.bidvestWits,_name.orlandopirates,_name.capetownAjax,  _name.supersport,_name.royalAM,_name.maritzburg,_name.freestate,_name.mpulamanga,        _name.platinumAFS,_name.polokwane,_name.pretoria,_name.chippa,_name.morokaSwallows,_name.amazulu],
    2014.0: [_name.mamelodi,_name.kaizer,_name.bidvestWits,_name.orlandopirates,_name.supersport,    _name.royalAM,_name.mpulamanga,_name.platinumAFS,_name.amazulu,_name.maritzburg,         _name.pretoria,_name.capetownAjax,_name.morokaSwallows,_name.freestate,_name.polokwane,_name.goldenarrows],
    2013.0: [_name.kaizer,_name.platinum,_name.orlandopirates,_name.bidvestWits,_name.royalAM,       _name.supersport,_name.freestate,_name.pretoria,_name.morokaSwallows,_name.mamelodi,     _name.maritzburg,_name.amazulu,_name.goldenarrows,_name.capetownAjax,_name.chippa,_name.blackLeopards],
    2012.0: [_name.orlandopirates,_name.morokaSwallows,_name.supersport,_name.mamelodi,_name.kaizer, _name.freestate,_name.amazulu,_name.royalAM,_name.capetownAjax,_name.platinumAFS,        _name.maritzburg,_name.bidvestWits,_name.goldenarrows,_name.blackLeopards],
    2011.0: [_name.orlandopirates,_name.capetownAjax,_name.kaizer,_name.mamelodi,_name.royalAM,      _name.bidvestWits,_name.supersport,_name.santosAfrica,_name.freestate,_name.platinumAFS, _name.goldenarrows,_name.maritzburg,_name.morokaSwallows,_name.amazulu],
    2010.0: [_name.supersport,_name.mamelodi,_name.kaizer,_name.santosAfrica,_name.orlandopirates,   _name.royalAM,_name.capetownAjax,_name.morokaSwallows,_name.amazulu,_name.bidvestWits,   _name.maritzburg,_name.goldenarrows,_name.freestate,_name.platinumAFS],
    2009.0: [_name.supersport,_name.orlandopirates,_name.kaizer,_name.freestate,_name.goldenarrows,  _name.bidvestWits,_name.capetownAjax,_name.amazulu,_name.mamelodi,_name.santosAfrica,    _name.morokaSwallows,_name.maritzburg,_name.platinumAFS,_name.royalAM],
    2008.0: [_name.supersport,_name.capetownAjax,],
    2007.0: [_name.mamelodi,_name.platinum,],
    2006.0: [_name.mamelodi,_name.orlandopirates,],
    2005.0: [_name.kaizer,_name.orlandopirates,],
    2004.0: [_name.kaizer,_name.capetownAjax,],
    2003.0: [_name.orlandopirates,_name.supersport,],
    2002.0: [_name.santosAfrica,_name.supersport,],
    2001.0: [_name.orlandopirates,_name.kaizer,],
    2000.0: [_name.mamelodi,_name.orlandopirates,],
    1999.0: [_name.mamelodi,_name.kaizer,],
    1998.0: [_name.mamelodi,_name.orlandopirates,],
    1997.0: [_name.manningRangers,_name.kaizer,],
  },

  leagueName.nigeria : {
    2022.0: [_name.riversUtd,_name.plateau,_name.remoStars,_name.kwaraUtd,_name.rangersInt,   _name.nasarawa,_name.enyimba],
    2021.0: [_name.akwa,_name.enyimba,_name.kwaraUtd,_name.nasarawa,_name.kano,       _name.riversUtd,_name.rangersInt,_name.lobiStars,_name.plateau,_name.mfm,   ],
    2020.0: [_name.plateau,_name.enyimba,_name.riversUtd,_name.lobiStars,_name.rangersInt,  _name.kano],
    2019.0: [_name.enyimba,_name.kano,_name.rangersInt,_name.akwa,_name.lobiStars,    ],
    2018.0: [_name.lobiStars,_name.akwa,_name.kano,_name.enyimba,_name.plateau,       ],
    2017.0: [_name.plateau,_name.mfm,_name.enyimba,_name.akwa,_name.nasarawa,         ],
    2016.0: [_name.rangersInt,_name.riversUtd,_name.wikki,_name.ifeanyi,_name.lobiStars, _name.sunshinestars,_name.kano,_name.plateau],
    2015.0: [_name.enyimba,_name.warriWolves,_name.nasarawa,_name.wikki,  ],
    2014.0: [_name.kano,],
    2013.0: [_name.kano,],
    2012.0: [_name.kano,],
    2011.0: [_name.dolphin,],
    2010.0: [_name.enyimba,],
    2009.0: [_name.bayelsa],
    2008.0: [_name.kano,],
    2007.0: [_name.enyimba,],
    2006.0: [_name.oceanBoys,],
    2005.0: [_name.enyimba,],
    2004.0: [_name.dolphin,],
    2003.0: [_name.enyimba,],
    2002.0: [_name.enyimba,],
    2001.0: [_name.enyimba,],
    2000.0: [_name.juliusBerger,],
  }

};