import 'package:fifa/values/club_names.dart';
import 'package:fifa/values/league_names.dart';


ClubName _name = ClubName();
LeagueOfficialNames leagueName = LeagueOfficialNames();

Map<String,dynamic> mapAsia = {

  leagueName.china : {
    2022.0: [],
    2021.0: [_name.shandong,_name.shanghaisipg,],
    2020.0: [_name.jiangsu,_name.ghuangzhou,],
    2019.0: [_name.ghuangzhou,_name.beijingguoan,],
    2018.0: [_name.shanghaisipg,_name.ghuangzhou,],
    2017.0: [_name.ghuangzhou,_name.shanghaisipg,],
    2016.0: [_name.ghuangzhou,_name.jiangsu,],
    2015.0: [_name.ghuangzhou,_name.shanghaisipg,],
    2014.0: [_name.ghuangzhou,_name.beijingguoan,],
    2013.0: [_name.ghuangzhou,_name.shandong,],
    2012.0: [_name.ghuangzhou,_name.jiangsu,],
    2011.0: [_name.ghuangzhou,_name.beijingguoan,],
    2010.0: [_name.shandong,_name.tianjin,],
    2009.0: [_name.beijingguoan,_name.changchun,],
    2008.0: [_name.shandong,_name.shanghaishenhua,],
    2007.0: [_name.changchun,_name.beijingguoan,],
    2006.0: [_name.shandong,_name.shanghaishenhua,],
    2005.0: [_name.dalian,_name.shanghaishenhua,],
    2004.0: [_name.shenzhen,_name.shandong,],
    2003.0: [_name.shanghaishenhua,_name.chengfeng],
    2002.0: [_name.dalian,_name.shenzhen,],
    2001.0: [_name.dalian,_name.shanghaishenhua,],
    2000.0: [_name.dalian,_name.shanghaishenhua,],
    1999.0: [_name.shandong,_name.liaoning,],
    1998.0: [_name.dalian,_name.shanghaishenhua,],
    1997.0: [_name.dalian,_name.shanghaishenhua,],
    1996.0: [_name.dalian,_name.shanghaishenhua,],
    1995.0: [_name.shanghaishenhua,_name.beijingguoan,],
    1994.0: [_name.dalian,_name.ghuangzhou,],
  },

  leagueName.japao : {
    2022.0: [],
    2021.0: [_name.kawasakifrontale,_name.yokohamamarinos,_name.visselkobe,_name.kashimaantlers,_name.nagoya,   _name.urawareddiamonds,_name.sagantosu,_name.avispa,_name.fcTokyo,_name.sapporo,    _name.hiroshima,_name.cerezoOsaka,_name.gambaOsaka,_name.shimizuSPulse,_name.kashiwaReysol,   _name.shonanbellmare,_name.tokushima,_name.oitatrinita,_name.vegaltaSendai,_name.yokohamaFC],
    2020.0: [_name.kawasakifrontale,_name.gambaOsaka,_name.nagoya,_name.cerezoOsaka,_name.kashimaantlers,       _name.fcTokyo,_name.kashiwaReysol,_name.hiroshima,_name.yokohamamarinos,_name.urawareddiamonds,  _name.oitatrinita,_name.sapporo,_name.sagantosu,_name.visselkobe,_name.yokohamaFC,  _name.shimizuSPulse,_name.vegaltaSendai,_name.shonanbellmare],
    2019.0: [_name.yokohamamarinos,_name.fcTokyo,_name.kashimaantlers,_name.kawasakifrontale,_name.cerezoOsaka, _name.hiroshima,_name.gambaOsaka,_name.visselkobe,_name.oitatrinita,_name.sapporo,  _name.vegaltaSendai,_name.shimizuSPulse,_name.nagoya,_name.urawareddiamonds,_name.sagantosu,  _name.shonanbellmare,_name.matsumoto,_name.jubiloiwata],
    2018.0: [_name.kawasakifrontale,_name.hiroshima,_name.kashimaantlers,_name.sapporo,_name.urawareddiamonds,  _name.fcTokyo,_name.cerezoOsaka,_name.shimizuSPulse,_name.gambaOsaka,_name.visselkobe,  _name.vegaltaSendai,_name.yokohamamarinos,_name.shonanbellmare,_name.sagantosu,_name.nagoya,  _name.jubiloiwata,_name.kashiwaReysol,],
    2017.0: [_name.kawasakifrontale,_name.kashimaantlers,_name.cerezoOsaka,_name.kashiwaReysol,_name.yokohamamarinos,  _name.jubiloiwata,_name.urawareddiamonds,_name.sagantosu,_name.visselkobe,_name.gambaOsaka, _name.sapporo,_name.fcTokyo,_name.shimizuSPulse,_name.hiroshima,               _name.ventforet,_name.albirex,_name.omiyaardija],
    2016.0: [_name.kashimaantlers,_name.urawareddiamonds,_name.kawasakifrontale,_name.hiroshima,_name.omiyaardija, _name.gambaOsaka,_name.kashiwaReysol,_name.jubiloiwata,_name.fcTokyo,_name.vegaltaSendai,  _name.yokohamamarinos,_name.visselkobe,_name.albirex,_name.nagoya,_name.sagantosu,  _name.shonanbellmare,_name.ventforet,_name.avispa],
    2015.0: [_name.hiroshima,_name.gambaOsaka,_name.urawareddiamonds,_name.fcTokyo,_name.kashimaantlers,        _name.kawasakifrontale,_name.yokohamamarinos,_name.shonanbellmare,_name.nagoya,_name.kashiwaReysol,  _name.sagantosu,_name.visselkobe,_name.ventforet,_name.vegaltaSendai,_name.albirex,  _name.matsumoto,_name.shimizuSPulse,_name.yamagata],
    2014.0: [_name.gambaOsaka,_name.urawareddiamonds,_name.kashimaantlers,_name.kashiwaReysol,_name.sagantosu,  _name.kawasakifrontale,_name.yokohamamarinos,_name.hiroshima,_name.fcTokyo,_name.nagoya,   _name.visselkobe,_name.albirex,_name.ventforet,_name.vegaltaSendai,_name.shimizuSPulse,  _name.omiyaardija,_name.cerezoOsaka,_name.tokushima],
    2013.0: [_name.hiroshima,_name.yokohamamarinos,_name.kawasakifrontale,_name.cerezoOsaka,_name.kashimaantlers, _name.urawareddiamonds,_name.albirex,_name.fcTokyo,_name.shimizuSPulse,_name.kashiwaReysol,  _name.nagoya,_name.sagantosu,_name.vegaltaSendai,_name.omiyaardija,_name.ventforet,  _name.shonanbellmare,_name.jubiloiwata,_name.oitatrinita],
    2012.0: [_name.hiroshima,_name.vegaltaSendai,_name.urawareddiamonds,],
    2011.0: [_name.kashiwaReysol,_name.nagoya,_name.gambaOsaka,],
    2010.0: [_name.nagoya,_name.gambaOsaka,_name.cerezoOsaka,],
    2009.0: [_name.kashimaantlers,_name.kawasakifrontale,_name.gambaOsaka,],
    2008.0: [_name.kashimaantlers,_name.kawasakifrontale,_name.nagoya,],
    2007.0: [_name.kashimaantlers,_name.urawareddiamonds,_name.gambaOsaka,],
    2006.0: [_name.urawareddiamonds,_name.kawasakifrontale,_name.gambaOsaka,],
    2005.0: [_name.gambaOsaka,_name.urawareddiamonds,_name.kashimaantlers,],
    2004.0: [_name.yokohamamarinos,_name.urawareddiamonds,_name.gambaOsaka,],
    2003.0: [_name.yokohamamarinos,_name.jubiloiwata,_name.jefUnited,],
    2002.0: [_name.jubiloiwata,_name.yokohamamarinos,_name.gambaOsaka,],
    2001.0: [_name.kashimaantlers,_name.jubiloiwata,_name.jefUnited,],
    2000.0: [_name.kashimaantlers,_name.yokohamamarinos,_name.kashiwaReysol,],
    1999.0: [_name.jubiloiwata,_name.shimizuSPulse,_name.kashiwaReysol,],

    1998.0: [_name.kashimaantlers,_name.jubiloiwata,_name.shimizuSPulse,],
    1997.0: [_name.jubiloiwata,_name.kashimaantlers,_name.yokohamamarinos,],
    1996.0: [_name.kashimaantlers,_name.nagoya,_name.flugels,],
    1995.0: [_name.yokohamamarinos,_name.tokyoVerdy,_name.nagoya,],
    1994.0: [_name.tokyoVerdy,_name.hiroshima,_name.kashimaantlers,],
    1993.0: [_name.tokyoVerdy,_name.kashimaantlers,_name.shimizuSPulse,],
  },

  leagueName.coreiaSul : {
    2021.0: [_name.jeonbuk,_name.ulsan,],
    2020.0: [_name.jeonbuk,_name.ulsan,],
    2019.0: [_name.jeonbuk,_name.ulsan,],
    2018.0: [_name.jeonbuk,_name.gyeongnam,],
    2017.0: [_name.jeonbuk,_name.jeju,],
    2016.0: [_name.fcseoul,_name.jeonbuk,],
    2015.0: [_name.jeonbuk,_name.suwonsamsung,],
    2014.0: [_name.jeonbuk,_name.suwonsamsung,],
    2013.0: [_name.pohang,_name.ulsan,],
    2012.0: [_name.fcseoul,_name.jeonbuk,],
    2011.0: [_name.jeonbuk,_name.ulsan,],
    2010.0: [_name.fcseoul,_name.jeju,],
    2009.0: [_name.jeonbuk,_name.seongnam,],
    2008.0: [_name.suwonsamsung,_name.fcseoul,],
    2007.0: [_name.pohang,_name.seongnam,],
    2006.0: [_name.seongnam,_name.suwonsamsung,],
    2005.0: [_name.ulsan,_name.incheon,],
    2004.0: [_name.suwonsamsung,_name.pohang,],
    2003.0: [_name.seongnam,_name.ulsan,],
    2002.0: [_name.seongnam,_name.ulsan,],
    2001.0: [_name.seongnam,_name.fcseoul,],
    2000.0: [_name.fcseoul,_name.jeju,],
    1999.0: [_name.suwonsamsung,_name.busan,],
    1998.0: [_name.suwonsamsung,_name.ulsan,],
    1997.0: [_name.busan,_name.jeonnam,],
    1996.0: [_name.ulsan,_name.suwonsamsung,],
    1995.0: [_name.seongnam,_name.pohang,],
    1994.0: [_name.seongnam,_name.jeju,],
    1993.0: [_name.seongnam,_name.fcseoul,],
    1992.0: [_name.pohang,_name.seongnam,],
    1991.0: [_name.busan,_name.ulsan,],
    1990.0: [_name.fcseoul,_name.busan,],
    1989.0: [_name.jeju,_name.fcseoul],
    1988.0: [_name.pohang,_name.ulsan,],
    1987.0: [_name.busan,_name.pohang,],
    1986.0: [_name.pohang,_name.fcseoul,],
    1985.0: [_name.fcseoul,_name.pohang,],
    1984.0: [_name.busan,_name.jeju,],
    1983.0: [_name.hallelujah,_name.busan,],
  },

  leagueName.australia : {
    2022.0: [],
    2021.0: [_name.melbournecity,_name.sydneyFC,_name.macarthur,_name.adelaide,      _name.centralcoast,_name.brisbane,_name.wellingtonphoenix,_name.sydneywanderers,_name.perth,_name.westernunited,               _name.newcastlejets,_name.melbournevictory],
    2020.0: [_name.sydneyFC,_name.melbournecity,_name.perth,_name.westernunited,     _name.wellingtonphoenix,_name.westernunited,_name.adelaide,_name.newcastlejets,_name.sydneywanderers,_name.melbournevictory,   _name.centralcoast],
    2019.0: [_name.sydneyFC,_name.perth,_name.melbournevictory,_name.adelaide,       _name.melbournecity,_name.wellingtonphoenix,_name.newcastlejets,_name.sydneywanderers,_name.brisbane,_name.centralcoast],
    2018.0: [_name.melbournevictory,_name.newcastlejets,_name.sydneyFC,_name.melbournecity,  _name.adelaide,_name.brisbane,_name.sydneywanderers,_name.perth,_name.wellingtonphoenix,_name.centralcoast],
    2017.0: [_name.sydneyFC,_name.melbournevictory,_name.brisbane,_name.melbournecity,       _name.perth,_name.sydneywanderers,_name.wellingtonphoenix,_name.centralcoast,_name.adelaide,_name.newcastlejets],
    2016.0: [_name.adelaide,_name.sydneywanderers,_name.brisbane,_name.melbournecity,        _name.perth,_name.melbournevictory,_name.sydneyFC,_name.newcastlejets,_name.wellingtonphoenix,_name.centralcoast],
    2015.0: [_name.melbournevictory,_name.sydneyFC,_name.adelaide,_name.wellingtonphoenix,   _name.melbournecity,_name.brisbane,_name.perth,_name.centralcoast,_name.sydneywanderers,_name.newcastlejets],
    2014.0: [_name.brisbane,_name.sydneywanderers,_name.centralcoast,_name.melbournevictory, _name.sydneyFC,_name.adelaide,_name.newcastlejets,_name.perth,_name.wellingtonphoenix,_name.melbournecity],
    2013.0: [_name.centralcoast,_name.sydneywanderers,_name.melbournevictory,_name.adelaide,  _name.brisbane,_name.perth,_name.sydneyFC,_name.newcastlejets,_name.melbournecity,_name.wellingtonphoenix],
    2012.0: [_name.brisbane,_name.perth,_name.centralcoast,_name.wellingtonphoenix,           _name.sydneyFC,_name.melbournecity,_name.newcastlejets,_name.melbournevictory,_name.adelaide,_name.goldCoast],
    2011.0: [_name.brisbane,_name.centralcoast,_name.adelaide,_name.goldCoast,                _name.melbournevictory,_name.wellingtonphoenix,_name.newcastlejets,_name.melbournecity,_name.sydneyFC,_name.perth,_name.queensland],
    2010.0: [_name.sydneyFC,_name.melbournevictory,_name.goldCoast,_name.wellingtonphoenix,_name.perth,  _name.newcastlejets,_name.queensland,_name.centralcoast,_name.brisbane,_name.adelaide],
    2009.0: [_name.melbournevictory,_name.adelaide,_name.brisbane,_name.centralcoast,         _name.sydneyFC,_name.wellingtonphoenix,_name.perth,_name.newcastlejets],
    2008.0: [_name.newcastlejets,_name.centralcoast,_name.sydneyFC,_name.brisbane,            _name.melbournevictory,_name.adelaide,_name.perth,_name.wellingtonphoenix],
    2007.0: [_name.melbournevictory,_name.adelaide,_name.newcastlejets,_name.sydneyFC,       _name.brisbane,_name.centralcoast,_name.perth,_name.newZealandKnights],
    2006.0: [_name.sydneyFC,_name.centralcoast,_name.adelaide,_name.newcastlejets,           _name.perth,_name.brisbane,_name.melbournevictory,_name.newZealandKnights],

    2005.0: [],
    //National_Soccer_League
    2004.0: [_name.perth,_name.parramattaPower,_name.adelaide,_name.marconiStallions,_name.southMelbourne],
    2003.0: [_name.perth,_name.sydneyOlympic,_name.adelaideCity,_name.parramattaPower,],
    2002.0: [_name.sydneyOlympic,_name.perth,],
    2001.0: [_name.wollongongWolves,_name.southMelbourne,],
    2000.0: [_name.wollongongWolves,_name.perth,],
    1999.0: [_name.southMelbourne,_name.sydneyUtd],
    1998.0: [_name.southMelbourne,_name.carlton],
    1997.0: [_name.brisbaneStrikers,_name.sydneyUtd,],
    1996.0: [_name.melbourneKnights,_name.marconiStallions,],
    1995.0: [_name.melbourneKnights,_name.adelaideCity,],
    1994.0: [_name.adelaideCity,_name.melbourneKnights,],
    1993.0: [_name.marconiStallions,_name.adelaideCity,],
    1992.0: [_name.adelaideCity,_name.melbourneKnights,],
    1991.0: [_name.southMelbourne,_name.melbourneKnights,],
    1990.0: [_name.sydneyOlympic,_name.marconiStallions,],
    1989.0: [_name.marconiStallions,_name.sydneyOlympic,],
    1988.0: [_name.marconiStallions,_name.sydneyUtd,],
    1987.0: [_name.apiaLeichhardt,_name.prestonLions,],
    1986.0: [_name.adelaideCity,_name.sydneyOlympic,],
    1985.0: [_name.brunswick,_name.maccabiHakoah,],
    1984.0: [_name.southMelbourne,_name.sydneyOlympic,],
    1983.0: [_name.stGeorgeAUS,_name.maccabiHakoah,],
    1982.0: [_name.maccabiHakoah,_name.stGeorgeAUS,],
    1981.0: [_name.maccabiHakoah,],
    1980.0: [_name.maccabiHakoah,],
    1979.0: [_name.marconiStallions,],
    1978.0: [_name.westAdelaide,_name.maccabiHakoah,],
    1977.0: [_name.maccabiHakoah,_name.marconiStallions,],
  },


  leagueName.arabia : {
    2022.0: [_name.alhilal,_name.alIttihad,_name.alnassr,_name.alShabab,_name.damac,],
    2021.0: [_name.alhilal,_name.alShabab,],
    2020.0: [_name.alhilal,_name.alnassr,],
    2019.0: [_name.alnassr,_name.alhilal,],
    2018.0: [_name.alhilal,_name.alahli,],
    2017.0: [_name.alhilal,_name.alahli,],
    2016.0: [_name.alahli,_name.alhilal,],
    2015.0: [_name.alnassr,_name.alahli,],
    2014.0: [_name.alnassr,_name.alhilal,],
    2013.0: [_name.alfateh,_name.alhilal,],
    2012.0: [_name.alShabab,_name.alahli,],
    2011.0: [_name.alhilal,_name.alIttihad,],
    2010.0: [_name.alhilal,_name.alIttihad,],
    2009.0: [_name.alIttihad,_name.alhilal,],
    2008.0: [_name.alhilal,_name.alIttihad,],
    2007.0: [_name.alIttihad,_name.alhilal,],
    2006.0: [_name.alShabab,_name.alhilal,],
    2005.0: [_name.alhilal,_name.alShabab,],
    2004.0: [_name.alShabab,_name.alIttihad,],
    2003.0: [_name.alIttihad,_name.alahli,],
    2002.0: [_name.alhilal,_name.alIttihad,],
    2001.0: [_name.alIttihad,_name.alnassr,],
    2000.0: [_name.alIttihad,_name.alahli,],
    1999.0: [_name.alIttihad,_name.alahli,],
    1998.0: [_name.alhilal,_name.alShabab,],
    1997.0: [_name.alIttihad,_name.alhilal,],
    1996.0: [_name.alhilal,_name.alahli,],
    1995.0: [_name.alnassr,_name.alhilal,],
    1994.0: [_name.alnassr,],
    1993.0: [_name.alShabab,_name.alhilal,],
    1992.0: [_name.alShabab,_name.alettifaq,],
    1991.0: [_name.alShabab,],
    1990.0: [_name.alhilal,],
    1989.0: [_name.alnassr,],
    1988.0: [_name.alhilal,],
    1987.0: [_name.alettifaq,],
    1986.0: [_name.alhilal,],
    1985.0: [_name.alhilal,],
    1984.0: [_name.alahli,],
    1983.0: [_name.alettifaq,],
    1982.0: [_name.alIttihad,],
    1981.0: [_name.alnassr,],
    1980.0: [_name.alnassr,],
    1979.0: [_name.alhilal,],
    1978.0: [_name.alahli,],
    1977.0: [_name.alhilal,],
    1976.0: [],
    1975.0: [_name.alnassr,],
  },

  leagueName.qatar : {
    2022.0: [_name.alsadd,_name.alduhail,_name.alwakrah,_name.alarabi,_name.algharafa,    ],
    2021.0: [_name.alsadd,_name.alduhail,_name.alrayyan,_name.algharafa,_name.alahliQAT,  ],
    2020.0: [_name.alduhail,_name.alrayyan,_name.alsadd,_name.algharafa,_name.alsailiya,  ],
    2019.0: [_name.alsadd,_name.alduhail,_name.alsailiya,_name.alrayyan,_name.alahliQAT,  ],
    2018.0: [_name.alduhail,_name.alsadd,_name.alrayyan,_name.algharafa,_name.ummSalal,   ],
    2017.0: [_name.alduhail,_name.alsadd,_name.alrayyan,_name.eljaish,_name.algharafa,    ],
    2016.0: [_name.alrayyan,_name.eljaish,_name.alsadd,_name.alduhail,_name.ummSalal,     ],
    2015.0: [_name.alduhail,_name.alsadd,_name.eljaish,_name.qatar,_name.alahliQAT,       ],
    2014.0: [_name.alduhail,_name.eljaish,_name.alsadd,_name.alsailiya,_name.alarabi,     ],
    2013.0: [_name.alsadd,_name.alduhail,_name.eljaish,_name.alrayyan,_name.ummSalal,     ],
    2012.0: [_name.alduhail,_name.eljaish,_name.alrayyan,_name.alsadd,_name.alkhor,       ],
    2011.0: [_name.alduhail,_name.algharafa,_name.alrayyan,_name.alarabi,_name.qatar,     ],
    2010.0: [_name.algharafa,_name.alsadd,_name.alarabi,_name.qatar,_name.alrayyan,       ],
    2009.0: [_name.algharafa,_name.alsadd,_name.alrayyan,_name.qatar,_name.alkhor,        ],
    2008.0: [_name.algharafa,_name.alsadd,_name.ummSalal,_name.qatar,_name.alrayyan,      ],
    2007.0: [_name.alsadd,_name.algharafa,_name.ummSalal,_name.alrayyan,_name.alwakrah,   ],
    2006.0: [_name.alsadd,_name.qatar,_name.alarabi,_name.alrayyan,_name.alahliQAT,       ],
    2005.0: [_name.algharafa,_name.alrayyan,_name.alkhor,_name.qatar,_name.alarabi,       ],
    2004.0: [_name.alsadd,_name.qatar,_name.alarabi,_name.alahliQAT,_name.alrayyan,       ],
    2003.0: [_name.qatar,_name.alsadd,_name.alkhor,_name.algharafa,_name.alahliQAT,       ],
    2002.0: [_name.algharafa,_name.qatar,_name.alrayyan,_name.alsadd,_name.alwakrah,      ],
    2001.0: [_name.alwakrah,_name.alarabi,_name.altaawoun,_name.alrayyan,_name.algharafa, ],
    2000.0: [_name.alsadd,_name.alrayyan,_name.alarabi,_name.algharafa,_name.alahliQAT,   ],
    1999.0: [_name.alrayyan,_name.algharafa,_name.alsadd,_name.alarabi,_name.alwakrah,    ],
    1998.0: [_name.algharafa,_name.alrayyan,_name.alsadd,_name.alarabi,_name.alahliQAT,   ],
    1997.0: [_name.alarabi,_name.alrayyan,_name.algharafa,_name.alwakrah,_name.alsadd,    ],
    1996.0: [_name.alarabi,_name.alrayyan,_name.alwakrah,_name.alsadd,_name.algharafa,    ],
    1995.0: [_name.alrayyan,],
    1994.0: [_name.alarabi,],
    1993.0: [_name.alarabi,],
    1992.0: [_name.algharafa,],
    1991.0: [_name.alarabi,],
    1990.0: [_name.alrayyan,],
    1989.0: [_name.alsadd,],
    1988.0: [_name.alsadd,],
    1987.0: [_name.alsadd,],
    1986.0: [_name.alrayyan,],
    1985.0: [_name.alarabi,],
    1984.0: [_name.alrayyan,],
    1983.0: [_name.alarabi,],
    1982.0: [_name.alrayyan,],
    1981.0: [_name.alsadd,],
    1980.0: [_name.alsadd,],
    1979.0: [_name.alsadd,],
    1978.0: [_name.alrayyan,],
    1977.0: [_name.qatar,],
    1976.0: [_name.alrayyan,],
    1975.0: [],
    1974.0: [_name.alsadd,],
    1973.0: [_name.qatar,],
  },

  leagueName.eau : {
    2022.0: [],
    2021.0: [_name.aljazira,_name.baniyas,],
    2020.0: [],
    2019.0: [_name.alsharjah,_name.shababalahli,],
    2018.0: [_name.alain,_name.alWahda,],
    2017.0: [_name.aljazira,_name.alwasl,],
    2016.0: [_name.shababalahli,_name.alain,],
    2015.0: [_name.alain,_name.aljazira,],
    2014.0: [_name.shababalahli,_name.alWahda,],
    2013.0: [_name.alain,_name.shababalahli,],
    2012.0: [_name.alain,_name.alnasrEAU,],
    2011.0: [_name.aljazira,_name.baniyas,],
    2010.0: [_name.alWahda,_name.aljazira,],
    2009.0: [_name.shababalahli,_name.aljazira,],
    2008.0: [_name.alShababEAU,_name.aljazira,],
    2007.0: [_name.alwasl,_name.alWahda,],
    2006.0: [_name.shababalahli,_name.alWahda,],
    2005.0: [_name.alWahda,_name.alain,],
    2004.0: [_name.alain,_name.shababalahli,],
    2003.0: [_name.alain,_name.alWahda,],
    2002.0: [_name.alain,_name.aljazira,],
    2001.0: [_name.alWahda,_name.alain,],
    2000.0: [_name.alain,_name.alnasrEAU,],
    1999.0: [_name.alWahda,_name.alain,],
    1998.0: [_name.alain,_name.alsharjah,],
    1997.0: [_name.alwasl,_name.alnasrEAU,],
    1996.0: [_name.alsharjah,_name.alwasl,],
    1995.0: [_name.alShababEAU,_name.alwasl,],
    1994.0: [_name.alsharjah,_name.alain,],
    1993.0: [_name.alain,_name.alwasl,],
    1992.0: [_name.alwasl,_name.alsharjah],
    1991.0: [],
    1990.0: [_name.alShababEAU,_name.alwasl,],
    1989.0: [_name.alsharjah,_name.alwasl,],
    1988.0: [_name.alwasl,_name.alsharjah,],
    1987.0: [_name.alsharjah,_name.alwasl,],
    1986.0: [_name.alnasrEAU,_name.alwasl,],
    1985.0: [_name.alwasl,_name.alShababEAU,],
    1984.0: [_name.alain,_name.alwasl,],
    1983.0: [_name.alwasl,_name.alsharjah,],
    1982.0: [_name.alwasl,_name.alsharjah,],
    1981.0: [_name.alain,_name.alnasrEAU,],
    1980.0: [_name.shababalahli,],
    1979.0: [_name.alnasrEAU,_name.alsharjah,],
    1978.0: [_name.alnasrEAU,_name.alain,],
    1977.0: [_name.alain,_name.alsharjah,],
    1976.0: [_name.shababalahli,_name.alain,],
    1975.0: [_name.shababalahli,_name.alsharjah,],
    1974.0: [_name.alsharjah,_name.shababalahli,],
  },
  leagueName.india : {
    2022.0: [_name.hyderabad,_name.kerala,_name.jamshedpur,_name.mohunBagan,  _name.mumbai,_name.bengaluru,_name.odisha,_name.chennaiyin,_name.goa,_name.northeast,              _name.eastBengal],
    2021.0: [_name.mumbai,_name.mohunBagan,_name.northeast,_name.goa,         _name.hyderabad,_name.jamshedpur,_name.bengaluru,_name.chennaiyin,_name.eastBengal,_name.kerala,   _name.odisha],
    2020.0: [_name.mohunBagan,_name.chennaiyin,_name.goa,_name.bengaluru,     _name.mumbai,_name.odisha,_name.kerala,_name.jamshedpur,_name.northeast,_name.hyderabad],
    2019.0: [_name.bengaluru,_name.goa,_name.mumbai,_name.northeast,    _name.jamshedpur,_name.mohunBagan,_name.pune,_name.delhi,_name.kerala,_name.chennaiyin],
    2018.0: [_name.chennaiyin,_name.bengaluru,_name.goa,_name.pune,     _name.jamshedpur,_name.kerala,_name.mumbai,_name.delhi,_name.mohunBagan,_name.northeast],
    2017.0: [_name.aizawl,_name.mohunBagan,_name.eastBengal,],
    2016.0: [_name.bengaluru,_name.mohunBagan,_name.eastBengal,],
    2015.0: [_name.mohunBagan,_name.bengaluru,],
    2014.0: [_name.bengaluru,_name.eastBengal,_name.salgaocar,],
    2013.0: [_name.churchill,_name.pune,_name.eastBengal],
    2012.0: [_name.dempo,_name.eastBengal,_name.churchill,],
    2011.0: [_name.salgaocar,_name.eastBengal,_name.dempo,],
    2010.0: [_name.dempo,_name.churchill,_name.pune],
    2009.0: [_name.churchill,_name.mohunBagan,_name.sportingGoa,],
    2008.0: [_name.dempo,_name.churchill,_name.jct,],
    2007.0: [_name.dempo,_name.jct,_name.mahindra,_name.mahindra,],
    2006.0: [_name.mahindra,_name.eastBengal,_name.mohunBagan,],
    2005.0: [_name.dempo,_name.sportingGoa,_name.eastBengal,],
    2004.0: [_name.eastBengal,_name.dempo,_name.mahindra,],
    2003.0: [_name.eastBengal,_name.salgaocar,_name.vascoIND,],
    2002.0: [_name.mohunBagan,_name.churchill,_name.vascoIND,],
    2001.0: [_name.eastBengal,_name.mohunBagan,_name.churchill,],
    2000.0: [_name.mohunBagan,_name.churchill,_name.salgaocar,],
    1999.0: [_name.salgaocar,_name.eastBengal,_name.churchill,],
    1998.0: [_name.mohunBagan,_name.eastBengal,_name.salgaocar,],
    1997.0: [_name.jct,_name.churchill,_name.eastBengal,],
  },
  leagueName.tailandia : {
    2022.0: [_name.buriram],
    2021.0: [_name.pathum,],
    2020.0: [],
    2019.0: [_name.chiangrai,],
    2018.0: [_name.buriram,],
    2017.0: [_name.buriram,],
    2016.0: [_name.muangthong,],
    2015.0: [_name.buriram,],
    2014.0: [_name.buriram,],
    2013.0: [_name.buriram,],
    2012.0: [_name.muangthong,],
    2011.0: [_name.buriram,],
    2010.0: [_name.muangthong,],
    2009.0: [_name.muangthong,],
    2008.0: [_name.buriram,],
    2007.0: [_name.muangthong,],
    2006.0: [_name.muangthong,],

    2002.0: [_name.policeTero,],
    2001.0: [],
    2000.0: [_name.policeTero,],
    1999.0: [_name.thaiAirForce,],
    1998.0: [],
    1997.0: [_name.thaiAirForce,],
    1996.0: [_name.bangkokBank,],
    1995.0: [_name.thai,],
    1994.0: [_name.bangkokBank,],
    1993.0: [_name.thai,],
    1992.0: [_name.thai,],
    1991.0: [],
    1990.0: [_name.thai,],
    1989.0: [_name.bangkokBank,],

    1987.0: [_name.thaiAirForce,],
    1986.0: [_name.bangkokBank,],

    1984.0: [_name.bangkokBank,],

    1981.0: [_name.bangkokBank,],
  },

  leagueName.iran : {
    2022.0: [_name.esteghlal,_name.persepolis,_name.sepahan,],
    2021.0: [_name.persepolis,_name.sepahan,_name.esteghlal,],
    2020.0: [_name.persepolis,_name.esteghlal,_name.foolad,],
    2019.0: [_name.persepolis,_name.sepahan,_name.esteghlal,],
    2018.0: [_name.persepolis,_name.zobahan,_name.esteghlal,],
    2017.0: [_name.persepolis,_name.esteghlal,_name.tractor,],
    2016.0: [_name.esteghlalKhuzestan,_name.persepolis,_name.esteghlal,],
    2015.0: [_name.sepahan,_name.tractor,_name.naftTehran,],
    2014.0: [_name.foolad,_name.persepolis,_name.naftTehran,],
    2013.0: [_name.esteghlal,_name.tractor,_name.sepahan,],
    2012.0: [_name.sepahan,_name.tractor,_name.esteghlal,],
    2011.0: [_name.sepahan,_name.esteghlal,_name.zobahan,],
    2010.0: [_name.sepahan,_name.zobahan,_name.esteghlal,],
    2009.0: [_name.esteghlal,_name.zobahan,],
    2008.0: [_name.persepolis,_name.sepahan,],
    2007.0: [_name.saipa,_name.esteghlal,_name.persepolis],
    2006.0: [_name.esteghlal,_name.pastehran,_name.saipa],
    2005.0: [_name.foolad,_name.zobahan,_name.esteghlal,],
    2004.0: [_name.pastehran,_name.esteghlal,_name.foolad,],
    2003.0: [_name.sepahan,_name.pastehran,_name.persepolis,],
    2002.0: [_name.persepolis,_name.esteghlal,_name.foolad,],
    2001.0: [_name.esteghlal,_name.persepolis,_name.saipa,],
    2000.0: [_name.persepolis,_name.esteghlal,],
    1999.0: [_name.persepolis,_name.esteghlal,_name.sepahan,],
    1998.0: [_name.esteghlal,_name.pastehran,_name.zobahan,],
    1997.0: [_name.persepolis,_name.bahman,_name.sepahan,],
    1996.0: [_name.persepolis,_name.bahman,_name.esteghlal,],
    1995.0: [_name.saipa,_name.esteghlal,],
    1994.0: [_name.saipa,_name.persepolis,],
    1993.0: [_name.pastehran,_name.persepolis,_name.keshavarz,],
    1992.0: [_name.pastehran,_name.esteghlal,_name.persepolis,],
    1991.0: [],
    1990.0: [_name.esteghlal,_name.persepolis,_name.malavan,],
    1989.0: [],
    1988.0: [],
    1987.0: [],
    1986.0: [],
    1985.0: [],
    1984.0: [],
    1983.0: [],
    1982.0: [],
    1981.0: [],
    1980.0: [],
    1979.0: [],
    1978.0: [_name.pastehran,_name.persepolis,_name.malavan],
    1977.0: [_name.pastehran,_name.persepolis,],
    1976.0: [_name.persepolis,_name.homa,_name.pastehran],
    1975.0: [_name.esteghlal,_name.persepolis,_name.homa],
    1974.0: [_name.persepolis,_name.esteghlal,_name.pastehran,],
    1973.0: [],
    1972.0: [],
    1971.0: [],
    1970.0: [],
    1969.0: [],
    1968.0: [],
    1967.0: [],
    1966.0: [],
    1965.0: [],
    1964.0: [],
    1963.0: [],
    1962.0: [],
    1961.0: [],
    1960.0: [],
  }
};