import 'package:fifa/values/club_names.dart';
import 'package:fifa/values/league_names.dart';


ClubName n = ClubName();
LeagueOfficialNames leagueName = LeagueOfficialNames();

Map<String,dynamic> mapAsia = {

  leagueName.china: {
    //2025.0: [],
    //2024.0: [],
    //2023.0: [n.shanghaisipg,n.shanghaishenhua,n.shandong,n.chengdu,n.beijingguoan,n.zhejiang,n.wuhan3towns,n.tianjin,],
    2022.0: [n.wuhan3towns,n.shandong,n.zhejiang,n.shanghaisipg,n.chengdu,       n.henan,n.beijingguoan,n.tianjin,n.meizhou,n.shanghaishenhua,    n.dalian,n.cangzhou,n.changchun,n.shenzhen,n.ghuangzhouCity,n.wuhan,    n.ghuangzhou,n.hebei],
    2021.0: [n.shandong,n.shanghaisipg,n.ghuangzhou,n.changchun,n.beijingguoan,  n.shenzhen,n.ghuangzhouCity,n.hebei,n.shanghaishenhua,n.henan,   n.cangzhou,n.tianjin,n.chongqing,n.wuhan,n.dalian,n.qingdaofc],
    2020.0: [n.jiangsu,n.ghuangzhou,n.beijingguoan,n.shanghaisipg,n.chongqing,   n.hebei,n.shandong,n.shanghaishenhua,n.shenzhen,n.wuhan,         n.cangzhou,n.ghuangzhouCity,n.dalian,n.qingdaofc,n.henan,n.tianjin],
    2019.0: [n.ghuangzhou,n.beijingguoan,n.shanghaisipg,n.jiangsu,n.shandong,    n.wuhan,n.tianjin,n.dalian,n.chongqing,n.hebei,                  n.ghuangzhouCity,n.shanghaishenhua,n.tianjin,n.shenzhen,n.chengfeng],
    2018.0: [n.shanghaisipg,n.ghuangzhou,n.shandong,n.beijingguoan,n.jiangsu,    n.hebei,n.shanghaishenhua,n.chengfeng,n.tianjin,n.ghuangzhouCity, n.dalian,n.henan,n.chongqing,n.tianjin,n.changchun,n.guizhou],
    2017.0: [n.ghuangzhou,n.shanghaisipg,n.tianjin,n.hebei,n.ghuangzhouCity,     n.shandong,n.changchun,n.chengfeng,n.beijingguoan,n.chongqing,    n.shanghaishenhua,n.jiangsu,n.tianjin,n.henan,n.yanbian,n.liaoning],
    2016.0: [n.ghuangzhou,n.jiangsu,n.shanghaisipg,n.shanghaishenhua,n.beijingguoan, n.ghuangzhouCity,n.hebei,n.chongqing,n.yanbian,n.tianjin,     n.liaoning,n.changchun,n.henan,n.shandong,n.zhejiang,n.cangzhou],
    2015.0: [n.ghuangzhou,n.shanghaisipg,n.shandong,n.beijingguoan,n.henan,       n.shanghaishenhua,n.cangzhou,n.chongqing,n.jiangsu,n.changchun,  n.zhejiang,n.liaoning,n.tianjin,n.ghuangzhouCity,n.chengfeng,n.shenxin],
    2014.0: [n.ghuangzhou,n.beijingguoan,n.ghuangzhouCity,n.shandong,n.shanghaisipg, n.chengfeng,n.tianjin,n.jiangsu,n.shanghaishenhua,n.liaoning, n.shenxin,n.zhejiang,n.changchun,n.henan,n.dalian,n.shaoxing],
    2013.0: [n.ghuangzhou,n.shandong,n.beijingguoan,n.chengfeng,n.dalian,         n.ghuangzhouCity,n.shenxin,n.shanghaishenhua,n.shanghaisipg,n.liaoning,  n.tianjin,n.zhejiang,n.jiangsu,n.changchun,n.qingdaofc,n.wuhan],
    2012.0: [n.ghuangzhou,n.jiangsu,n.beijingguoan,n.chengfeng,n.dalian,          n.changchun,n.ghuangzhouCity,n.tianjin,n.shanghaishenhua,n.liaoning,   n.zhejiang,n.shandong,n.qingdaofc,n.dalian,n.shenxin,n.henan],
    2011.0: [n.ghuangzhou,n.beijingguoan,n.liaoning,n.jiangsu,n.shandong,         n.qingdaofc,n.changchun,n.zhejiang,n.chengfeng,n.tianjin,       n.shanghaishenhua,n.dalian,n.henan,n.shenxin,n.chengdu,n.shenzhen],
    2010.0: [n.shandong,n.tianjin,n.shanghaishenhua,n.zhejiang,n.beijingguoan,    n.dalian,n.liaoning,n.henan,n.changchun,n.chengfeng,          n.jiangsu,n.shenzhen,n.shenxin,n.qingdaofc,n.chongqing,n.ghuangzhouCity],
    2009.0: [n.beijingguoan,n.changchun,n.henan,n.shandong,n.shanghaishenhua,     n.tianjin,n.chengdu,n.dalian,n.ghuangzhou,n.jiangsu,          n.shenzhen,n.chengfeng,n.qingdaofc,n.ghuangzhouCity,n.zhejiang,n.chongqing],
    2008.0: [n.shandong,n.shanghaishenhua,n.beijingguoan,n.tianjin,n.chengfeng,   n.changchun,n.ghuangzhou,n.qingdaofc,n.zhejiang,n.henan,        n.ghuangzhouCity,n.shenzhen,n.chengdu,n.dalian,n.liaoning,n.wuhan],
    2007.0: [n.changchun,n.beijingguoan,n.shandong,n.shanghaishenhua,n.dalian,    n.tianjin,n.wuhan,n.qingdaofc,n.liaoning,n.ghuangzhouCity,      n.zhejiang,n.henan,n.chengfeng,n.shenzhen,n.xiamen],
    2006.0: [n.shandong,n.shanghaishenhua,n.beijingguoan,n.changchun,n.dalian,    n.tianjin,n.shanghaiunited,n.xiamen,n.chengfeng,n.wuhan,      n.shenzhen,n.liaoning,n.ghuangzhouCity,n.qingdaofc,n.chongqing],
    2005.0: [n.dalian,n.shanghaishenhua,n.shandong,n.tianjin,n.wuhan,             n.beijingguoan,n.qingdaofc,n.chengfeng,n.sichuan,n.liaoning,    n.shanghaizobon,n.shenzhen,n.ghuangzhouCity,n.chongqing],
    2004.0: [n.shenzhen,n.shandong,n.chengfeng,n.liaoning,n.dalian,               n.tianjin,n.beijingguoan,n.ghuangzhouCity,n.sichuan,n.shanghaishenhua,  n.qingdaofc,n.chongqing],
    2003.0: [n.shanghaishenhua,n.chengfeng,n.dalian,n.shenzhen,n.ghuangzhouCity,  n.liaoning,n.yunnan,n.sichuan,n.beijingguoan,n.tianjin,       n.qingdaofc,n.shandong,n.chongqing,n.august1,n.harbin],
    2002.0: [n.dalian,n.shenzhen,n.beijingguoan,n.shandong,n.liaoning,            n.chongqing,n.yunnan,n.qingdaofc,n.chengfeng,n.tianjin,         n.ghuangzhouCity,n.shanghaishenhua,n.august1,n.sichuan,n.harbin],
    2001.0: [n.dalian,n.shanghaishenhua,n.liaoning,n.sichuan,n.shenzhen,          n.shandong,n.tianjin,n.beijingguoan,n.harbin,n.yunnan,        n.chongqing,n.august1,n.qingdaofc,n.ghuangzhouCity],
    2000.0: [n.dalian,n.shanghaishenhua,n.sichuan,n.chongqing,n.shandong,         n.beijingguoan,n.ghuangzhouCity,n.liaoning,n.shenzhen,n.tianjin, n.qingdaofc,n.yunnan,n.xiamen,n.yanbian],
    1999.0: [n.shandong,n.liaoning,n.sichuan,n.chongqing,n.shanghaishenhua,       n.beijingguoan,n.tianjin,n.yanbian,n.dalian,n.qingdaofc,        n.ghuangzhouCity,n.shenzhen,n.matsunichi,n.wuhan],
    1998.0: [n.dalian,n.shanghaishenhua,n.beijingguoan,n.matsunichi,n.sichuan,    n.qingdaofc,n.chongqing,n.wuhan,n.shandong,n.ghuangzhouCity,    n.yanbian,n.shenzhen,n.august1,n.ghuangzhou],
    1997.0: [n.dalian,n.shanghaishenhua,n.beijingguoan,n.yanbian,n.chongqing,     n.shandong,n.sichuan,n.ghuangzhou,n.qingdaofc,n.august1,        n.tianjin,n.guangdong],
    1996.0: [n.dalian,n.shanghaishenhua,n.august1,n.beijingguoan,n.shandong,      n.sichuan,n.ghuangzhou,n.tianjin,n.guangdong,n.yanbian,       n.shenzhen,n.matsunichi],
    1995.0: [n.shanghaishenhua,n.beijingguoan,n.dalian,n.guangdong,n.ghuangzhou,  n.shandong,n.yanbian,n.tianjin,n.august1,n.sichuan,           n.qingdaofc,n.liaoning],
    1994.0: [n.dalian,n.ghuangzhou,n.shanghaishenhua,n.liaoning,n.shandong,       n.sichuan,n.guangdong,n.beijingguoan,n.august1,n.yanbian,     n.ghuangzhouCity,n.jiangsu],
    1993.0: [n.liaoning,n.guangdong,n.beijingguoan,n.dalian,n.august1,            n.foshan,n.shanghaishenhua,n.ghuangzhou],
    1992.0: [n.liaoning,n.ghuangzhou,n.dalian,n.august1,n.shanghaishenhua,        n.beijingguoan,n.guangdong,],
    1991.0: [n.liaoning,n.shanghaishenhua,n.beijingguoan,n.ghuangzhouBaiyunshan,n.august1,  n.dalian,n.chinaOlympic,n.tianjin],
    1990.0: [n.liaoning,n.august1,n.dalian,n.shanghaishenhua,n.tianjin,           n.chinaOlympic,n.guangdong,n.henan],
    1989.0: [n.chinaOlympic,n.liaoning,n.shanghaishenhua,n.august1,n.tianjin,n.guangdong,n.shandong,n.ghuangzhou],
    1988.0: [n.liaoning,n.chinaOlympic,n.tianjin,n.shandong,n.guangdong,       n.shanghaishenhua,n.ghuangzhou,n.august1,n.beijingguoan,n.dalian],
    1987.0: [n.liaoning,n.tianjin,n.shanghaishenhua,n.shandong,n.august1,      n.beijingguoan,n.ghuangzhou,n.wuhan],
  },

  leagueName.japao: {
    //2025.0: [],
    //2024.0: [],
    //2023.0: [n.visselkobe,n.yokohamamarinos,n.nagoya,n.urawareddiamonds,n.kashimaantlers,n.cerezoosaka,n.kawasakifrontale,n.avispa,n.hiroshima,n.sagantosu,n.fctokyo,n.gambaosaka,n.sapporo,n.albirex,n.kyoto,n.yokohamafc,n.kashiwareysol,n.shonanbellmare],
    2022.0: [n.yokohamamarinos,n.kawasakifrontale,n.hiroshima,n.kashimaantlers,n.cerezoosaka, n.fctokyo,n.kashiwareysol,n.nagoya,n.urawareddiamonds,n.sapporo,   n.sagantosu,n.shonanbellmare,n.visselkobe,n.avispa,n.kyoto,n.shimizuspulse,n.jubiloiwata],
    2021.0: [n.kawasakifrontale,n.yokohamamarinos,n.visselkobe,n.kashimaantlers,n.nagoya,   n.urawareddiamonds,n.sagantosu,n.avispa,n.fctokyo,n.sapporo,        n.hiroshima,n.cerezoosaka,n.gambaosaka,n.shimizuspulse,n.kashiwareysol,      n.shonanbellmare,n.tokushima,n.oitatrinita,n.vegaltaSendai,n.yokohamafc],
    2020.0: [n.kawasakifrontale,n.gambaosaka,n.nagoya,n.cerezoosaka,n.kashimaantlers,       n.fctokyo,n.kashiwareysol,n.hiroshima,n.yokohamamarinos,n.urawareddiamonds,  n.oitatrinita,n.sapporo,n.sagantosu,n.visselkobe,n.yokohamafc,  n.shimizuspulse,n.vegaltaSendai,n.shonanbellmare],
    2019.0: [n.yokohamamarinos,n.fctokyo,n.kashimaantlers,n.kawasakifrontale,n.cerezoosaka, n.hiroshima,n.gambaosaka,n.visselkobe,n.oitatrinita,n.sapporo,  n.vegaltaSendai,n.shimizuspulse,n.nagoya,n.urawareddiamonds,n.sagantosu,     n.shonanbellmare,n.matsumoto,n.jubiloiwata],
    2018.0: [n.kawasakifrontale,n.hiroshima,n.kashimaantlers,n.sapporo,n.urawareddiamonds,  n.fctokyo,n.cerezoosaka,n.shimizuspulse,n.gambaosaka,n.visselkobe,  n.vegaltaSendai,n.yokohamamarinos,n.shonanbellmare,n.sagantosu,n.nagoya, n.jubiloiwata,n.kashiwareysol,],
    2017.0: [n.kawasakifrontale,n.kashimaantlers,n.cerezoosaka,n.kashiwareysol,n.yokohamamarinos,  n.jubiloiwata,n.urawareddiamonds,n.sagantosu,n.visselkobe,n.gambaosaka, n.sapporo,n.fctokyo,n.shimizuspulse,n.hiroshima,                  n.ventforet,n.albirex,n.omiyaardija],
    2016.0: [n.kashimaantlers,n.urawareddiamonds,n.kawasakifrontale,n.hiroshima,n.omiyaardija, n.gambaosaka,n.kashiwareysol,n.jubiloiwata,n.fctokyo,n.vegaltaSendai,  n.yokohamamarinos,n.visselkobe,n.albirex,n.nagoya,n.sagantosu,     n.shonanbellmare,n.ventforet,n.avispa],
    2015.0: [n.hiroshima,n.gambaosaka,n.urawareddiamonds,n.fctokyo,n.kashimaantlers,        n.kawasakifrontale,n.yokohamamarinos,n.shonanbellmare,n.nagoya,n.kashiwareysol,  n.sagantosu,n.visselkobe,n.ventforet,n.vegaltaSendai,n.albirex,  n.matsumoto,n.shimizuspulse,n.yamagata],
    2014.0: [n.gambaosaka,n.urawareddiamonds,n.kashimaantlers,n.kashiwareysol,n.sagantosu,  n.kawasakifrontale,n.yokohamamarinos,n.hiroshima,n.fctokyo,n.nagoya,   n.visselkobe,n.albirex,n.ventforet,n.vegaltaSendai,n.shimizuspulse,     n.omiyaardija,n.cerezoosaka,n.tokushima],
    2013.0: [n.hiroshima,n.yokohamamarinos,n.kawasakifrontale,n.cerezoosaka,n.kashimaantlers, n.urawareddiamonds,n.albirex,n.fctokyo,n.shimizuspulse,n.kashiwareysol,  n.nagoya,n.sagantosu,n.vegaltaSendai,n.omiyaardija,n.ventforet,     n.shonanbellmare,n.jubiloiwata,n.oitatrinita],
    2012.0: [n.hiroshima,n.vegaltaSendai,n.urawareddiamonds,n.yokohamamarinos,n.sagantosu,    n.kashiwareysol,n.nagoya,n.kawasakifrontale,n.shimizuspulse,n.fctokyo,  n.kashimaantlers,n.jubiloiwata,n.omiyaardija,n.cerezoosaka,n.albirex,   n.visselkobe,n.gambaosaka,n.sapporo],
    2011.0: [n.kashiwareysol,n.nagoya,n.gambaosaka,n.vegaltaSendai,n.yokohamamarinos,         n.kashimaantlers,n.hiroshima,n.jubiloiwata,n.visselkobe,n.shimizuspulse,  n.kawasakifrontale,n.cerezoosaka,n.omiyaardija,n.albirex,n.urawareddiamonds,   n.ventforet,n.avispa,n.yamagata],
    2010.0: [n.nagoya,n.gambaosaka,n.cerezoosaka,n.kashimaantlers,n.kawasakifrontale,         n.shimizuspulse,n.hiroshima,n.yokohamamarinos,n.albirex,n.urawareddiamonds, n.jubiloiwata,n.omiyaardija,n.yamagata,n.vegaltaSendai,n.visselkobe,  n.fctokyo,n.kyoto,n.shonanbellmare],
    2009.0: [n.kashimaantlers,n.kawasakifrontale,n.gambaosaka,n.hiroshima,n.fctokyo,          n.urawareddiamonds,n.shimizuspulse,n.albirex,n.nagoya,n.yokohamamarinos,    n.jubiloiwata,n.kyoto,n.omiyaardija,n.visselkobe,n.yamagata,      n.kashiwareysol,n.oitatrinita,n.jefUnited],
    2008.0: [n.kashimaantlers,n.kawasakifrontale,n.nagoya,n.oitatrinita,n.shimizuspulse,      n.fctokyo,n.urawareddiamonds,n.gambaosaka,n.yokohamamarinos,n.visselkobe,   n.kashiwareysol,n.omiyaardija,n.albirex,n.kyoto,n.jefUnited,      n.jubiloiwata,n.tokyoVerdy,n.sapporo],
    2007.0: [n.kashimaantlers,n.urawareddiamonds,n.gambaosaka,n.shimizuspulse,n.kawasakifrontale,  n.albirex,n.yokohamamarinos,n.kashiwareysol,n.jubiloiwata,n.visselkobe, n.nagoya,n.fctokyo,n.jefUnited,n.oitatrinita,n.omiyaardija,      n.hiroshima,n.ventforet,n.yokohamafc],
    2006.0: [n.urawareddiamonds,n.kawasakifrontale,n.gambaosaka,n.shimizuspulse,n.jubiloiwata,  n.kashimaantlers,n.nagoya,n.oitatrinita,n.yokohamamarinos,n.hiroshima,    n.jefUnited,n.omiyaardija,n.fctokyo,n.albirex,n.ventforet,        n.avispa,n.cerezoosaka,n.kyoto],
    2005.0: [n.gambaosaka,n.urawareddiamonds,n.kashimaantlers,n.jefUnited,n.cerezoosaka,       n.jubiloiwata,n.hiroshima,n.kawasakifrontale,n.yokohamamarinos,n.fctokyo,  n.oitatrinita,n.albirex,n.omiyaardija,n.nagoya,n.shimizuspulse,   n.kashiwareysol,n.tokyoVerdy,n.visselkobe],
    2004.0: [n.yokohamamarinos,n.urawareddiamonds,n.gambaosaka,n.jefUnited,n.jubiloiwata,      n.kashimaantlers,n.nagoya,n.fctokyo,n.tokyoVerdy,n.albirex,                n.visselkobe,n.hiroshima,n.oitatrinita,n.shimizuspulse,n.cerezoosaka,  n.kashiwareysol],
    2003.0: [n.yokohamamarinos,n.jubiloiwata,n.jefUnited,n.fctokyo,n.kashimaantlers,           n.urawareddiamonds,n.nagoya,n.tokyoVerdy,n.cerezoosaka,n.gambaosaka,       n.shimizuspulse,n.kashiwareysol,n.visselkobe,n.oitatrinita,n.vegaltaSendai,  n.kyoto],
    2002.0: [n.jubiloiwata,n.yokohamamarinos,n.gambaosaka,n.kashimaantlers,n.kyoto,            n.nagoya,n.jefUnited,n.shimizuspulse,n.fctokyo,n.tokyoVerdy,               n.urawareddiamonds,n.kashiwareysol,n.vegaltaSendai,n.visselkobe,n.hiroshima,  n.sapporo],
    2001.0: [n.kashimaantlers,n.jubiloiwata,n.jefUnited,n.shimizuspulse,n.nagoya,              n.kashiwareysol,n.gambaosaka,n.fctokyo,n.hiroshima,n.urawareddiamonds,     n.sapporo,n.visselkobe,n.yokohamamarinos,n.tokyoVerdy,n.avispa,     n.cerezoosaka],
    2000.0: [n.kashimaantlers,n.yokohamamarinos,n.kashiwareysol,n.jubiloiwata,n.cerezoosaka,   n.gambaosaka,n.fctokyo,n.shimizuspulse,n.nagoya,n.tokyoVerdy,              n.hiroshima,n.avispa,n.visselkobe,n.jefUnited,n.kyoto,         n.kawasakifrontale],
    1999.0: [n.jubiloiwata,n.shimizuspulse,n.kashiwareysol,n.nagoya,n.yokohamamarinos,         n.cerezoosaka,n.tokyoVerdy,n.hiroshima,n.kashimaantlers,n.visselkobe,      n.gambaosaka,n.kyoto,n.jefUnited,n.avispa,n.urawareddiamonds,  n.shonanbellmare],

    1998.0: [n.kashimaantlers,n.jubiloiwata,n.shimizuspulse,],
    1997.0: [n.jubiloiwata,n.kashimaantlers,n.yokohamamarinos,],
    1996.0: [n.kashimaantlers,n.nagoya,n.flugels,],
    1995.0: [n.yokohamamarinos,n.tokyoVerdy,n.nagoya,],
    1994.0: [n.tokyoVerdy,n.hiroshima,n.kashimaantlers,],
    1993.0: [n.tokyoVerdy,n.kashimaantlers,n.shimizuspulse,],
  },

  leagueName.coreiaSul: {
    //2025.0: [],
    //2024.0: [],
    2023.0: [n.ulsan,n.pohang,n.jeonbuk,n.fcseoul,n.gwangju,  n.incheon,n.daejeon,n.jeju,n.daegu,n.suwonfc,n.gangwon,n.suwonsamsung,],
    2022.0: [n.ulsan,n.jeonbuk,n.pohang,n.incheon,n.jeju,     n.gangwon,n.suwonfc,n.daegu,n.fcseoul,n.suwonsamsung,       n.gimcheon,n.seongnam],
    2021.0: [n.jeonbuk,n.ulsan,n.daegu,n.jeju,n.suwonfc,      n.suwonsamsung,n.fcseoul,n.incheon,n.pohang,n.seongnam,    n.gangwon,n.gwangju],
    2020.0: [n.jeonbuk,n.ulsan,n.pohang,n.gimcheon,n.daegu,   n.gwangju,n.gangwon,n.suwonsamsung,n.fcseoul,n.seongnam,   n.incheon,n.busan],
    2019.0: [n.jeonbuk,n.ulsan,n.fcseoul,n.pohang,n.daegu,    n.gangwon,n.gimcheon,n.suwonsamsung,n.seongnam,n.incheon,  n.gyeongnam,n.jeju],
    2018.0: [n.jeonbuk,n.gyeongnam,n.ulsan,n.pohang,n.jeju,   n.suwonsamsung,n.daegu,n.gangwon,n.incheon,n.gimcheon,     n.fcseoul,n.jeonnam],
    2017.0: [n.jeonbuk,n.jeju,n.suwonsamsung,n.ulsan,n.fcseoul, n.gangwon,n.pohang,n.daegu,n.incheon,n.jeonnam,          n.gimcheon,n.gwangju],
    2016.0: [n.fcseoul,n.jeonbuk,n.jeju,n.ulsan,n.jeonnam,      n.gimcheon,n.suwonsamsung,n.gwangju,n.pohang,n.incheon,    n.seongnam,n.suwonfc],
    2015.0: [n.jeonbuk,n.suwonsamsung,n.pohang,n.fcseoul,n.seongnam, n.jeju,n.ulsan,n.incheon,n.jeonnam,n.gwangju,       n.busan,n.daejeon],
    2014.0: [n.jeonbuk,n.suwonsamsung,n.fcseoul,n.pohang,n.jeju,  n.ulsan,n.jeonnam,n.busan,n.seongnam,n.incheon,         n.gyeongnam,n.gimcheon],
    2013.0: [n.pohang,n.ulsan,n.jeonbuk,n.fcseoul,n.suwonsamsung, n.busan,n.incheon,n.seongnam,n.jeju,n.jeonnam,          n.gyeongnam,n.gangwon,n.daegu,n.daejeon],
    2012.0: [n.fcseoul,n.jeonbuk,n.pohang,n.suwonsamsung,n.ulsan, n.jeju,n.busan,n.gyeongnam,n.incheon,n.daegu,          n.jeonnam,n.seongnam,n.daejeon,n.gangwon,n.gwangju,n.gimcheon],
    2011.0: [n.jeonbuk,n.ulsan,n.pohang,n.suwonsamsung,n.fcseoul, n.busan,n.jeonnam,n.gyeongnam,n.jeju,n.seongnam,       n.gwangju,n.daegu,n.incheon,n.gimcheon,n.daejeon,n.gangwon],
    2010.0: [n.fcseoul,n.jeju,n.jeonbuk,n.ulsan,n.seongnam,       n.gyeongnam,n.suwonsamsung,n.busan,n.pohang,n.jeonnam, n.incheon,n.gangwon,n.daejeon,n.gimcheon,n.daegu],
    2009.0: [n.jeonbuk,n.seongnam,n.pohang,n.jeonnam,n.fcseoul,   n.incheon,n.gyeongnam,n.ulsan,n.daejeon,n.suwonsamsung, n.gimcheon,n.busan,n.gangwon,n.jeju,n.daegu],
    2008.0: [n.suwonsamsung,n.fcseoul,n.ulsan,n.jeonbuk,n.seongnam, n.pohang,n.incheon,n.gyeongnam,n.jeonnam,n.jeju,      n.daegu,n.busan,n.daejeon,n.gwangju],
    2007.0: [n.pohang,n.seongnam,n.suwonsamsung,n.ulsan,n.gyeongnam, n.daejeon,n.fcseoul,n.jeonbuk,n.incheon,n.jeonnam,  n.jeju,n.daegu,n.busan,n.gwangju],
    2006.0: [n.seongnam,n.suwonsamsung,n.pohang,n.fcseoul,n.ulsan,   n.jeonnam,n.daegu,n.busan,n.incheon,n.daejeon,   n.jeonbuk,n.gyeongnam,n.jeju,n.gimcheon],
    2005.0: [n.ulsan,n.incheon,n.seongnam,n.busan,n.pohang,       n.fcseoul,n.daejeon,n.daegu,n.suwonsamsung,n.busan, n.jeonnam,n.jeonbuk,n.gimcheon],
    2004.0: [n.suwonsamsung,n.pohang,n.ulsan,n.jeonnam,n.fcseoul,    n.jeonbuk,n.busan,n.gimcheon,n.seongnam,n.daegu, n.daejeon,n.incheon,n.jeju],
    2003.0: [n.seongnam,n.ulsan,n.suwonsamsung,n.jeonnam,n.jeonbuk,  n.daejeon,n.pohang,n.fcseoul,n.busan,n.gimcheon, n.daegu,n.jeju],
    2002.0: [n.seongnam,n.ulsan,n.suwonsamsung,n.fcseoul,n.jeonnam,  n.pohang,n.jeonbuk,n.jeju,n.busan,n.daegu],
    2001.0: [n.seongnam,n.fcseoul,n.suwonsamsung,n.busan,n.pohang,   n.ulsan,n.jeju,n.jeonnam,n.jeonbuk,n.daejeon],
    2000.0: [n.fcseoul,n.jeju,n.seongnam,n.jeonbuk,n.suwonsamsung,   n.busan,n.jeonnam,n.daejeon,n.pohang,n.ulsan],
    1999.0: [n.suwonsamsung,n.busan,n.jeju,n.jeonnam,n.pohang,       n.ulsan,n.jeonbuk,n.daejeon,n.fcseoul,n.seongnam],
    1998.0: [n.suwonsamsung,n.ulsan,n.pohang,n.jeonnam,n.busan,      n.jeonbuk,n.jeju,n.fcseoul,n.daejeon,n.seongnam],
    1997.0: [n.busan,n.jeonnam,n.ulsan,n.pohang,n.suwonsamsung,      n.jeonbuk,n.daejeon,n.seongnam,n.fcseoul,n.jeju],
    1996.0: [n.ulsan,n.suwonsamsung,n.pohang,n.jeju,n.jeonbuk,       n.jeonnam,n.busan,n.fcseoul,n.seongnam],
    1995.0: [n.seongnam,n.pohang,n.ulsan,n.jeju,n.jeonnam,           n.jeonbuk,n.busan,n.fcseoul],
    1994.0: [n.seongnam,n.jeju,n.pohang,n.ulsan,n.fcseoul,n.busan,n.chonbuk],
    1993.0: [n.seongnam,n.fcseoul,n.ulsan,n.pohang,n.jeju,n.busan],
    1992.0: [n.pohang,n.seongnam,n.ulsan,n.fcseoul,n.busan,n.jeju],
    1991.0: [n.busan,n.ulsan,n.pohang,n.jeju,n.seongnam,n.fcseoul],
    1990.0: [n.fcseoul,n.busan,n.pohang,n.jeju,n.ulsan,n.seongnam],
    1989.0: [n.jeju,n.fcseoul,n.busan,n.pohang,n.seongnam,n.ulsan],
    1988.0: [n.pohang,n.ulsan,n.jeju,n.fcseoul,n.busan],
    1987.0: [n.busan,n.pohang,n.jeju,n.ulsan,n.fcseoul],
    1986.0: [n.pohang,n.fcseoul,n.busan,n.ulsan,n.jeju,n.hanil,],
    1985.0: [n.fcseoul,n.pohang,n.busan,n.ulsan,n.jeju,n.gimcheon,n.hanil,n.hallelujah],
    1984.0: [n.busan,n.jeju,n.ulsan,n.hallelujah,n.pohang,n.hanil,n.fcseoul,n.kookmin],
    1983.0: [n.hallelujah,n.busan,n.jeju,n.pohang,n.kookmin],
  },

  leagueName.bangladesh: {
    //https://en.wikipedia.org/wiki/Bangladesh_Premier_League_(football)

    //2025.0: [],
    //2024.0: [],
    2023.0: [],
    2022.0: [n.bashundhara,n.dhakaAbahani,n.saif,],
    2021.0: [n.bashundhara,n.sheikhJamal,n.dhakaAbahani,],
    2020.0: [],
    2019.0: [n.bashundhara,n.dhakaAbahani,n.sheikhrussel,],
    2018.0: [n.dhakaAbahani,n.sheikhJamal,n.chittagong,],
    2017.0: [],
    2016.0: [n.dhakaAbahani,n.chittagong,n.sheikhrussel,],
    2015.0: [n.sheikhJamal,n.sheikhrussel,n.mohammedan,],
    2014.0: [n.sheikhJamal,n.dhakaAbahani,n.muktijoddgrenlandha,],
    2013.0: [n.sheikhrussel,n.sheikhJamal,n.dhakaAbahani,],
    2012.0: [n.dhakaAbahani,n.muktijoddgrenlandha,n.mohammedan,],
    2011.0: [n.sheikhJamal,n.muktijoddgrenlandha,n.sheikhrussel,],
    2010.0: [n.dhakaAbahani,n.mohammedan,n.sheikhrussel,],
    2009.0: [n.dhakaAbahani,n.mohammedan,n.sheikhrussel,],
    2008.0: [],
    2007.0: [n.dhakaAbahani,n.mohammedan,n.muktijoddgrenlandha,],
  },

  leagueName.brunei: {
  //https://en.wikipedia.org/wiki/Brunei_Super_League
    //2025.0: [],
    //2024.0: [],
    //2023.0: [n.kasuka,n.indera,n.msabdb,n.msppdb,n.aksebersatu,n.kotaranger,n.kualabelait,n.wijaya,],
    2022.0: [],
    2021.0: [],
    2020.0: [],
    2019.0: [n.msabdb,n.kasuka,n.wijaya,n.indera,n.kotaranger,],
    2018.0: [n.msabdb,n.kotaranger,n.indera,],
    2017.0: [],
    2016.0: [n.msabdb,n.indera,n.wijaya,],
    2015.0: [n.msabdb,n.indera,n.najip,],
    2014.0: [n.indera,n.msabdb,n.najip,],
    2013.0: [n.indera,n.msabdb,],
  },

  leagueName.butao: {
    //https://en.wikipedia.org/wiki/Bhutan_Premier_League
    //2025.0: [],
    //2024.0: [],
    2023.0: [],
    2022.0: [n.paro,n.thimphucity],
    2021.0: [n.paro,n.thimphucity,],
    2020.0: [n.thimphucity,n.ugyen,n.paro,],
    2019.0: [n.paro,n.transportutd,n.thimphucity,],
    2018.0: [n.transportutd,n.paro,n.thimphucity,],
    2017.0: [n.transportutd,n.thimphucity,n.ugyen,],
    2016.0: [n.thimphucity,n.drukutd,n.ugyen,],
    2015.0: [n.terton,n.thimphu,n.thimphucity,],
    2014.0: [n.drukutd,n.ugyen,n.thimphucity,],
    2013.0: [n.ugyen,n.yeedzin,n.thimphucity,],
    2012.0: [n.yeedzin,n.drukpol,n.ugyen,],
  },

  leagueName.camboja: {
    //2025.0: [],
    //2024.0: [],
    2023.0: [],
    2022.0: [n.phnomPenhCrown,n.visakha,n.preahKhan,n.boeungKet,n.nagaworld,      n.tiffy,n.angkor,n.kirivong],
    2021.0: [n.phnomPenhCrown,n.preahKhan,n.visakha,n.nagaworld,n.boeungKet,      n.angkor,n.tiffy,n.kirivong],
    2020.0: [n.boeungKet,n.preahKhan,n.phnomPenhCrown,n.tiffy,n.visakha,          ],
    2019.0: [n.preahKhan,n.visakha,n.nagaworld,n.boeungKet,n.angkor,              ],
    2018.0: [n.nagaworld,n.boeungKet,n.visakha,n.nationaldef,n.phnomPenhCrown,    ],
    2017.0: [n.boeungKet,n.preahKhan,n.nagaworld,n.nationaldef,n.phnomPenhCrown,  ],
    2016.0: [n.boeungKet,n.nationaldef,n.nagaworld,n.preahKhan,n.phnomPenhCrown,  ],
    2015.0: [n.phnomPenhCrown,n.nagaworld,n.boeungKet,n.angkor,n.nationaldef,     ],
    2014.0: [n.phnomPenhCrown,n.boeungKet,n.nagaworld,n.svayrieng,n.angkor,       ],
    2013.0: [n.svayrieng,n.boeungKet,n.phnomPenhCrown,n.buildbright,n.nagaworld,  ],
    2012.0: [n.boeungKet,n.nagaworld,n.preahKhan,n.policeCAMB,n.phnomPenhCrown,   ],
    2011.0: [n.phnomPenhCrown,n.nagaworld,n.preahKhan,n.nationaldef,n.buildbright,],
    2010.0: [n.phnomPenhCrown,n.preahKhan,n.buildbright,n.nagaworld,n.kirivong,   ],
    2009.0: [n.nagaworld,n.khemara,n.preahKhan,n.phnomPenhCrown,n.kirivong,       ],
    2008.0: [n.phnomPenhCrown,n.nationaldef,n.nagaworld,n.preahKhan,n.buildbright,],
    2007.0: [n.nagaworld,n.khemara,n.phnomPenhCrown,n.tiffy,n.buildbright,        ],
    2006.0: [n.khemara,n.nagaworld,n.phnomPenhCrown,],
    2005.0: [n.khemara,n.phnomPenhCrown,n.policeCAMB,n.nagaworld,],
  },

  leagueName.cingapura: {
    //2025.0: [],
    //2024.0: [],
    2023.0: [],
    2022.0: [n.albirexSINGAPORE,],
    2021.0: [n.lionCitySailors,],
    2020.0: [n.tampines,],
    2019.0: [n.bruneidpmm,],
    2018.0: [n.albirexSINGAPORE,n.tampines,],
    2017.0: [n.albirexSINGAPORE,n.tampines,],
    2016.0: [n.albirexSINGAPORE,n.tampines,],
    2015.0: [n.bruneidpmm,n.tampines,],
    2014.0: [n.warriors,n.bruneidpmm,],
    2013.0: [n.tampines,n.lionCitySailors,],
    2012.0: [n.tampines,n.bruneidpmm,],
    2011.0: [n.tampines,n.lionCitySailors,],
    2010.0: [],
    2009.0: [n.warriors,n.tampines,],
    2008.0: [n.warriors,],
    2007.0: [n.warriors,n.lionCitySailors,],
    2006.0: [n.warriors,n.tampines,],
    2005.0: [n.tampines,n.warriors,],
    2004.0: [n.tampines,n.lionCitySailors,],
    2003.0: [n.lionCitySailors,n.geylang,],
    2002.0: [n.warriors,n.lionCitySailors,],
    2001.0: [n.geylang,n.warriors,],
    2000.0: [n.warriors,],
    1999.0: [n.lionCitySailors,],
    1998.0: [n.warriors,],
    1997.0: [n.warriors,],
    1996.0: [n.geylang,n.warriors,],
  },

  leagueName.coreiaNorte: {
    //https://www.rsssf.org/tablesn/nkorchamp.html
    //2025.0: [],
    //2024.0: [],
    2023.0: [],
    2022.0: [n.april25,n.ryomyong,n.kigwancha,],
    2021.0: [],
    2020.0: [],
    2019.0: [n.april25,n.ryomyong,n.sobaeksu,],
    2018.0: [n.april25,n.ryomyong,n.kigwancha,],
    2017.0: [n.april25,n.hwaebul,],
    2016.0: [n.kigwancha,n.april25,n.amnokgang,],
    2015.0: [n.april25,n.hwaebul,],
    2014.0: [n.hwaebul,n.april25,n.amnokgang,],
    2013.0: [n.april25,],
    2012.0: [n.april25,n.sonbong,n.ryomyong,],
    2011.0: [n.april25,n.sobaeksu,n.amnokgang,],
    2010.0: [n.april25,n.sobaeksu,n.amnokgang,],
    2009.0: [n.pyongyang,],
    2008.0: [n.amnokgang,],
    2007.0: [n.pyongyang,n.amnokgang],
    2006.0: [n.amnokgang,],
    2005.0: [n.pyongyang,],
    2004.0: [n.pyongyang,],
    2003.0: [n.april25,],
    2002.0: [n.april25,],
    2001.0: [n.amnokgang,],
    2000.0: [n.kigwancha,],
    1999.0: [n.kigwancha,],
    1998.0: [n.kigwancha,],
    1997.0: [n.kigwancha,],
    1996.0: [n.kigwancha,],
    1995.0: [n.april25,],
    1994.0: [n.april25,],
    1993.0: [n.april25,],
    1992.0: [n.april25,],
    1991.0: [n.pyongyang,],
    1990.0: [n.april25,],
    1989.0: [n.chandongcha,],
    1988.0: [n.april25,],
    1987.0: [n.april25,],
    1986.0: [n.april25,],
    1985.0: [n.april25,],
  },

  leagueName.hongkong: {
    //https://en.wikipedia.org/wiki/List_of_Hong_Kong_football_champions

    //2025.0: [],
    //2024.0: [],
    2023.0: [n.kitchee,n.leeMan,n.rangersHK,],
    2022.0: [],
    2021.0: [n.kitchee,n.easternSC,n.leeMan,],
    2020.0: [n.kitchee,n.easternSC,n.rf,],
    2019.0: [n.taipo,n.rf,n.southerndistrict,],
    2018.0: [n.kitchee,n.taipo,n.pegasus,],
    2017.0: [n.kitchee,n.easternSC,n.southerndistrict,],
    2016.0: [n.easternSC,n.kitchee,n.southchina,],
    2015.0: [n.kitchee,n.easternSC,n.pegasus,],
    2014.0: [n.kitchee,n.pegasus,n.southchina,],
    2013.0: [n.southchina,n.kitchee,n.tuenmun,],
    2012.0: [n.kitchee,n.pegasus,n.southchina,],
    2011.0: [n.kitchee,n.southchina,n.pegasus,],
    2010.0: [n.southchina,n.pegasus,n.kitchee,],
    2009.0: [n.southchina,n.kitchee,n.citizen,],
    2008.0: [n.southchina,n.citizen,n.taipo,],
    2007.0: [n.southchina,n.kitchee,n.sunhei,],
    2006.0: [n.happyvalley,n.sunhei,n.rangersHK,],
    2005.0: [n.sunhei,n.happyvalley,n.kitchee,],
    2004.0: [n.sunhei,n.kitchee,n.happyvalley,],
    2003.0: [n.happyvalley,n.sunhei,n.rangersHK,],
    2002.0: [n.sunhei,n.happyvalley,n.southchina,],
    2001.0: [n.happyvalley,n.instantdict,n.southchina,],
    2000.0: [n.southchina,n.sunhei,n.happyvalley,],
    1999.0: [n.happyvalley,n.southchina,n.yeehope,],
    1998.0: [n.instantdict,n.southchina,n.happyvalley,],
    1997.0: [n.southchina,n.instantdict,n.sunhei,],
    1996.0: [n.instantdict,n.southchina,n.sunhei,],
    1995.0: [n.easternSC,n.southchina,n.sunhei,],
    1994.0: [n.easternSC,n.instantdict,n.southchina,],
    1993.0: [n.easternSC,n.southchina,n.instantdict,],
    1992.0: [n.southchina,n.easternSC,n.happyvalley,],
    1991.0: [n.southchina,n.happyvalley,n.laisun,],
    1990.0: [n.southchina,n.easternSC,n.happyvalley,],
    1989.0: [n.happyvalley,n.southchina,n.laisun,],
    1988.0: [n.southchina,n.happyvalley,n.singtao,],
    1987.0: [n.southchina,n.easternSC,n.happyvalley,],
    1986.0: [n.southchina,n.happyvalley,],
    1985.0: [n.seiko,n.southchina,],
    1984.0: [n.seiko,n.bulova,n.happyvalley,],
    1983.0: [n.seiko,n.bulova,n.easternSC,],
    1982.0: [n.seiko,n.happyvalley,n.bulova,],
    1981.0: [n.seiko,n.southchina,n.happyvalley,],
    1980.0: [n.seiko,n.happyvalley,n.bulova,],
    1979.0: [n.seiko,n.happyvalley,n.easternSC,],
    1978.0: [n.southchina,n.happyvalley,],
    1977.0: [n.southchina,n.seiko,n.happyvalley,],
    1976.0: [n.southchina,n.seiko,n.rangersHK,],
    1975.0: [n.seiko,n.happyvalley,n.rangersHK,],
    1974.0: [n.southchina,n.seiko,],
    1973.0: [n.seiko,n.southchina,],
    1972.0: [n.southchina,],
    1971.0: [n.rangersHK,n.jardines,n.singtao,],
    1970.0: [n.jardines,n.singtao,],
    1969.0: [n.southchina,n.singtao,n.jardines,],
    1968.0: [n.southchina,n.singtao,n.easternSC,],
    1967.0: [n.kmb,n.southchina,n.singtao,],
    1966.0: [n.southchina,n.happyvalley,n.singtao,],
    1965.0: [n.happyvalley,n.southchina,n.singtao,],
    1964.0: [n.kitchee,n.happyvalley,n.southchina,],
    1963.0: [n.yuenlong,n.tungwah,n.kitchee,],
    1962.0: [n.southchina,n.happyvalley,n.singtao,],
    1961.0: [n.southchina,n.happyvalley,n.tungwah,],
    1960.0: [n.southchina,n.happyvalley,n.tungwah,],
    1959.0: [n.southchina,n.kmb,n.tungwah,],
    1958.0: [n.southchina,n.kmb,n.kitchee,],
    1957.0: [n.southchina,n.kitchee,n.kmb,],
    1956.0: [n.easternSC,n.southchina,n.kmb,],
    1955.0: [n.southchina,n.kitchee,n.kmb,],
    1954.0: [n.kmb,n.southchina,n.kitchee,],
    1953.0: [n.southchina,n.kitchee,n.easternSC,],
    1952.0: [n.southchina,],
    1951.0: [n.southchina,n.kmb,],
    1950.0: [n.kitchee,n.kmb,],
    1949.0: [n.southchina,n.kmb,],
    1948.0: [n.kitchee,n.singtao,n.kmb,],
    1947.0: [n.singtao,n.southchina,],
  },

  leagueName.india: {
    //2025.0: [],
    //2024.0: [],
    2023.0: [],
    2022.0: [n.hyderabad,n.kerala,n.jamshedpur,n.mohunbagan,  n.mumbai,n.bengaluru,n.odisha,n.chennaiyin,n.goa,n.northeast,              n.eastbengal],
    2021.0: [n.mumbai,n.mohunbagan,n.northeast,n.goa,         n.hyderabad,n.jamshedpur,n.bengaluru,n.chennaiyin,n.eastbengal,n.kerala,   n.odisha],
    2020.0: [n.mohunbagan,n.chennaiyin,n.goa,n.bengaluru,     n.mumbai,n.odisha,n.kerala,n.jamshedpur,n.northeast,n.hyderabad],
    2019.0: [n.bengaluru,n.goa,n.mumbai,n.northeast,    n.jamshedpur,n.mohunbagan,n.pune,n.delhi,n.kerala,n.chennaiyin],
    2018.0: [n.chennaiyin,n.bengaluru,n.goa,n.pune,     n.jamshedpur,n.kerala,n.mumbai,n.delhi,n.mohunbagan,n.northeast],
    2017.0: [n.aizawl,n.mohunbagan,n.eastbengal,],
    2016.0: [n.bengaluru,n.mohunbagan,n.eastbengal,],
    2015.0: [n.mohunbagan,n.bengaluru,],
    2014.0: [n.bengaluru,n.eastbengal,n.salgaocar,],
    2013.0: [n.churchill,n.pune,n.eastbengal],
    2012.0: [n.dempo,n.eastbengal,n.churchill,],
    2011.0: [n.salgaocar,n.eastbengal,n.dempo,],
    2010.0: [n.dempo,n.churchill,n.pune],
    2009.0: [n.churchill,n.mohunbagan,n.sportingGoa,],
    2008.0: [n.dempo,n.churchill,n.jct,],
    2007.0: [n.dempo,n.jct,n.mahindra,n.mahindra,],
    2006.0: [n.mahindra,n.eastbengal,n.mohunbagan,],
    2005.0: [n.dempo,n.sportingGoa,n.eastbengal,],
    2004.0: [n.eastbengal,n.dempo,n.mahindra,],
    2003.0: [n.eastbengal,n.salgaocar,n.vascoIND,],
    2002.0: [n.mohunbagan,n.churchill,n.vascoIND,],
    2001.0: [n.eastbengal,n.mohunbagan,n.churchill,],
    2000.0: [n.mohunbagan,n.churchill,n.salgaocar,],
    1999.0: [n.salgaocar,n.eastbengal,n.churchill,],
    1998.0: [n.mohunbagan,n.eastbengal,n.salgaocar,],
    1997.0: [n.jct,n.churchill,n.eastbengal,],
  },
  leagueName.maldivas: {
    //https://en.wikipedia.org/wiki/Dhivehi_Premier_League
    //2025.0: [],
    //2024.0: [],
    2023.0: [],
    2022.0: [n.maziya,n.eaglesmale,],
    2021.0: [n.maziya,n.valenciaMALD,],
    2020.0: [n.maziya,n.eaglesmale,],
    2019.0: [],
    2018.0: [n.tcsports,n.maziya,],
    2017.0: [n.newradiant,n.tcsports,],
    2016.0: [n.maziya,n.tcsports,],
    2015.0: [n.newradiant,n.tcsports,],
  },

  leagueName.tailandia: {
    //https://en.wikipedia.org/wiki/Thai_League_1
    //https://www.rsssf.org/tablest/thaichamp.html
    //2025.0: [],
    //2024.0: [],
    2023.0: [n.buriram,n.bangkok,n.portfc,n.muangthong,n.chiangmai,n.chonburi,n.policetero,n.ratchaburi,n.pathum,n.lamphun,n.prachuap,n.sukhothai,n.khonkaen,n.nakhon,n.nongbuapitchaya,n.lampang],
    2022.0: [n.buriram,n.pathum,n.bangkok,n.muangthong,n.chiangrai,n.nongbuapitchaya,n.chonburi,n.portfc,n.nakhon,n.khonkaen,n.policetero,n.ratchaburi,n.prachuap,n.suphanburi,n.samutprakan,n.chiangmai],
    2021.0: [n.pathum,n.buriram,n.portfc,n.chiangrai,n.bangkok,   n.samutprakan,n.muangthong,n.ratchaburi,n.nakhon,n.prachuap,n.policetero,n.chonburi,n.suphanburi,n.sukhothai,n.trat,n.rayong],
    2020.0: [],
    2019.0: [n.chiangrai,n.buriram,n.portfc,n.bangkok,n.muangthong,  n.samutprakan,n.chonburi,n.ratchaburi,n.prachuap,n.trat,n.rayong,n.sukhothai,n.nakhon,n.suphanburi,n.chainat,n.chiangmai],
    2018.0: [n.buriram,n.bangkok,n.portfc,n.muangthong,n.chiangrai,  n.prachuap,n.nakhon,n.pattaya,n.chonburi,n.suphanburi,n.sukhothai,n.ratchaburi,n.chainat,n.pathum,n.policetero,n.navyTHAI,n.ubon,n.airforceTHAI],
    2017.0: [n.buriram,n.muangthong,n.bangkok,n.chiangrai,n.pathum,  n.ratchaburi,n.chonburi,n.pattaya,n.portfc,n.ubon,n.suphanburi,n.nakhon,n.navyTHAI,n.policetero,n.sukhothai,n.thaihonda,n.sisaket,n.supersamut],
    2016.0: [n.muangthong,n.bangkok,n.pathum,n.buriram,n.chonburi,   n.ratchaburi,n.sukhothai,n.chiangrai,n.policetero,n.suphanburi,n.nakhon,n.pattaya,n.sisaket,n.navyTHAI,n.supersamut,n.armyTHAI,n.chainat,n.bbcu],
    2015.0: [n.buriram,n.muangthong,n.suphanburi,n.chonburi,n.bangkok, n.pathum,n.ratchaburi,n.nakhon,n.chiangrai,n.armyTHAI,n.supersamut,n.chainat,n.sisaket,n.saraburi,n.navyTHAI,n.policetero,n.portfc,n.tot,],
    2014.0: [n.buriram,n.chonburi,n.policetero,n.ratchaburi,n.muangthong, n.suphanburi,n.chiangrai,n.bangkok,n.armyTHAI,n.pathum,n.supersamut,n.sisaket,n.portfc,n.chainat,n.tot,n.policeTHAI,n.rayong,n.songkhla,n.airforceTHAI,n.samutsongkhram],
    2013.0: [n.buriram,n.muangthong,n.chonburi,n.suphanburi,n.pathum, n.armyTHAI,n.policetero,n.supersamut,n.policeTHAI,n.chainat,n.chiangrai,n.songkhla,n.bangkok,n.tot,n.ratchaburi,n.samutsongkhram,n.pattaya,n.sisaket],
    2012.0: [n.muangthong,n.chonburi,n.policetero,n.buriram,n.supersamut,  n.sisaket,n.samutsongkhram,n.pathum,n.chiangrai,n.armyTHAI,n.policeTHAI,n.tot,n.songkhla,n.chainat,n.pattaya,n.portfc,n.bbcu,n.ttm],
    2011.0: [n.buriram,n.chonburi,n.muangthong,n.pattaya,n.pathum,   n.supersamut,n.portfc,n.policetero,n.policeTHAI,n.chiangrai,n.ttm,n.sisaket,n.armyTHAI,n.tot,n.samutsongkhram,n.navyTHAI,n.thawiwatthana,n.khonkaen],
    2010.0: [n.muangthong,n.buriram,n.chonburi,n.portfc,n.pathum,    n.pattaya,n.supersamut,n.samutsongkhram,n.policetero,n.navyTHAI,n.policeTHAI,n.tot,n.ttm,n.sisaket,n.bangkok,n.armyTHAI],
    2009.0: [n.muangthong,n.chonburi,n.pathum,n.policetero,n.supersamut,  n.portfc,n.tot,n.ttm,n.buriram,n.samutsongkhram,n.pattaya,n.navyTHAI,n.bangkok,n.nakhon,n.bbcu,n.nakhonpathom],
    2008.0: [n.buriram,n.chonburi,n.policetero,n.supersamut,n.tot,       n.krungthaibank,n.samutsongkhram,n.bbcu,n.nakhonpathom,n.bangkok,n.pattaya,n.ttm,n.portfc,n.bangkokbank,n.armyTHAI,n.customsutd],
    2007.0: [n.chonburi,n.krungthaibank,n.policetero,n.bangkok,n.armyTHAI,n.ttm,n.bangkokbank,n.buriram,n.supersamut,n.tot,n.nakhonpathom,n.portfc,n.suphanburi,n.thaihonda,n.navyTHAI,n.policeTHAI],
    2006.0: [n.bangkok,n.supersamut,n.policetero,n.ttm,n.bangkokbank,n.armyTHAI,n.portfc,n.chonburi,n.krungthaibank,n.buriram,n.thaihonda,n.suphanburi],
    2005.0: [n.ttm,n.buriram,n.supersamut,n.portfc,n.krungthaibank,n.policetero,n.bangkok,n.bangkokbank,n.tot,n.navyTHAI,],
    2004.0: [n.krungthaibank,n.policetero,n.supersamut,n.bangkok,n.portfc,n.bangkokbank,n.navyTHAI,n.ttm,n.airforceTHAI,n.sinthana],
    2003.0: [n.krungthaibank,n.policetero,n.portfc,n.bangkokbank,n.airforceTHAI,n.supersamut,n.sinthana,n.ttm,n.tot,n.bcc],
    2002.0: [n.policetero,n.supersamut,n.bangkokbank,n.airforceTHAI,n.sinthana,n.portfc,n.krungthaibank,n.ttm,n.tot,n.navyTHAI,n.policeTHAI,n.rbac],
    2001.0: [],
    2000.0: [n.policetero,n.airforceTHAI,n.thai,n.rbac,n.portfc,n.navyTHAI,n.policeTHAI,n.supersamut,n.bangkokbank,n.krungthaibank,n.sinthana,n.tot],
    1999.0: [n.airforceTHAI,n.portfc,n.policetero,n.supersamut,n.tot,n.thai,n.sinthana,n.bangkokbank,n.rbac,n.krungthaibank,n.armyTHAI,],
    1998.0: [n.sinthana,n.airforceTHAI,n.policetero,n.portfc,n.bangkokbank,n.tot,n.armyTHAI,n.thai,n.krungthaibank,n.supersamut,n.rbac,n.rajpracha],
    1997.0: [n.airforceTHAI,n.sinthana,n.bangkokbank,n.portfc,n.policetero,n.thai,n.rbac,n.tot,n.armyTHAI,n.rajpracha,n.policeTHAI,n.navyTHAI,],
    1996.0: [n.bangkokbank,n.rbac,n.thai,n.tot,n.rajpracha,n.sinthana,n.airforceTHAI,n.armyTHAI,n.navyTHAI,n.policeTHAI,n.portfc,n.policetero,n.ttm,n.supersamut,],
    //Khǒr Royal Cup
    1995.0: [n.thai,],
    1994.0: [n.bangkokbank,],
    1993.0: [n.thai,],
    1992.0: [n.thai,n.bangkokbank,],
    1991.0: [n.thai,n.portfc,],
    1990.0: [n.portfc,],
    1989.0: [n.krungthaibank],
    1988.0: [n.krungthaibank,],
    1987.0: [n.airforceTHAI,],
    1986.0: [n.bangkokbank,n.rajpracha,],
    1985.0: [n.portfc,n.bangkokbank,],
    1984.0: [n.bangkokbank,n.krungthaibank,],
    1983.0: [n.armyTHAI,],
    1982.0: [n.rajpracha,],
    1981.0: [n.bangkokbank,],
    1980.0: [n.rajpracha,],
    1979.0: [n.portfc,],
    1978.0: [n.portfc,],
    1977.0: [n.rajvithi,],
    1976.0: [n.portfc,],
    1975.0: [n.rajvithi,],
    1974.0: [n.portfc,],
    1973.0: [n.rajvithi,],
    1972.0: [n.portfc,],
    1971.0: [n.rajpracha,],
    1970.0: [n.rajpracha,],
    1969.0: [n.bangkokbank,n.airforceTHAI,],
    1968.0: [n.portfc,],
    1967.0: [n.bangkokbank,n.airforceTHAI,],
    1966.0: [n.bangkokbank,],
    1965.0: [n.policeTHAI,],
    1964.0: [n.bangkokbank,],
  },


  leagueName.filipinas: {
    //2025.0: [],
    //2024.0: [],
    2023.0: [],
    2022.0: [],
    2021.0: [],
    2020.0: [n.unitedCity,n.kaya,n.azkals,],
    2019.0: [n.unitedCity,n.kaya,n.stallionLaguna,],
    2018.0: [n.unitedCity,n.kaya,n.davao,n.stallionLaguna,],
    2017.0: [n.unitedCity,n.globalCebu,n.loyola,],
    2016.0: [],
    2015.0: [n.loyola,],
    2014.0: [n.unitedCity,],
    2013.0: [n.unitedCity,],
    2012.0: [],
    2011.0: [n.globalCebu,],
  },



  leagueName.indonesia: {
    //https://en.wikipedia.org/wiki/1994%E2%80%9395_Liga_Indonesia_Premier_Division

    //2025.0: [],
    //2024.0: [],
    2023.0: [],
    2022.0: [n.bali,n.persib,n.bhayangkara,n.arema,n.persebaya,n.borneo,n.psis,n.persija,n.madura,],
    2021.0: [],
    2020.0: [n.persib,n.bali,n.borneo,n.persipura,n.psis,n.psmMakassar,n.persiraja,n.madura,n.persija,],
    2019.0: [n.bali,n.persebaya,n.persipura,n.bhayangkara,n.madura,n.persib,n.borneo,n.pss,n.arema,n.persija,n.persela,n.psmMakassar,],
    2018.0: [n.persija,n.psmMakassar,],
    2017.0: [n.bhayangkara,n.bali,],
    2016.0: [],
    2015.0: [],
    2014.0: [n.persib,n.persipura,n.arema,n.madura,],
    2013.0: [n.persipura,n.arema,],
    2012.0: [n.sriwijaya,n.persipura,],
    2011.0: [n.persipura,n.arema,],
    2010.0: [n.arema,n.persipura,],
    2009.0: [n.persipura,n.persiwa,],
    2008.0: [n.sriwijaya,],
    2007.0: [],
    2006.0: [],
    2005.0: [n.persipura,n.persija,n.psis,n.psmsMedan, ],
    2004.0: [n.persebaya,],
    2003.0: [],
    2002.0: [],
    2001.0: [n.persija,n.psmMakassar],
    2000.0: [n.psmMakassar,n.bontang,],
    1999.0: [n.psis,n.persebaya,n.persija,n.psmsMedan,],
    1998.0: [],
    1997.0: [n.persebaya,n.bandung,n.psmMakassar,n.mitrakukar],
    1996.0: [n.bandung,n.psmMakassar,n.mitrakukar,n.persipura,],
    1995.0: [n.persib,n.petrokimia,],
    1994.0: [],
    1993.0: [],
    1992.0: [],
    1991.0: [],
    1990.0: [],
    1989.0: [],
    1988.0: [],
    1987.0: [],
    1986.0: [],
    1985.0: [],
    1984.0: [],
    1983.0: [],
    1982.0: [],
    1981.0: [],
    1980.0: [],
    1979.0: [],
    1978.0: [],
    1977.0: [],
    1976.0: [],
    1975.0: [],
    1974.0: [],
    1973.0: [],
    1972.0: [],
    1971.0: [],
    1970.0: [],
  },
  leagueName.laos: {
    //https://en.wikipedia.org/wiki/Lao_Premier_League
    //2025.0: [],
    //2024.0: [],
    2023.0: [],
    2022.0: [n.youngElephants,],
    2021.0: [],
    2020.0: [n.chanthabouly,],
    2019.0: [n.chanthabouly,],
    2018.0: [n.chanthabouly,],
    2017.0: [n.chanthabouly,],
    2016.0: [n.lanexang,],
    2015.0: [n.chanthabouly,],
    2014.0: [n.hoanganh,],
    2013.0: [n.shbvientiane,],
    2012.0: [n.laopolice,],
    2011.0: [n.yotha,],
    2010.0: [n.laobank,],
    2009.0: [],
    2008.0: [n.laoarmy,],
    2007.0: [n.laoamerican,],
    2006.0: [n.vientianefc,],
    2005.0: [n.vientianefc,],
    2004.0: [n.yotha,],
    2003.0: [n.yotha,],
    2002.0: [n.yotha,],
    2001.0: [n.laobank,],
  },

  leagueName.malasia: {
    //2025.0: [],
    //2024.0: [],
    2023.0: [],
    2022.0: [n.johordarul,n.terengganu,n.sabah,],
    2021.0: [n.johordarul,n.kedah,n.penang,],
    2020.0: [n.johordarul,n.kedah,n.terengganu,],
    2019.0: [n.johordarul,n.sripahang,n.selangor,],
    2018.0: [n.johordarul,n.perak,],
    2017.0: [n.johordarul,n.sripahang,n.felda,],
    2016.0: [n.johordarul,n.felda,n.kedah,],
    2015.0: [n.johordarul,n.selangor,n.sripahang,],
    2014.0: [n.johordarul,n.selangor,n.sripahang,],
    2013.0: [n.lionsxii,n.selangor,n.johordarul,],
    2012.0: [n.kelantan,n.lionsxii,n.selangor,],
    2011.0: [n.kelantan,n.terengganu,n.selangor,],
    2010.0: [n.selangor,n.kelantan,n.terengganu,],
    2009.0: [n.selangor,n.perlis,n.kedah,],
    2008.0: [n.kedah,n.negeri,n.johordarul,],
    2007.0: [n.kedah,n.perak,n.bruneidpmm],
    2006.0: [],
    2005.0: [n.perlis,n.sripahang,n.perak,],
    2004.0: [n.sripahang,],
  },

  leagueName.myanmar: {
    //2025.0: [],
    //2024.0: [],
    2023.0: [],
    2022.0: [n.shanUnited,n.yangon,],
    2021.0: [],
    2020.0: [n.shanUnited,n.hanthawaddy,],
    2019.0: [n.shanUnited,n.ayeyawady,],
    2018.0: [n.yangon,n.shanUnited,],
    2017.0: [n.shanUnited,n.yangon,],
    2016.0: [n.yadanarbon,n.yangon,],
    2015.0: [n.yangon,n.yadanarbon,],
    2014.0: [n.yadanarbon,n.yangon,],
    2013.0: [n.yangon,n.naypyitaw,],
    2012.0: [n.yangon,n.kanbawza,],
    2011.0: [n.yangon,n.ayeyawady,],
    2010.0: [n.yadanarbon,n.zeyar,],
    2009.0: [n.yadanarbon,n.ayeyawady,],
  },

  leagueName.nepal: {
    //https://www.rsssf.org/tablesn/nepalchamp.html
    //2025.0: [],
    //2024.0: [],
    2023.0: [],
    2022.0: [n.machhindra,],
    2021.0: [],
    2020.0: [n.machhindra,],
    2019.0: [n.manangMarshyangdi,],
    2018.0: [],
    2017.0: [],
    2016.0: [],
    2015.0: [],
    2014.0: [n.manangMarshyangdi,],
    2013.0: [n.threestar,],
    2012.0: [],
    2011.0: [n.nepalPolice,],
    2010.0: [n.nepalPolice,],
    2009.0: [],
    2008.0: [],
    2007.0: [],
    2006.0: [n.manangMarshyangdi,],
    2005.0: [],
    2004.0: [n.threestar,],
    2003.0: [n.manangMarshyangdi,],
    2002.0: [],
    2001.0: [],
    2000.0: [n.manangMarshyangdi,],
    1999.0: [],
    1998.0: [n.threestar,],
    1997.0: [n.threestar,],
  },


  leagueName.srilanka: {
    //https://en.wikipedia.org/wiki/Sri_Lanka_Champions_League
    //2025.0: [],
    //2024.0: [],
    2023.0: [],
    2022.0: [n.mataracity,n.javalane,],
    2021.0: [],
    2020.0: [],
    2019.0: [n.defendersSRI,n.colombo,],
    2018.0: [n.colombo,n.renown,],
    2017.0: [n.colombo,n.renown,],
    2016.0: [n.colombo,n.renown,],
    2015.0: [n.solidSRI,n.colombo,],
    2014.0: [n.airforceSRI,n.ratnam,],
    2013.0: [],
    2012.0: [n.ratnam,n.defendersSRI,],
    2011.0: [n.donboscoSRI,n.defendersSRI,],
    2010.0: [n.renown,n.airforceSRI,],
    2009.0: [n.defendersSRI,n.ratnam,],
    2008.0: [n.ratnam,],
    2007.0: [n.ratnam,n.bluestar,],
    2006.0: [n.negambo,n.ratnam,],
    2005.0: [n.saunders,n.ratnam,],
    2004.0: [n.bluestar,n.ratnam,],
    2003.0: [n.negambo,],
    2002.0: [n.saunders,n.negambo,],
    2001.0: [n.saunders,n.negambo,],
    2000.0: [n.ratnam,],
    1999.0: [n.saunders,],
    1998.0: [n.ratnam,],
    1997.0: [n.saunders,],
    1996.0: [n.saunders,],
    1995.0: [n.pettah,],
    1994.0: [n.renown,],
    1993.0: [n.renown],
    1992.0: [n.saunders,],
    1991.0: [n.saunders,n.ratnam,],
    1990.0: [n.renown,],
    1989.0: [n.saunders,],
    1988.0: [n.oldbens,],
    1987.0: [n.saunders,],
    1986.0: [n.saunders,],
    1985.0: [n.saunders,],
  },


  leagueName.taiwan: {
    //https://en.wikipedia.org/wiki/Taiwan_Football_Premier_League
    //https://en.wikipedia.org/wiki/Intercity_Football_League
    //https://en.wikipedia.org/wiki/Enterprise_Football_League
    //2025.0: [],
    //2024.0: [],
    2023.0: [],
    2022.0: [n.tainancity,n.taichung,n.taipower,],
    2021.0: [n.tainancity,n.taipower,n.taichung,],
    2020.0: [n.tainancity,n.taipower,n.taichung,],
    2019.0: [n.tatung,n.taipower,n.hangyuen,],
    2018.0: [n.tatung,n.taipower,n.hangyuen,],
    2017.0: [n.tatung,n.taipower,n.hangyuen,],
    2016.0: [n.taipower,n.tatung,],
    2015.0: [],
    2014.0: [n.taipower,n.nstc,],
    2013.0: [n.tatung,n.taipower,],
    2012.0: [n.taipower,n.taipeicollege,],
    2011.0: [n.taipower,n.tatung,],
    2010.0: [n.taipower,n.taipeicollege,],
    2009.0: [n.taipeicollege,n.taipower,],
    2008.0: [n.taipower,n.tatung,n.taipeicollege,],
    2007.0: [n.taipower,n.nstc,],
    2006.0: [n.tatung,n.taipower,],
    2005.0: [n.tatung,n.taipower,n.nstc,],
    2004.0: [n.taipower,n.tatung,n.mingchuan,],
    2003.0: [n.taipower,n.tatung,n.taipeicollege,],
    2002.0: [n.taipower,n.tatung,n.mingchuan,],
    2001.0: [n.taipower,n.tatung,],
    2000.0: [],
    1999.0: [n.taipower,n.tatung,n.nstc,],
    1998.0: [n.taipower,n.taipeibank,n.flyingcamel,],
    1997.0: [n.taipower,n.tatung,n.taipeicollege,],
    1996.0: [n.taipower,n.tatung,n.taipeibank,],
    1995.0: [n.taipower,n.tatung,n.taipeibank,],
    1994.0: [n.taipower,n.taipeibank,n.nstc,],
    1993.0: [n.flyingcamel,n.taipower,n.taipeibank,],
    1992.0: [n.taipower,n.tatung,n.flyingcamel,],
    1991.0: [n.taipeibank,n.nstc,n.taipower,],
    1990.0: [n.taipower,n.taipeibank,n.nstc,],
    1989.0: [n.taipeibank,n.flyingcamel,n.nstc,],
    1988.0: [n.flyingcamel,n.taipower,n.nstc,],
    1987.0: [n.taipower,n.flyingcamel,n.taipeibank,],
    1986.0: [n.taipeibank,n.flyingcamel,n.nstc,],
    1985.0: [n.flyingcamel,n.taipeibank,n.nstc,],
    1984.0: [n.flyingcamel,n.nstc,n.taipeibank,],
    1983.0: [n.flyingcamel,n.taipeibank,n.taipower,],
  },

  leagueName.vietna: {
    //2025.0: [],
    //2024.0: [],
    2023.0: [],
    2022.0: [n.hanoi,n.haiphong,n.topenland,n.viettel],
    2021.0: [],
    2020.0: [n.viettel,n.hanoi,n.saigon,n.thanquangnihh],
    2019.0: [n.hanoi,],
    2018.0: [n.hanoi,],
    2017.0: [n.quangNam,],
    2016.0: [n.hanoi,],
    2015.0: [n.becamex],
    2014.0: [n.becamex,],
    2013.0: [n.hanoi,],
    2012.0: [n.danang,],
    2011.0: [n.songLam,],
    2010.0: [n.hanoi,],
    2009.0: [n.danang,],
    2008.0: [n.becamex,],
    2007.0: [n.becamex,],
    2006.0: [n.dongtam,],
    2005.0: [n.dongtam,],
    2004.0: [n.gialai,],
    2003.0: [n.gialai,],
    2002.0: [n.hochiminh,],
    2001.0: [n.songLam,],
    2000.0: [n.songLam,],
    1999.0: [],
    1998.0: [n.viettel,],
    1997.0: [n.hochiminh,],
    1996.0: [],
    1995.0: [],
    1994.0: [n.hochiminh,],
    1993.0: [],
    1992.0: [],
    1991.0: [],
    1990.0: [n.viettel,],
    1989.0: [],
    1988.0: [],
    1987.0: [n.viettel,],
    1986.0: [n.hochiminh,],
    1985.0: [],
    1984.0: [],
    1983.0: [n.viettel,],
    1982.0: [n.viettel,],
    1981.0: [],
    1980.0: [],
    1979.0: [],
    1978.0: [],
    1977.0: [],
    1976.0: [],
    1975.0: [],
    1974.0: [],
    1973.0: [],
    1972.0: [],
    1971.0: [],
    1970.0: [],
  },

  leagueName.quirguistao: {
    //https://en.wikipedia.org/wiki/Kyrgyz_Premier_League
    //2025.0: [],
    //2024.0: [],
    2023.0: [],
    2022.0: [n.abdyshatakant,n.alay,n.algabishkek,n.dordoibishkek,n.neftchikochkorata,n.kaganat,],
    2021.0: [n.dordoibishkek,n.abdyshatakant,n.algabishkek,n.alay,n.kaganat,n.neftchikochkorata,],
    2020.0: [n.dordoibishkek,n.algabishkek,n.neftchikochkorata,n.abdyshatakant,n.alay,n.kaganat,],
    2019.0: [n.dordoibishkek,n.alay,n.algabishkek,n.neftchikochkorata,n.abdyshatakant,n.ilbirs,],
    2018.0: [n.dordoibishkek,n.alay,n.abdyshatakant,n.neftchikochkorata,n.algabishkek,n.ilbirs,],
    2017.0: [n.alay,n.abdyshatakant,n.dordoibishkek,n.neftchikochkorata,n.algabishkek,n.karabalta],
    2016.0: [n.alay,n.dordoibishkek,n.algabishkek,n.abdyshatakant,n.karabalta,n.alatoo,n.aldierkurshab],
    2015.0: [n.alay,n.dordoibishkek,n.abdyshatakant,n.algabishkek,n.alatoo,n.kgutd],
    2014.0: [n.dordoibishkek,n.abdyshatakant,n.algabishkek,n.alay,],
    2013.0: [n.alay,n.dordoibishkek,n.abdyshatakant,n.algabishkek,],
    2012.0: [n.dordoibishkek,n.algabishkek,n.alay,],
    2011.0: [n.dordoibishkek,n.neftchikochkorata,n.abdyshatakant,n.algabishkek,n.alay,],
    2010.0: [n.neftchikochkorata,n.dordoibishkek,n.abdyshatakant,n.algabishkek,],
    2009.0: [n.dordoibishkek,],
    2008.0: [n.dordoibishkek,],
    2007.0: [n.dordoibishkek,],
    2006.0: [n.dordoibishkek,],
    2005.0: [n.dordoibishkek,],
    2004.0: [n.dordoibishkek,],
    2003.0: [n.zhashtyk,],
    2002.0: [n.algabishkek,],
    2001.0: [n.algabishkek,],
    2000.0: [n.algabishkek,],
    1999.0: [n.dinamobishkek,],
    1998.0: [n.dinamobishkek,],
    1997.0: [n.dinamobishkek,],
    1996.0: [n.metallurgkadamjay],
    1995.0: [n.kantoil,],
    1994.0: [n.kantoil,],
    1993.0: [n.algabishkek,],
    1992.0: [n.algabishkek,],
  },

  leagueName.tadjiquistao: {
    //2025.0: [],
    //2024.0: [],
    2023.0: [],
    2022.0: [n.istiklol,n.ravshan,n.khujand,],
    2021.0: [n.istiklol,n.khujand,n.pamirDushanbe,],
    2020.0: [n.istiklol,n.khujand,n.pamirDushanbe,],
    2019.0: [n.istiklol,n.khujand,n.regartadaz,],
    2018.0: [n.istiklol,n.khujand,],
    2017.0: [n.istiklol,n.khujand,n.pamirDushanbe,],
    2016.0: [n.istiklol,n.khosilot,n.regartadaz,],
    2015.0: [n.istiklol,n.khujand,n.ravshan,],
    2014.0: [n.istiklol,],
    2013.0: [n.ravshan,n.istiklol,],
    2012.0: [n.ravshan,n.regartadaz,n.istiklol,],
    2011.0: [n.istiklol,n.regartadaz,n.ravshan,],
    2010.0: [n.istiklol,n.regartadaz,n.vakhsh,],
    2009.0: [n.vakhsh,n.regartadaz,n.khujand,],
    2008.0: [n.regartadaz,n.parvoz,n.khujand,],
    2007.0: [n.regartadaz,n.parvoz,n.vakhsh,],
    2006.0: [n.regartadaz,],
    2005.0: [n.vakhsh,n.regartadaz,],
    2004.0: [n.regartadaz,n.vakhsh,],
    2003.0: [n.regartadaz,n.khujand,],
    2002.0: [n.regartadaz,n.khujand,],
    2001.0: [n.regartadaz,],
    2000.0: [n.varzob,n.regartadaz,],
    1999.0: [n.varzob,],
    1998.0: [n.varzob,n.khujand,],
    1997.0: [n.vakhsh,],
    1996.0: [n.dynamodushambe,n.sitora,n.khujand,],
    1995.0: [n.pamirDushanbe,n.istaravshan,n.sitora,],
    1994.0: [n.sitora,n.pamirDushanbe,],
    1993.0: [n.sitora,n.pamirDushanbe,],
    1992.0: [n.pamirDushanbe,n.regartadaz,n.vakhsh,],
  },

  leagueName.turcomenistao: {
    //https://en.wikipedia.org/wiki/%C3%9Dokary_Liga
    //2025.0: [],
    //2024.0: [],
    2023.0: [],
    2022.0: [n.ahalAnew,n.altynAsyr,n.merw,],
    2021.0: [n.altynAsyr,n.ahalAnew,n.sagadam,],
    2020.0: [n.altynAsyr,n.ahalAnew,n.sagadam,],
    2019.0: [n.altynAsyr,n.ahalAnew,n.sagadam,],
    2018.0: [n.altynAsyr,n.ahalAnew,n.energetikturk,],
    2017.0: [n.altynAsyr,n.ahalAnew,n.sagadam,],
    2016.0: [n.altynAsyr,n.nebitci,n.energetikturk,],
    2015.0: [n.altynAsyr,n.nebitci,n.ashgabat,],
    2014.0: [n.altynAsyr,n.ahalAnew,n.sagadam,],
    2013.0: [n.yedigen,n.nebitci,n.altynAsyr,],
    2012.0: [n.nebitci,n.merw,n.ashgabat,],
    2011.0: [n.nebitci,n.yedigen,n.ashgabat,],
    2010.0: [n.nebitci,n.altynAsyr,],
    2009.0: [n.yedigen,n.nebitci,n.merw,],
    2008.0: [n.ashgabat,n.yedigen,n.nebitci,],
    2007.0: [n.ashgabat,n.yedigen,n.nebitci,],
    2006.0: [n.yedigen,n.nebitci,n.ashgabat,],
    2005.0: [n.yedigen,n.gazcy,n.nebitci,],
    2004.0: [n.nebitci,n.nisaAshgabat,n.merw,],
    2003.0: [n.nisaAshgabat,n.nebitci,n.sagadam,],
    2002.0: [n.sagadam,n.nisaAshgabat,],
    2001.0: [n.nisaAshgabat,n.kopetdag,n.nebitci,],
    2000.0: [n.kopetdag,n.nebitci,n.nisaAshgabat,],
    1999.0: [n.nisaAshgabat,n.kopetdag,],
    1998.0: [n.kopetdag,n.dagdan,n.nisaAshgabat,],
    1997.0: [],
    1996.0: [n.nisaAshgabat,n.kopetdag,],
    1995.0: [n.kopetdag,n.nisaAshgabat,n.nebitci,],
    1994.0: [n.kopetdag,n.nisaAshgabat,n.merw,],
    1993.0: [n.kopetdag,n.buzmeyin,n.nebitci,],
    1992.0: [n.kopetdag,n.nebitci,],
  },

  leagueName.uzbekistao: {
    //2025.0: [],
    //2024.0: [],
    2023.0: [],
    2022.0: [n.pakhtakor,n.navbahor,n.nasafqarshi,n.agmk,n.qizilqum,         ],
    2021.0: [n.pakhtakor,n.sogdiyona,n.agmk,n.nasafqarshi,n.bunyodkor,       ],
    2020.0: [n.pakhtakor,n.nasafqarshi,n.agmk,n.bunyodkor,n.kokand,          ],
    2019.0: [n.pakhtakor,n.loktashkent,n.bunyodkor,n.sogdiyona,n.metallurg,  ],
    2018.0: [n.loktashkent,n.pakhtakor,n.navbahor,n.bunyodkor,n.metallurg,   ],
    2017.0: [n.loktashkent,n.nasafqarshi,n.pakhtakor,n.bunyodkor,n.navbahor, ],
    2016.0: [n.loktashkent,n.bunyodkor,n.nasafqarshi,n.buxoro,n.pakhtakor,  ],
    2015.0: [n.pakhtakor,n.loktashkent,n.nasafqarshi,n.bunyodkor,n.neftchifargona, ],
    2014.0: [n.pakhtakor,n.loktashkent,n.nasafqarshi,n.bunyodkor,],
    2013.0: [n.bunyodkor,n.loktashkent,n.nasafqarshi,n.pakhtakor,n.agmk,   ],
    2012.0: [n.pakhtakor,n.bunyodkor,n.loktashkent,n.nasafqarshi,],
    2011.0: [n.bunyodkor,n.nasafqarshi,n.neftchifargona,n.mubarek,n.navbahor, ],
    2010.0: [n.bunyodkor,n.pakhtakor,],
    2009.0: [n.bunyodkor,n.pakhtakor,],
    2008.0: [n.bunyodkor,n.pakhtakor,],
    2007.0: [n.pakhtakor,],
    2006.0: [n.pakhtakor,n.neftchifargona,],
    2005.0: [n.pakhtakor,],
    2004.0: [n.pakhtakor,n.neftchifargona,],
    2003.0: [n.pakhtakor,n.neftchifargona,],
    2002.0: [n.pakhtakor,n.neftchifargona,],
    2001.0: [n.neftchifargona,n.pakhtakor,],
    2000.0: [n.dustlik,n.neftchifargona,],
    1999.0: [n.dustlik,n.neftchifargona,],
    1998.0: [n.pakhtakor,n.neftchifargona,],
    1997.0: [n.mhsk,n.neftchifargona,],
    1996.0: [n.navbahor,n.neftchifargona,],
    1995.0: [n.neftchifargona,n.mhsk,],
    1994.0: [n.neftchifargona,],
    1993.0: [n.neftchifargona,n.pakhtakor,],
    1992.0: [n.pakhtakor,],
  },



};