import 'package:fifa/values/club_names.dart';
import 'package:fifa/values/league_names.dart';


ClubName _name = ClubName();
LeagueOfficialNames leagueName = LeagueOfficialNames();

Map<String,dynamic> mapAsia = {

  leagueName.china : {
    2022.0: [_name.wuhan,_name.shandong,_name.shanghaishenhua],//DESATUALIZADO
    2021.0: [_name.shandong,_name.shanghaisipg,_name.ghuangzhou,_name.changchun,_name.beijingguoan,  _name.shenzhen,_name.ghuangzhouCity,_name.hebei,_name.shanghaishenhua,_name.henan,   _name.cangzhou,_name.tianjin,_name.chongqing,_name.wuhan,_name.dalian,_name.qingdao],
    2020.0: [_name.jiangsu,_name.ghuangzhou,_name.beijingguoan,_name.shanghaisipg,_name.chongqing,   _name.hebei,_name.shandong,_name.shanghaishenhua,_name.shenzhen,_name.wuhan,         _name.cangzhou,_name.ghuangzhouCity,_name.dalian,_name.qingdao,_name.henan,_name.tianjin],
    2019.0: [_name.ghuangzhou,_name.beijingguoan,_name.shanghaisipg,_name.jiangsu,_name.shandong,    _name.wuhan,_name.tianjin,_name.dalian,_name.chongqing,_name.hebei,                  _name.ghuangzhouCity,_name.shanghaishenhua,_name.tianjin,_name.shenzhen,_name.chengfeng],
    2018.0: [_name.shanghaisipg,_name.ghuangzhou,_name.shandong,_name.beijingguoan,_name.jiangsu,    _name.hebei,_name.shanghaishenhua,_name.chengfeng,_name.tianjin,_name.ghuangzhouCity, _name.dalian,_name.henan,_name.chongqing,_name.tianjin,_name.changchun,_name.guizhou],
    2017.0: [_name.ghuangzhou,_name.shanghaisipg,_name.tianjin,_name.hebei,_name.ghuangzhouCity,     _name.shandong,_name.changchun,_name.chengfeng,_name.beijingguoan,_name.chongqing,    _name.shanghaishenhua,_name.jiangsu,_name.tianjin,_name.henan,_name.yanbian,_name.liaoning],
    2016.0: [_name.ghuangzhou,_name.jiangsu,_name.shanghaisipg,_name.shanghaishenhua,_name.beijingguoan, _name.ghuangzhouCity,_name.hebei,_name.chongqing,_name.yanbian,_name.tianjin,     _name.liaoning,_name.changchun,_name.henan,_name.shandong,_name.zhejiang,_name.cangzhou],
    2015.0: [_name.ghuangzhou,_name.shanghaisipg,_name.shandong,_name.beijingguoan,_name.henan,       _name.shanghaishenhua,_name.cangzhou,_name.chongqing,_name.jiangsu,_name.changchun,  _name.zhejiang,_name.liaoning,_name.tianjin,_name.ghuangzhouCity,_name.chengfeng,_name.shenxin],
    2014.0: [_name.ghuangzhou,_name.beijingguoan,_name.ghuangzhouCity,_name.shandong,_name.shanghaisipg, _name.chengfeng,_name.tianjin,_name.jiangsu,_name.shanghaishenhua,_name.liaoning, _name.shenxin,_name.zhejiang,_name.changchun,_name.henan,_name.dalian,_name.shaoxing],
    2013.0: [_name.ghuangzhou,_name.shandong,_name.beijingguoan,_name.chengfeng,_name.dalian,         _name.ghuangzhouCity,_name.shenxin,_name.shanghaishenhua,_name.shanghaisipg,_name.liaoning,  _name.tianjin,_name.zhejiang,_name.jiangsu,_name.changchun,_name.qingdao,_name.wuhan],
    2012.0: [_name.ghuangzhou,_name.jiangsu,_name.beijingguoan,_name.chengfeng,_name.dalian,          _name.changchun,_name.ghuangzhouCity,_name.tianjin,_name.shanghaishenhua,_name.liaoning,   _name.zhejiang,_name.shandong,_name.qingdao,_name.dalian,_name.shenxin,_name.henan],
    2011.0: [_name.ghuangzhou,_name.beijingguoan,_name.liaoning,_name.jiangsu,_name.shandong,         _name.qingdao,_name.changchun,_name.zhejiang,_name.chengfeng,_name.tianjin,       _name.shanghaishenhua,_name.dalian,_name.henan,_name.shenxin,_name.chengdu,_name.shenzhen],
    2010.0: [_name.shandong,_name.tianjin,_name.shanghaishenhua,_name.zhejiang,_name.beijingguoan,    _name.dalian,_name.liaoning,_name.henan,_name.changchun,_name.chengfeng,          _name.jiangsu,_name.shenzhen,_name.shenxin,_name.qingdao,_name.chongqing,_name.ghuangzhouCity],
    2009.0: [_name.beijingguoan,_name.changchun,_name.henan,_name.shandong,_name.shanghaishenhua,     _name.tianjin,_name.chengdu,_name.dalian,_name.ghuangzhou,_name.jiangsu,          _name.shenzhen,_name.chengfeng,_name.qingdao,_name.ghuangzhouCity,_name.zhejiang,_name.chongqing],
    2008.0: [_name.shandong,_name.shanghaishenhua,_name.beijingguoan,_name.tianjin,_name.chengfeng,   _name.changchun,_name.ghuangzhou,_name.qingdao,_name.zhejiang,_name.henan,        _name.ghuangzhouCity,_name.shenzhen,_name.chengdu,_name.dalian,_name.liaoning,_name.wuhan],
    2007.0: [_name.changchun,_name.beijingguoan,_name.shandong,_name.shanghaishenhua,_name.dalian,    _name.tianjin,_name.wuhan,_name.qingdao,_name.liaoning,_name.ghuangzhouCity,      _name.zhejiang,_name.henan,_name.chengfeng,_name.shenzhen,_name.xiamen],
    2006.0: [_name.shandong,_name.shanghaishenhua,_name.beijingguoan,_name.changchun,_name.dalian,    _name.tianjin,_name.shanghaiunited,_name.xiamen,_name.chengfeng,_name.wuhan,      _name.shenzhen,_name.liaoning,_name.ghuangzhouCity,_name.qingdao,_name.chongqing],
    2005.0: [_name.dalian,_name.shanghaishenhua,_name.shandong,_name.tianjin,_name.wuhan,             _name.beijingguoan,_name.qingdao,_name.chengfeng,_name.sichuan,_name.liaoning,    _name.shanghaizobon,_name.shenzhen,_name.ghuangzhouCity,_name.chongqing],
    2004.0: [_name.shenzhen,_name.shandong,_name.chengfeng,_name.liaoning,_name.dalian,               _name.tianjin,_name.beijingguoan,_name.ghuangzhouCity,_name.sichuan,_name.shanghaishenhua,  _name.qingdao,_name.chongqing],
    2003.0: [_name.shanghaishenhua,_name.chengfeng,_name.dalian,_name.shenzhen,_name.ghuangzhouCity,  _name.liaoning,_name.yunnan,_name.sichuan,_name.beijingguoan,_name.tianjin,       _name.qingdao,_name.shandong,_name.chongqing,_name.august1,_name.harbin],
    2002.0: [_name.dalian,_name.shenzhen,_name.beijingguoan,_name.shandong,_name.liaoning,            _name.chongqing,_name.yunnan,_name.qingdao,_name.chengfeng,_name.tianjin,         _name.ghuangzhouCity,_name.shanghaishenhua,_name.august1,_name.sichuan,_name.harbin],
    2001.0: [_name.dalian,_name.shanghaishenhua,_name.liaoning,_name.sichuan,_name.shenzhen,          _name.shandong,_name.tianjin,_name.beijingguoan,_name.harbin,_name.yunnan,        _name.chongqing,_name.august1,_name.qingdao,_name.ghuangzhouCity],
    2000.0: [_name.dalian,_name.shanghaishenhua,_name.sichuan,_name.chongqing,_name.shandong,         _name.beijingguoan,_name.ghuangzhouCity,_name.liaoning,_name.shenzhen,_name.tianjin, _name.qingdao,_name.yunnan,_name.xiamen,_name.yanbian],
    1999.0: [_name.shandong,_name.liaoning,_name.sichuan,_name.chongqing,_name.shanghaishenhua,       _name.beijingguoan,_name.tianjin,_name.yanbian,_name.dalian,_name.qingdao,        _name.ghuangzhouCity,_name.shenzhen,_name.matsunichi,_name.wuhan],
    1998.0: [_name.dalian,_name.shanghaishenhua,_name.beijingguoan,_name.matsunichi,_name.sichuan,    _name.qingdao,_name.chongqing,_name.wuhan,_name.shandong,_name.ghuangzhouCity,    _name.yanbian,_name.shenzhen,_name.august1,_name.ghuangzhou],
    1997.0: [_name.dalian,_name.shanghaishenhua,_name.beijingguoan,_name.yanbian,_name.chongqing,     _name.shandong,_name.sichuan,_name.ghuangzhou,_name.qingdao,_name.august1,        _name.tianjin,_name.guangdong],
    1996.0: [_name.dalian,_name.shanghaishenhua,_name.august1,_name.beijingguoan,_name.shandong,      _name.sichuan,_name.ghuangzhou,_name.tianjin,_name.guangdong,_name.yanbian,       _name.shenzhen,_name.matsunichi],
    1995.0: [_name.shanghaishenhua,_name.beijingguoan,_name.dalian,_name.guangdong,_name.ghuangzhou,  _name.shandong,_name.yanbian,_name.tianjin,_name.august1,_name.sichuan,           _name.qingdao,_name.liaoning],
    1994.0: [_name.dalian,_name.ghuangzhou,_name.shanghaishenhua,_name.liaoning,_name.shandong,       _name.sichuan,_name.guangdong,_name.beijingguoan,_name.august1,_name.yanbian,     _name.ghuangzhouCity,_name.jiangsu],
    1993.0: [_name.liaoning,_name.guangdong,_name.beijingguoan,_name.dalian,_name.august1,            _name.foshan,_name.shanghaishenhua,_name.ghuangzhou],
    1992.0: [_name.liaoning,_name.ghuangzhou,_name.dalian,_name.august1,_name.shanghaishenhua,        _name.beijingguoan,_name.guangdong,],
    1991.0: [_name.liaoning,_name.shanghaishenhua,_name.beijingguoan,_name.ghuangzhouBaiyunshan,_name.august1,  _name.dalian,_name.chinaOlympic,_name.tianjin],
    1990.0: [_name.liaoning,_name.august1,_name.dalian,_name.shanghaishenhua,_name.tianjin,           _name.chinaOlympic,_name.guangdong,_name.henan],
    1989.0: [_name.chinaOlympic,_name.liaoning,_name.shanghaishenhua,_name.august1,_name.tianjin,_name.guangdong,_name.shandong,_name.ghuangzhou],
    1988.0: [_name.liaoning,_name.chinaOlympic,_name.tianjin,_name.shandong,_name.guangdong,       _name.shanghaishenhua,_name.ghuangzhou,_name.august1,_name.beijingguoan,_name.dalian],
    1987.0: [_name.liaoning,_name.tianjin,_name.shanghaishenhua,_name.shandong,_name.august1,      _name.beijingguoan,_name.ghuangzhou,_name.wuhan],
  },

  leagueName.japao : {
    2022.0: [],
    2021.0: [_name.kawasakifrontale,_name.yokohamamarinos,_name.visselkobe,_name.kashimaantlers,_name.nagoya,   _name.urawareddiamonds,_name.sagantosu,_name.avispa,_name.fcTokyo,_name.sapporo,    _name.hiroshima,_name.cerezoOsaka,_name.gambaOsaka,_name.shimizuSPulse,_name.kashiwaReysol,      _name.shonanbellmare,_name.tokushima,_name.oitatrinita,_name.vegaltaSendai,_name.yokohamaFC],
    2020.0: [_name.kawasakifrontale,_name.gambaOsaka,_name.nagoya,_name.cerezoOsaka,_name.kashimaantlers,       _name.fcTokyo,_name.kashiwaReysol,_name.hiroshima,_name.yokohamamarinos,_name.urawareddiamonds,  _name.oitatrinita,_name.sapporo,_name.sagantosu,_name.visselkobe,_name.yokohamaFC,  _name.shimizuSPulse,_name.vegaltaSendai,_name.shonanbellmare],
    2019.0: [_name.yokohamamarinos,_name.fcTokyo,_name.kashimaantlers,_name.kawasakifrontale,_name.cerezoOsaka, _name.hiroshima,_name.gambaOsaka,_name.visselkobe,_name.oitatrinita,_name.sapporo,  _name.vegaltaSendai,_name.shimizuSPulse,_name.nagoya,_name.urawareddiamonds,_name.sagantosu,     _name.shonanbellmare,_name.matsumoto,_name.jubiloiwata],
    2018.0: [_name.kawasakifrontale,_name.hiroshima,_name.kashimaantlers,_name.sapporo,_name.urawareddiamonds,  _name.fcTokyo,_name.cerezoOsaka,_name.shimizuSPulse,_name.gambaOsaka,_name.visselkobe,  _name.vegaltaSendai,_name.yokohamamarinos,_name.shonanbellmare,_name.sagantosu,_name.nagoya, _name.jubiloiwata,_name.kashiwaReysol,],
    2017.0: [_name.kawasakifrontale,_name.kashimaantlers,_name.cerezoOsaka,_name.kashiwaReysol,_name.yokohamamarinos,  _name.jubiloiwata,_name.urawareddiamonds,_name.sagantosu,_name.visselkobe,_name.gambaOsaka, _name.sapporo,_name.fcTokyo,_name.shimizuSPulse,_name.hiroshima,                  _name.ventforet,_name.albirex,_name.omiyaardija],
    2016.0: [_name.kashimaantlers,_name.urawareddiamonds,_name.kawasakifrontale,_name.hiroshima,_name.omiyaardija, _name.gambaOsaka,_name.kashiwaReysol,_name.jubiloiwata,_name.fcTokyo,_name.vegaltaSendai,  _name.yokohamamarinos,_name.visselkobe,_name.albirex,_name.nagoya,_name.sagantosu,     _name.shonanbellmare,_name.ventforet,_name.avispa],
    2015.0: [_name.hiroshima,_name.gambaOsaka,_name.urawareddiamonds,_name.fcTokyo,_name.kashimaantlers,        _name.kawasakifrontale,_name.yokohamamarinos,_name.shonanbellmare,_name.nagoya,_name.kashiwaReysol,  _name.sagantosu,_name.visselkobe,_name.ventforet,_name.vegaltaSendai,_name.albirex,  _name.matsumoto,_name.shimizuSPulse,_name.yamagata],
    2014.0: [_name.gambaOsaka,_name.urawareddiamonds,_name.kashimaantlers,_name.kashiwaReysol,_name.sagantosu,  _name.kawasakifrontale,_name.yokohamamarinos,_name.hiroshima,_name.fcTokyo,_name.nagoya,   _name.visselkobe,_name.albirex,_name.ventforet,_name.vegaltaSendai,_name.shimizuSPulse,     _name.omiyaardija,_name.cerezoOsaka,_name.tokushima],
    2013.0: [_name.hiroshima,_name.yokohamamarinos,_name.kawasakifrontale,_name.cerezoOsaka,_name.kashimaantlers, _name.urawareddiamonds,_name.albirex,_name.fcTokyo,_name.shimizuSPulse,_name.kashiwaReysol,  _name.nagoya,_name.sagantosu,_name.vegaltaSendai,_name.omiyaardija,_name.ventforet,     _name.shonanbellmare,_name.jubiloiwata,_name.oitatrinita],
    2012.0: [_name.hiroshima,_name.vegaltaSendai,_name.urawareddiamonds,_name.yokohamamarinos,_name.sagantosu,    _name.kashiwaReysol,_name.nagoya,_name.kawasakifrontale,_name.shimizuSPulse,_name.fcTokyo,  _name.kashimaantlers,_name.jubiloiwata,_name.omiyaardija,_name.cerezoOsaka,_name.albirex,   _name.visselkobe,_name.gambaOsaka,_name.sapporo],
    2011.0: [_name.kashiwaReysol,_name.nagoya,_name.gambaOsaka,_name.vegaltaSendai,_name.yokohamamarinos,         _name.kashimaantlers,_name.hiroshima,_name.jubiloiwata,_name.visselkobe,_name.shimizuSPulse,  _name.kawasakifrontale,_name.cerezoOsaka,_name.omiyaardija,_name.albirex,_name.urawareddiamonds,   _name.ventforet,_name.avispa,_name.yamagata],
    2010.0: [_name.nagoya,_name.gambaOsaka,_name.cerezoOsaka,_name.kashimaantlers,_name.kawasakifrontale,         _name.shimizuSPulse,_name.hiroshima,_name.yokohamamarinos,_name.albirex,_name.urawareddiamonds, _name.jubiloiwata,_name.omiyaardija,_name.yamagata,_name.vegaltaSendai,_name.visselkobe,  _name.fcTokyo,_name.kyoto,_name.shonanbellmare],
    2009.0: [_name.kashimaantlers,_name.kawasakifrontale,_name.gambaOsaka,_name.hiroshima,_name.fcTokyo,          _name.urawareddiamonds,_name.shimizuSPulse,_name.albirex,_name.nagoya,_name.yokohamamarinos,    _name.jubiloiwata,_name.kyoto,_name.omiyaardija,_name.visselkobe,_name.yamagata,      _name.kashiwaReysol,_name.oitatrinita,_name.jefUnited],
    2008.0: [_name.kashimaantlers,_name.kawasakifrontale,_name.nagoya,_name.oitatrinita,_name.shimizuSPulse,      _name.fcTokyo,_name.urawareddiamonds,_name.gambaOsaka,_name.yokohamamarinos,_name.visselkobe,   _name.kashiwaReysol,_name.omiyaardija,_name.albirex,_name.kyoto,_name.jefUnited,      _name.jubiloiwata,_name.tokyoVerdy,_name.sapporo],
    2007.0: [_name.kashimaantlers,_name.urawareddiamonds,_name.gambaOsaka,_name.shimizuSPulse,_name.kawasakifrontale,  _name.albirex,_name.yokohamamarinos,_name.kashiwaReysol,_name.jubiloiwata,_name.visselkobe, _name.nagoya,_name.fcTokyo,_name.jefUnited,_name.oitatrinita,_name.omiyaardija,      _name.hiroshima,_name.ventforet,_name.yokohamaFC],
    2006.0: [_name.urawareddiamonds,_name.kawasakifrontale,_name.gambaOsaka,_name.shimizuSPulse,_name.jubiloiwata,  _name.kashimaantlers,_name.nagoya,_name.oitatrinita,_name.yokohamamarinos,_name.hiroshima,    _name.jefUnited,_name.omiyaardija,_name.fcTokyo,_name.albirex,_name.ventforet,        _name.avispa,_name.cerezoOsaka,_name.kyoto],
    2005.0: [_name.gambaOsaka,_name.urawareddiamonds,_name.kashimaantlers,_name.jefUnited,_name.cerezoOsaka,       _name.jubiloiwata,_name.hiroshima,_name.kawasakifrontale,_name.yokohamamarinos,_name.fcTokyo,  _name.oitatrinita,_name.albirex,_name.omiyaardija,_name.nagoya,_name.shimizuSPulse,   _name.kashiwaReysol,_name.tokyoVerdy,_name.visselkobe],
    2004.0: [_name.yokohamamarinos,_name.urawareddiamonds,_name.gambaOsaka,_name.jefUnited,_name.jubiloiwata,      _name.kashimaantlers,_name.nagoya,_name.fcTokyo,_name.tokyoVerdy,_name.albirex,                _name.visselkobe,_name.hiroshima,_name.oitatrinita,_name.shimizuSPulse,_name.cerezoOsaka,  _name.kashiwaReysol],
    2003.0: [_name.yokohamamarinos,_name.jubiloiwata,_name.jefUnited,_name.fcTokyo,_name.kashimaantlers,           _name.urawareddiamonds,_name.nagoya,_name.tokyoVerdy,_name.cerezoOsaka,_name.gambaOsaka,       _name.shimizuSPulse,_name.kashiwaReysol,_name.visselkobe,_name.oitatrinita,_name.vegaltaSendai,  _name.kyoto],
    2002.0: [_name.jubiloiwata,_name.yokohamamarinos,_name.gambaOsaka,_name.kashimaantlers,_name.kyoto,            _name.nagoya,_name.jefUnited,_name.shimizuSPulse,_name.fcTokyo,_name.tokyoVerdy,               _name.urawareddiamonds,_name.kashiwaReysol,_name.vegaltaSendai,_name.visselkobe,_name.hiroshima,  _name.sapporo],
    2001.0: [_name.kashimaantlers,_name.jubiloiwata,_name.jefUnited,_name.shimizuSPulse,_name.nagoya,              _name.kashiwaReysol,_name.gambaOsaka,_name.fcTokyo,_name.hiroshima,_name.urawareddiamonds,     _name.sapporo,_name.visselkobe,_name.yokohamamarinos,_name.tokyoVerdy,_name.avispa,     _name.cerezoOsaka],
    2000.0: [_name.kashimaantlers,_name.yokohamamarinos,_name.kashiwaReysol,_name.jubiloiwata,_name.cerezoOsaka,   _name.gambaOsaka,_name.fcTokyo,_name.shimizuSPulse,_name.nagoya,_name.tokyoVerdy,              _name.hiroshima,_name.avispa,_name.visselkobe,_name.jefUnited,_name.kyoto,         _name.kawasakifrontale],
    1999.0: [_name.jubiloiwata,_name.shimizuSPulse,_name.kashiwaReysol,_name.nagoya,_name.yokohamamarinos,         _name.cerezoOsaka,_name.tokyoVerdy,_name.hiroshima,_name.kashimaantlers,_name.visselkobe,      _name.gambaOsaka,_name.kyoto,_name.jefUnited,_name.avispa,_name.urawareddiamonds,  _name.shonanbellmare],

    1998.0: [_name.kashimaantlers,_name.jubiloiwata,_name.shimizuSPulse,],
    1997.0: [_name.jubiloiwata,_name.kashimaantlers,_name.yokohamamarinos,],
    1996.0: [_name.kashimaantlers,_name.nagoya,_name.flugels,],
    1995.0: [_name.yokohamamarinos,_name.tokyoVerdy,_name.nagoya,],
    1994.0: [_name.tokyoVerdy,_name.hiroshima,_name.kashimaantlers,],
    1993.0: [_name.tokyoVerdy,_name.kashimaantlers,_name.shimizuSPulse,],
  },

  leagueName.coreiaSul : {
    2021.0: [_name.jeonbuk,_name.ulsan,_name.daegu,_name.jeju,_name.suwonFC,      _name.suwonsamsung,_name.fcseoul,_name.incheon,_name.pohang,_name.seongnam,    _name.gangwon,_name.gwangju],
    2020.0: [_name.jeonbuk,_name.ulsan,_name.pohang,_name.gimcheon,_name.daegu,   _name.gwangju,_name.gangwon,_name.suwonsamsung,_name.fcseoul,_name.seongnam,   _name.incheon,_name.busan],
    2019.0: [_name.jeonbuk,_name.ulsan,_name.fcseoul,_name.pohang,_name.daegu,    _name.gangwon,_name.gimcheon,_name.suwonsamsung,_name.seongnam,_name.incheon,  _name.gyeongnam,_name.jeju],
    2018.0: [_name.jeonbuk,_name.gyeongnam,_name.ulsan,_name.pohang,_name.jeju,   _name.suwonsamsung,_name.daegu,_name.gangwon,_name.incheon,_name.gimcheon,     _name.fcseoul,_name.jeonnam],
    2017.0: [_name.jeonbuk,_name.jeju,_name.suwonsamsung,_name.ulsan,_name.fcseoul, _name.gangwon,_name.pohang,_name.daegu,_name.incheon,_name.jeonnam,          _name.gimcheon,_name.gwangju],
    2016.0: [_name.fcseoul,_name.jeonbuk,_name.jeju,_name.ulsan,_name.jeonnam,      _name.gimcheon,_name.suwonsamsung,_name.gwangju,_name.pohang,_name.incheon,    _name.seongnam,_name.suwonFC],
    2015.0: [_name.jeonbuk,_name.suwonsamsung,_name.pohang,_name.fcseoul,_name.seongnam, _name.jeju,_name.ulsan,_name.incheon,_name.jeonnam,_name.gwangju,       _name.busan,_name.daejeon],
    2014.0: [_name.jeonbuk,_name.suwonsamsung,_name.fcseoul,_name.pohang,_name.jeju,  _name.ulsan,_name.jeonnam,_name.busan,_name.seongnam,_name.incheon,         _name.gyeongnam,_name.gimcheon],
    2013.0: [_name.pohang,_name.ulsan,_name.jeonbuk,_name.fcseoul,_name.suwonsamsung, _name.busan,_name.incheon,_name.seongnam,_name.jeju,_name.jeonnam,          _name.gyeongnam,_name.gangwon,_name.daegu,_name.daejeon],
    2012.0: [_name.fcseoul,_name.jeonbuk,_name.pohang,_name.suwonsamsung,_name.ulsan, _name.jeju,_name.busan,_name.gyeongnam,_name.incheon,_name.daegu,          _name.jeonnam,_name.seongnam,_name.daejeon,_name.gangwon,_name.gwangju,_name.gimcheon],
    2011.0: [_name.jeonbuk,_name.ulsan,_name.pohang,_name.suwonsamsung,_name.fcseoul, _name.busan,_name.jeonnam,_name.gyeongnam,_name.jeju,_name.seongnam,       _name.gwangju,_name.daegu,_name.incheon,_name.gimcheon,_name.daejeon,_name.gangwon],
    2010.0: [_name.fcseoul,_name.jeju,_name.jeonbuk,_name.ulsan,_name.seongnam,       _name.gyeongnam,_name.suwonsamsung,_name.busan,_name.pohang,_name.jeonnam, _name.incheon,_name.gangwon,_name.daejeon,_name.gimcheon,_name.daegu],
    2009.0: [_name.jeonbuk,_name.seongnam,_name.pohang,_name.jeonnam,_name.fcseoul,   _name.incheon,_name.gyeongnam,_name.ulsan,_name.daejeon,_name.suwonsamsung, _name.gimcheon,_name.busan,_name.gangwon,_name.jeju,_name.daegu],
    2008.0: [_name.suwonsamsung,_name.fcseoul,_name.ulsan,_name.jeonbuk,_name.seongnam, _name.pohang,_name.incheon,_name.gyeongnam,_name.jeonnam,_name.jeju,      _name.daegu,_name.busan,_name.daejeon,_name.gwangju],
    2007.0: [_name.pohang,_name.seongnam,_name.suwonsamsung,_name.ulsan,_name.gyeongnam, _name.daejeon,_name.fcseoul,_name.jeonbuk,_name.incheon,_name.jeonnam,  _name.jeju,_name.daegu,_name.busan,_name.gwangju],
    2006.0: [_name.seongnam,_name.suwonsamsung,_name.pohang,_name.fcseoul,_name.ulsan,   _name.jeonnam,_name.daegu,_name.busan,_name.incheon,_name.daejeon,   _name.jeonbuk,_name.gyeongnam,_name.jeju,_name.gimcheon],
    2005.0: [_name.ulsan,_name.incheon,_name.seongnam,_name.busan,_name.pohang,       _name.fcseoul,_name.daejeon,_name.daegu,_name.suwonsamsung,_name.busan, _name.jeonnam,_name.jeonbuk,_name.gimcheon],
    2004.0: [_name.suwonsamsung,_name.pohang,_name.ulsan,_name.jeonnam,_name.fcseoul,    _name.jeonbuk,_name.busan,_name.gimcheon,_name.seongnam,_name.daegu, _name.daejeon,_name.incheon,_name.jeju],
    2003.0: [_name.seongnam,_name.ulsan,_name.suwonsamsung,_name.jeonnam,_name.jeonbuk,  _name.daejeon,_name.pohang,_name.fcseoul,_name.busan,_name.gimcheon, _name.daegu,_name.jeju],
    2002.0: [_name.seongnam,_name.ulsan,_name.suwonsamsung,_name.fcseoul,_name.jeonnam,  _name.pohang,_name.jeonbuk,_name.jeju,_name.busan,_name.daegu],
    2001.0: [_name.seongnam,_name.fcseoul,_name.suwonsamsung,_name.busan,_name.pohang,   _name.ulsan,_name.jeju,_name.jeonnam,_name.jeonbuk,_name.daejeon],
    2000.0: [_name.fcseoul,_name.jeju,_name.seongnam,_name.jeonbuk,_name.suwonsamsung,   _name.busan,_name.jeonnam,_name.daejeon,_name.pohang,_name.ulsan],
    1999.0: [_name.suwonsamsung,_name.busan,_name.jeju,_name.jeonnam,_name.pohang,       _name.ulsan,_name.jeonbuk,_name.daejeon,_name.fcseoul,_name.seongnam],
    1998.0: [_name.suwonsamsung,_name.ulsan,_name.pohang,_name.jeonnam,_name.busan,      _name.jeonbuk,_name.jeju,_name.fcseoul,_name.daejeon,_name.seongnam],
    1997.0: [_name.busan,_name.jeonnam,_name.ulsan,_name.pohang,_name.suwonsamsung,      _name.jeonbuk,_name.daejeon,_name.seongnam,_name.fcseoul,_name.jeju],
    1996.0: [_name.ulsan,_name.suwonsamsung,_name.pohang,_name.jeju,_name.jeonbuk,       _name.jeonnam,_name.busan,_name.fcseoul,_name.seongnam],
    1995.0: [_name.seongnam,_name.pohang,_name.ulsan,_name.jeju,_name.jeonnam,           _name.jeonbuk,_name.busan,_name.fcseoul],
    1994.0: [_name.seongnam,_name.jeju,_name.pohang,_name.ulsan,_name.fcseoul,_name.busan,_name.chonbuk],
    1993.0: [_name.seongnam,_name.fcseoul,_name.ulsan,_name.pohang,_name.jeju,_name.busan],
    1992.0: [_name.pohang,_name.seongnam,_name.ulsan,_name.fcseoul,_name.busan,_name.jeju],
    1991.0: [_name.busan,_name.ulsan,_name.pohang,_name.jeju,_name.seongnam,_name.fcseoul],
    1990.0: [_name.fcseoul,_name.busan,_name.pohang,_name.jeju,_name.ulsan,_name.seongnam],
    1989.0: [_name.jeju,_name.fcseoul,_name.busan,_name.pohang,_name.seongnam,_name.ulsan],
    1988.0: [_name.pohang,_name.ulsan,_name.jeju,_name.fcseoul,_name.busan],
    1987.0: [_name.busan,_name.pohang,_name.jeju,_name.ulsan,_name.fcseoul],
    1986.0: [_name.pohang,_name.fcseoul,_name.busan,_name.ulsan,_name.jeju,_name.hanil,],
    1985.0: [_name.fcseoul,_name.pohang,_name.busan,_name.ulsan,_name.jeju,_name.gimcheon,_name.hanil,_name.hallelujah],
    1984.0: [_name.busan,_name.jeju,_name.ulsan,_name.hallelujah,_name.pohang,_name.hanil,_name.fcseoul,_name.kookmin],
    1983.0: [_name.hallelujah,_name.busan,_name.jeju,_name.pohang,_name.kookmin],
  },

  leagueName.australia : {
    2022.0: [],
    2021.0: [_name.melbournecity,_name.sydneyFC,_name.macarthur,_name.adelaide,      _name.centralcoast,_name.brisbane,_name.wellingtonphoenix,_name.sydneywanderers,_name.perth,_name.westernunited,               _name.newcastlejets,_name.melbournevictory],
    2020.0: [_name.sydneyFC,_name.melbournecity,_name.perth,_name.westernunited,     _name.wellingtonphoenix,_name.westernunited,_name.adelaide,_name.newcastlejets,_name.sydneywanderers,_name.melbournevictory,   _name.centralcoast],
    2019.0: [_name.sydneyFC,_name.perth,_name.melbournevictory,_name.adelaide,       _name.melbournecity,_name.wellingtonphoenix,_name.newcastlejets,_name.sydneywanderers,_name.brisbane,_name.centralcoast],
    2018.0: [_name.melbournevictory,_name.newcastlejets,_name.sydneyFC,_name.melbournecity,  _name.adelaide,_name.brisbane,_name.sydneywanderers,_name.perth,_name.wellingtonphoenix,_name.centralcoast],
    2017.0: [_name.sydneyFC,_name.melbournevictory,_name.brisbane,_name.melbournecity,       _name.perth,_name.sydneywanderers,_name.wellingtonphoenix,_name.centralcoast,_name.adelaide,_name.newcastlejets],
    2016.0: [_name.adelaide,_name.sydneywanderers,_name.brisbane,_name.melbournecity,        _name.perth,_name.melbournevictory,_name.sydneyFC,_name.newcastlejets,_name.wellingtonphoenix,_name.centralcoast],
    2015.0: [_name.melbournevictory,_name.sydneyFC,_name.adelaide,_name.wellingtonphoenix,   _name.melbournecity,_name.brisbane,_name.perth,_name.centralcoast,_name.sydneywanderers,_name.newcastlejets],
    2014.0: [_name.brisbane,_name.sydneywanderers,_name.centralcoast,_name.melbournevictory, _name.sydneyFC,_name.adelaide,_name.newcastlejets,_name.perth,_name.wellingtonphoenix,_name.melbournecity],
    2013.0: [_name.centralcoast,_name.sydneywanderers,_name.melbournevictory,_name.adelaide,  _name.brisbane,_name.perth,_name.sydneyFC,_name.newcastlejets,_name.melbournecity,_name.wellingtonphoenix],
    2012.0: [_name.brisbane,_name.perth,_name.centralcoast,_name.wellingtonphoenix,           _name.sydneyFC,_name.melbournecity,_name.newcastlejets,_name.melbournevictory,_name.adelaide,_name.goldCoast],
    2011.0: [_name.brisbane,_name.centralcoast,_name.adelaide,_name.goldCoast,                _name.melbournevictory,_name.wellingtonphoenix,_name.newcastlejets,_name.melbournecity,_name.sydneyFC,_name.perth,_name.queensland],
    2010.0: [_name.sydneyFC,_name.melbournevictory,_name.goldCoast,_name.wellingtonphoenix,_name.perth,  _name.newcastlejets,_name.queensland,_name.centralcoast,_name.brisbane,_name.adelaide],
    2009.0: [_name.melbournevictory,_name.adelaide,_name.brisbane,_name.centralcoast,         _name.sydneyFC,_name.wellingtonphoenix,_name.perth,_name.newcastlejets],
    2008.0: [_name.newcastlejets,_name.centralcoast,_name.sydneyFC,_name.brisbane,            _name.melbournevictory,_name.adelaide,_name.perth,_name.wellingtonphoenix],
    2007.0: [_name.melbournevictory,_name.adelaide,_name.newcastlejets,_name.sydneyFC,       _name.brisbane,_name.centralcoast,_name.perth,_name.newZealandKnights],
    2006.0: [_name.sydneyFC,_name.centralcoast,_name.adelaide,_name.newcastlejets,           _name.perth,_name.brisbane,_name.melbournevictory,_name.newZealandKnights],

    2005.0: [],
    //National_Soccer_League
    2004.0: [_name.perth,_name.parramattaPower,_name.adelaide,_name.marconiStallions,_name.southMelbourne],
    2003.0: [_name.perth,_name.sydneyOlympic,_name.adelaideCity,_name.parramattaPower,],
    2002.0: [_name.sydneyOlympic,_name.perth,],
    2001.0: [_name.wollongongWolves,_name.southMelbourne,],
    2000.0: [_name.wollongongWolves,_name.perth,],
    1999.0: [_name.southMelbourne,_name.sydneyUtd],
    1998.0: [_name.southMelbourne,_name.carlton],
    1997.0: [_name.brisbaneStrikers,_name.sydneyUtd,],
    1996.0: [_name.melbourneKnights,_name.marconiStallions,],
    1995.0: [_name.melbourneKnights,_name.adelaideCity,],
    1994.0: [_name.adelaideCity,_name.melbourneKnights,],
    1993.0: [_name.marconiStallions,_name.adelaideCity,],
    1992.0: [_name.adelaideCity,_name.melbourneKnights,],
    1991.0: [_name.southMelbourne,_name.melbourneKnights,],
    1990.0: [_name.sydneyOlympic,_name.marconiStallions,],
    1989.0: [_name.marconiStallions,_name.sydneyOlympic,],
    1988.0: [_name.marconiStallions,_name.sydneyUtd,],
    1987.0: [_name.apiaLeichhardt,_name.prestonLions,],
    1986.0: [_name.adelaideCity,_name.sydneyOlympic,],
    1985.0: [_name.brunswick,_name.maccabiHakoah,],
    1984.0: [_name.southMelbourne,_name.sydneyOlympic,],
    1983.0: [_name.stGeorgeAUS,_name.maccabiHakoah,],
    1982.0: [_name.maccabiHakoah,_name.stGeorgeAUS,],
    1981.0: [_name.maccabiHakoah,],
    1980.0: [_name.maccabiHakoah,],
    1979.0: [_name.marconiStallions,],
    1978.0: [_name.westAdelaide,_name.maccabiHakoah,],
    1977.0: [_name.maccabiHakoah,_name.marconiStallions,],
  },


  leagueName.arabia : {
    2022.0: [_name.alhilal,_name.alIttihad,_name.alnassr,_name.alShabab,_name.damac,],
    2021.0: [_name.alhilal,_name.alShabab,_name.alIttihad,_name.altaawoun,_name.alettifaq,   _name.alnassr],
    2020.0: [_name.alhilal,_name.alnassr,_name.alahli,_name.alwehda,_name.alFaisalyARABIA,   _name.alraed],
    2019.0: [_name.alnassr,_name.alhilal,_name.altaawoun,_name.alahli,_name.alShabab,        _name.alFaisalyARABIA,],
    2018.0: [_name.alhilal,_name.alahli,_name.alnassr,_name.alettifaq,_name.alfateh,         _name.alFaisalyARABIA,],
    2017.0: [_name.alhilal,_name.alahli,_name.alnassr,_name.alIttihad,_name.alraed,          _name.alShabab,],
    2016.0: [_name.alahli,_name.alhilal,_name.alIttihad,_name.altaawoun,_name.alfateh,       _name.alShabab,],
    2015.0: [_name.alnassr,_name.alahli,_name.alhilal,_name.alIttihad,_name.alShabab,        _name.alfateh,],
    2014.0: [_name.alnassr,_name.alhilal,_name.alahli,_name.alShabab,_name.altaawoun,        _name.alFaisalyARABIA,],
    2013.0: [_name.alfateh,_name.alhilal,_name.alShabab,_name.alnassr,_name.alahli,          _name.alettifaq,],
    2012.0: [_name.alShabab,_name.alahli,_name.alhilal,_name.alettifaq,_name.alIttihad,      _name.alfateh],
    2011.0: [_name.alhilal,_name.alIttihad,_name.alettifaq,_name.alShabab,_name.alnassr,     _name.alahli,],
    2010.0: [_name.alhilal,_name.alIttihad,_name.alnassr,_name.alShabab,_name.alwehda,       _name.alahli,],
    2009.0: [_name.alIttihad,_name.alhilal,_name.alahli,_name.alShabab,_name.alnassr,        _name.alettifaq,],
    2008.0: [_name.alhilal,_name.alIttihad,_name.alShabab,_name.alettifaq,_name.alnassr,     _name.alwehda,],
    2007.0: [_name.alIttihad,_name.alhilal,_name.alwehda,_name.alShabab,_name.alahli,        _name.alettifaq,],
    2006.0: [_name.alShabab,_name.alhilal,_name.alIttihad,_name.alahli,_name.alettifaq,      _name.alnassr,],
    2005.0: [_name.alhilal,_name.alShabab,_name.alIttihad,_name.alnassr,_name.alahli,        _name.alwehda,],
    2004.0: [_name.alShabab,_name.alIttihad,_name.alhilal,_name.alahli,_name.alettifaq,      _name.alnassr,],
    2003.0: [_name.alIttihad,_name.alahli,_name.alQadisiya,_name.alnassr,_name.alhilal,  _name.alShabab,_name.altai,],
    2002.0: [_name.alhilal,_name.alIttihad,_name.alnassr,_name.alahli,_name.alriad,      _name.alshoulla,_name.alnajma,],
    2001.0: [_name.alIttihad,_name.alnassr,_name.alahli,_name.alhilal,_name.alriad,      _name.alansarARABIA,_name.alShabab],
    2000.0: [_name.alIttihad,_name.alahli,_name.alShabab,_name.alnassr,_name.alhilal,    _name.alriad,_name.alettifaq,],
    1999.0: [_name.alIttihad,_name.alahli,_name.alhilal,_name.alShabab,_name.alnassr,    _name.alettifaq,_name.alriad,],
    1998.0: [_name.alhilal,_name.alShabab,_name.alahli,_name.alnajma,_name.alnassr,      _name.alettifaq,_name.alIttihad,],
    1997.0: [_name.alIttihad,_name.alhilal,_name.alnassr,_name.alShabab,_name.alahli,    _name.alriad,_name.alettifaq,],
    1996.0: [_name.alhilal,_name.alahli,_name.alIttihad,_name.alnassr,_name.alettifaq,   _name.alnajma,_name.altai,],
    1995.0: [_name.alnassr,_name.alhilal,_name.alriad,_name.alettifaq,_name.alShabab,    _name.alahli,_name.alIttihad,],
    1994.0: [_name.alnassr,_name.alriad,_name.alhilal,_name.alShabab,_name.alQadisiya,   _name.alahli,_name.alIttihad,],
    1993.0: [_name.alShabab,_name.alhilal,_name.alIttihad,_name.alettifaq,_name.alahli,  _name.alriad,_name.alraed,],
    1992.0: [_name.alShabab,_name.alettifaq,_name.alahli,_name.alnassr,_name.alIttihad,  _name.alQadisiya,_name.alhilal,],
    1991.0: [_name.alShabab,_name.alnassr,_name.alhilal,_name.alettifaq,_name.alIttihad, _name.alriad,_name.alahli,],
    1990.0: [_name.alhilal,_name.alahli,_name.alnassr,_name.altai,_name.alShabab,        _name.alQadisiya,_name.alettifaq,],
    1989.0: [_name.alnassr,_name.alShabab,_name.alhilal,_name.alahli,_name.alettifaq,    _name.alIttihad,_name.altai,],
    1988.0: [_name.alhilal,_name.alettifaq,_name.alnassr,_name.alIttihad,_name.alShabab, _name.altai,],
    1987.0: [_name.alettifaq,_name.alhilal,_name.alnassr,_name.altai,_name.alShabab,     _name.alahli,],
    1986.0: [_name.alhilal,_name.alIttihad,_name.alnassr,_name.alwehda,_name.altai,      _name.alahli,],
    1985.0: [_name.alhilal,_name.alShabab,_name.alahli,_name.alettifaq,_name.alnassr,    _name.alIttihad,],
    1984.0: [_name.alahli,_name.alIttihad,_name.alettifaq,_name.alQadisiya,_name.alnassr, _name.alhilal,],
    1983.0: [_name.alettifaq,_name.alhilal,_name.alShabab,_name.alnassr,_name.alahli,    _name.alIttihad,_name.alQadisiya,_name.alnahda,_name.alrawdhah,_name.ohod],
    1982.0: [_name.alIttihad,_name.alShabab,_name.alhilal,_name.alnassr,  ],
    1981.0: [_name.alnassr,_name.alhilal,_name.alQadisiya,_name.alahli,_name.alettifaq,   _name.alIttihad,],
    1980.0: [_name.alnassr,_name.alhilal,_name.alIttihad,_name.alahli,_name.alShabab,     _name.alettifaq,_name.alnahda,_name.alQadisiya,_name.alwehda,_name.ohod],
    1979.0: [_name.alhilal,_name.alnassr,_name.alIttihad,_name.alahli,_name.alQadisiya,    _name.alettifaq,_name.alnahda,_name.alwehda,_name.altai,_name.alriad],
    1978.0: [_name.alahli,_name.alnassr,_name.alettifaq,_name.alIttihad,_name.alQadisiya,  _name.alhilal,_name.alnahda,_name.alwehda,_name.alShabab,_name.ohod],
    1977.0: [_name.alhilal,_name.alnassr,_name.alahli,_name.alIttihad,_name.alwehda,   _name.alQadisiya,_name.alShabab,_name.alriad],
    1976.0: [],
    1975.0: [_name.alnassr,],
  },

  leagueName.qatar : {
    2022.0: [_name.alsadd,_name.alduhail,_name.alwakrah,_name.alarabi,_name.algharafa,    ],
    2021.0: [_name.alsadd,_name.alduhail,_name.alrayyan,_name.algharafa,_name.alahliQAT,  ],
    2020.0: [_name.alduhail,_name.alrayyan,_name.alsadd,_name.algharafa,_name.alsailiya,  ],
    2019.0: [_name.alsadd,_name.alduhail,_name.alsailiya,_name.alrayyan,_name.alahliQAT,  ],
    2018.0: [_name.alduhail,_name.alsadd,_name.alrayyan,_name.algharafa,_name.ummSalal,   ],
    2017.0: [_name.alduhail,_name.alsadd,_name.alrayyan,_name.eljaish,_name.algharafa,    ],
    2016.0: [_name.alrayyan,_name.eljaish,_name.alsadd,_name.alduhail,_name.ummSalal,     ],
    2015.0: [_name.alduhail,_name.alsadd,_name.eljaish,_name.qatar,_name.alahliQAT,       ],
    2014.0: [_name.alduhail,_name.eljaish,_name.alsadd,_name.alsailiya,_name.alarabi,     ],
    2013.0: [_name.alsadd,_name.alduhail,_name.eljaish,_name.alrayyan,_name.ummSalal,     ],
    2012.0: [_name.alduhail,_name.eljaish,_name.alrayyan,_name.alsadd,_name.alkhor,       ],
    2011.0: [_name.alduhail,_name.algharafa,_name.alrayyan,_name.alarabi,_name.qatar,     ],
    2010.0: [_name.algharafa,_name.alsadd,_name.alarabi,_name.qatar,_name.alrayyan,       ],
    2009.0: [_name.algharafa,_name.alsadd,_name.alrayyan,_name.qatar,_name.alkhor,        ],
    2008.0: [_name.algharafa,_name.alsadd,_name.ummSalal,_name.qatar,_name.alrayyan,      ],
    2007.0: [_name.alsadd,_name.algharafa,_name.ummSalal,_name.alrayyan,_name.alwakrah,   ],
    2006.0: [_name.alsadd,_name.qatar,_name.alarabi,_name.alrayyan,_name.alahliQAT,       ],
    2005.0: [_name.algharafa,_name.alrayyan,_name.alkhor,_name.qatar,_name.alarabi,       ],
    2004.0: [_name.alsadd,_name.qatar,_name.alarabi,_name.alahliQAT,_name.alrayyan,       ],
    2003.0: [_name.qatar,_name.alsadd,_name.alkhor,_name.algharafa,_name.alahliQAT,       ],
    2002.0: [_name.algharafa,_name.qatar,_name.alrayyan,_name.alsadd,_name.alwakrah,      ],
    2001.0: [_name.alwakrah,_name.alarabi,_name.altaawoun,_name.alrayyan,_name.algharafa, ],
    2000.0: [_name.alsadd,_name.alrayyan,_name.alarabi,_name.algharafa,_name.alahliQAT,   ],
    1999.0: [_name.alrayyan,_name.algharafa,_name.alsadd,_name.alarabi,_name.alwakrah,    ],
    1998.0: [_name.algharafa,_name.alrayyan,_name.alsadd,_name.alarabi,_name.alahliQAT,   ],
    1997.0: [_name.alarabi,_name.alrayyan,_name.algharafa,_name.alwakrah,_name.alsadd,    ],
    1996.0: [_name.alarabi,_name.alrayyan,_name.alwakrah,_name.alsadd,_name.algharafa,    ],
    1995.0: [_name.alrayyan,],
    1994.0: [_name.alarabi,_name.alrayyan,],
    1993.0: [_name.alarabi,],
    1992.0: [_name.algharafa,_name.qatar,_name.alsadd,_name.alarabi,_name.alrayyan,_name.alahliQAT,_name.alwakrah,_name.altaawoun,_name.alshamal],
    1991.0: [_name.alarabi,],
    1990.0: [_name.alrayyan,],
    1989.0: [_name.alsadd,],
    1988.0: [_name.alsadd,],
    1987.0: [_name.alsadd,],
    1986.0: [_name.alrayyan,],
    1985.0: [_name.alarabi,_name.qatar,_name.alrayyan,_name.alahliQAT,_name.alsadd,_name.altaawoun,_name.algharafa],
    1984.0: [_name.alrayyan,_name.alahliQAT,_name.alarabi,_name.qatar,_name.alsadd,_name.altaawoun,_name.alwakrah],
    1983.0: [_name.alarabi,],
    1982.0: [_name.alrayyan,],
    1981.0: [_name.alsadd,_name.alarabi],
    1980.0: [_name.alsadd,],
    1979.0: [_name.alsadd,],
    1978.0: [_name.alrayyan,],
    1977.0: [_name.qatar,],
    1976.0: [_name.alrayyan,],
    1975.0: [],
    1974.0: [_name.alsadd,],
    1973.0: [_name.qatar,],
  },

  leagueName.eau : {
    2022.0: [],
    2021.0: [_name.aljazira,_name.baniyas,],
    2020.0: [],
    2019.0: [_name.alsharjah,_name.shababalahli,],
    2018.0: [_name.alain,_name.alWahda,],
    2017.0: [_name.aljazira,_name.alwasl,],
    2016.0: [_name.shababalahli,_name.alain,],
    2015.0: [_name.alain,_name.aljazira,],
    2014.0: [_name.shababalahli,_name.alWahda,],
    2013.0: [_name.alain,_name.shababalahli,],
    2012.0: [_name.alain,_name.alnasrEAU,],
    2011.0: [_name.aljazira,_name.baniyas,],
    2010.0: [_name.alWahda,_name.aljazira,],
    2009.0: [_name.shababalahli,_name.aljazira,],
    2008.0: [_name.alShababEAU,_name.aljazira,],
    2007.0: [_name.alwasl,_name.alWahda,],
    2006.0: [_name.shababalahli,_name.alWahda,],
    2005.0: [_name.alWahda,_name.alain,],
    2004.0: [_name.alain,_name.shababalahli,],
    2003.0: [_name.alain,_name.alWahda,],
    2002.0: [_name.alain,_name.aljazira,],
    2001.0: [_name.alWahda,_name.alain,],
    2000.0: [_name.alain,_name.alnasrEAU,],
    1999.0: [_name.alWahda,_name.alain,],
    1998.0: [_name.alain,_name.alsharjah,],
    1997.0: [_name.alwasl,_name.alnasrEAU,],
    1996.0: [_name.alsharjah,_name.alwasl,],
    1995.0: [_name.alShababEAU,_name.alwasl,],
    1994.0: [_name.alsharjah,_name.alain,],
    1993.0: [_name.alain,_name.alwasl,],
    1992.0: [_name.alwasl,_name.alsharjah],
    1991.0: [],
    1990.0: [_name.alShababEAU,_name.alwasl,],
    1989.0: [_name.alsharjah,_name.alwasl,],
    1988.0: [_name.alwasl,_name.alsharjah,],
    1987.0: [_name.alsharjah,_name.alwasl,],
    1986.0: [_name.alnasrEAU,_name.alwasl,],
    1985.0: [_name.alwasl,_name.alShababEAU,],
    1984.0: [_name.alain,_name.alwasl,],
    1983.0: [_name.alwasl,_name.alsharjah,],
    1982.0: [_name.alwasl,_name.alsharjah,],
    1981.0: [_name.alain,_name.alnasrEAU,],
    1980.0: [_name.shababalahli,],
    1979.0: [_name.alnasrEAU,_name.alsharjah,],
    1978.0: [_name.alnasrEAU,_name.alain,],
    1977.0: [_name.alain,_name.alsharjah,],
    1976.0: [_name.shababalahli,_name.alain,],
    1975.0: [_name.shababalahli,_name.alsharjah,],
    1974.0: [_name.alsharjah,_name.shababalahli,],
  },
  leagueName.india : {
    2022.0: [_name.hyderabad,_name.kerala,_name.jamshedpur,_name.mohunBagan,  _name.mumbai,_name.bengaluru,_name.odisha,_name.chennaiyin,_name.goa,_name.northeast,              _name.eastBengal],
    2021.0: [_name.mumbai,_name.mohunBagan,_name.northeast,_name.goa,         _name.hyderabad,_name.jamshedpur,_name.bengaluru,_name.chennaiyin,_name.eastBengal,_name.kerala,   _name.odisha],
    2020.0: [_name.mohunBagan,_name.chennaiyin,_name.goa,_name.bengaluru,     _name.mumbai,_name.odisha,_name.kerala,_name.jamshedpur,_name.northeast,_name.hyderabad],
    2019.0: [_name.bengaluru,_name.goa,_name.mumbai,_name.northeast,    _name.jamshedpur,_name.mohunBagan,_name.pune,_name.delhi,_name.kerala,_name.chennaiyin],
    2018.0: [_name.chennaiyin,_name.bengaluru,_name.goa,_name.pune,     _name.jamshedpur,_name.kerala,_name.mumbai,_name.delhi,_name.mohunBagan,_name.northeast],
    2017.0: [_name.aizawl,_name.mohunBagan,_name.eastBengal,],
    2016.0: [_name.bengaluru,_name.mohunBagan,_name.eastBengal,],
    2015.0: [_name.mohunBagan,_name.bengaluru,],
    2014.0: [_name.bengaluru,_name.eastBengal,_name.salgaocar,],
    2013.0: [_name.churchill,_name.pune,_name.eastBengal],
    2012.0: [_name.dempo,_name.eastBengal,_name.churchill,],
    2011.0: [_name.salgaocar,_name.eastBengal,_name.dempo,],
    2010.0: [_name.dempo,_name.churchill,_name.pune],
    2009.0: [_name.churchill,_name.mohunBagan,_name.sportingGoa,],
    2008.0: [_name.dempo,_name.churchill,_name.jct,],
    2007.0: [_name.dempo,_name.jct,_name.mahindra,_name.mahindra,],
    2006.0: [_name.mahindra,_name.eastBengal,_name.mohunBagan,],
    2005.0: [_name.dempo,_name.sportingGoa,_name.eastBengal,],
    2004.0: [_name.eastBengal,_name.dempo,_name.mahindra,],
    2003.0: [_name.eastBengal,_name.salgaocar,_name.vascoIND,],
    2002.0: [_name.mohunBagan,_name.churchill,_name.vascoIND,],
    2001.0: [_name.eastBengal,_name.mohunBagan,_name.churchill,],
    2000.0: [_name.mohunBagan,_name.churchill,_name.salgaocar,],
    1999.0: [_name.salgaocar,_name.eastBengal,_name.churchill,],
    1998.0: [_name.mohunBagan,_name.eastBengal,_name.salgaocar,],
    1997.0: [_name.jct,_name.churchill,_name.eastBengal,],
  },
  leagueName.tailandia : {
    2022.0: [_name.buriram],
    2021.0: [_name.pathum,],
    2020.0: [],
    2019.0: [_name.chiangrai,],
    2018.0: [_name.buriram,],
    2017.0: [_name.buriram,],
    2016.0: [_name.muangthong,],
    2015.0: [_name.buriram,],
    2014.0: [_name.buriram,],
    2013.0: [_name.buriram,],
    2012.0: [_name.muangthong,],
    2011.0: [_name.buriram,],
    2010.0: [_name.muangthong,],
    2009.0: [_name.muangthong,],
    2008.0: [_name.buriram,],
    2007.0: [_name.muangthong,],
    2006.0: [_name.muangthong,],

    2002.0: [_name.policeTero,],
    2001.0: [],
    2000.0: [_name.policeTero,],
    1999.0: [_name.thaiAirForce,],
    1998.0: [],
    1997.0: [_name.thaiAirForce,],
    1996.0: [_name.bangkokBank,],
    1995.0: [_name.thai,],
    1994.0: [_name.bangkokBank,],
    1993.0: [_name.thai,],
    1992.0: [_name.thai,],
    1991.0: [],
    1990.0: [_name.thai,],
    1989.0: [_name.bangkokBank,],

    1987.0: [_name.thaiAirForce,],
    1986.0: [_name.bangkokBank,],

    1984.0: [_name.bangkokBank,],

    1981.0: [_name.bangkokBank,],
  },

  leagueName.iran : {
    2022.0: [_name.esteghlal,_name.persepolis,_name.sepahan,],
    2021.0: [_name.persepolis,_name.sepahan,_name.esteghlal,],
    2020.0: [_name.persepolis,_name.esteghlal,_name.foolad,],
    2019.0: [_name.persepolis,_name.sepahan,_name.esteghlal,],
    2018.0: [_name.persepolis,_name.zobahan,_name.esteghlal,],
    2017.0: [_name.persepolis,_name.esteghlal,_name.tractor,],
    2016.0: [_name.esteghlalKhuzestan,_name.persepolis,_name.esteghlal,],
    2015.0: [_name.sepahan,_name.tractor,_name.naftTehran,],
    2014.0: [_name.foolad,_name.persepolis,_name.naftTehran,],
    2013.0: [_name.esteghlal,_name.tractor,_name.sepahan,],
    2012.0: [_name.sepahan,_name.tractor,_name.esteghlal,],
    2011.0: [_name.sepahan,_name.esteghlal,_name.zobahan,],
    2010.0: [_name.sepahan,_name.zobahan,_name.esteghlal,],
    2009.0: [_name.esteghlal,_name.zobahan,],
    2008.0: [_name.persepolis,_name.sepahan,],
    2007.0: [_name.saipa,_name.esteghlal,_name.persepolis],
    2006.0: [_name.esteghlal,_name.pastehran,_name.saipa],
    2005.0: [_name.foolad,_name.zobahan,_name.esteghlal,],
    2004.0: [_name.pastehran,_name.esteghlal,_name.foolad,],
    2003.0: [_name.sepahan,_name.pastehran,_name.persepolis,],
    2002.0: [_name.persepolis,_name.esteghlal,_name.foolad,],
    2001.0: [_name.esteghlal,_name.persepolis,_name.saipa,],
    2000.0: [_name.persepolis,_name.esteghlal,],
    1999.0: [_name.persepolis,_name.esteghlal,_name.sepahan,],
    1998.0: [_name.esteghlal,_name.pastehran,_name.zobahan,],
    1997.0: [_name.persepolis,_name.bahman,_name.sepahan,],
    1996.0: [_name.persepolis,_name.bahman,_name.esteghlal,],
    1995.0: [_name.saipa,_name.esteghlal,],
    1994.0: [_name.saipa,_name.persepolis,],
    1993.0: [_name.pastehran,_name.persepolis,_name.keshavarz,],
    1992.0: [_name.pastehran,_name.esteghlal,_name.persepolis,],
    1991.0: [],
    1990.0: [_name.esteghlal,_name.persepolis,_name.malavan,],
    1989.0: [],
    1988.0: [],
    1987.0: [],
    1986.0: [],
    1985.0: [],
    1984.0: [],
    1983.0: [],
    1982.0: [],
    1981.0: [],
    1980.0: [],
    1979.0: [],
    1978.0: [_name.pastehran,_name.persepolis,_name.malavan],
    1977.0: [_name.pastehran,_name.persepolis,],
    1976.0: [_name.persepolis,_name.homa,_name.pastehran],
    1975.0: [_name.esteghlal,_name.persepolis,_name.homa],
    1974.0: [_name.persepolis,_name.esteghlal,_name.pastehran,],
    1973.0: [],
    1972.0: [],
    1971.0: [],
    1970.0: [],
    1969.0: [],
    1968.0: [],
    1967.0: [],
    1966.0: [],
    1965.0: [],
    1964.0: [],
    1963.0: [],
    1962.0: [],
    1961.0: [],
    1960.0: [],
  },
  leagueName.iraque : {
    2022.0: [_name.alShortaIRAQ,_name.alQuwaAlJawiya,_name.alTalaba,],
    2021.0: [_name.alQuwaAlJawiya,_name.alzawraa,_name.alnajaf],
    2020.0: [],
    2019.0: [_name.alShortaIRAQ,_name.alQuwaAlJawiya,_name.alzawraa,],
    2018.0: [_name.alzawraa,_name.alQuwaAlJawiya,_name.alnaft,],
    2017.0: [_name.alQuwaAlJawiya,_name.alnaft,_name.alShortaIRAQ,],
    2016.0: [_name.alzawraa,_name.naftAlwasat,_name.alTalaba,],
    2015.0: [_name.naftAlwasat,_name.alQuwaAlJawiya,_name.alShortaIRAQ,],
    2014.0: [],
    2013.0: [_name.alShortaIRAQ,_name.erbil,_name.alQuwaAlJawiya,],
    2012.0: [_name.erbil,_name.duhok,_name.alQuwaAlJawiya,],
    2011.0: [_name.alzawraa,_name.erbil,_name.alsinaa,],
    2010.0: [_name.duhok,_name.alTalaba,_name.alzawraa,],
    2009.0: [_name.erbil,_name.alnajaf,_name.duhok,],
    2008.0: [_name.erbil,_name.alzawraa,_name.alQuwaAlJawiya,],
    2007.0: [_name.erbil,_name.alQuwaAlJawiya,_name.alnajaf],
    2006.0: [_name.alzawraa,_name.alnajaf,_name.erbil,],
    2005.0: [_name.alQuwaAlJawiya,_name.alminaa,_name.alTalaba],
    2004.0: [],
    2003.0: [],
    2002.0: [_name.alTalaba,_name.alQuwaAlJawiya,_name.alShortaIRAQ,],
    2001.0: [_name.alzawraa,_name.alQuwaAlJawiya,_name.alShortaIRAQ,],
    2000.0: [_name.alzawraa,_name.alQuwaAlJawiya,_name.alShortaIRAQ,],
    1999.0: [_name.alzawraa,_name.alTalaba,_name.alQuwaAlJawiya,],
    1998.0: [_name.alShortaIRAQ,_name.alQuwaAlJawiya,_name.alzawraa,],
    1997.0: [_name.alQuwaAlJawiya,_name.alzawraa,_name.alTalaba,],
    1996.0: [_name.alzawraa,_name.alnajaf,_name.alShortaIRAQ,],
    1995.0: [_name.alzawraa,_name.alQuwaAlJawiya,_name.alnajaf,],
    1994.0: [_name.alzawraa,_name.alQuwaAlJawiya,_name.alTalaba,],
    1993.0: [_name.alTalaba,_name.alzawraa,_name.alQuwaAlJawiya,],
    1992.0: [_name.alQuwaAlJawiya,_name.alzawraa,],
    1991.0: [_name.alzawraa,_name.alTalaba,_name.alShortaIRAQ,],
    1990.0: [_name.alQuwaAlJawiya,_name.alRasheed,_name.alShortaIRAQ,],
    1989.0: [_name.alRasheed,_name.alTalaba,],
    1988.0: [_name.alRasheed,_name.aljaishIRAQ,],
    1987.0: [_name.alRasheed,_name.aljaishIRAQ,],
    1986.0: [_name.alTalaba,_name.alRasheed,],
    1985.0: [],
    1984.0: [_name.aljaishIRAQ,_name.alTalaba,],
    1983.0: [_name.salahaddin,_name.alTalaba,],
    1982.0: [_name.alTalaba,],
    1981.0: [_name.alTalaba,_name.alShortaIRAQ,],
    1980.0: [_name.alShortaIRAQ,_name.alzawraa,],
    1979.0: [_name.alzawraa,_name.alShortaIRAQ,],
    1978.0: [_name.alminaa,_name.alzawraa,],
    1977.0: [_name.alzawraa,],
    1976.0: [_name.alzawraa],
    1975.0: [_name.alQuwaAlJawiya,],
    1974.0: [_name.alQuwaAlJawiya,],
    1973.0: [],
    1972.0: [],
    1971.0: [],
    1970.0: [],
    1969.0: [],
    1968.0: [],
    1967.0: [],
    1966.0: [],
    1965.0: [],
    1964.0: [],
    1963.0: [],
    1962.0: [],
    1961.0: [],
    1960.0: [],
  }
};