import 'package:fifa/values/club_names.dart';
import 'package:fifa/values/league_names.dart';


ClubName n = ClubName();
LeagueOfficialNames leagueName = LeagueOfficialNames();

Map<String,dynamic> mapCopas = {

   leagueName.englandCup : {
     //2023.0: [],
    2022.0: [n.liverpool, n.chelsea,      n.mancity,n.crystalpalace,         n.nottinghamforest,n.middlesbrough,n.southampton,n.everton,   ],
    2021.0: [n.leicester,n.chelsea,       n.southampton,n.mancity,           n.manutd,n.sheffieldunited,n.bournemouth,n.everton, ],
    2020.0: [n.arsenal,n.chelsea,         n.mancity,n.manutd,                n.sheffieldunited,n.leicester,n.newcastle,n.norwich,],
    2019.0: [n.mancity,n.watford,         n.brighton,n.wolves,               n.swansea,n.crystalpalace,n.millwall,n.manutd,      ],
    2018.0: [n.chelsea,n.manutd,          n.southampton,n.tottenham,         n.leicester,n.brighton,n.wigan,n.swansea,           ],
    2017.0: [n.arsenal,n.chelsea,         n.mancity,n.tottenham,             n.lincoln,n.manutd,n.middlesbrough,n.millwall,      ],
    2016.0: [n.manutd,n.crystalpalace,    n.everton,n.watford,               n.westham,n.reading,n.chelsea,n.arsenal,            ],
    2015.0: [n.arsenal,n.astonvilla,      n.reading,n.liverpool,             n.manutd,n.blackburn,n.bradford,n.westbromwich,     ],
    2014.0: [n.arsenal,n.hullcity,        n.wigan,n.sheffieldunited,         n.everton,n.sunderland,n.mancity,n.charlton,        ],
    2013.0: [n.wigan,n.mancity,           n.millwall,n.chelsea,              n.everton,n.barnsley,n.blackburn,n.manutd,          ],
    2012.0: [n.chelsea,n.liverpool,       n.tottenham,n.everton,             n.leicester,n.stoke,n.bolton,n.sunderland,          ],
    2011.0: [n.mancity,n.stoke,           n.bolton,n.manutd,                 n.arsenal,n.westham,n.birmigham,n.reading,          ],
    2010.0: [n.chelsea,n.portsmouth,      n.astonvilla,n.tottenham,          n.stoke,n.birmigham,n.reading,n.fulham,             ],
    2009.0: [n.chelsea,n.everton,         n.arsenal,n.manutd,                n.coventry,n.middlesbrough,n.hullcity,n.fulham,     ],
    2008.0: [n.portsmouth,n.cardiffcity,  n.westbromwich,n.barnsley,         n.manutd,n.middlesbrough,n.bristolrovers,n.chelsea,    ],
    2007.0: [n.chelsea,n.manutd,          n.blackburn,n.watford,             n.tottenham,n.middlesbrough,n.mancity,n.plymouth,      ],
    2006.0: [n.liverpool,n.westham,       n.chelsea,n.middlesbrough,         n.birmigham,n.mancity,n.newcastle,n.charlton,          ],
    2005.0: [n.arsenal,n.manutd,          n.blackburn,n.newcastle,           n.bolton,n.southampton,n.leicester,n.tottenham,        ],
    2004.0: [n.manutd,n.millwall,         n.arsenal,n.sunderland,            n.fulham,n.tranmere,n.portsmouth,n.sheffieldunited,    ],
    2003.0: [n.arsenal,n.southampton,     n.sheffieldunited,n.watford,       n.chelsea,n.wolves,n.leeds,n.burnley,                  ],
    2002.0: [n.arsenal,n.chelsea,         n.middlesbrough,n.fulham,          n.newcastle,n.tottenham,n.everton,n.westbromwich,      ],
    2001.0: [n.liverpool,n.arsenal,       n.wycombe,n.tottenham,             n.tranmere,n.blackburn,n.leicester,n.westham,          ],
    2000.0: [n.chelsea,n.astonvilla,      n.newcastle,n.bolton,              n.gillingham,n.everton,n.tranmere,n.charlton,          ],
    1999.0: [n.manutd,n.newcastle,        n.arsenal,n.tottenham,             n.chelsea,n.everton,n.derbycount,n.barnsley,           ],
    1998.0: [n.arsenal,n.newcastle,       n.wolves,n.sheffieldunited,        n.westham,n.barnsley,n.leeds,n.coventry,               ],
    1997.0: [n.chelsea,n.middlesbrough,   n.wimbledon,n.chesterfield,        n.portsmouth,n.derbycount,n.sheffieldwednesday,n.wrexham,   ],
    1996.0: [n.manutd,n.liverpool,        n.chelsea,n.astonvilla,            n.southampton,n.leeds,n.wimbledon,n.nottinghamforest,       ],
    1995.0: [n.everton,n.manutd,          n.tottenham,n.crystalpalace,       n.newcastle,n.qpr,n.liverpool,n.wolves,                     ],
    1994.0: [n.manutd,n.chelsea,          n.oldham,n.luton,                  n.charlton,n.wolves,n.bolton,n.westham,                     ],
    1993.0: [n.arsenal,n.sheffieldwednesday, n.tottenham,n.sheffieldunited,  n.ipswich,n.derbycount,n.mancity,n.blackburn,           ],
    1992.0: [n.liverpool,n.sunderland,     n.portsmouth,n.norwich,           n.astonvilla,n.chelsea,n.nottinghamforest,n.southampton,    ],
    1991.0: [n.tottenham,n.nottinghamforest, n.arsenal,n.westham,            n.notts,n.norwich,n.cambridge,n.everton,                    ],
    1990.0: [n.manutd,n.crystalpalace,     n.oldham,n.liverpool,             n.sheffieldunited,n.cambridge,n.astonvilla,n.qpr,           ],
    1989.0: [n.liverpool,n.everton,        n.nottinghamforest,n.norwich,     n.brentford,n.wimbledon,n.manutd,n.westham,                 ],
    1988.0: [n.wimbledon,n.liverpool,      n.luton,n.nottinghamforest,       n.watford,n.mancity,n.portsmouth,n.arsenal,                 ],
    1987.0: [n.coventry,n.tottenham,       n.leeds,n.watford,                n.sheffieldwednesday,n.wimbledon,n.wigan,n.arsenal,         ],
    1986.0: [n.liverpool,n.everton,        n.southampton,n.sheffieldwednesday, n.watford,n.luton,n.brighton,n.westham,                   ],
    1985.0: [n.manutd,n.everton,           n.liverpool,n.luton,              n.westham,n.ipswich,n.barnsley,n.millwall,              ],
    1984.0: [n.everton,n.watford,          n.southampton,n.plymouth,         n.notts,n.birmigham,n.sheffieldwednesday,n.derbycount,      ],
    1983.0: [n.manutd,n.brighton,          n.arsenal,n.sheffieldwednesday,   n.everton,n.norwich,n.astonvilla,n.burnley,                 ],
    1982.0: [n.tottenham,n.qpr,            n.leicester,n.westbromwich,       n.chelsea,n.crystalpalace,n.shrewsbury,n.coventry,          ],
    1981.0: [n.tottenham,n.mancity,        n.wolves,n.ipswich,           n.exeter,n.everton,n.middlesbrough,n.nottinghamforest,      ],
    1980.0: [n.westham,n.arsenal,          n.everton,n.liverpool,            n.astonvilla,n.watford,n.ipswich,n.tottenham,           ],
    1979.0: [n.arsenal,n.manutd,           n.wolves,n.liverpool,             n.southampton,n.tottenham,n.shrewsbury,n.ipswich,       ],
    1978.0: [n.ipswich,n.arsenal,      n.westbromwich,n.leyton,          n.millwall,n.wrexham,n.nottinghamforest,n.middlesbrough,    ],
    1977.0: [n.manutd,n.liverpool,         n.leeds,n.everton,                n.astonvilla,n.middlesbrough,n.wolves,n.derbycount,         ],
    1976.0: [n.southampton,n.manutd,       n.crystalpalace,n.derbycount,     n.bradford,n.wolves,n.sunderland,n.newcastle,               ],
    1975.0: [n.westham,n.fulham,           n.ipswich,n.birmigham,        n.arsenal,n.carlisle,n.leeds,n.middlesbrough,               ],
    1974.0: [n.liverpool,n.newcastle,      n.leicester,n.burnley,            n.bristol,n.nottinghamforest,n.qpr,n.wrexham,               ],
    1973.0: [n.sunderland,n.leeds,         n.arsenal,n.wolves,               n.luton,n.derbycount,n.chelsea,n.coventry,                  ],
    1972.0: [n.leeds,n.arsenal,            n.birmigham,n.stoke,              n.tottenham,n.leyton,n.huddersfield,n.manutd,               ],
    1971.0: [n.arsenal,n.liverpool,        n.stoke,n.everton,                n.leicester,n.tottenham,n.hullcity,n.colchester,            ],
    1970.0: [n.chelsea,n.leeds,            n.watford,n.manutd,               n.qpr,n.swindon,n.liverpool,n.middlesbrough,                ],
    1969.0: [n.mancity,n.leicester,        n.everton,n.westbromwich,         n.tottenham,n.mansfield,n.manutd,n.chelsea,                 ],
    1968.0: [n.westbromwich,n.everton,     n.birmigham,n.leeds,              n.liverpool,n.leicester,n.chelsea,n.sheffieldunited,        ],
    1967.0: [n.tottenham,n.chelsea,        n.nottinghamforest,n.leeds,       n.birmigham,n.sheffieldwednesday,n.everton,n.mancity,       ],
    1966.0: [n.everton,n.sheffieldwednesday, n.manutd,n.chelsea,             n.mancity,n.blackburn,n.prestonnorthend,n.hullcity,         ],
    1965.0: [n.liverpool,n.leeds,          n.chelsea,n.manutd,               n.leicester,n.crystalpalace,n.peterborough,n.wolves,        ],
    1964.0: [n.westham,n.prestonnorthend,  n.manutd,n.swansea,               n.burnley,n.oxford,n.sunderland,n.liverpool,                ],
    1963.0: [n.manutd,n.leicester,         n.southampton,n.liverpool,        n.coventry,n.norwich,n.nottinghamforest,n.westham,          ],
    1962.0: [n.tottenham,n.burnley,        n.manutd,n.fulham,                n.astonvilla,n.sheffieldunited,n.prestonnorthend,n.blackburn, ],
    1961.0: [n.tottenham,n.leicester,      n.burnley,n.sheffieldunited,      n.sunderland,n.barnsley,n.sheffieldwednesday,n.newcastle,   ],
    1960.0: [n.wolves,n.blackburn,         n.astonvilla,n.sheffieldwednesday, n.leicester,n.burnley,n.prestonnorthend,n.sheffieldunited, ],
    1959.0: [n.nottinghamforest,n.luton,   n.astonvilla,n.norwich,           n.bolton,n.blackpool,n.burnley,n.sheffieldunited,           ],
    1958.0: [n.bolton,n.manutd,            n.blackburn,n.fulham,             n.wolves,n.westbromwich,n.liverpool,n.bristolrovers,        ],
    1957.0: [n.astonvilla,n.manutd,        n.westbromwich,n.birmigham,       n.burnley,n.bournemouth,n.arsenal,n.nottinghamforest,       ],
    1956.0: [n.mancity,n.birmigham,        n.tottenham,n.sunderland,         n.everton,n.arsenal,n.westham,n.newcastle,                  ],
    1955.0: [n.newcastle,n.mancity,        n.york,n.sunderland,              n.huddersfield,n.birmigham,n.notts,n.wolves,                ],
    1954.0: [n.westbromwich,n.prestonnorthend, n.sheffieldwednesday,n.portvale, n.tottenham,n.leicester,n.bolton,n.leyton,               ],
    1953.0: [n.blackpool,n.bolton,         n.tottenham,n.everton,            n.arsenal,n.gateshead,n.birmigham,n.astonvilla,             ],
    1952.0: [n.newcastle,n.arsenal,        n.blackburn,n.chelsea,            n.portsmouth,n.luton,n.burnley,n.sheffieldunited,           ],
    1951.0: [n.newcastle,n.blackpool,      n.wolves,n.birmigham,             n.bristolrovers,n.fulham,n.sunderland,n.manutd,             ],
    1950.0: [n.arsenal,n.liverpool,        n.chelsea,n.everton,              n.leeds,n.blackpool,n.manutd,n.derbycount,                  ],
    1949.0: [n.wolves,n.leicester,         n.manutd,n.portsmouth,            n.westbromwich,n.brentford,n.hullcity,n.derbycount,         ],
    1948.0: [n.manutd,n.blackpool,         n.derbycount,n.tottenham,         n.prestonnorthend,n.fulham,n.qpr,n.southampton,             ],
    1947.0: [n.charlton,n.burnley,         n.newcastle,n.liverpool,          n.prestonnorthend,n.middlesbrough,n.sheffieldunited,n.birmigham,],
    1946.0: [n.derbycount,n.charlton,      n.birmigham,n.bolton,             n.astonvilla,n.brentford,n.bradford,n.stoke,                ],
  },
  
  leagueName.italyCup : {
    //2023.0: [],
    2022.0: [n.inter, n.juventus,n.milan,n.fiorentina,],
    2021.0: [n.juventus,n.atalanta,n.napoli,n.inter,],
    2020.0: [n.napoli,n.juventus,n.milan,n.inter,],
    2019.0: [n.lazio,n.atalanta,n.fiorentina,n.milan,],
    2018.0: [n.juventus,n.milan,n.lazio,n.atalanta,],
    2017.0: [n.juventus,n.lazio,n.napoli,n.roma],
    2016.0: [n.juventus,n.milan,n.alessandria,n.inter],
    2015.0: [n.juventus,n.lazio,n.fiorentina,n.napoli],
    2014.0: [n.napoli,n.fiorentina,n.roma,n.udinese],
    2013.0: [n.lazio,n.roma,n.juventus,n.inter],
    2012.0: [n.napoli,n.juventus,n.siena,n.milan],
    2011.0: [n.inter,n.palermo,n.roma,n.milan],
    2010.0: [n.inter,n.roma,n.fiorentina,n.udinese],
    2009.0: [n.lazio,n.sampdoria,n.juventus,n.inter],
    2008.0: [n.roma,n.inter,n.catania,n.lazio],
    2007.0: [n.roma,n.inter,n.sampdoria,n.milan],
    2006.0: [n.inter,n.roma,n.palermo,n.udinese],
    2005.0: [n.inter,n.roma,n.cagliari,n.udinese],
    2004.0: [n.lazio,n.juventus,n.milan,n.inter],
    2003.0: [n.milan,n.roma,n.perugia,n.lazio],
    2002.0: [n.parma,n.juventus,n.milan,n.brescia],
    2001.0: [n.fiorentina,n.parma,n.udinese,n.milan],
    2000.0: [n.lazio,n.inter,n.cagliari,n.venezia],
    1999.0: [n.parma,n.fiorentina,n.inter,n.bologna],
    1998.0: [n.lazio,n.milan,n.parma,n.juventus],
    1997.0: [n.vicenza,n.napoli,n.inter,n.bologna],
    1996.0: [n.fiorentina,n.atalanta,n.bologna,n.inter],
    1995.0: [n.juventus,n.parma,n.foggia,n.lazio],
    1994.0: [n.sampdoria,n.ancona,n.torino,n.parma],
    1993.0: [n.torino,n.roma,n.juventus,n.milan],
    1992.0: [n.parma,n.juventus,n.sampdoria,n.milan],
    1991.0: [n.roma,n.sampdoria,n.napoli,n.milan],
    1990.0: [n.juventus,n.milan,n.napoli,n.roma],
    1989.0: [n.sampdoria,n.napoli,n.atalanta,n.pisa],
    1988.0: [n.sampdoria,n.torino,n.juventus,n.inter],
    1987.0: [n.napoli,n.atalanta,n.cagliari,n.cremonese],
    1986.0: [n.roma,n.sampdoria,n.fiorentina,n.como],
    1985.0: [n.sampdoria,n.milan,n.inter,n.fiorentina],
    1984.0: [n.roma,n.hellasVerona,n.bari,n.torino],
    1983.0: [n.juventus,n.hellasVerona,n.torino,n.inter],
    1982.0: [n.inter,n.torino,n.catanzaro,n.sampdoria],
    1981.0: [n.roma,n.torino,n.bologna,n.juventus],
    1980.0: [n.roma,n.torino,n.ternana,n.juventus],
    1979.0: [n.juventus,n.palermo,n.napoli,n.catanzaro],
    1978.0: [n.inter,n.napoli,n.milan,n.fiorentina],
    1977.0: [n.milan,n.inter,n.juventus,n.bologna],
    1976.0: [n.napoli,n.hellasVerona,n.inter,n.fiorentina],
    1975.0: [n.fiorentina,n.milan,n.juventus,n.torino],
    1974.0: [n.bologna,n.palermo,n.inter,n.fiorentina],
    1973.0: [n.milan,n.juventus,n.inter,n.atalanta],
    1972.0: [n.milan,n.napoli,n.fiorentina,n.torino],
    1971.0: [n.torino,n.milan,n.fiorentina,n.napoli],
    1970.0: [n.bologna,n.torino,n.cagliari,n.varese],
    1969.0: [n.roma,n.cagliari,n.foggia,n.torino],
    1968.0: [n.torino,n.milan,n.inter,n.bologna],
    1967.0: [n.milan,n.padova,n.inter,n.juventus],
    1966.0: [n.fiorentina,n.catanzaro,n.juventus,n.inter],
    1965.0: [n.juventus,n.inter,n.roma,n.torino],
    1964.0: [n.roma,n.torino,n.fiorentina,n.juventus],
    1963.0: [n.atalanta,n.torino,n.hellasVerona,n.bari],
    1962.0: [n.napoli,n.spal,n.mantova,n.juventus],
    1961.0: [n.fiorentina,n.lazio,n.juventus,n.torino],
    1960.0: [n.juventus,n.fiorentina,n.lazio,n.torino],
    1959.0: [n.juventus,n.inter,n.genoa,n.hellasVerona],
    1958.0: [n.lazio,n.fiorentina,n.bologna,n.juventus],
  },
  leagueName.spainCup : {
    //2023.0: [],
    2022.0: [n.realbetis, n.valencia,        n.rayovallecano,n.athleticbilbao,],
    2021.0: [n.barcelona,n.athleticbilbao,   n.sevilla,n.levante,            ],
    2020.0: [n.realsociedad,n.athleticbilbao, n.mirandes,n.granada,          ],
    2019.0: [n.valencia,n.barcelona,         n.realbetis,n.realmadrid,       ],
    2018.0: [n.barcelona,n.sevilla,          n.valencia,n.leganes,           ],
    2017.0: [n.barcelona,n.alaves,           n.atleticomadrid,n.celtavigo,   ],
    2016.0: [n.barcelona,n.sevilla,          n.valencia,n.celtavigo,         ],
    2015.0: [n.barcelona,n.athleticbilbao,   n.villareal,n.espanyol,         ],
    2014.0: [n.realmadrid,n.barcelona,       n.atleticomadrid,n.realsociedad,],
    2013.0: [n.atleticomadrid,n.realmadrid,  n.sevilla,n.barcelona,          ],
    2012.0: [n.barcelona,n.athleticbilbao,   n.valencia,n.mirandes,          ],
    2011.0: [n.realmadrid,n.barcelona,       n.sevilla,n.almeria,            ],
    2010.0: [n.sevilla,n.atleticomadrid,     n.getafe,n.racingSantander,     ], //n.lacoruna,n.celtavigo,n.mallorca,n.osasuna,       ],
    2009.0: [n.barcelona,n.athleticbilbao,   n.mallorca,n.sevilla,           ], //n.espanyol,n.sportinggijon,n.realbetis,n.valencia, ],
    2008.0: [n.valencia,n.getafe,            n.barcelona,n.racingSantander,  ],
    2007.0: [n.sevilla,n.getafe,             n.lacoruna,n.barcelona,         ],
    2006.0: [n.espanyol,n.zaragoza,          n.lacoruna,n.realmadrid,        ],
    2005.0: [n.realbetis,n.osasuna,          n.athleticbilbao,n.atleticomadrid, ],
    2004.0: [n.zaragoza,n.realmadrid,        n.alaves,n.sevilla,             ],
    2003.0: [n.mallorca,n.huelva,            n.lacoruna,n.osasuna,           ],
    2002.0: [n.lacoruna,n.realmadrid,        n.figueres,n.athleticbilbao,    ],
    2001.0: [n.zaragoza,n.celtavigo,         n.atleticomadrid,n.barcelona,   ],
    2000.0: [n.espanyol,n.atleticomadrid,    n.realmadrid,n.barcelona,       ],
    1999.0: [n.valencia,n.atleticomadrid,    n.realmadrid,n.lacoruna,        ],
    1998.0: [n.barcelona,n.mallorca,         n.zaragoza,n.alaves,            ],
    1997.0: [n.barcelona,n.realbetis,        n.laspalmas,n.celtavigo,        ],
    1996.0: [n.atleticomadrid,n.barcelona,   n.valencia,n.espanyol,          ],
    1995.0: [n.lacoruna,n.valencia,          n.sportinggijon,n.albacete,     ],
    1994.0: [n.zaragoza,n.celtavigo,         n.realbetis,n.tenerife,         ],
    1993.0: [n.realmadrid,n.zaragoza,        n.barcelona,n.valencia,         ],
    1992.0: [n.atleticomadrid,n.realmadrid,  n.lacoruna,n.sportinggijon,     ],
    1991.0: [n.atleticomadrid,n.mallorca,    n.barcelona,n.sportinggijon,    ],
    1990.0: [n.barcelona,n.realmadrid,       n.valencia,n.cadiz,             ],
    1989.0: [n.realmadrid,n.valladolid,      n.atleticomadrid,n.lacoruna,    ],
    1988.0: [n.barcelona,n.valladolid,       n.osasuna,n.realmadrid,         ],
    1987.0: [n.realsociedad,n.atleticomadrid, n.athleticbilbao,n.realmadrid, ],
    1986.0: [n.zaragoza,n.barcelona,        n.realmadrid,n.athleticbilbao,   ],
    1985.0: [n.atleticomadrid,n.athleticbilbao, n.zaragoza,n.realbetis,      ],
    1984.0: [n.athleticbilbao,n.barcelona,  n.realmadrid,n.laspalmas,        ],
    1983.0: [n.barcelona,n.realmadrid,      n.realsociedad,n.sportinggijon,  ],
    1982.0: [n.realmadrid,n.sportinggijon,  n.realsociedad,n.rayovallecano,  ],
    1981.0: [n.barcelona,n.sportinggijon,   n.athleticbilbao,n.sevilla,      ],
    1980.0: [n.realmadrid,n.realmadridB,    n.atleticomadrid,n.sportinggijon,],
    1979.0: [n.valencia,n.realmadrid,       n.valladolid,n.sevilla,          ],
    1978.0: [n.barcelona,n.laspalmas,       n.realsociedad,n.sportinggijon,  ],
    1977.0: [n.realbetis,n.athleticbilbao,  n.espanyol,n.salamanca,          ],
    1976.0: [n.atleticomadrid,n.zaragoza,   n.realsociedad,n.realbetis,      ],
    1975.0: [n.realmadrid,n.atleticomadrid, n.zaragoza,n.athleticbilbao,     ],
    1974.0: [n.realmadrid,n.barcelona,      n.laspalmas,n.atleticomadrid,    ],
    1973.0: [n.athleticbilbao,n.castellon,  n.malaga,n.sportinggijon,        ],
    1972.0: [n.atleticomadrid,n.valencia,   n.athleticbilbao,n.realmadrid,   ],
    1971.0: [n.barcelona,n.valencia,        n.atleticomadrid,n.sevilla,      ],
    1970.0: [n.realmadrid,n.valencia,       n.athleticbilbao,n.zaragoza,     ],
    1969.0: [n.athleticbilbao,n.elche,      n.granada,n.realsociedad,        ],
    1968.0: [n.barcelona,n.realmadrid,      n.atleticomadrid,n.celtavigo,    ],
    1967.0: [n.valencia,n.athleticbilbao,   n.elche,n.cordoba,               ],
    1966.0: [n.zaragoza,n.athleticbilbao,   n.barcelona,n.realbetis,         ],
    1965.0: [n.atleticomadrid,n.zaragoza,   n.realsociedad,n.athleticbilbao, ],
    1964.0: [n.zaragoza,n.atleticomadrid,   n.barcelona,n.valencia,          ],
    1963.0: [n.barcelona,n.zaragoza,        n.valencia,n.realmadrid,         ],
    1962.0: [n.realmadrid,n.sevilla,        n.zaragoza,n.valencia,           ],
    1961.0: [n.atleticomadrid,n.realmadrid, n.valladolid,n.realbetis,        ],
    1960.0: [n.atleticomadrid,n.realmadrid, n.athleticbilbao,n.elche,        ],
    1959.0: [n.barcelona,n.granada,         n.realmadrid,n.valencia,         ],
    1958.0: [n.athleticbilbao,n.realmadrid, n.barcelona,n.realsociedad,      ],
    1957.0: [n.barcelona,n.espanyol,        n.realsociedad,n.valencia,       ],
    1956.0: [n.athleticbilbao,n.atleticomadrid, n.realmadrid,n.espanyol,     ],
    1955.0: [n.athleticbilbao,n.sevilla,    n.barcelona,n.realmadrid,        ],
    1954.0: [n.valencia,n.barcelona,        n.sevilla,n.realmadrid,          ],
    1953.0: [n.barcelona,n.athleticbilbao,  n.atleticomadrid,n.realmadrid,   ],
    1952.0: [n.barcelona,n.valencia,        n.valladolid,n.realmadrid,       ],
    1951.0: [n.barcelona,n.realsociedad,    n.athleticbilbao,n.realmadrid,   ],
    1950.0: [n.athleticbilbao,n.valladolid, n.valencia,n.realmadrid,         ],
    1949.0: [n.valencia,n.athleticbilbao,   n.barcelona,n.espanyol,          ],
    1948.0: [n.sevilla,n.celtavigo,         n.realsociedad,n.espanyol,       ],
    1947.0: [n.realmadrid,n.espanyol,       n.athleticbilbao,n.tarragona,    ],
    1946.0: [n.realmadrid,n.valencia,       n.realOviedo,n.sevilla,          ],
    1945.0: [n.athleticbilbao,n.valencia,   n.espanyol,n.granada,            ],
  },

   leagueName.franceCup : {
    2023.0: [n.toulouse,n.nantes,],
    2022.0: [n.nantes,n.nice],
    2021.0: [n.psg,n.monaco,],
    2020.0: [n.psg,n.saintetienne],
    2019.0: [n.rennes,n.psg],
    2018.0: [n.psg,n.vendee],
    2017.0: [n.psg,n.angers],
    2016.0: [n.psg,n.om],
    2015.0: [n.psg,n.auxerre],
    2014.0: [n.guingamp,n.rennes],
    2013.0: [n.bordeaux,n.evian],
    2012.0: [n.lyon,n.quevilly],
    2011.0: [n.lille,n.psg],
    2010.0: [n.psg,n.monaco],
    2009.0: [n.guingamp,n.rennes],
    2008.0: [n.lyon,n.psg],
    2007.0: [n.sochaux,n.om],
    2006.0: [n.psg,n.om],
    2005.0: [n.auxerre,n.sedan],
    2004.0: [n.psg,n.chateauroux],
    2003.0: [n.auxerre,n.psg],
    2002.0: [n.lorient,n.bastia],
    2001.0: [n.strasbourg,n.amiens],
    2000.0: [n.nantes,n.calais],
    1999.0: [n.nantes,n.sedan],
    1998.0: [n.psg,n.lens],
    1997.0: [n.nice,n.guingamp],
    1996.0: [n.auxerre,n.nimes],
    1995.0: [n.psg,n.strasbourg],
    1994.0: [n.auxerre,n.montpellier,],
    1993.0: [n.psg,n.nantes],
    1992.0: [],
    1991.0: [n.monaco,n.om],
    1990.0: [n.montpellier,n.racingParis],
    1989.0: [n.om,n.monaco,],
    1988.0: [n.metz,n.sochaux,],
    1987.0: [n.bordeaux,n.om],
    1986.0: [n.bordeaux,n.om],
    1985.0: [n.monaco,n.psg],
    1984.0: [n.metz,n.monaco],
    1983.0: [n.psg,n.nantes],
    1982.0: [n.psg,n.saintetienne],
    1981.0: [n.bastia,n.saintetienne],
    1980.0: [n.monaco,n.orleans],
    1979.0: [n.nantes,n.auxerre],
    1978.0: [n.nancy,n.nice],
    1977.0: [n.saintetienne,n.reims],
    1976.0: [n.om,n.lyon],
    1975.0: [n.saintetienne,n.lens],
    1974.0: [n.saintetienne,n.monaco],
    1973.0: [n.lyon,n.nantes],
    1972.0: [n.om,n.bastia],
    1971.0: [n.rennes,n.lyon],
    1970.0: [n.saintetienne,n.nantes],
    1969.0: [n.om,n.bordeaux],
    1968.0: [n.saintetienne,n.bordeaux],
    1967.0: [n.lyon,n.sochaux],
    1966.0: [n.strasbourg,n.nantes],
    1965.0: [n.rennes,n.sedan],
    1964.0: [n.lyon,n.bordeaux],
    1963.0: [n.monaco,n.lyon],
    1962.0: [n.saintetienne,n.nancy],
    1961.0: [n.sedan,n.nimes],
    1960.0: [n.monaco,n.saintetienne],
    1959.0: [n.lehavre,n.sochaux,],
    1958.0: [n.reims,n.nimes,],
    1957.0: [n.toulouse,n.angers,],
    1956.0: [n.sedan,n.troyes,],
    1955.0: [n.lille,n.bordeaux,],
    1954.0: [n.nice,n.om,],
    1953.0: [n.lille,n.nancy,],
    1952.0: [n.nice,n.bordeaux,],
    1951.0: [n.strasbourg,n.valenciennes,],
    1950.0: [n.reims,n.racingParis,],
    1949.0: [n.racingParis,n.lille,],
    1948.0: [n.lille,n.lens,],
    1947.0: [n.lille,n.strasbourg,],
    1946.0: [n.lille,n.redstar,],
  },

  leagueName.germanyCup : {
    //2023.0: [],
    2022.0: [n.rbleipzig,n.freiburg,          n.unionberlin,n.hamburgo,       ], 
    2021.0: [n.dortmund,n.rbleipzig,          n.holsteinkiel,n.werderbremen,  ],
    2020.0: [n.bayernmunique,n.leverkusen,    n.eintrachtfrankfurt,n.saarbrucken,],
    2019.0: [n.bayernmunique,n.rbleipzig,     n.werderbremen,n.hamburgo,      ],
    2018.0: [n.eintrachtfrankfurt,n.bayernmunique, n.schalke04,n.leverkusen,  ],
    2017.0: [n.dortmund,n.eintrachtfrankfurt, n.bayernmunique,n.moenchengladbach, ],
    2016.0: [n.bayernmunique,n.dortmund,      n.werderbremen,n.herthaberlim,   ],
    2015.0: [n.wolfsburg,n.dortmund,          n.arminiabiefeld,n.bayernmunique,],
    2014.0: [n.bayernmunique,n.dortmund,      n.wolfsburg,n.kaiserslautern,    ],
    2013.0: [n.bayernmunique,n.stuttgart,     n.wolfsburg,n.freiburg,          ],
    2012.0: [n.dortmund,n.bayernmunique,      n.greutherfurth,n.moenchengladbach, ],
    2011.0: [n.schalke04,n.duisburg,          n.bayernmunique,n.energiecottbus,],
    2010.0: [n.bayernmunique,n.werderbremen,  n.schalke04,n.augsburg,          ],
    2009.0: [n.werderbremen,n.leverkusen,     n.hamburgo,n.mainz05],
    2008.0: [n.bayernmunique,   n.dortmund,   n.wolfsburg,n.carlzeissjena,],
    2007.0: [n.nurnberg,        n.stuttgart,  n.eintrachtfrankfurt,n.wolfsburg,],
    2006.0: [n.bayernmunique,   n.eintrachtfrankfurt,  n.stpauli,n.arminiabiefeld,],
    2005.0: [n.bayernmunique,   n.schalke04,  n.arminiabiefeld,n.werderbremen,  ],
    2004.0: [n.werderbremen,    n.alemanniaaachen,     n.lubeck,n.moenchengladbach,],
    2003.0: [n.bayernmunique,   n.kaiserslautern,n.leverkusen,n.werderbremen,   ],
    2002.0: [n.schalke04,       n.leverkusen, n.bayernmunique,n.koln,      ],
    2001.0: [n.schalke04,       n.unionberlin,n.stuttgart,n.moenchengladbach, ],
    2000.0: [n.bayernmunique,n.werderbremen,  n.hansarostock,n.stuttgarterkickers,   ],
    1999.0: [n.werderbremen,n.bayernmunique,  n.wolfsburg,n.oberhausen,       ],
    1998.0: [n.bayernmunique,n.duisburg,      n.stuttgart,n.trier,            ],
    1997.0: [n.stuttgart,n.energiecottbus,    n.hamburgo,n.karlsruher,        ],
    1996.0: [n.kaiserslautern,n.karlsruher,   n.leverkusen,n.fortunadusseldorf,],
    1995.0: [n.moenchengladbach,n.wolfsburg,  n.kaiserslautern,n.koln,     ],
    1994.0: [n.werderbremen,n.rotweissessen,  n.dynamodresden,n.tennisborussiaberlin, ],
    1993.0: [n.leverkusen,n.herthaberlim,     n.eintrachtfrankfurt,n.chemnitzer,],
    1992.0: [n.hannover96,   n.moenchengladbach],
    1991.0: [n.werderbremen, n.koln        ],
    1990.0: [n.kaiserslautern,n.werderbremen, ],
    1989.0: [n.dortmund,n.werderbremen,       ],
    1988.0: [n.eintrachtfrankfurt,n.bochum,   ],
    1987.0: [n.hamburgo,n.stuttgarterkickers,        ],
    1986.0: [n.bayernmunique,n.stuttgart,     ],
    1985.0: [n.uerdigen,n.bayernmunique,      ],
    1984.0: [n.bayernmunique,n.moenchengladbach,],
    1983.0: [n.koln,n.fortunakoln,         ],
    1982.0: [n.bayernmunique,n.nurnberg,      ],
    1981.0: [n.eintrachtfrankfurt,n.kaiserslautern,],
    1980.0: [n.fortunadusseldorf,n.koln,   ],
    1979.0: [n.fortunadusseldorf,n.herthaberlim],
    1978.0: [n.koln,n.fortunadusseldorf,   ],
    1977.0: [n.koln,n.herthaberlim,        ],
    1976.0: [n.hamburgo,n.kaiserslautern,     ],
    1975.0: [n.eintrachtfrankfurt,n.duisburg, ],
    1974.0: [n.eintrachtfrankfurt,n.hamburgo, ],
    1973.0: [n.moenchengladbach,n.koln,    ],
    1972.0: [n.schalke04,n.kaiserslautern,    ],
    1971.0: [n.bayernmunique,n.koln,       ],
    1970.0: [n.kickersoffenbach,n.koln,    ],
    1969.0: [n.bayernmunique,n.schalke04,     ],
    1968.0: [n.koln,n.bochum,              ],
    1967.0: [n.bayernmunique,n.hamburgo,      ],
    1966.0: [n.bayernmunique,n.duisburg,      ],
    1965.0: [n.dortmund,n.alemanniaaachen,             ],
    1964.0: [n.munich1860,n.eintrachtfrankfurt,],
    1963.0: [n.hamburgo,n.dortmund,],
    1962.0: [n.nurnberg,n.fortunadusseldorf,],
    1961.0: [n.werderbremen,n.kaiserslautern,],
    1960.0: [n.moenchengladbach,n.karlsruher,],
    1959.0: [],
    1958.0: [n.stuttgart,n.fortunadusseldorf,],
    1957.0: [n.bayernmunique,n.fortunadusseldorf,],
    1956.0: [n.karlsruher,n.hamburgo,],
    1955.0: [n.karlsruher,n.schalke04,],
    1954.0: [n.stuttgart,n.koln,],
    1953.0: [n.rotweissessen,n.alemanniaaachen,],
  },

   leagueName.portugalCup : {
     //2023.0: [],
    2022.0: [n.porto,n.tondela,],
    2021.0: [n.braga,n.benfica,],
    2020.0: [n.porto,n.benfica,],
    2019.0: [n.sporting,n.porto,],
    2018.0: [n.aves,n.sporting,],
    2017.0: [n.benfica,n.vitoriaguimaraes,],
    2016.0: [n.braga,n.porto,],
    2015.0: [n.sporting,n.braga,],
    2014.0: [n.benfica,n.rioAve,],
    2013.0: [n.vitoriaguimaraes,n.benfica,],
    2012.0: [n.coimbra,n.sporting,],
    2011.0: [n.porto,n.vitoriaguimaraes,],
    2010.0: [n.porto,n.chaves,],
    2009.0: [n.porto,n.pacosDeFerreira,],
    2008.0: [n.sporting,n.porto,],
    2007.0: [n.sporting,n.belenenses,],
    2006.0: [n.porto,n.setubal,],
    2005.0: [n.setubal,n.benfica,],
    2004.0: [n.benfica,n.porto,],
    2003.0: [n.porto,n.leiria,],
    2002.0: [n.sporting,n.leixoes,],
    2001.0: [n.porto,n.maritimo,],
    2000.0: [n.porto,n.sporting,],
    1999.0: [n.beiramar,n.campomaiorense,],
    1998.0: [n.porto,n.braga,],
    1997.0: [n.boavista,n.benfica,],
    1996.0: [n.benfica,n.sporting,],
    1995.0: [n.sporting,n.maritimo,],
    1994.0: [n.porto,n.sporting,],
    1993.0: [n.benfica,n.boavista,],
    1992.0: [n.boavista,n.porto,],
    1991.0: [n.porto,n.beiramar,],
    1990.0: [n.estrelaamadora,n.farense,],
    1989.0: [n.belenenses,n.benfica,],
    1988.0: [n.porto,n.vitoriaguimaraes,],
    1987.0: [n.benfica,n.sporting,],
    1986.0: [n.benfica,n.belenenses,],
    1985.0: [n.benfica,n.porto,],
    1984.0: [n.porto,n.rioAve,],
    1983.0: [n.benfica,n.porto,],
    1982.0: [n.sporting,n.braga,],
    1981.0: [n.benfica,n.porto,],
    1980.0: [n.benfica,n.porto,],
    1979.0: [n.boavista,n.sporting,],
    1978.0: [n.sporting,n.porto,],
    1977.0: [n.porto,n.braga,],
    1976.0: [n.boavista,n.vitoriaguimaraes,],
    1975.0: [n.boavista,n.benfica,],
    1974.0: [n.sporting,n.benfica,],
    1973.0: [n.sporting,n.setubal,],
    1972.0: [n.benfica,n.sporting,],
    1971.0: [n.sporting,n.benfica,],
    1970.0: [n.benfica,n.sporting,],
    1969.0: [n.benfica,n.coimbra,],
    1968.0: [n.porto,n.setubal,],
    1967.0: [n.setubal,n.coimbra,],
    1966.0: [n.braga,n.setubal,],
    1965.0: [n.setubal,n.benfica,],
    1964.0: [n.benfica,n.porto,],
    1963.0: [n.sporting,n.vitoriaguimaraes,],
    1962.0: [n.benfica,n.setubal,],
    1961.0: [n.leixoes,n.porto,],
    1960.0: [n.belenenses,n.sporting,],
    1959.0: [n.benfica,n.porto,],
    1958.0: [n.porto,n.benfica,],
    1957.0: [n.benfica,n.covilha,],
    1956.0: [n.porto,n.torreense,],
    1955.0: [n.benfica,n.sporting,],
    1954.0: [n.sporting,n.setubal,],
    1953.0: [n.benfica,n.porto,],
    1952.0: [n.benfica,n.sporting,],
    1951.0: [n.benfica,n.coimbra,],
    1950.0: [],
    1949.0: [n.benfica,n.atleticoPT,],
    1948.0: [n.sporting,n.belenenses,],
    1947.0: [],
    1946.0: [n.sporting,n.atleticoPT],
    1945.0: [n.sporting,n.olhanense],
  },

  leagueName.turkeyCup : {
    //2023.0: [],
    2022.0: [n.sivasspor,n.kayserispor,],
    2021.0: [n.besiktas,n.antalyaspor,],
    2020.0: [n.trabzonspor,n.alanyaspor,],
    2019.0: [n.galatasaray,n.akhisarspor,],
    2018.0: [n.akhisarspor,n.fenerbahce,],
    2017.0: [n.konyaspor,n.istanbulbasaksehir,],
    2016.0: [n.galatasaray,n.fenerbahce,],
    2015.0: [n.galatasaray,n.bursaspor,],
    2014.0: [n.galatasaray,n.eskisehirspor,],
    2013.0: [n.fenerbahce,n.trabzonspor,],
    2012.0: [n.fenerbahce,n.trabzonspor,],
    2011.0: [n.besiktas,n.istanbulbasaksehir,],
    2010.0: [n.trabzonspor,n.fenerbahce,],
    2009.0: [n.besiktas,n.fenerbahce,],
    2008.0: [n.kayserispor,n.genclerbirligi,],
    2007.0: [n.besiktas,],
    2006.0: [n.besiktas,n.fenerbahce,],
    2005.0: [n.galatasaray,n.fenerbahce,],
    2004.0: [n.trabzonspor,n.genclerbirligi,],
    2003.0: [n.trabzonspor,n.genclerbirligi,],
    2002.0: [n.kocaelispor,n.besiktas,],
    2001.0: [n.genclerbirligi,n.fenerbahce,],
    2000.0: [n.galatasaray,n.antalyaspor,],
    1999.0: [n.galatasaray,n.besiktas,],
    1998.0: [n.besiktas,n.galatasaray,],
    1997.0: [n.kocaelispor,n.trabzonspor,],
    1996.0: [n.galatasaray,n.fenerbahce,],
    1995.0: [n.trabzonspor,n.galatasaray,],
    1994.0: [n.besiktas,n.galatasaray,],
    1993.0: [n.galatasaray,n.besiktas,],
    1992.0: [n.trabzonspor,n.bursaspor,],
    1991.0: [n.galatasaray,n.ankaragucu,],
    1990.0: [n.besiktas,n.trabzonspor,],
    1989.0: [n.besiktas,n.fenerbahce,],
    1988.0: [n.sakaryaspor,n.samsunspor,],
    1987.0: [n.genclerbirligi,n.eskisehirspor,],
    1986.0: [n.bursaspor,n.altay,],
    1985.0: [n.galatasaray,n.trabzonspor,],
    1984.0: [n.trabzonspor,n.besiktas,],
    1983.0: [n.fenerbahce,n.mersinidmanyurdu,],
    1982.0: [n.galatasaray,n.ankaragucu,],
    1981.0: [n.ankaragucu,n.boluspor,],
    1980.0: [n.altay,n.galatasaray,],
    1979.0: [n.fenerbahce,n.altay,],
    1978.0: [n.trabzonspor,n.besiktas,],
    1977.0: [n.trabzonspor,n.besiktas,],
    1976.0: [n.galatasaray,n.trabzonspor,],
    1975.0: [n.besiktas,n.trabzonspor,],
    1974.0: [n.fenerbahce,n.bursaspor,],
    1973.0: [n.galatasaray,n.ankaragucu,],
    1972.0: [n.ankaragucu,n.altay,],
    1971.0: [n.eskisehirspor,n.bursaspor,],
    1970.0: [n.goztepe,n.eskisehirspor,],
    1969.0: [n.goztepe,n.galatasaray,],
    1968.0: [n.fenerbahce,n.altay,],
    1967.0: [n.altay,n.goztepe,],
    1966.0: [n.galatasaray,n.besiktas,],
    1965.0: [n.galatasaray,n.fenerbahce,],
    1964.0: [n.galatasaray,n.altay,],
    1963.0: [n.galatasaray,n.fenerbahce,],
  },
  leagueName.russiaCup : {
    //2023.0: [],
    2022.0: [n.spartakmoscou,n.dinamoMoscou,],
    2021.0: [n.lokomotivMoscou,n.krylyaSovetov,],
    2020.0: [n.zenit,n.khimki,],
    2019.0: [n.lokomotivMoscou,n.ural,],
    2018.0: [n.tosno,n.avangard,],
    2017.0: [n.lokomotivMoscou,n.ural,],
    2016.0: [n.zenit,n.cska,],
    2015.0: [n.lokomotivMoscou,n.kubanKrasnodar,],
    2014.0: [n.rostov,n.krasnodar,],
    2013.0: [n.cska,n.anzhi,],
    2012.0: [n.rubinKazan,n.dinamoMoscou,],
    2011.0: [n.cska,n.alania,],
    2010.0: [n.zenit,n.sibir],
    2009.0: [n.cska,n.rubinKazan,],
    2008.0: [n.cska,n.amkar,],
    2007.0: [n.lokomotivMoscou,n.moskva],
    2006.0: [n.cska,n.spartakmoscou,],
    2005.0: [n.cska,n.khimki,],
    2004.0: [n.akhmatGrozny,n.krylyaSovetov,],
    2003.0: [n.spartakmoscou,n.rostov,],
    2002.0: [n.cska,n.zenit,],
    2001.0: [n.lokomotivMoscou,n.anzhi,],
    2000.0: [n.lokomotivMoscou,n.cska,],
    1999.0: [n.zenit,n.dinamoMoscou,],
    1998.0: [n.spartakmoscou,n.lokomotivMoscou,],
    1997.0: [n.lokomotivMoscou,n.dinamoMoscou,],
    1996.0: [n.lokomotivMoscou,n.spartakmoscou,],
    1995.0: [n.dinamoMoscou,n.rotor,],
    1994.0: [n.spartakmoscou,n.cska,],
    1993.0: [n.torpedo,n.cska,],
  },
  
   leagueName.brazilCup : {
     //https://www.bolanaarea.com/copa_do_brasil_2007.htm
     //2023.0: [],
    2022.0: [n.flamengo,n.corinthians,n.saopaulo,n.fluminense,  n.atleticogo,n.americamg,n.atleticopr,n.fortaleza, n.ceara,n.santos,n.atleticomg,n.palmeiras,n.cruzeiro,n.goias,n.botafogo,n.bahia,               ],
    2021.0: [n.atleticomg, n.atleticopr,n.fortaleza,n.flamengo, n.saopaulo,n.gremio,n.santos,n.fluminense,         n.bahia,n.atleticogo,n.juazeirense,n.crb,n.vitoria,n.vasco,n.criciuma,n.abc,                   ],
    2020.0: [n.palmeiras, n.gremio,n.americamg,n.saopaulo,      n.ceara,n.internacional,n.flamengo,n.cuiaba,       n.botafogo,n.atleticogo,n.juventude,n.fortaleza,n.corinthians,n.santos,n.atleticopr,n.bragantino, ],
    2019.0: [n.atleticopr, n.internacional,n.gremio,n.cruzeiro, n.bahia,n.palmeiras,n.flamengo,n.atleticomg,       n.fluminense,n.santos,n.juventude,n.corinthians,n.fortaleza,n.saopaulo,n.paysandu,n.sampaio,   ],
    2018.0: [n.cruzeiro,n.corinthians,n.palmeiras,n.flamengo,   n.gremio,n.santos,n.bahia,n.chapecoense,           n.vitoria,n.atleticomg,n.goias,n.atleticopr,n.pontepreta,n.vasco,n.luverdense,n.americamg,     ],
    2017.0: [n.cruzeiro,n.flamengo,n.gremio,n.botafogo,         n.santos,n.atleticomg,n.palmeiras,n.atleticopr,    n.internacional,n.sport,n.fluminense,n.parana,n.atleticogo,n.chapecoense,n.santacruz,n.paysandu, ],
    2016.0: [n.gremio,n.atleticomg,n.cruzeiro,n.internacional,  n.santos,n.juventude,n.corinthians,n.palmeiras,    n.pontepreta,n.fortaleza,n.botafogoPB,n.vasco,n.botafogo,n.atleticopr,n.fluminense,n.saopaulo, ],
    2015.0: [n.palmeiras,n.santos,n.fluminense,n.saopaulo,      n.gremio,n.vasco,n.figueirense,n.internacional,    n.ceara,n.flamengo,n.paysandu,n.ituano,n.coritiba,n.atleticomg,n.cruzeiro,n.corinthians,       ],
    2014.0: [n.atleticomg,n.cruzeiro,n.flamengo,n.santos,       n.corinthians,n.abc,n.americaRN,n.botafogo,        n.ceara,n.palmeiras,n.vasco,n.santarita,n.coritiba,n.bragantino,n.atleticopr,n.gremio,         ],
    2013.0: [n.flamengo,n.atleticopr,n.goias,n.gremio,          n.botafogo,n.internacional,n.vasco,n.corinthians,  n.cruzeiro,n.nacionalAM,n.santos,n.luverdense,n.salgueiro,n.fluminense,n.palmeiras,n.atleticomg,],
    2012.0: [n.palmeiras,n.coritiba,n.gremio,n.saopaulo,        n.atleticopr,n.vitoria,n.bahia,n.goias,            n.pontepreta,n.atleticomg,n.fortaleza,n.paysandu,n.portuguesa,n.cruzeiro,n.botafogo,n.parana,   ],
    2011.0: [n.vasco,n.coritiba,n.avai,n.ceara,                 n.atleticopr,n.palmeiras,n.saopaulo,n.flamengo,    n.botafogo,n.caxias,n.santoandre,n.bahia,n.nautico,n.gremioBarueri,n.horizonte,n.goias,         ],
    2010.0: [n.santos,n.vitoria,n.gremio,n.atleticogo,          n.atleticomg,n.vasco,n.fluminense,n.palmeiras,     n.guarani,n.goias,n.avai,n.corinthians,n.santacruz,n.atleticopr,n.portuguesa,n.sport,           ],
    2009.0: [n.corinthians,n.internacional,n.vasco,n.coritiba,  n.fluminense,n.flamengo,n.vitoria,n.pontepreta,    n.goias,n.atleticomg,n.atleticopr,n.americanoRJ,n.csa,n.fortaleza,n.nautico,n.icasa,            ],
    2008.0: [n.sport,n.corinthians,n.vasco,n.botafogo,          n.saocaetano,n.internacional,n.atleticomg,n.corinthiansAL,   n.parana,n.nautico,n.goias,n.portuguesa,n.criciuma,n.juventude,n.palmeiras,n.atleticogo,         ],
    2007.0: [n.fluminense,n.figueirense,n.brasiliense,n.botafogo, n.nautico,n.atleticomg,n.ipatinga,n.atleticopr,  n.atleticogo,n.cruzeiro,n.sport,n.corinthians,n.coritiba,n.gama,n.bahia,n.avai,                  ],
    2006.0: [n.flamengo,n.vasco,n.ipatinga,n.fluminense,        n.santos,n.atleticomg,n.voltaredonda,n.cruzeiro,   n.vitoria,n.fortaleza,n.guarani,n.brasiliense,n.nautico,n.novembro15,n.criciuma,n.vilanova,      ],
    2005.0: [n.paulista,n.fluminense,n.cruzeiro,n.ceara,        n.atleticomg,n.treze,n.baraunas,n.figueirense,     n.internacional,n.vasco,n.corinthians,n.santacruz,n.coritiba,n.flamengo,n.ituano,n.gremio,       ],
    2004.0: [n.santoandre,n.flamengo,n.novembro15,n.vitoria,    n.gremio,n.corinthians,n.palmas,n.palmeiras,       n.fortaleza,n.goias,n.gama,n.internacional,n.fluminense,n.guarani,n.americanoRJ,n.santacruz,     ],
    2003.0: [n.cruzeiro,n.flamengo,n.goias,n.sport,             n.atleticomg,n.saopaulo,n.vitoria,n.vasco,         n.palmeiras,n.bahia,n.fluminense,n.botafogo,n.vilanova,n.nautico,n.figueirense,n.remo,n.criciuma,],
    2002.0: [n.corinthians,n.brasiliense,n.saopaulo,n.atleticomg, n.parana,n.bahia,n.fluminense,n.vasco,           n.csa,n.portuguesa,n.internacional,n.figueirense,n.confianca,n.botafogo,n.cruzeiro,n.juventude,  ],
    2001.0: [n.gremio,n.corinthians,n.coritiba,n.pontepreta,    n.saopaulo,n.fortaleza,n.atleticopr,n.flamengo,    n.remo,n.juventude,n.bahia,n.portuguesa,n.fluminense,n.vitoria,n.flamengoPI,n.goias,             ],
    2000.0: [n.cruzeiro,n.saopaulo,n.santos,n.atleticomg,       n.fluminense,n.botafogo,n.flamengo,n.palmeiras,    n.abc,n.bahia,n.americaRN,n.portuguesa,n.vasco,n.atleticopr,n.corinthians,n.juventude,           ],
    1999.0: [n.juventude,n.botafogo,n.internacional,n.palmeiras, n.flamengo,n.bahia,n.goias,n.atleticopr,          n.vitoria,n.vasco,n.portuguesa,n.corinthians,n.gremio,n.saopaulo,n.guarani,n.coritiba,           ],
    1998.0: [n.palmeiras,n.cruzeiro,n.santos,n.vasco,           n.saopaulo,n.vitoria,n.parana,n.sport,             n.atleticomg,n.flamengo,n.americamg,n.botafogo,n.vilanova,n.bahia,n.corinthians,n.gremio,        ],
    1997.0: [n.gremio,n.flamengo,n.corinthians,n.palmeiras,     n.santos,n.atleticopr,n.internacional,n.riobrancoAC, n.ceara,n.vitoria,n.santacruz,n.portuguesa,n.saopaulo,n.vasco,n.bahia,n.atleticomg,            ],
    1996.0: [n.cruzeiro,n.palmeiras,n.flamengo,n.gremio,        n.corinthians,n.criciuma,n.internacional,n.parana, n.atleticopr,n.saopaulo,n.fluminense,n.atleticomg,n.remo,n.botafogo,n.coritiba,n.vasco,          ],
    1995.0: [n.corinthians,n.gremio,n.vasco,n.flamengo,         n.parana,n.saopaulo,n.atleticomg,n.cruzeiro,       n.palmeiras,n.internacional,n.bahia,n.remo,n.vitoria,n.nacionalAM,n.riobrancoAC,n.kabure,        ],
    1994.0: [n.gremio,n.ceara,n.vasco,n.linhares,               n.vitoria,n.internacional,n.comercialms,n.atleticomg,  n.bahia,n.palmeiras,n.remo,n.corinthians,n.santacruz,n.saojoseAP,n.kabure,n.ariquemes,       ],
    1993.0: [n.cruzeiro,n.gremio,n.vasco,n.flamengo,            n.ceara,n.palmeiras,n.londrina,n.saopaulo,         n.nautico,n.vitoria,n.internacional,n.remo,n.riobrancoAC,n.sport,n.paysandu,n.uniaobandeirante,  ],
    1992.0: [n.internacional,n.fluminense,n.palmeiras,n.sport,  n.gremio,n.atleticopr,n.criciuma,n.csa,            n.atleticomg,n.corinthians,n.parana,n.vasco,n.remo,n.sergipe,n.fortaleza,n.bahia,                ],
    1991.0: [n.criciuma,n.gremio,n.remo,n.coritiba,             n.botafogo,n.corinthians,n.goias,n.vitoria,        n.sport,n.vasco,n.atleticomg,n.santacruz,n.caxias,n.paysandu,n.cruzeiro,n.fluminense,            ],
    1990.0: [n.flamengo,n.goias,n.nautico,n.criciuma,           n.atleticomg,n.saopaulo,n.remo,n.bahia,            n.taguatinga,n.gremio,n.botafogo,n.coritiba,n.ceara,n.santacruz,n.rionegro,n.operarioms,         ],
    1989.0: [n.gremio,n.sport,n.flamengo,n.goias,               n.atleticomg,n.vitoria,n.corinthians,n.bahia,      n.tiradentes,n.mixto,n.guarani,n.vasco,n.cruzeiro,n.internacional,n.nautico,n.blumenau,          ],

    //TAÇA BRASIL
    1967.0: [n.palmeiras,n.nautico,n.gremio,n.cruzeiro,   n.atleticomg,n.americaCE,n.botafogo,n.treze,n.goytacaz,n.paysandu,n.leonico,n.riobrancoES,n.csa,n.ferroviarioPR,n.goias,n.americaSE,n.rabello,n.abc,n.piaui,n.motoclub,n.perdigao],
    1966.0: [n.cruzeiro,n.santos,n.fluminense,n.nautico,  n.palmeiras,n.vitoria,n.gremio,n.fortaleza,n.paysandu,n.csa,n.americanoRJ,n.ferroviarioPR,n.flamengoPI,n.anapolis,n.campinense,n.interlages,n.rabello,n.desportiva,n.sampaio,n.abc,n.confianca,n.rionegro],
    1965.0: [n.santos,n.vasco,n.palmeiras,n.nautico,      ],
    1964.0: [n.santos,n.flamengo,n.palmeiras,n.ceara,     ],
    1963.0: [n.santos,n.bahia,n.gremio,n.botafogo,        ],
    1962.0: [n.santos,n.botafogo,n.sport,n.internacional, ],
    1961.0: [n.santos,n.bahia,n.americaRJ,n.nautico,      ],
    1960.0: [n.palmeiras,n.fortaleza,n.fluminense,n.santacruz],
    1959.0: [n.bahia,n.santos,n.vasco,n.gremio,           ],
  },

  leagueName.argentinaCup : {
    //2023.0: [],
    2022.0: [n.patronato,n.talleres,],
    2021.0: [],
    2020.0: [n.bocajuniors,n.talleres,],
    2019.0: [n.riverplate,n.centralCordoba,],
    2018.0: [n.rosario,n.gimnasia,],
    2017.0: [n.riverplate,n.atleticotucuman,],
    2016.0: [n.riverplate,n.rosario,],
    2015.0: [n.bocajuniors,n.rosario,],
    2014.0: [n.huracan,n.rosario,],
    2013.0: [n.arsenalsarandi,n.sanlorenzo,],
    2012.0: [n.bocajuniors,n.racing],
  },

  leagueName.mexicoCup : {
    //2023.0: [],
    2022.0: [],
    2021.0: [],
    2020.0: [n.monterrey,n.tijuana,],
    2019.0: [n.americamex,n.juarez,],
    2018.0: [n.necaxa,n.toluca,],
    2017.0: [n.chivas,n.morelia,],
    2016.0: [n.veracruz,n.necaxa,],
    2015.0: [n.puebla,n.chivas,],
    2014.0: [n.tigres,n.alebrijes,],
    2013.0: [n.cruzazul,n.atlante,],
    2012.0: [n.dorados,n.correcaminos,],
    2011.0: [],
    2010.0: [],
    2009.0: [],
    2008.0: [],
    2007.0: [],
    2006.0: [],
    2005.0: [],
    2004.0: [],
    2003.0: [],
    2002.0: [],
    2001.0: [],
    2000.0: [],
    1999.0: [],
    1998.0: [],
    1997.0: [n.cruzazul,n.torosneza,],
    1996.0: [n.tigres,n.atlas,],
    1995.0: [n.necaxa,n.veracruz,],
    1994.0: [],
    1993.0: [],
    1992.0: [n.monterrey,n.cobras,],
    1991.0: [n.leonesnegros,n.americamex,],
    1990.0: [n.puebla,n.tigres,],
    1989.0: [n.toluca,n.leonesnegros,],
    1988.0: [n.puebla,n.cruzazul,],
    1987.0: [],
    1986.0: [],
    1985.0: [],
    1984.0: [],
    1983.0: [],
    1982.0: [],
    1981.0: [],
    1980.0: [],
    1979.0: [],
    1978.0: [],
    1977.0: [],
    1976.0: [n.tigres,n.americamex,],
    1975.0: [n.pumas,n.leonesnegros,],
    1974.0: [n.americamex,n.cruzazul,],
    1973.0: [],
    1972.0: [n.leon,n.puebla,],
    1971.0: [n.leon,n.zacatepec,],
    1970.0: [n.chivas,n.torreon,],
    1969.0: [n.cruzazul,n.monterrey,],
    1968.0: [n.atlas,n.veracruz,],
    1967.0: [n.leon,n.chivas,],
    1966.0: [n.necaxa,n.leon,],
    1965.0: [n.americamex,n.morelia,],
    1964.0: [n.americamex,n.monterrey,],
    1963.0: [n.chivas,n.atlante,],
    1962.0: [n.atlas,n.tampico,],
    1961.0: [n.tampico,n.toluca,],
    1960.0: [n.necaxa,n.tampico,],
    1959.0: [n.zacatepec,n.leon,],
    1958.0: [n.leon,n.zacatepec,],
    1957.0: [n.zacatepec,n.leon,],
    1956.0: [n.toluca,n.irapuato,],
    1955.0: [n.americamex,n.chivas,],
    1954.0: [n.americamex,n.chivas,],
    1953.0: [n.puebla,n.leon,],
    1952.0: [n.atlante,n.chivas,],
    1951.0: [n.atlante,n.chivas,],
    1950.0: [n.atlas,n.veracruz,],
    1949.0: [n.leon,n.atlante,],
    1948.0: [n.veracruz,n.chivas,],
  },

};