import 'package:fifa/values/club_names.dart';
import 'package:fifa/values/league_names.dart';

ClubName n = ClubName();
LeagueOfficialNames leagueName = LeagueOfficialNames();

Map<String,dynamic> mapEuropaNordicosBalticos = {


  leagueName.dinamarca : {
    //2025.0: [],
    //2024.0: [],
    2023.0: [],
    2022.0: [n.copenhague,n.midtjylland,n.silkeborg,n.brondby,n.aalborg,n.randers,n.viborg,n.obodense,n.nordsjaelland,n.aarhus,n.vejle,n.sonderjyske],
    2021.0: [n.brondby,n.midtjylland,n.copenhague,n.aarhus,n.nordsjaelland,n.randers,n.aalborg,n.sonderjyske,n.obodense,n.vejle,n.lyngby,n.horsens],
    2020.0: [n.midtjylland,n.copenhague,n.aarhus,n.brondby,n.aalborg,n.nordsjaelland],
    2019.0: [n.copenhague,n.midtjylland,n.esbjerg,n.brondby,n.obodense,n.nordsjaelland],
    2018.0: [n.midtjylland,n.brondby,n.nordsjaelland,n.copenhague,n.aalborg,n.horsens],
    2017.0: [n.copenhague,n.brondby,n.lyngby,n.midtjylland,n.nordsjaelland,n.sonderjyske],
    2016.0: [n.copenhague,n.sonderjyske,n.midtjylland,n.brondby,n.aalborg,n.randers,n.obodense,n.viborg,n.nordsjaelland,n.aarhus,n.esbjerg,n.hobro],
    2015.0: [n.midtjylland,n.copenhague,n.brondby,n.randers,n.aalborg,n.nordsjaelland,n.hobro,n.esbjerg,n.obodense,n.sonderjyske,n.vestsjaelland,n.silkeborg],
    2014.0: [n.aalborg,n.copenhague,n.midtjylland,n.brondby,n.esbjerg,n.nordsjaelland,n.randers,n.obodense,n.vestsjaelland,n.sonderjyske,n.aarhus,n.viborg],
    2013.0: [n.copenhague,n.nordsjaelland,n.randers,n.esbjerg,n.aalborg,n.midtjylland,n.aarhus,n.sonderjyske,n.brondby,n.obodense,n.horsens,n.silkeborg],
    2012.0: [n.nordsjaelland,n.copenhague,n.midtjylland,n.horsens,n.aarhus,n.sonderjyske,n.aalborg,n.silkeborg,n.brondby,n.obodense,n.lyngby,n.havnarboltfelag],
    2011.0: [n.copenhague,n.obodense,n.brondby,n.midtjylland,n.silkeborg,n.nordsjaelland,n.sonderjyske,n.lyngby,n.horsens,n.aalborg,n.randers,n.esbjerg],
    2010.0: [n.copenhague,n.obodense,n.brondby,n.esbjerg,n.aalborg,n.midtjylland,n.nordsjaelland,n.silkeborg,n.sonderjyske,n.randers,n.aarhus,n.havnarboltfelag],
    2009.0: [n.copenhague,n.obodense,n.brondby,n.midtjylland,n.randers,n.aarhus,n.aalborg,n.nordsjaelland,n.esbjerg,n.sonderjyske,n.vejle,n.horsens],
    2008.0: [n.aalborg,n.midtjylland,n.copenhague,n.obodense,n.horsens,n.randers,n.esbjerg,n.brondby,n.nordsjaelland,n.aarhus,n.viborg,n.lyngby],
    2007.0: [n.copenhague,n.midtjylland,n.aalborg,n.obodense,n.nordsjaelland,n.brondby,n.esbjerg,n.randers,n.viborg,n.horsens,n.vejle,n.silkeborg],
    2006.0: [n.copenhague,n.brondby,n.obodense,n.viborg,n.aalborg,n.esbjerg,n.midtjylland,n.silkeborg,n.nordsjaelland,n.horsens,n.sonderjyske,n.aarhus],
    2005.0: [n.brondby,n.copenhague,n.midtjylland,n.aalborg,n.esbjerg,n.obodense,n.viborg,n.silkeborg,n.aarhus,n.nordsjaelland,n.herfolge,n.randers],
    2004.0: [n.copenhague,n.brondby,n.esbjerg,n.obodense,n.aalborg,n.midtjylland,n.viborg,n.aarhus,n.nordsjaelland,n.herfolge,n.frem,n.ab],
    2003.0: [n.copenhague,n.brondby,n.farum,n.obodense,n.esbjerg,n.aalborg,n.midtjylland,n.viborg,n.ab,n.aarhus,n.silkeborg,n.koge],
    2002.0: [n.brondby,n.copenhague,n.midtjylland,n.aalborg,n.ab,n.obodense,n.esbjerg,n.viborg,n.silkeborg,n.aarhus,n.vejle,n.lyngby],
    2001.0: [n.copenhague,n.brondby,n.silkeborg,n.midtjylland,n.aalborg,n.viborg,n.obodense,n.aarhus,n.lyngby,n.ab,n.herfolge,n.sonderjyske],
    2000.0: [n.herfolge,n.brondby,n.ab,n.viborg,n.aalborg,n.silkeborg,n.lyngby,n.copenhague,n.obodense,n.aarhus,n.vejle,n.esbjerg],
    1999.0: [n.aalborg,n.brondby,n.ab,n.lyngby,n.herfolge,n.vejle,n.copenhague,n.viborg,n.silkeborg,n.aarhus,n.aarhusfremad,n.b93],
    1998.0: [n.brondby,n.silkeborg,n.copenhague,n.vejle,n.ab,n.lyngby,n.aalborg,n.aarhus,n.herfolge,n.aarhusfremad,n.ikast,n.obodense],
    1997.0: [n.brondby,n.vejle,n.aarhus,n.herfolge,n.aalborg,n.silkeborg,n.obodense,n.copenhague,n.lyngby,n.ab,n.viborg,n.hvidovre],
    1996.0: [n.brondby,n.aarhus,n.obodense,n.lyngby,n.aalborg,n.silkeborg,n.copenhague,n.viborg,n.vejle,n.herfolge,n.ikast,n.naestved],
    1995.0: [n.aalborg,n.brondby,n.silkeborg,n.aarhus,n.naestved,    n.copenhague,n.lyngby,n.obodense,],
    1994.0: [n.silkeborg,n.copenhague,n.brondby,n.obodense,n.aalborg,  n.lyngby,n.ikast,n.aarhus,],
    1993.0: [n.copenhague,n.obodense,n.brondby,n.aalborg,n.silkeborg,  n.aarhus,n.lyngby,n.naestved,],
    1992.0: [n.lyngby,n.b1903,n.frem,n.aarhus,n.aalborg,              n.silkeborg,n.brondby,n.naestved],
    1991.0: [n.brondby,n.lyngby,n.aarhus,n.frem,n.obodense,           n.aalborg,n.b1903,n.vejle,n.silkeborg,n.ikast],
    1990.0: [n.brondby,n.b1903,n.ikast,n.silkeborg,n.frem,n.lyngby,n.aarhus,n.obodense,n.vejle,n.aalborg,n.naestved,n.herfolge,n.kb,n.viborg],
    1989.0: [n.obodense,n.brondby,n.lyngby,n.vejle,n.aarhus,n.b1903,n.silkeborg,n.frem,n.naestved,n.ikast,n.aalborg,n.herfolge,n.b1913,n.bronshoj],
    1988.0: [n.brondby,n.naestved,n.lyngby,n.b1903,n.vejle,n.obodense,n.herfolge,n.aarhus,n.silkeborg,n.ikast,n.aalborg,n.bronshoj,n.kb,n.randersfreja],
    1987.0: [n.brondby,n.ikast,n.aarhus,n.obodense,n.vejle,n.naestved,n.bronshoj,n.lyngby,n.b1903,n.aalborg,n.kb,n.herfolge,n.hvidovre,n.kastrup],
    1986.0: [n.aarhus,n.brondby,n.naestved,n.lyngby,n.b1903,n.ikast,n.vejle,n.obodense,n.bronshoj,n.kb,n.herfolge,n.kastrup,n.esbjerg,n.randersfreja],
    1985.0: [n.brondby,n.lyngby,n.aarhus,n.obodense,n.herfolge,n.naestved,n.vejle,n.esbjerg,n.kastrup,n.bronshoj,n.ikast,n.b1903,n.frem,n.hvidovre,n.koge,n.b93],
    1984.0: [n.vejle,n.aarhus,n.lyngby,n.brondby,n.bronshoj,n.koge,n.ikast,n.herfolge,n.obodense,n.naestved,n.hvidovre,n.frem,n.esbjerg,n.herningfremad,n.kb,n.b1909],
    1983.0: [n.lyngby,n.obodense,n.aarhus,n.brondby,n.frem,n.ikast,n.naestved,n.vejle,n.esbjerg,n.koge,n.hvidovre,n.bronshoj,n.herningfremad,n.b1903,n.b93,n.kolding],
    1982.0: [n.obodense,n.aarhus,n.b1903,n.brondby,n.lyngby,n.hvidovre,n.vejle,n.naestved,n.kolding,n.koge,n.esbjerg,n.b93,n.ikast,n.b1901,n.kb,n.b1909],
    1981.0: [n.hvidovre,n.lyngby,n.naestved,n.aarhus,n.esbjerg,n.obodense,n.kb,n.b1901,n.vejle,n.koge,n.b93,n.ikast,n.b1903,n.kastrup,n.herfolge,n.viborg],
    1980.0: [n.kb,n.naestved,n.obodense,n.aarhus,n.ikast,n.b93,n.b1903,n.vejle,n.koge,n.esbjerg,n.hvidovre,n.lyngby,n.kastrup,n.fremad,n.frem,n.aalborg],
    1979.0: [n.esbjerg,n.kb,n.b1903,n.kastrup,n.obodense,n.naestved,n.frem,n.vejle,n.aarhus,n.ikast,n.hvidovre,n.aalborg,n.b93,n.b1901,n.aarhusvsk,n.slagelse],
    1978.0: [n.vejle,n.esbjerg,n.aarhus,n.obodense,n.b1903,n.kb,n.b93,n.slagelse,n.aarhusvsk,n.frem,n.kastrup,n.b1901,n.naestved,n.frederikshavn,n.koge,n.randersfreja],
    1977.0: [n.obodense,n.b1903,n.esbjerg,n.vejle,n.b1901,n.kastrup,n.kb,n.koge,n.aarhus,n.randersfreja,n.frem,n.frederikshavn,n.b93,n.aalborg,n.b1909,n.holbaek],
    1976.0: [n.b1903,n.frem,n.kb,n.aalborg,n.obodense,n.vejle,n.holbaek,n.b1901,n.koge,n.kastrup,n.esbjerg,n.randersfreja,n.b93,n.naestved,n.fremad,n.vanlose],
    1975.0: [n.koge,n.holbaek,n.naestved,n.kb,n.esbjerg,n.b1903,n.aalborg,n.vanlose,n.b1901,n.vejle,n.frem,n.randersfreja,n.fremad,n.b93,n.slagelse,n.b1909],
    1974.0: [n.kb,n.vejle,n.b1903,n.holbaek,n.b1901,n.randersfreja,n.frem,n.naestved,n.koge,n.aalborg,n.slagelse,n.hvidovre],
    1973.0: [n.hvidovre,n.randersfreja,n.kb,n.vejle,n.koge,n.aalborg,n.b1901,n.naestved,n.b1903,n.frem,n.ab,n.aarhus],
    1972.0: [n.vejle,n.b1903,n.naestved,n.b1901,n.randersfreja,n.hvidovre,n.frem,n.aarhus,n.koge,n.kb,n.bronshoj,n.b1909],
    1971.0: [n.vejle,n.hvidovre,n.frem,n.kb,n.randersfreja,n.koge,n.bronshoj,n.b1903,n.b1901,n.b1909,n.aalborg,n.ab],
    1970.0: [n.b1903,n.ab,n.hvidovre,n.vejle,n.b1901,n.frem,n.bronshoj,n.aalborg,n.randersfreja,n.kb,n.b1913,n.horsens],
    1969.0: [n.b1903,n.kb,n.aalborg,n.hvidovre,n.horsens,n.ab,n.b1913,n.vejle,n.frem,n.b1901,n.b1909,n.esbjerg],
    1968.0: [n.kb,n.esbjerg,n.frem,n.b1913,n.vejle,n.b1909,n.aalborg,n.hvidovre,n.ab,n.horsens,n.obodense,n.aarhus],
    1967.0: [n.ab,n.frem,n.horsens,n.hvidovre,n.aalborg,n.esbjerg,n.kb,n.vejle,n.obodense,n.aarhus,n.b1903,n.koge],
    1966.0: [n.hvidovre,n.frem,n.kb,n.aarhus,n.vejle,n.ab,n.esbjerg,n.b1903,n.aalborg,n.koge,n.b1909,n.b1913],
    1965.0: [n.esbjerg,n.vejle,n.b1903,n.frem,n.hvidovre,n.kb,n.aalborg,n.aarhus,n.b1909,n.b1913,n.b93,n.b1901],
    1964.0: [n.b1909,n.aarhus,n.kb,n.esbjerg,n.vejle,n.b1913,n.b1901,n.b93,n.frem,n.b1903,n.ab,n.bronshoj],
    1963.0: [n.esbjerg,n.b1913,n.b1903,n.b1909,n.aarhus,n.vejle,n.kb,n.b1901,n.ab,n.bronshoj,n.aalborg,n.koge],
    1962.0: [n.esbjerg,n.b1913,n.aarhus,n.kb,n.vejle,n.bronshoj,n.ab,n.koge,n.b1903,n.b1909,n.obodense,n.frederikshavn],
    1961.0: [n.esbjerg,n.kb,n.b1913,n.b1903,n.aarhus,n.b1909,n.vejle,n.frederikshavn,n.koge,n.obodense,n.skovshoved,n.aia],
    1960.0: [n.aarhus,n.kb,n.vejle,n.obodense,n.frederikshavn,n.esbjerg,n.b1913,n.b1909,n.b1903,n.skovshoved,n.ab,n.frem],
    1959.0: [n.b1909,n.kb,n.vejle,n.obodense,n.aarhus,n.esbjerg,n.ab,n.frem,n.skovshoved,n.b1903,n.koge,n.b93],
    1958.0: [n.vejle,n.frem,n.obodense,n.b1909,n.esbjerg,n.aarhus,n.kb,n.ab,n.koge,n.skovshoved,n.aia,n.kfum],
    1957.0: [n.aarhus,n.ab,n.frem,n.skovshoved,n.kb,n.vejle,n.esbjerg,n.b1909,n.aia,n.b1903],
    1956.0: [n.aarhus,n.esbjerg,n.ab,n.b1909,n.skovshoved,n.b1903,n.frem,n.aia,n.kb,n.koge],
    1955.0: [n.aarhus,n.ab,n.frem,n.kb,n.esbjerg,n.koge,n.b1909,n.b1903,n.skovshoved,n.obodense],
    1954.0: [n.koge,n.kb,n.ab,n.frem,n.skovshoved,n.obodense,n.aarhus,n.b1903,n.esbjerg,n.b93],
    1953.0: [n.kb,n.skovshoved,n.obodense,n.ab,n.koge,n.b93,n.esbjerg,n.frem,n.b1903,n.b1909],
    1952.0: [n.ab,n.koge,n.b1909,n.obodense,n.skovshoved,n.b93,n.frem,n.b1903,n.esbjerg,n.aarhus],
    1951.0: [n.ab,n.obodense,n.aarhus,n.koge,n.b1903,n.frem,n.b93,n.esbjerg,n.b1909,n.kb],
    1950.0: [n.kb,n.ab,n.aarhus,n.koge,n.b1903,n.frem,n.obodense,n.b93,n.esbjerg,n.osterbros],
  },

  leagueName.finlandia : {
    //2024.0: [],
    2023.0: [],
    2022.0: [n.helsinki,n.kups,n.honka,n.haka,n.turku,n.sjk,n.oulu,n.vps,n.ilves,n.mariehamn,n.lahti,n.helsingfors],
    2021.0: [n.helsinki,n.kups,n.sjk,n.turku,n.ilves,n.helsingfors,n.lahti,n.haka,n.honka,n.mariehamn,n.oulu,n.ktp],
    2020.0: [n.helsinki,n.turku,n.kups,n.honka,n.ilves,n.lahti,n.sjk,n.helsingfors,n.mariehamn,n.haka,n.tps,n.rops],
    2019.0: [n.kups,n.turku,n.honka,n.ilves,n.helsinki,n.mariehamn,n.helsingfors,n.lahti,n.sjk,n.rops,n.kpv,n.vps],
    2018.0: [n.helsinki,n.rops,n.kups,n.honka,n.ilves,n.vps,n.turku,n.lahti,n.sjk,n.mariehamn,n.tps,n.kemikings],
    2017.0: [n.helsinki,n.kups,n.ilves,n.lahti,n.mariehamn,n.sjk,n.rops,n.vps,n.turku,n.kemikings,n.helsingfors,n.jjk],
    2016.0: [n.mariehamn,n.helsinki,n.sjk,n.vps,n.ilves,n.rops,n.kups,n.lahti,n.kemikings,n.helsingfors,n.turku,n.vantaa],
    2015.0: [n.sjk,n.rops,n.helsinki,n.turku,n.lahti,n.mariehamn,n.helsingfors,n.ilves,n.kups,n.vps,n.ktp,n.ffjaro],
    2014.0: [n.helsinki,n.sjk,n.lahti,n.vps,n.mariehamn,n.ffjaro,n.kups,n.mypa,n.rops,n.turku,n.honka,n.tps],
    2013.0: [n.helsinki,n.honka,n.vps,n.mariehamn,n.lahti,n.mypa,n.kups,n.tps,n.turku,n.ffjaro,n.rops,n.jjk],
    2012.0: [n.helsinki,n.turku,n.tps,n.mariehamn,n.lahti,n.mypa,n.honka,n.vps,n.jjk,n.kups,n.ffjaro,n.haka],
    2011.0: [n.helsinki,n.turku,n.jjk,n.honka,n.tps,n.kups,n.mariehamn,n.mypa,n.vps,n.haka,n.ffjaro,n.rops],
    2010.0: [n.helsinki,n.kups,n.tps,n.honka,n.ffjaro,n.turku,n.tampere,n.haka,n.mypa,n.vps,n.oulu,n.mariehamn,n.jjk,n.lahti],
    2009.0: [n.helsinki,n.honka,n.tps,n.mariehamn,n.turku,n.haka,n.tampere,n.vps,n.mypa,n.ffjaro,n.lahti,n.kups,n.jjk,n.rops],
    2008.0: [n.turku,n.honka,n.lahti,n.helsinki,n.mypa,n.tps,n.tampere,n.haka,n.ffjaro,n.rops,n.vps,n.mariehamn,n.kups,n.ktp],
    2007.0: [n.tampere,n.haka,n.tps,n.honka,n.mypa,n.mariehamn,n.helsinki,n.lahti,n.turku,n.vps,n.ffjaro,n.ktp,n.viikingit,n.oulu],
    2006.0: [n.tampere,n.helsinki,n.haka,n.honka,n.mariehamn,n.mypa,n.tps,n.lahti,n.vps,n.turku,n.ktp,n.ffjaro,n.kups],
    2005.0: [n.mypa,n.helsinki,n.tampere,n.haka,n.turku,n.lahti,n.vantaanallianssi,n.ktp,n.tps,n.kups,n.ffjaro,n.mariehamn,n.rops,n.tp47],
    2004.0: [n.haka,n.vantaanallianssi,n.tampere,n.turku,n.tps,n.helsinki,n.lahti,n.mypa,n.ktp,n.tp47,n.ffjaro,n.rops,n.jazz,n.hameenlinna],
    2003.0: [n.helsinki,n.haka,n.tampere,n.mypa,n.lahti,n.vantaanallianssi,n.turku,n.ffjaro,n.tps,n.jokerit,n.hameenlinna,n.jazz,n.ktp,n.kups],
    2002.0: [n.helsinki,n.mypa,n.haka,n.vantaanallianssi,n.tampere,n.turku,n.ffjaro,n.lahti,n.kups,n.tps,n.hameenlinna,n.jokerit,n.jazz,n.ktp,n.vps,n.tp47],
    2001.0: [n.tampere,n.helsinki,n.mypa,n.haka,n.turku,n.vps,n.atlantis,n.kups,n.lahti,n.jazz,n.jokerit,n.rops],
    2000.0: [n.haka,n.jokerit,n.mypa,n.helsinki,n.jazz,n.tampere,n.turku,n.lahti,n.rops,n.vps,n.tps,n.ktp],
    1999.0: [n.haka,n.helsinki,n.mypa,n.jokerit,n.turku,n.jazz,n.ktp,n.rops,n.tps,n.lahti,n.vps,n.tpv],
    1998.0: [n.haka,n.vps,n.pk35,n.helsinki,n.jazz,n.tps,n.mypa,n.rops,n.finnpa,n.ffjaro],
    1997.0: [n.helsinki,n.vps,n.finnpa,n.tps,n.mypa,n.rops,n.jazz,n.ffjaro,n.seinajoki,n.turku],
    1996.0: [n.jazz,n.mypa,n.tps,n.finnpa,n.ffjaro,n.turku,n.vps,n.helsinki,n.rops,n.ilves,n.haka,n.mp],
    1995.0: [n.haka,n.mypa,n.helsinki,n.jazz,n.ffjaro,n.tps,n.ilves,n.finnpa,n.rops,n.vps,n.mp,n.tpv,n.kuusysi,n.ponnistus],
    1994.0: [n.tpv,n.mypa,n.helsinki,n.jazz,n.rops,n.haka,n.ffjaro,n.tps,n.kuusysi,n.finnpa,n.mp,n.ilves,n.oulu,n.kups],
    1993.0: [n.jazz,n.mypa,n.helsinki,n.kuusysi,n.finnpa,n.tpv,n.rops,n.tps,n.mp,n.ffjaro,n.kups,n.haka,n.oulu,n.ilves],
    1992.0: [n.helsinki,n.kuusysi,n.jazz,n.mypa,n.ffjaro,n.haka,n.rops,n.ilves,n.tps,n.mp,n.oulu,n.kups],
    1991.0: [n.kuusysi,n.mp,n.haka,n.ffjaro,n.helsinki,n.ilves,n.rops,n.jazz,n.tps,n.kups,n.oulu,n.lahti],
    1990.0: [n.helsinki,n.kuusysi,n.mp,n.lahti,n.kuusysi,n.rops,n.kups,n.haka,n.ilves,n.oulu,n.kpv,n.kumu],
    1989.0: [n.kuusysi,n.tps,n.rops,n.haka,n.helsinki,n.ilves,n.kups,n.lahti,n.oulu,n.mp,n.kemikings,n.ffjaro],
    1988.0: [n.helsinki,n.kuusysi,n.rops,n.lahti,n.tps,n.haka,n.kemikings,n.mp,n.ilves,n.oulu,n.kups,n.jazz],
    1987.0: [n.helsinki,n.kuusysi,n.tps,n.ilves,n.rops,n.jazz,n.mp,n.kups,n.haka,n.lahti,n.kemikings,n.koparit],
    1986.0: [n.kuusysi,n.tps,n.helsinki,n.rops,n.haka,n.ilves,n.mp,n.jazz,n.koparit,n.kups,n.kemikings,n.oulu],
    1985.0: [n.tps,n.helsinki,n.kemikings,n.ilves,n.kuusysi,n.kups,n.rops,n.haka,n.jazz,n.oulu,n.koparit,n.kpv],
    1984.0: [n.haka,n.tps,n.kuusysi,n.ilves,n.helsinki,n.rops,n.kemikings,n.kups,n.jazz,n.koparit,n.kpv,n.mp],
    1983.0: [n.tps,n.ilves,n.haka,n.kuusysi,n.helsinki,n.rops,n.kpv,n.koparit,n.kups,n.ops,n.lahti,n.ktp],
    1982.0: [n.tps,n.koparit,n.haka,n.ilves,n.helsinki,n.kuusysi,n.kpv,n.kups,n.ops,n.sepsi78,n.ktp,n.kuopion],
    1981.0: [n.koparit,n.helsinki,n.tps,n.haka,n.ktp,n.ops,n.ilves,n.kups,n.sepsi78,n.rops,n.mp,n.mp],
    1980.0: [n.ops,n.tps,n.helsinki,n.haka,n.ktp,n.ilves,n.sepsi78,n.kups,n.oulu,n.lahti,n.koparit,n.kpv],
    1979.0: [n.ops,n.kups,n.helsinki,n.lahti,n.koparit,n.tps,n.haka,n.ktp,n.kpv,n.ilves,n.pyrkiva,n.mp],
    1978.0: [n.helsinki,n.koparit,n.haka,n.tps,n.ops,n.mp,n.kups,n.kpv,n.lahti,n.pyrkiva,n.kif,n.oulu],
    1977.0: [n.haka,n.kups,n.tps,n.ops,n.lahti,n.kpv,n.helsinki,n.kif,n.mp,n.oulu,n.mp,n.vps],
    1976.0: [n.kups,n.haka,n.helsinki,n.lahti,n.mp,n.mp,n.vps,n.kpv,n.ops,n.tps,n.gbk,n.koparit],
    1975.0: [n.tps,n.kups,n.kpv,n.mp,n.koparit,n.lahti,n.vps,n.helsinki,n.mp,n.haka,n.oulu,n.mypa],
    1974.0: [n.kups,n.lahti,n.helsinki,n.mp,n.koparit,n.tps,n.oulu,n.haka,n.kpv,n.mp,n.kuusysi,n.ilveskissat],
    1973.0: [n.helsinki,n.kpv,n.lahti,n.kups,n.oulu,n.koparit,n.mp,n.kuusysi,n.tps,n.ilveskissat,n.ponnistus,n.tapa],
    1972.0: [n.tps,n.mp,n.lahti,n.kups,n.kpv,n.kuusysi,n.koparit,n.tapa,n.helsinki,n.helsingfors,n.vps,n.haka],
    1971.0: [n.tps,n.helsingfors,n.kpv,n.helsinki,n.mp,n.kuusysi,n.kups,n.haka,n.lahti,n.vps,n.tpv,n.oulu,n.mp,n.ilveskissat],
    1970.0: [n.lahti,n.mp,n.helsingfors,n.kups,n.helsinki,n.kpv,n.tps,n.haka,n.kuusysi,n.ilveskissat,n.kemin,n.kuopion],
    1969.0: [n.kpv,n.kups,n.helsinki,n.lahti,n.mp,n.ilveskissat,n.haka,n.tps,n.kuopion,n.kuusysi,n.ktp,n.porin],
    1968.0: [n.tps,n.lahti,n.helsinki,n.kups,n.kpv,n.kuusysi,n.haka,n.mp,n.ktp,n.porin,n.ponnistus,n.vps],
    1967.0: [n.lahti,n.kups,n.tps,n.kuusysi,n.helsinki,n.haka,n.ktp,n.kpv,n.vps,n.mp,n.aboifk,n.ilveskissat],
    1966.0: [n.kups,n.helsinki,n.haka,n.mp,n.lahti,n.ktp,n.tps,n.ilveskissat,n.vps,n.helsingfors,n.gbk,n.oulu],
    1965.0: [n.haka,n.helsinki,n.lahti,n.gbk,n.helsingfors,n.kups,n.ilveskissat,n.ktp,n.vps,n.kuusysi,n.aboifk,n.tapa],
    1964.0: [n.helsinki,n.kups,n.ktp,n.haka,n.lahti,n.helsingfors,n.ilveskissat,n.aboifk,n.gbk,n.hps,n.mp,n.kif],
    1963.0: [n.lahti,n.haka,n.aboifk,n.helsingfors,n.ktp,n.kups,n.mp,n.hps,n.kif,n.tps,n.tapa,n.vasaifk],
    1962.0: [n.haka,n.lahti,n.tapa,n.mp,n.kups,n.hps,n.helsingfors,n.tps,n.kif,n.vps,n.helsinki,n.hango],
    1961.0: [n.helsingfors,n.kif,n.haka,n.tps,n.lahti,n.helsinki,n.hps,n.tapa,n.kups,n.vasaifk,n.pallopojat,n.tuto],
    1960.0: [n.haka,n.tps,n.kif,n.hps,n.helsingfors,n.kups,n.pallopojat,n.vasaifk,n.helsinki,n.ru38,n.tkt,n.drott],
    1959.0: [n.helsingfors,n.ru38,n.haka,n.kups,n.hps,n.tps,n.vasaifk,n.helsinki,n.pallopojat,n.gbk],
    1958.0: [n.kups,n.hps,n.helsingfors,n.tps,n.helsinki,n.vasaifk,n.haka,n.ilveskissat,n.vps],
    1957.0: [n.hps,n.haka,n.tps,n.kups,n.ilveskissat,n.helsinki,n.vps,n.ktp,n.kif,n.kotkanreipas],
    1956.0: [n.kups,n.helsinki,n.kif,n.ilveskissat,n.haka,n.vps,n.ktp,n.hps,n.vasaifk,n.pyrkiva],
    1955.0: [n.kif,n.haka,n.vasaifk,n.kups,n.vps,n.ktp,n.pyrkiva,n.helsinki,n.tuto,n.kotkanreipas,n.ktp],
    1954.0: [n.pyrkiva,n.kups,n.helsinki,n.vasaifk,n.tuto,n.ktp,n.kif,n.haka,n.jantevakotka,n.koparit],
    1953.0: [n.vasaifk,n.jantevakotka,n.kups,n.haka,n.pyrkiva,n.helsinki,n.kif,n.ktp,n.vps,n.kaja],
    1952.0: [n.ktp,n.vasaifk,n.pyrkiva,n.jantevakotka,n.kups,n.vps,n.haka,n.kif,n.tpk,n.tps],
    1951.0: [n.ktp,n.vasaifk,n.tpk,n.haka,n.kups,n.tps,n.kif,n.vps,n.sudet,n.ilveskissat],
    1950.0: [n.ilveskissat,n.kups,n.vasaifk,n.ktp,n.vps,n.kif,n.tps,n.haka,n.turunweikot,n.kullervo],
  },

  leagueName.islandia : {
    //2024.0: [],
    2023.0: [],
    2022.0: [n.breidablik,n.ka,n.vikingurreykjavik,n.kr,n.stjarnan,n.valur,n.keflavik,n.ibv,n.framIslandia,n.fh,n.akraness,n.leiknirreykjavik],
    2021.0: [n.vikingurreykjavik,n.breidablik,n.kr,n.ka,n.valur,n.fh,n.stjarnan,n.leiknirreykjavik,n.akraness,n.keflavik,n.hk,n.fylkir],
    2020.0: [n.valur,n.fh,n.stjarnan,n.breidablik,n.kr,n.fylkir,n.ka,n.akraness,n.hk,n.vikingurreykjavik,n.grotta,n.fjolnir],
    2019.0: [n.kr,n.breidablik,n.fh,n.stjarnan,n.ka,n.valur,n.vikingurreykjavik,n.fylkir,n.hk,n.akraness,n.grindavik,n.ibv],
    2018.0: [n.valur,n.breidablik,n.stjarnan,n.kr,n.fh,n.ibv,n.ka,n.fylkir,n.vikingurreykjavik,n.grindavik,n.fjolnir,n.keflavik],
    2017.0: [n.valur,n.stjarnan,n.fh,n.kr,n.grindavik,n.breidablik,n.ka,n.vikingurreykjavik,n.ibv,n.fjolnir,n.vikingurolafsvik,n.akraness],
    2016.0: [n.fh,n.stjarnan,n.kr,n.fjolnir,n.valur,n.breidablik,n.vikingurreykjavik,n.akraness,n.ibv,n.vikingurolafsvik,n.fylkir,n.trotturreykjavik],
    2015.0: [n.fh,n.breidablik,n.kr,n.stjarnan,n.valur,n.fjolnir,n.akraness,n.fylkir,n.vikingurreykjavik,n.ibv,n.leiknirreykjavik,n.keflavik],
    2014.0: [n.stjarnan,n.fh,n.kr,n.vikingurreykjavik,n.valur,n.fylkir,n.breidablik,n.keflavik,n.fjolnir,n.ibv,n.framIslandia,n.torakureyri],
    2013.0: [n.kr,n.fh,n.stjarnan,n.breidablik,n.valur,n.ibv,n.fylkir,n.keflavik,n.torakureyri,n.framIslandia,n.vikingurolafsvik,n.akraness],
    2012.0: [n.fh,n.breidablik,n.ibv,n.kr,n.stjarnan,n.akraness,n.fylkir,n.valur,n.keflavik,n.framIslandia,n.selfoss,n.grindavik],
    2011.0: [n.kr,n.fh,n.ibv,n.stjarnan,n.valur,n.breidablik,n.fylkir,n.keflavik,n.framIslandia,n.grindavik,n.torakureyri,n.vikingurreykjavik],
    2010.0: [n.breidablik,n.fh,n.ibv,n.kr,n.framIslandia,n.keflavik,n.valur,n.stjarnan,n.fylkir,n.grindavik,n.haukar,n.selfoss],
    2009.0: [n.fh,n.kr,n.fylkir,n.framIslandia,n.breidablik,n.keflavik,n.stjarnan,n.valur,n.grindavik,n.ibv,n.trotturreykjavik,n.fjolnir],
    2008.0: [n.fh,n.keflavik,n.framIslandia,n.kr,n.valur,n.fjolnir,n.grindavik,n.breidablik,n.fylkir,n.trotturreykjavik,n.hk,n.akraness],
    2007.0: [n.valur,n.fh,n.akraness,n.fylkir,n.breidablik,n.keflavik,n.framIslandia,n.kr,n.hk,n.vikingurreykjavik],
    2006.0: [n.fh,n.kr,n.valur,n.keflavik,n.breidablik,n.akraness,n.vikingurreykjavik,n.fylkir,n.grindavik,n.ibv],
    2005.0: [n.fh,n.valur,n.akraness,n.keflavik,n.fylkir,n.kr,n.grindavik,n.ibv,n.framIslandia,n.trotturreykjavik],
    2004.0: [n.fh,n.ibv,n.akraness,n.fylkir,n.keflavik,n.kr,n.grindavik,n.framIslandia,n.vikingurreykjavik,n.ka],
    2003.0: [n.kr,n.fh,n.akraness,n.fylkir,n.ibv,n.grindavik,n.framIslandia,n.ka,n.trotturreykjavik,n.valur],
    2002.0: [n.kr,n.fylkir,n.grindavik,n.ka,n.akraness,n.fh,n.ibv,n.framIslandia,n.keflavik,n.torakureyri],
    2001.0: [n.akraness,n.ibv,n.fh,n.grindavik,n.fylkir,n.keflavik,n.kr,n.framIslandia,n.valur,n.breidablik],
    2000.0: [n.kr,n.fylkir,n.grindavik,n.ibv,n.akraness,n.keflavik,n.breidablik,n.framIslandia,n.stjarnan,n.leiftur],
    1999.0: [n.kr,n.ibv,n.leiftur,n.akraness,n.breidablik,n.grindavik,n.framIslandia,n.keflavik,n.valur,n.vikingurreykjavik],
    1998.0: [n.ibv,n.kr,n.akraness,n.keflavik,n.leiftur,n.framIslandia,n.grindavik,n.valur,n.trotturreykjavik,n.ir],
    1997.0: [n.ibv,n.akraness,n.leiftur,n.framIslandia,n.kr,n.keflavik,n.grindavik,n.valur,n.skallagrimur,n.stjarnan],
    1996.0: [n.akraness,n.kr,n.leiftur,n.ibv,n.valur,n.stjarnan,n.grindavik,n.keflavik,n.fylkir,n.breidablik],
    1995.0: [n.akraness,n.kr,n.ibv,n.keflavik,n.leiftur,n.grindavik,n.valur,n.breidablik,n.fh,n.framlarvik],
    1994.0: [n.akraness,n.fh,n.keflavik,n.valur,n.kr,n.framIslandia,n.breidablik,n.ibv,n.torakureyri,n.stjarnan],
    1993.0: [n.akraness,n.fh,n.keflavik,n.framIslandia,n.kr,n.valur,n.torakureyri,n.ibv,n.fylkir,n.vikingurreykjavik],
    1992.0: [n.akraness,n.kr,n.torakureyri,n.valur,n.framIslandia,n.fh,n.vikingurreykjavik,n.ibv,n.breidablik,n.ka],
    1991.0: [n.vikingurreykjavik,n.framIslandia,n.kr,n.valur,n.breidablik,n.ka,n.ibv,n.fh,n.stjarnan,n.vidir],
    1990.0: [n.framIslandia,n.kr,n.ibv,n.valur,n.stjarnan,n.fh,n.vikingurreykjavik,n.ka,n.torakureyri,n.akraness],
    1989.0: [n.ka,n.fh,n.framIslandia,n.kr,n.valur,n.akraness,n.torakureyri,n.vikingurreykjavik,n.fylkir,n.keflavik],
    1988.0: [n.framIslandia,n.valur,n.akraness,n.ka,n.kr,n.torakureyri,n.vikingurreykjavik,n.keflavik,n.leiftur,n.volsungur],
    1987.0: [n.valur,n.framIslandia,n.akraness,n.torakureyri,n.kr,n.ka,n.keflavik,n.volsungur,n.vidir,n.fh],
    1986.0: [n.framIslandia,n.valur,n.akraness,n.kr,n.keflavik,n.torakureyri,n.vidir,n.fh,n.breidablik,n.ibv],
    1985.0: [n.valur,n.akraness,n.torakureyri,n.framIslandia,n.keflavik,n.kr,n.fh,n.vidir,n.trotturreykjavik,n.vikingurreykjavik],
    1984.0: [n.akraness,n.valur,n.keflavik,n.kr,n.vikingurreykjavik,n.framIslandia,n.torakureyri,n.trotturreykjavik,n.breidablik,n.ka],
    1983.0: [n.akraness,n.kr,n.breidablik,n.torakureyri,n.valur,n.trotturreykjavik,n.vikingurreykjavik,n.keflavik,n.ibv,n.ibi],
    1982.0: [n.vikingurreykjavik,n.ibv,n.kr,n.akraness,n.valur,n.ibi,n.breidablik,n.keflavik,n.framIslandia,n.ka],
    1981.0: [n.vikingurreykjavik,n.framIslandia,n.akraness,n.breidablik,n.valur,n.ibv,n.ka,n.kr,n.torakureyri,n.fh],
    1980.0: [n.valur,n.framIslandia,n.akraness,n.vikingurreykjavik,n.breidablik,n.ibv,n.kr,n.fh,n.keflavik,n.trotturreykjavik],
    1979.0: [n.ibv,n.akraness,n.valur,n.keflavik,n.kr,n.framIslandia,n.vikingurreykjavik,n.trotturreykjavik,n.ka,n.haukar],
    1978.0: [n.valur,n.akraness,n.keflavik,n.ibv,n.vikingurreykjavik,n.framIslandia,n.trotturreykjavik,n.ka,n.fh,n.breidablik],
    1977.0: [n.akraness,n.valur,n.ibv,n.keflavik,n.vikingurreykjavik,n.breidablik,n.fh,n.framIslandia,n.kr,n.torakureyri],
    1976.0: [n.valur,n.framIslandia,n.akraness,n.vikingurreykjavik,n.breidablik,n.keflavik,n.kr,n.fh,n.trotturreykjavik],
    1975.0: [n.akraness,n.framIslandia,n.valur,n.vikingurreykjavik,n.keflavik,n.fh,n.kr,n.ibv],
    1974.0: [n.akraness,n.keflavik,n.valur,n.ibv,n.kr,n.framIslandia,n.vikingurreykjavik,n.iba],
    1973.0: [n.keflavik,n.valur,n.ibv,n.framIslandia,n.akraness,n.iba,n.kr,n.breidablik],
    1972.0: [n.framIslandia,n.ibv,n.keflavik,n.akraness,n.valur,n.breidablik,n.kr,n.vikingurreykjavik],
    1971.0: [n.keflavik,n.ibv,n.framIslandia,n.akraness,n.valur,n.breidablik,n.kr,n.iba],
    1970.0: [n.akraness,n.framIslandia,n.keflavik,n.kr,n.valur,n.iba,n.ibv,n.vikingurreykjavik],
    1969.0: [n.keflavik,n.akraness,n.kr,n.ibv,n.valur,n.framIslandia,n.iba],
    1968.0: [n.kr,n.framIslandia,n.iba,n.valur,n.ibv,n.keflavik],
    1967.0: [n.valur,n.framIslandia,n.iba,n.keflavik,n.kr,n.akraness],
    1966.0: [n.valur,n.keflavik,n.iba,n.kr,n.akraness,n.trotturreykjavik],
    1965.0: [n.kr,n.akraness,n.keflavik,n.iba,n.valur,n.framIslandia],
    1964.0: [n.keflavik,n.akraness,n.kr,n.valur,n.framIslandia,n.trotturreykjavik],
    1963.0: [n.kr,n.akraness,n.valur,n.framIslandia,n.keflavik,n.iba],
    1962.0: [n.framIslandia,n.valur,n.akraness,n.kr,n.iba,n.ibi],
    1961.0: [n.kr,n.akraness,n.valur,n.iba,n.framIslandia,n.ibh],
    1960.0: [n.akraness,n.kr,n.framIslandia,n.valur,n.iba,n.keflavik],
    1959.0: [n.kr,n.akraness,n.valur,n.framIslandia,n.keflavik,n.trotturreykjavik],
    1958.0: [n.akraness,n.kr,n.valur,n.keflavik,n.framIslandia,n.ibh],
    1957.0: [n.akraness,n.framIslandia,n.valur,n.ibh,n.kr,n.iba],
    1956.0: [n.valur,n.kr,n.akraness,n.framIslandia,n.iba,n.vikingurreykjavik],
    1955.0: [n.kr,n.akraness,n.valur,n.vikingurreykjavik,n.framIslandia,n.trotturreykjavik],
    1954.0: [n.akraness,n.kr,n.framIslandia,n.valur,n.trotturreykjavik,n.vikingurreykjavik],
    1953.0: [n.akraness,n.valur,n.kr,n.vikingurreykjavik,n.framIslandia,n.trotturreykjavik],
    1952.0: [n.kr,n.akraness,n.framIslandia,n.valur,n.vikingurreykjavik],
    1951.0: [n.akraness,n.valur,n.kr,n.vikingurreykjavik,n.framIslandia],
    1950.0: [n.kr,n.framIslandia,n.akraness,n.vikingurreykjavik,n.valur],
  },

  leagueName.noruega : {
    //2025.0: [],
    //2024.0: [],
    2023.0: [n.bodoglimt,n.brann,n.tromso,n.viking,n.lillestrom,n.molde,n.sarpsborg,n.stabaek,n.rosenborg,n.oddgrenland,n.haugesund,n.stromsgodset,n.valerenga,n.sandefjord,n.hamkam,n.aalesund,],
    2022.0: [n.molde,n.bodoglimt,n.rosenborg,n.lillestrom,n.oddgrenland,n.valerenga,n.tromso,n.sarpsborg,n.aalesund,n.haugesund,n.viking,n.stromsgodset,n.hamkam,n.sandefjord,n.kristiansund,n.jerv,],
    2021.0: [n.bodoglimt,n.molde,n.viking,n.lillestrom,n.rosenborg,n.kristiansund,n.valerenga,n.sarpsborg,n.stromsgodset,n.sandefjord,n.haugesund,n.tromso,n.oddgrenland,n.brann,n.stabaek,n.mjondalen,],
    2020.0: [n.bodoglimt,n.molde,n.valerenga,n.rosenborg,n.kristiansund,n.viking,n.oddgrenland,n.stabaek,n.haugesund,n.brann,n.sandefjord,n.sarpsborg,n.stromsgodset,n.mjondalen,n.start,n.aalesund,],
    2019.0: [n.molde,n.bodoglimt,n.rosenborg,n.oddgrenland,n.viking,n.kristiansund,n.haugesund,n.stabaek,n.brann,n.valerenga,n.stromsgodset,n.sarpsborg,n.mjondalen,n.lillestrom,n.tromso,n.ranheim,],
    2018.0: [n.rosenborg,n.molde,n.brann,n.haugesund,n.kristiansund,n.valerenga,n.ranheim,n.sarpsborg,n.oddgrenland,n.tromso,n.bodoglimt,n.lillestrom,n.stromsgodset,n.stabaek,n.start,n.sandefjord,],
    2017.0: [n.rosenborg,n.molde,n.sarpsborg,n.stromsgodset,n.brann,n.oddgrenland,n.kristiansund,n.valerenga,n.stabaek,n.haugesund,n.tromso,n.lillestrom,n.sandefjord,n.sogndal,n.aalesund,n.viking,],
    2016.0: [n.rosenborg,n.brann,n.oddgrenland,n.haugesund,n.molde,n.sarpsborg,n.stromsgodset,n.viking,n.aalesund,n.valerenga,n.sogndal,n.lillestrom,n.tromso,n.stabaek,n.bodoglimt,n.start,],
    2015.0: [n.rosenborg,n.stromsgodset,n.stabaek,n.oddgrenland,n.viking,n.molde,n.valerenga,n.lillestrom,n.bodoglimt,n.aalesund,n.sarpsborg,n.haugesund,n.tromso,n.start,n.mjondalen,n.sandefjord,],
    2014.0: [n.molde,n.rosenborg,n.oddgrenland,n.stromsgodset,n.lillestrom,n.valerenga,n.aalesund,n.sarpsborg,n.stabaek,n.viking,n.haugesund,n.start,n.bodoglimt,n.brann,n.sogndal,n.sandnesulf,],
    2013.0: [n.stromsgodset,n.rosenborg,n.haugesund,n.aalesund,n.viking,n.molde,n.oddgrenland,n.brann,n.start,n.lillestrom,n.valerenga,n.sogndal,n.sandnesulf,n.sarpsborg,n.tromso,n.honefoss,],
    2012.0: [n.molde,n.stromsgodset,n.rosenborg,n.tromso,n.viking,n.brann,n.haugesund,n.valerenga,n.lillestrom,n.oddgrenland,n.aalesund,n.sogndal,n.honefoss,n.sandnesulf,n.fredrikstad,n.stabaek,],
    2011.0: [n.molde,n.tromso,n.rosenborg,n.brann,n.oddgrenland,n.haugesund,n.valerenga,n.stromsgodset,n.aalesund,n.stabaek,n.viking,n.fredrikstad,n.lillestrom,n.sogndal,n.start,n.sarpsborg,],
    2010.0: [n.rosenborg,n.valerenga,n.tromso,n.aalesund,n.oddgrenland,n.haugesund,n.stromsgodset,n.start,n.viking,n.lillestrom,n.molde,n.stabaek,n.brann,n.honefoss,n.kongsvinger,n.sandefjord,],
    2009.0: [n.rosenborg,n.molde,n.stabaek,n.oddgrenland,n.brann,n.tromso,n.valerenga,n.sandefjord,n.start,n.viking,n.lillestrom,n.stromsgodset,n.aalesund,n.fredrikstad,n.bodoglimt,n.lyn,],
    2008.0: [n.stabaek,n.fredrikstad,n.tromso,n.bodoglimt,n.rosenborg,n.viking,n.lyn,n.brann,n.molde,n.valerenga,n.stromsgodset,n.lillestrom,n.aalesund,n.hamkam,],
    2007.0: [n.brann,n.stabaek,n.viking,n.lillestrom,n.rosenborg,n.tromso,n.valerenga,n.fredrikstad,n.lyn,n.stromsgodset,n.aalesund,n.oddgrenland,n.start,n.sandefjord,],
    2006.0: [n.rosenborg,n.brann,n.valerenga,n.lillestrom,n.stabaek,n.start,n.lyn,n.fredrikstad,n.sandefjord,n.tromso,n.viking,n.oddgrenland,n.hamkam,n.molde,],
    2005.0: [n.valerenga,n.start,n.lyn,n.lillestrom,n.viking,n.brann,n.rosenborg,n.tromso,n.oddgrenland,n.hamkam,n.fredrikstad,n.molde,n.aalesund,n.bodoglimt,],
    2004.0: [n.rosenborg,n.valerenga,n.brann,n.tromso,n.hamkam,n.lyn,n.lillestrom,n.oddgrenland,n.viking,n.fredrikstad,n.molde,n.bodoglimt,n.stabaek,n.sogndal,],
    2003.0: [n.rosenborg,n.bodoglimt,n.stabaek,n.oddgrenland,n.viking,n.brann,n.lillestrom,n.sogndal,n.molde,n.lyn,n.tromso,n.valerenga,n.aalesund,n.bryne,],
    2002.0: [n.rosenborg,n.molde,n.lyn,n.viking,n.stabaek,n.oddgrenland,n.lillestrom,n.valerenga,n.bryne,n.bodoglimt,n.sogndal,n.brann,n.moss,n.start,],
    2001.0: [n.rosenborg,n.lillestrom,n.viking,n.stabaek,n.molde,n.oddgrenland,n.brann,n.sogndal,n.bodoglimt,n.moss,n.lyn,n.bryne,n.stromsgodset,n.tromso,],
    2000.0: [n.rosenborg,n.brann,n.viking,n.tromso,n.stabaek,n.lillestrom,n.molde,n.oddgrenland,n.moss,n.bodoglimt,n.bryne,n.valerenga,n.start,n.haugesund,],
    1999.0: [n.rosenborg,n.molde,n.brann,n.lillestrom,n.stabaek,n.tromso,n.oddgrenland,n.viking,n.bodoglimt,n.moss,n.valerenga,n.stromsgodset,n.skeid,n.kongsvinger,],
    1998.0: [n.rosenborg,n.molde,n.stabaek,n.viking,n.bodoglimt,n.brann,n.valerenga,n.lillestrom,n.moss,n.stromsgodset,n.tromso,n.kongsvinger,n.haugesund,n.sogndal,],
    1997.0: [n.rosenborg,n.brann,n.stromsgodset,n.molde,n.stabaek,n.kongsvinger,n.bodoglimt,n.viking,n.haugesund,n.lillestrom,n.sogndal,n.tromso,n.lyn,n.skeid,],
    1996.0: [n.rosenborg,n.lillestrom,n.viking,n.brann,n.tromso,n.stabaek,n.kongsvinger,n.molde,n.skeid,n.bodoglimt,n.stromsgodset,n.moss,n.valerenga,n.start,],
    1995.0: [n.rosenborg,n.molde,n.bodoglimt,n.lillestrom,n.viking,n.tromso,n.valerenga,n.start,n.stabaek,n.brann,n.kongsvinger,n.hodd,n.hamkam,n.strindheim,],
    1994.0: [n.rosenborg,n.lillestrom,n.viking,n.start,n.kongsvinger,n.brann,n.tromso,n.hamkam,n.valerenga,n.bodoglimt,n.sogndal,n.stromsgodset,],
    1993.0: [n.rosenborg,n.bodoglimt,n.lillestrom,n.viking,n.hamkam,n.tromso,n.brann,n.kongsvinger,n.start,n.molde,n.lyn,n.fyllingen,],
    1992.0: [n.rosenborg,n.kongsvinger,n.start,n.lillestrom,n.lyn,n.molde,n.brann,n.tromso,n.viking,n.hamkam,n.sogndal,n.mjondalen,],
    1991.0: [n.viking,n.rosenborg,n.start,n.lyn,n.lillestrom,n.tromso,n.molde,n.kongsvinger,n.sogndal,n.brann,n.fyllingen,n.stromsgodset,],
    1990.0: [n.rosenborg,n.tromso,n.molde,n.brann,n.viking,n.start,n.fyllingen,n.kongsvinger,n.stromsgodset,n.lillestrom,n.valerenga,n.moss,],
    1989.0: [n.lillestrom,n.rosenborg,n.tromso,n.molde,n.kongsvinger,n.viking,n.brann,n.moss,n.start,n.valerenga,n.sogndal,n.mjolner,],
    1988.0: [n.rosenborg,n.lillestrom,n.molde,n.moss,n.tromso,n.sogndal,n.valerenga,n.kongsvinger,n.brann,n.bryne,n.strommen,n.djerv1919,],
    1987.0: [n.moss,n.molde,n.kongsvinger,n.rosenborg,n.bryne,n.tromso,n.valerenga,n.brann,n.lillestrom,n.hamkam,n.mjondalen,n.start,],
    1986.0: [n.lillestrom,n.mjondalen,n.kongsvinger,n.start,n.hamkam,n.bryne,n.valerenga,n.rosenborg,n.molde,n.tromso,n.viking,n.strommen,],
    1985.0: [n.rosenborg,n.lillestrom,n.valerenga,n.kongsvinger,n.mjondalen,n.start,n.viking,n.molde,n.bryne,n.moss,n.brann,n.eik,],
    1984.0: [n.valerenga,n.viking,n.start,n.bryne,n.lillestrom,n.rosenborg,n.kongsvinger,n.molde,n.eik,n.moss,n.fredrikstad,n.strindheim,],
    1983.0: [n.valerenga,n.lillestrom,n.start,n.moss,n.eik,n.viking,n.rosenborg,n.bryne,n.kongsvinger,n.brann,n.mjondalen,n.hamarkameratene,],
    1982.0: [n.viking,n.bryne,n.lillestrom,n.valerenga,n.hamarkameratene,n.rosenborg,n.mjondalen,n.moss,n.start,n.fredrikstad,n.sogndal,n.molde,],
    1981.0: [n.valerenga,n.viking,n.rosenborg,n.fredrikstad,n.moss,n.hamarkameratene,n.lillestrom,n.start,n.bryne,n.brann,n.haugar,n.lyn,],
    1980.0: [n.start,n.bryne,n.lillestrom,n.viking,n.rosenborg,n.moss,n.fredrikstad,n.valerenga,n.lyn,n.molde,n.skeid,n.bodoglimt,],
    1979.0: [n.viking,n.moss,n.start,n.bryne,n.lillestrom,n.rosenborg,n.bodoglimt,n.valerenga,n.skeid,n.hamarkameratene,n.mjondalen,n.brann,],
    1978.0: [n.start,n.lillestrom,n.viking,n.skeid,n.brann,n.valerenga,n.bryne,n.moss,n.bodoglimt,n.molde,n.lyn,n.steinkjer,],
    1977.0: [n.lillestrom,n.bodoglimt,n.molde,n.start,n.viking,n.brann,n.valerenga,n.bryne,n.moss,n.hamarkameratene,n.mjondalen,n.rosenborg,],
    1976.0: [n.lillestrom,n.mjondalen,n.brann,n.start,n.viking,n.molde,n.hamarkameratene,n.rosenborg,n.bryne,n.stromsgodset,n.fredrikstad,n.vard,],
    1975.0: [n.viking,n.brann,n.start,n.rosenborg,n.stromsgodset,n.mjondalen,n.lillestrom,n.molde,n.fredrikstad,n.skeid,n.valerenga,n.osturnforening,],
    1974.0: [n.viking,n.molde,n.valerenga,n.brann,n.stromsgodset,n.skeid,n.start,n.rosenborg,n.mjondalen,n.hamkam,n.sarpsborg,n.raufoss,],
    1973.0: [n.viking,n.rosenborg,n.start,n.hamkam,n.brann,n.stromsgodset,n.skeid,n.raufoss,n.mjondalen,n.frigg,n.lyn,n.fredrikstad,],
    1972.0: [n.viking,n.fredrikstad,n.stromsgodset,n.rosenborg,n.lyn,n.skeid,n.mjondalen,n.brann,n.hamkam,n.sarpsborg,n.hodd,n.mjolner,],
    1971.0: [n.rosenborg,n.lyn,n.viking,n.fredrikstad,n.stromsgodset,n.hamkam,n.sarpsborg,n.hodd,n.brann,n.frigg,],
    1970.0: [n.stromsgodset,n.rosenborg,n.hamkam,n.brann,n.sarpsborg,n.viking,n.fredrikstad,n.hodd,n.skeid,n.pors,],
    1969.0: [n.rosenborg,n.fredrikstad,n.stromsgodset,n.skeid,n.viking,n.brann,n.sarpsborg,n.hodd,n.start,n.lyn,],
    1968.0: [n.lyn,n.rosenborg,n.viking,n.stromsgodset,n.brann,n.skeid,n.sarpsborg,n.fredrikstad,n.frigg,n.valerenga,],
    1967.0: [n.rosenborg,n.skeid,n.lyn,n.frigg,n.valerenga,n.fredrikstad,n.sarpsborg,n.stromsgodset,n.steinkjer,n.oddgrenland,],
    1966.0: [n.skeid,n.fredrikstad,n.lyn,n.frigg,n.valerenga,n.steinkjer,n.oddgrenland,n.sarpsborg,n.lisleby,n.hodd,],
    1965.0: [n.valerenga,n.lyn,n.sarpsborg,n.steinkjer,n.fredrikstad,n.skeid,n.oddgrenland,n.frigg,n.viking,n.sandefjord,],
    1964.0: [n.lyn,n.fredrikstad,n.sarpsborg,n.frigg,n.skeid,n.valerenga,n.sandefjord,n.viking,n.brann,n.raufoss,],
    1963.0: [n.brann,n.lyn,n.skeid,n.fredrikstad,n.frigg,n.sarpsborg,n.viking,n.valerenga,n.steinkjer,n.gjoviklyn,],
    1962.0: [n.brann,n.steinkjer,n.fredrikstad,n.frigg,n.lyn,n.valerenga,n.viking,n.skeid,n.rosenborg,n.oddgrenland,n.eik,n.sandefjord,n.lisleby,n.ornhorten,n.greaker,n.larvikturn,],
    1961.0: [n.fredrikstad,n.eik,n.lyn,n.rosenborg,n.greaker,n.valerenga,n.viking,n.larvikturn,n.sandefjord,n.oddgrenland,n.lisleby,n.skeid,n.strommen,n.stavanger,n.lillestrom,n.rapid,],
    1960.0: [n.fredrikstad,n.lillestrom,n.valerenga,n.eik,n.skeid,n.viking,n.larvikturn,n.rapid,n.greaker,n.sandefjord,n.oddgrenland,n.strommen,n.brann,n.raufoss,n.brage,n.start,],
    1959.0: [n.lillestrom,n.fredrikstad,n.eik,n.viking,n.larvikturn,n.strommen,n.skeid,n.raufoss,n.oddgrenland,n.sandefjord,n.brann,n.greaker,n.freidig,n.asker,n.arstad,n.kapp,],
    1958.0: [n.viking,n.skeid,n.larvikturn,n.fredrikstad,n.strommen,n.brann,n.asker,n.sandefjord,n.raufoss,n.oddgrenland,n.lillestrom,n.eik,n.molde,n.frigg,n.steinkjer,n.sparta,],
    1957.0: [n.fredrikstad,n.oddgrenland,n.strommen,n.larvikturn,n.sandefjord,n.lillestrom,n.skeid,n.viking,n.asker,n.steinkjer,n.frigg,n.valerenga,n.sparta,n.arstad,n.sarpsborg,n.rapid,],
    1956.0: [n.larvikturn,n.fredrikstad,n.asker,n.skeid,n.sandefjord,n.viking,n.valerenga,n.lillestrom,n.rapid,n.oddgrenland,n.frigg,n.brann,n.varegg,n.sarpsborg,n.kvik,n.ranheim,],
    1955.0: [n.larvikturn,n.fredrikstad,n.skeid,n.sandefjord,n.asker,n.viking,n.oddgrenland,n.valerenga,n.brann,n.lillestrom,n.sarpsborg,n.framlarvik,n.ranheim,n.sparta,n.strommen,n.freidig,],
    1954.0: [n.fredrikstad,n.skeid,n.sparta,n.strommen,n.lillestrom,n.asker,n.larvikturn,n.oddgrenland,n.viking,n.sarpsborg,n.sandefjord,n.freidig,n.varegg,n.geithus,n.moss,n.nordnes,],
    1953.0: [n.larvikturn,n.skeid,n.asker,n.fredrikstad,n.sarpsborg,n.viking,n.lillestrom,n.strommen,n.sandefjord,n.oddgrenland,n.sparta,n.varegg,n.lyn,n.brann,n.ranheim,n.arstad,],
    1952.0: [n.fredrikstad,n.brann,n.sarpsborg,n.skeid,n.oddgrenland,n.viking,n.asker,n.arstad,n.sparta,n.lyn,n.valerenga,n.sandefjord,n.strommen,n.kvik,n.ornhorten,n.snogg,],
    1951.0: [n.fredrikstad,n.oddgrenland,n.valerenga,n.lyn,n.sparta,n.skeid,n.sandefjord,n.viking,n.brann,n.strommen,n.sarpsborg,n.ornhorten,n.selbak,n.lisleby,n.framlarvik,n.kristiansund,],
    1950.0: [n.framlarvik,n.fredrikstad,n.sparta,n.sarpsborg,n.ornhorten,n.viking,n.valerenga,n.skeid,n.lyn,n.selbak,n.strommen,n.sandefjord,n.algard,n.ranheim,n.storm,n.mjondalen,],
    1949.0: [n.fredrikstad,n.valerenga,n.sparta,n.viking,n.sarpsborg,n.algard,n.lyn,n.sandefjord,n.skeid,n.ornhorten,n.mjondalen,n.storm,n.freidig,n.sandaker,n.pors,n.brann],
  },

  leagueName.suecia : {
    //2025.0: [],
    //2024.0: [],
    2023.0: [],
    2022.0: [n.hacken,n.djurgardens,n.hammarby,n.kalmar,n.aik,     n.elfsborg,n.malmo,n.ifkgoteborg,n.mjallby,n.varnamo,        n.sirius,n.norrkoping,n.degerfors,n.varbergs,n.helsingborg,n.sundsvall],
    2021.0: [n.malmo,n.aik,n.djurgardens,n.elfsborg,n.hammarby,    n.kalmar,n.norrkoping,n.ifkgoteborg,n.mjallby,n.varbergs,     n.sirius,n.hacken,n.degerfors,n.halmstads,n.orebro,n.ostersunds],
    2020.0: [n.malmo,n.elfsborg,n.hacken,n.djurgardens,n.mjallby,  n.norrkoping,n.orebro,n.hammarby,n.aik,n.sirius,             n.varbergs,n.ifkgoteborg,n.ostersunds,n.kalmar,n.helsingborg,n.falkenbergs],
    2019.0: [n.djurgardens,n.malmo,n.hammarby,n.aik,n.norrkoping,  n.hacken,n.ifkgoteborg,n.elfsborg,n.orebro,n.helsingborg,    n.sirius,n.ostersunds,n.falkenbergs,n.kalmar,n.sundsvall,n.elkilstuna],
    2018.0: [n.aik,n.norrkoping,n.malmo,n.hammarby,n.hacken,      n.ostersunds,n.djurgardens,n.sundsvall,n.orebro,n.kalmar,     n.ifkgoteborg,n.elfsborg,n.sirius,],
    2017.0: [n.malmo,n.aik,n.djurgardens,n.hacken,n.ostersunds,    n.norrkoping,n.sirius,n.elfsborg,n.hammarby,n.ifkgoteborg,   n.orebro,n.kalmar,n.sundsvall,n.jonkopings,n.halmstads,n.elkilstuna],
    2016.0: [n.malmo,n.aik,n.norrkoping,n.ifkgoteborg,n.elfsborg, n.kalmar,n.djurgardens,n.ostersunds,n.orebro,n.hacken,        n.hammarby],
    2015.0: [n.norrkoping,n.ifkgoteborg,n.aik,n.elfsborg,n.malmo, n.djurgardens,n.hacken,n.helsingborg,n.orebro,n.gefle,        n.hammarby],
    2014.0: [n.malmo,n.ifkgoteborg,n.aik,n.elfsborg,n.hacken,     n.orebro,n.djurgardens,n.atvidabergs,n.helsingborg,n.halmstads, n.kalmar,n.norrkoping,],
    2013.0: [n.malmo,n.aik,n.ifkgoteborg,n.kalmar,n.helsingborg,  n.elfsborg,n.djurgardens,n.atvidabergs,n.norrkoping,n.hacken, n.mjallby,n.gefle,],
    2012.0: [n.elfsborg,n.hacken,n.malmo,n.aik,n.norrkoping,      n.helsingborg,n.ifkgoteborg,],
    2011.0: [n.helsingborg,n.aik,n.elfsborg,n.malmo,n.gais,       n.hacken,n.ifkgoteborg],
    2010.0: [n.malmo,n.helsingborg,n.orebro,n.elfsborg,n.trelleborgs, n.mjallby,n.ifkgoteborg],
    2009.0: [n.aik,n.ifkgoteborg,n.elfsborg,n.kalmar,n.hacken,        n.orebro,n.malmo],
    2008.0: [n.kalmar,n.elfsborg,n.ifkgoteborg,n.helsingborg,n.aik,   n.malmo,n.orebro],
    2007.0: [n.ifkgoteborg,n.kalmar,n.djurgardens,n.elfsborg,n.aik,    n.hammarby,n.halmstads,n.helsingborg,n.malmo,],
    2006.0: [n.elfsborg,n.aik,n.hammarby,n.helsingborg,n.kalmar,      n.djurgardens,n.malmo,n.ifkgoteborg,n.gefle,n.gais,       ],
    2005.0: [n.djurgardens,n.ifkgoteborg,n.kalmar,n.hammarby,n.malmo,  n.helsingborg,n.elfsborg,n.hacken,n.orgryte,n.halmstads,  ],
    2004.0: [n.malmo,n.halmstads,n.ifkgoteborg,n.djurgardens,n.kalmar, n.hammarby,n.sundsvall,],
    2003.0: [n.djurgardens,n.hammarby,n.malmo,n.orgryte,n.aik,         n.helsingborg,n.ifkgoteborg,],
    2002.0: [n.djurgardens,n.malmo,n.orgryte,n.helsingborg,n.aik,      n.halmstads,n.orebro,n.sundsvall,n.hammarby,n.elfsborg,       n.landskrona,n.ifkgoteborg,n.norrkoping,n.kalmar],
    2001.0: [n.hammarby,n.djurgardens,n.aik,n.ifkgoteborg,n.helsingborg, n.orgryte,n.halmstads,n.orebro,n.malmo,n.elfsborg,          n.sundsvall,n.norrkoping,n.hacken,n.trelleborgs],
    2000.0: [n.halmstads,n.helsingborg,n.aik,n.ifkgoteborg,n.elfsborg,  n.trelleborgs,n.orgryte,n.hammarby,n.norrkoping,n.orebro,   n.sundsvall,n.hacken,n.gais,n.vastra],
    1999.0: [n.helsingborg,n.aik,n.halmstads,n.orgryte,n.norrkoping,    n.ifkgoteborg,n.vastra,n.trelleborgs,n.elfsborg,n.hammarby, n.kalmar,n.orebro,n.malmo,n.djurgardens],
    1998.0: [n.aik,n.helsingborg,n.hammarby,n.halmstads,n.vastra,       n.orebro,n.norrkoping,n.ifkgoteborg,n.malmo,n.elfsborg      ],
    1997.0: [n.halmstads,n.ifkgoteborg,n.malmo,n.orebro,n.orgryte,      n.helsingborg,n.elfsborg,n.aik,n.norrkoping,n.trelleborgs,  ],
    1996.0: [n.ifkgoteborg,n.malmo,n.helsingborg,n.aik,n.orebro,        n.osters,n.halmstads,n.norrkoping,n.degerfors,n.orgryte,     ],
    1995.0: [n.ifkgoteborg,n.helsingborg,n.halmstads,n.malmo,n.orebro,  n.djurgardens,n.orgryte,n.aik,n.degerfors,n.trelleborgs,      ],
    1994.0: [n.ifkgoteborg,n.orebro,n.malmo,n.norrkoping,n.osters,      n.aik,n.halmstads,n.degerfors,n.helsingborg,n.trelleborgs,   ],
    1993.0: [n.ifkgoteborg,n.norrkoping,n.aik,n.trelleborgs,n.halmstads, n.hacken,n.vastra,n.osters,n.helsingborg,n.malmo,           ],
    1992.0: [n.aik,n.norrkoping,n.osters,n.trelleborgs,n.ifkgoteborg,   n.malmo,n.djurgardens,n.orebro,n.vastra,n.gais],
    1991.0: [n.ifkgoteborg,n.norrkoping,n.orebro,n.malmo,n.djurgardens,  n.aik,n.halmstads,n.gais,n.osters,n.sundsvall],
    1990.0: [n.ifkgoteborg,n.norrkoping,n.orebro,n.osters,n.djurgardens,  n.malmo,n.gais,n.aik,n.halmstads,n.brage,              n.orgryte,n.hammarby],
    1989.0: [n.norrkoping,n.malmo,n.gais,n.orebro,n.halmstads,          n.djurgardens,n.ifkgoteborg,n.aik,n.orgryte,n.brage,     n.sundsvall,n.vastra],
    1988.0: [n.malmo,n.djurgardens,n.ifkgoteborg,n.orgryte,n.sundsvall,  n.norrkoping,n.brage,n.gais,n.vastra,n.aik,             n.osters,n.hammarby],
    1987.0: [n.ifkgoteborg,n.malmo,n.norrkoping,n.osters,n.brage,       n.hammarby,n.vastra,n.orgryte,n.aik,n.sundsvall,        n.halmstads,n.elfsborg],
    1986.0: [n.malmo,n.aik,n.ifkgoteborg,n.norrkoping,n.halmstads,      n.hammarby,n.osters,n.brage,n.orgryte,n.elfsborg,       n.kalmar,n.djurgardens],
    1985.0: [n.orgryte,n.ifkgoteborg,n.malmo,n.kalmar,n.aik,            n.hammarby,n.halmstads,n.osters,n.brage,n.norrkoping,   n.mjallby,n.trelleborgs],
    1984.0: [n.ifkgoteborg,n.norrkoping,n.aik,n.malmo,n.hammarby,       n.brage,n.kalmar,n.halmstads,n.orgryte,n.osters,        n.elfsborg,n.gefle],
    1983.0: [n.ifkgoteborg,n.osters,n.aik,n.malmo,n.hammarby,           n.halmstads,n.elfsborg,n.orgryte,n.brage,n.gefle,       n.mjallby,n.hacken],
    1982.0: [n.ifkgoteborg,n.hammarby,n.elfsborg,n.malmo,n.osters,      n.brage,n.orgryte,n.halmstads,n.kalmar,n.norrkoping,    n.aik,n.atvidabergs],
    1981.0: [n.osters,n.ifkgoteborg,n.norrkoping,n.brage,n.malmo,       n.orgryte,n.hammarby,n.aik,n.halmstads,n.atvidabergs,   n.elfsborg,n.kalmar,n.sundsvall,n.djurgardens],
    1980.0: [n.osters,n.malmo,n.ifkgoteborg,n.brage,n.hammarby,         n.elfsborg,n.sundsvall,n.halmstads,n.kalmar,n.norrkoping,  n.atvidabergs,n.djurgardens,n.landskrona,n.mjallby],
    1979.0: [n.halmstads,n.ifkgoteborg,n.elfsborg,n.malmo,n.norrkoping, n.hammarby,n.osters,n.kalmar,n.sundsvall,n.djurgardens,     n.atvidabergs,n.landskrona,n.aik],
    1978.0: [n.osters,n.malmo,n.ifkgoteborg,n.kalmar,n.djurgardens,      n.elfsborg,n.aik,n.halmstads,n.hammarby,n.landskrona,      n.norrkoping,n.atvidabergs,n.orebro,n.vasteras],
    1977.0: [n.malmo,n.elfsborg,n.kalmar,n.norrkoping,n.landskrona,     n.ifkgoteborg,n.hammarby,n.halmstads,n.osters,n.djurgardens, n.aik,n.orebro,n.sundsvall,n.bkderby],
    1976.0: [n.halmstads,n.malmo,n.osters,n.landskrona,n.orebro,        n.kalmar,n.aik,n.hammarby,n.norrkoping,n.elfsborg,         n.djurgardens,n.sundsvall,n.atvidabergs,n.orgryte],
    1975.0: [n.malmo,n.osters,n.djurgardens,n.landskrona,n.aik,          n.atvidabergs,n.orebro,n.norrkoping,n.elfsborg,n.hammarby, n.gais,n.sundsvall],
    1974.0: [n.malmo,n.aik,n.osters,n.gais,n.atvidabergs,               n.elfsborg,n.landskrona,n.djurgardens,n.hammarby,n.orebro,  n.halmstads,n.norrkoping,n.sirius,n.brynas],
    1973.0: [n.atvidabergs,n.osters,n.djurgardens,n.malmo,n.aik,         n.norrkoping,n.landskrona,n.hammarby,n.elfsborg,n.gais,    n.orebro,n.sirius,n.orgryte],
    1972.0: [n.atvidabergs,n.aik,n.osters,n.norrkoping,n.orebro,        n.malmo,n.djurgardens,n.landskrona,n.orgryte,n.hammarby,    n.gais,n.halmstads],
    1971.0: [n.malmo,n.atvidabergs,n.norrkoping,n.djurgardens,n.orgryte, n.landskrona,n.aik,n.orebro,n.osters,n.hammarby,           n.elfsborg,n.lulea],
    1970.0: [n.malmo,n.atvidabergs,n.djurgardens,n.elfsborg,n.hammarby,  n.norrkoping,n.osters,n.orebro,n.aik,n.orgryte,            n.ifkgoteborg,n.gais],
    1969.0: [n.ifkgoteborg,n.malmo,n.djurgardens,n.atvidabergs,n.orebro, n.osters,n.norrkoping,n.gais,n.aik,n.elfsborg,             ],
    1968.0: [n.osters,n.malmo,n.norrkoping,n.djurgardens,n.orebro,       n.elfsborg,n.atvidabergs,n.gais,n.ifkgoteborg,n.aik,       n.helsingborg,n.orgryte],
    1967.0: [n.malmo,n.djurgardens,n.helsingborg,n.orebro,n.aik,         n.norrkoping,n.elfsborg,n.gais,n.ifkgoteborg,n.orgryte,    n.hammarby,n.holmsund],
    1966.0: [n.djurgardens,n.norrkoping,n.elfsborg,n.ifkgoteborg,n.aik,  n.orgryte,n.orebro,n.gais,n.malmo,n.helsingborg,           n.brage,n.degerfors],
    1965.0: [n.malmo,n.elfsborg,n.aik,n.norrkoping,n.ifkgoteborg,       n.orebro,n.orgryte,n.djurgardens,n.degerfors,n.helsingborg, n.hammarby,n.sundsvall],
    1964.0: [n.djurgardens,n.malmo,n.orgryte,n.norrkoping,n.elfsborg,    n.degerfors,n.aik,n.orebro,n.ifkgoteborg,n.helsingborg,    ],
    1963.0: [n.norrkoping,n.degerfors,n.aik,n.malmo,n.ifkgoteborg,      n.djurgardens,n.orgryte,n.orebro,n.helsingborg,n.elfsborg,  n.hammarby,n.halmia],
    1962.0: [n.norrkoping,n.djurgardens,n.ifkgoteborg,n.orgryte,n.helsingborg, n.orebro,n.elfsborg,n.malmo,n.hammarby,n.degerfors,  n.ifkmalmo,n.hogadal],
    1961.0: [n.elfsborg,n.norrkoping,n.ifkgoteborg,n.orebro,n.malmo,    n.ifkmalmo,n.orgryte,n.helsingborg,n.degerfors,n.hammarby, n.aik,n.sandvikens,],
    1960.0: [n.norrkoping,n.ifkmalmo,n.orgryte,n.malmo,n.degerfors,     n.aik,n.hammarby,n.ifkgoteborg,n.sandvikens,n.helsingborg, n.djurgardens,n.jonkopings],
    1959.0: [n.djurgardens,n.norrkoping,n.ifkgoteborg,n.orgryte,n.malmo, n.hammarby,n.sandvikens,n.helsingborg,n.ifkmalmo,n.aik,    n.halmstads,n.gais],
    1958.0: [n.ifkgoteborg,n.norrkoping,n.djurgardens,n.malmo,n.helsingborg, n.gais,n.ifkmalmo,n.halmstads,n.aik,n.sandvikens,      ],
    1957.0: [n.norrkoping,n.malmo,n.helsingborg,n.gais,n.djurgardens,    n.aik,n.sandvikens,n.halmstads,n.ifkgoteborg,n.ifkmalmo,   n.vasteras,n.hammarby],
    1956.0: [n.norrkoping,n.malmo,n.djurgardens,n.sandvikens,n.aik,      n.ifkgoteborg,n.halmstads,n.helsingborg,n.hammarby,n.vasteras,  n.norrby,n.degerfors],
    1955.0: [n.djurgardens,n.halmstads,n.aik,n.norrkoping,n.helsingborg, n.hammarby,n.degerfors,n.malmo,n.ifkgoteborg,n.gais,       n.kalmar,n.sandvikens],
    1954.0: [n.gais,n.helsingborg,n.degerfors,n.aik,n.norrkoping,       n.djurgardens,n.malmo,n.ifkgoteborg,n.kalmar,n.sandvikens,  n.jonkopings,n.elfsborg],
    1953.0: [n.malmo,n.norrkoping,n.djurgardens,n.helsingborg,n.aik,     n.gais,n.jonkopings,n.degerfors,n.ifkgoteborg,n.elfsborg,  n.orebro,n.ifkmalmo],
    1952.0: [n.norrkoping,n.malmo,n.helsingborg,n.ifkgoteborg,n.gais,   n.degerfors,n.djurgardens,n.orebro,n.jonkopings,n.elfsborg, n.raa,n.atvidabergs],
    1951.0: [n.malmo,n.raa,n.degerfors,n.helsingborg,n.norrkoping,      n.djurgardens,n.gais,n.orebro,n.jonkopings,n.elfsborg,      n.aik,n.kalmar],
    1950.0: [n.malmo,n.jonkopings,n.helsingborg,n.aik,n.gais,           n.norrkoping,n.elfsborg,n.djurgardens,n.kalmar,n.degerfors, n.ifkgoteborg,n.halmia],
    1949.0: [n.malmo,n.helsingborg,n.gais,n.degerfors,n.aik,            n.ifkgoteborg,n.norrkoping,n.jonkopings,n.halmia,n.elfsborg, n.orebro,n.landskrona],
    1948.0: [n.norrkoping,n.malmo,n.aik,n.helsingborg,n.ifkgoteborg,    ],
    1947.0: [n.norrkoping,n.aik,n.malmo,n.elfsborg,n.ifkgoteborg,       ],
    1946.0: [n.norrkoping,n.malmo,n.ifkgoteborg,n.gais,n.degerfors,     n.aik,n.elfsborg,n.helsingborg,n.halmia,n.djurgardens,  n.jonkopings,n.halmstads],
    1945.0: [n.norrkoping,n.elfsborg,n.malmo,n.ifkgoteborg,n.degerfors, n.gais,n.aik,n.halmstads,n.halmia,n.helsingborg,        ],
  },

  leagueName.ilhasfaroe : {
    //2025.0: [],
    //2024.0: [],
    2023.0: [],
    2022.0: [n.kiklaksvik,n.vikingurgota,n.havnarboltfelag,n.b36,n.ebstreymur,n.b68,n.vestur,n.abFaroe,n.nsirunavik,n.skala],
    2021.0: [n.kiklaksvik,n.havnarboltfelag,n.vikingurgota,n.nsirunavik,n.b36,n.vestur,n.ebstreymur,n.b68,n.iffuglafjordur,n.tbtvoroyri],
    2020.0: [n.havnarboltfelag,n.nsirunavik,n.kiklaksvik,n.b36,n.vikingurgota,n.iffuglafjordur,n.ebstreymur,n.tbtvoroyri,n.abFaroe,n.skala],
    2019.0: [n.kiklaksvik,n.b36,n.nsirunavik,n.havnarboltfelag,n.vikingurgota,n.skala,n.abFaroe,n.tbtvoroyri,n.ebstreymur,n.iffuglafjordur],
    2018.0: [n.havnarboltfelag,n.nsirunavik,n.b36,n.kiklaksvik,n.vikingurgota,n.skala,n.tbtvoroyri,n.ebstreymur,n.abFaroe,n.vestur],
    2017.0: [n.vikingurgota,n.kiklaksvik,n.b36,n.nsirunavik,n.havnarboltfelag,n.skala,n.ebstreymur,n.tbtvoroyri,n.vestur,n.iffuglafjordur],
    2016.0: [n.vikingurgota,n.kiklaksvik,n.nsirunavik,n.b36,n.havnarboltfelag,n.iffuglafjordur,n.tbtvoroyri,n.skala,n.abFaroe,n.b68],
    2015.0: [n.b36,n.nsirunavik,n.vikingurgota,n.havnarboltfelag,n.kiklaksvik,n.iffuglafjordur,n.tbtvoroyri,n.abFaroe,n.suduroy,n.ebstreymur],
    2014.0: [n.b36,n.havnarboltfelag,n.vikingurgota,n.nsirunavik,n.ebstreymur,n.kiklaksvik,n.iffuglafjordur,n.abFaroe,n.skala,n.b68],
    2013.0: [n.havnarboltfelag,n.iffuglafjordur,n.b36,n.nsirunavik,n.ebstreymur,n.vikingurgota,n.abFaroe,n.kiklaksvik,n.tbtvoroyri,n.vestur],
    2012.0: [n.ebstreymur,n.iffuglafjordur,n.havnarboltfelag,n.kiklaksvik,n.vikingurgota,n.b36,n.nsirunavik,n.tbtvoroyri,n.b68,n.suduroy],
    2011.0: [n.b36,n.ebstreymur,n.vikingurgota,n.nsirunavik,n.kiklaksvik,n.b68,n.iffuglafjordur,n.havnarboltfelag,n.vestur,n.b71sandoy],
    2010.0: [n.havnarboltfelag,n.ebstreymur,n.nsirunavik,n.iffuglafjordur,n.vikingurgota,n.b36,n.b68,n.b71sandoy,n.suduroy,n.abFaroe],
    2009.0: [n.havnarboltfelag,n.ebstreymur,n.vikingurgota,n.nsirunavik,n.b68,n.abFaroe,n.iffuglafjordur,n.b36,n.kiklaksvik,n.vestur],
    2008.0: [n.ebstreymur,n.havnarboltfelag,n.b36,n.nsirunavik,n.vikingurgota,n.b68,n.iffuglafjordur,n.kiklaksvik,n.b71sandoy,n.skala],
    2007.0: [n.nsirunavik,n.ebstreymur,n.b36,n.havnarboltfelag,n.gigota,n.skala,n.kiklaksvik,n.b71sandoy,n.abFaroe,n.sumbavb],
    2006.0: [n.havnarboltfelag,n.ebstreymur,n.b36,n.kiklaksvik,n.nsirunavik,n.gigota,n.skala,n.vbvagur,n.b68,n.iffuglafjordur],
    2005.0: [n.b36,n.skala,n.havnarboltfelag,n.nsirunavik,n.ebstreymur,n.iffuglafjordur,n.kiklaksvik,n.vbvagur,n.gigota,n.tbtvoroyri],
    2004.0: [n.havnarboltfelag,n.b36,n.skala,n.kiklaksvik,n.vbvagur,n.ebstreymur,n.nsirunavik,n.gigota,n.iffuglafjordur,n.b68],
    2003.0: [n.havnarboltfelag,n.b36,n.b68,n.nsirunavik,n.kiklaksvik,n.ebstreymur,n.gigota,n.vbvagur,n.skala,n.fsvagar],
    2002.0: [n.havnarboltfelag,n.nsirunavik,n.kiklaksvik,n.gigota,n.b36,n.b68,n.vbvagur,n.skala,n.ebstreymur,n.tbtvoroyri],
    2001.0: [n.b36,n.gigota,n.b68,n.vbvagur,n.nsirunavik,n.kiklaksvik,n.havnarboltfelag,n.ebstreymur,n.b71sandoy,n.fsvagar],
    2000.0: [n.vbvagur,n.havnarboltfelag,n.b68,n.nsirunavik,n.kiklaksvik,n.b36,n.gigota,n.b71sandoy,n.fsvagar,n.sumbavb],
    1999.0: [n.kiklaksvik,n.gigota,n.b36,n.havnarboltfelag,n.nsirunavik,n.vbvagur,n.b68,n.b71sandoy,n.sumbavb,n.iffuglafjordur],
    1998.0: [n.havnarboltfelag,n.kiklaksvik,n.b36,n.gigota,n.nsirunavik,n.b68,n.vbvagur,n.iffuglafjordur,n.sumbavb,n.tbtvoroyri],
    1997.0: [n.b36,n.havnarboltfelag,n.gigota,n.vbvagur,n.kiklaksvik,n.nsirunavik,n.iffuglafjordur,n.b68,n.fsvagar,n.b71sandoy],
    1996.0: [n.gigota,n.kiklaksvik,n.havnarboltfelag,n.b36,n.vbvagur,n.iffuglafjordur,n.b68,n.b71sandoy,n.fsvagar,n.tbtvoroyri],
    1995.0: [n.gigota,n.havnarboltfelag,n.b68,n.b71sandoy,n.b36,n.fsvagar,n.tbtvoroyri,n.kiklaksvik,n.sumbavb,n.nsirunavik],
    1994.0: [n.gigota,n.havnarboltfelag,n.b71sandoy,n.kiklaksvik,n.b68,n.nsirunavik,n.b36,n.tbtvoroyri,n.iffuglafjordur,n.ebstreymur],
    1993.0: [n.gigota,n.havnarboltfelag,n.kiklaksvik,n.b71sandoy,n.b36,n.b68,n.tbtvoroyri,n.iffuglafjordur,n.leirvikif,n.vbvagur],
    1992.0: [n.b68,n.gigota,n.kiklaksvik,n.havnarboltfelag,n.tbtvoroyri,n.b36,n.vbvagur,n.b71sandoy,n.sifsandavagur,n.nsirunavik],
    1991.0: [n.kiklaksvik,n.b36,n.gigota,n.vbvagur,n.tbtvoroyri,n.havnarboltfelag,n.b68,n.nsirunavik,n.mbmidvagur,n.sumbavb],
    1990.0: [n.havnarboltfelag,n.b36,n.mbmidvagur,n.gigota,n.vbvagur,n.b68,n.kiklaksvik,n.tbtvoroyri,n.sifsandavagur,n.b71sandoy],
    1989.0: [n.b71sandoy,n.havnarboltfelag,n.b68,n.vbvagur,n.kiklaksvik,n.b36,n.gigota,n.sifsandavagur,n.iffuglafjordur,n.leirvikif],
    1988.0: [n.havnarboltfelag,n.b68,n.b36,n.iffuglafjordur,n.gigota,n.vbvagur,n.leirvikif,n.kiklaksvik,n.tbtvoroyri,n.nsirunavik],
    1987.0: [n.tbtvoroyri,n.havnarboltfelag,n.gigota,n.nsirunavik,n.kiklaksvik,n.b68,n.leirvikif,n.vbvagur],
    1986.0: [n.gigota,n.havnarboltfelag,n.b68,n.nsirunavik,n.tbtvoroyri,n.kiklaksvik,n.leirvikif,n.b36],
    1985.0: [n.b68,n.havnarboltfelag,n.kiklaksvik,n.leirvikif,n.gigota,n.nsirunavik,n.tbtvoroyri,n.iffuglafjordur],
    1984.0: [n.b68,n.tbtvoroyri,n.havnarboltfelag,n.leirvikif,n.kiklaksvik,n.gigota,n.nsirunavik,n.b36],
    1983.0: [n.gigota,n.havnarboltfelag,n.kiklaksvik,n.b68,n.b36,n.leirvikif,n.tbtvoroyri,n.mbmidvagur],
    1982.0: [n.havnarboltfelag,n.tbtvoroyri,n.kiklaksvik,n.gigota,n.b36,n.leirvikif,n.b68,n.iffuglafjordur],
    1981.0: [n.havnarboltfelag,n.tbtvoroyri,n.gigota,n.b68,n.iffuglafjordur,n.b36,n.kiklaksvik,n.vbvagur],
    1980.0: [n.tbtvoroyri,n.havnarboltfelag,n.kiklaksvik,n.gigota,n.iffuglafjordur,n.vbvagur,n.b36,n.mbmidvagur],
    1979.0: [n.iffuglafjordur,n.tbtvoroyri,n.havnarboltfelag,n.b36,n.mbmidvagur,n.kiklaksvik,n.vbvagur,n.nsirunavik],
    1978.0: [n.havnarboltfelag,n.tbtvoroyri,n.vbvagur,n.iffuglafjordur,n.kiklaksvik,n.mbmidvagur,n.b36],
    1977.0: [n.tbtvoroyri,n.havnarboltfelag,n.vbvagur,n.iffuglafjordur,n.kiklaksvik,n.b36,n.framtorshavn],
    1976.0: [n.tbtvoroyri,n.havnarboltfelag,n.kiklaksvik,n.vbvagur,n.b36,n.iffuglafjordur,n.nsirunavik],
    1975.0: [n.havnarboltfelag,n.kiklaksvik,n.tbtvoroyri,n.b36,n.vbvagur,n.iffuglafjordur],
    1974.0: [n.havnarboltfelag,n.kiklaksvik,n.vbvagur,n.tbtvoroyri,n.b36,n.iffuglafjordur],
    1973.0: [n.havnarboltfelag,n.kiklaksvik,n.tbtvoroyri,n.vbvagur,n.b36,n.iffuglafjordur],
    1972.0: [n.kiklaksvik,n.havnarboltfelag,n.b36,n.tbtvoroyri,n.vbvagur,n.iffuglafjordur],
    1971.0: [n.havnarboltfelag,n.kiklaksvik,n.vbvagur,n.tbtvoroyri,n.b36,n.iffuglafjordur],
    1970.0: [n.kiklaksvik,n.havnarboltfelag,n.tbtvoroyri,n.vbvagur,n.b36],
    1969.0: [n.kiklaksvik,n.havnarboltfelag,n.tbtvoroyri,n.b36,n.vbvagur],
    1968.0: [n.kiklaksvik,n.b36,n.havnarboltfelag,n.vbvagur,n.tbtvoroyri],
    1967.0: [n.kiklaksvik,n.havnarboltfelag,n.b36,n.vbvagur,n.tbtvoroyri],
    1966.0: [n.kiklaksvik,n.havnarboltfelag,n.b36,n.tbtvoroyri,n.vbvagur],
    1965.0: [n.havnarboltfelag,n.b36,n.kiklaksvik,n.tbtvoroyri],
    1964.0: [n.havnarboltfelag,n.b36,n.tbtvoroyri],
    1963.0: [n.havnarboltfelag,n.kiklaksvik,n.b36,n.tbtvoroyri],
    1962.0: [n.b36,n.kiklaksvik,n.havnarboltfelag,n.tbtvoroyri],
    1961.0: [n.kiklaksvik,n.b36,n.tbtvoroyri,n.havnarboltfelag],
    1960.0: [n.havnarboltfelag,n.b36,n.kiklaksvik,n.tbtvoroyri],
    1959.0: [n.b36,n.havnarboltfelag,n.kiklaksvik,n.tbtvoroyri,n.vbvagur],
    1958.0: [n.kiklaksvik,n.havnarboltfelag,n.b36,n.tbtvoroyri,n.vbvagur],
    1957.0: [n.kiklaksvik,n.vbvagur,n.tbtvoroyri,n.b36,n.havnarboltfelag],
    1956.0: [n.kiklaksvik,n.tbtvoroyri,n.havnarboltfelag,n.b36,n.vbvagur],
    1955.0: [n.havnarboltfelag,n.tbtvoroyri,n.kiklaksvik,n.b36],
    1954.0: [n.kiklaksvik,n.havnarboltfelag,n.b36,n.tbtvoroyri],
    1953.0: [n.kiklaksvik,n.havnarboltfelag,n.tbtvoroyri,n.b36,n.vbvagur],
    1952.0: [n.kiklaksvik,n.tbtvoroyri,n.havnarboltfelag,n.vbvagur,n.b36],
    1951.0: [n.tbtvoroyri,n.kiklaksvik,n.b36,n.havnarboltfelag],
    1950.0: [n.b36,n.tbtvoroyri,n.havnarboltfelag,n.kiklaksvik,n.vbvagur],
  },

  //////////////////////////////////////////////////////////////////////////////
  // BALTICOS
  //////////////////////////////////////////////////////////////////////////////

  leagueName.estonia : {
    //2025.0: [],
    //2024.0: [],
    2023.0: [],
    2022.0: [n.floratallinn,n.levadiatallinn,n.paidelinnameeskond,n.nommekalju,n.kuressaare,n.tartutammeka,n.narvatrans,n.tallinnakalev,n.legion,n.vaprus],
    2021.0: [n.levadiatallinn,n.floratallinn,n.paidelinnameeskond,n.nommekalju,n.legion,n.narvatrans,n.kuressaare,n.viljanditulevik,n.tartutammeka,n.vaprus],
    2020.0: [n.floratallinn,n.paidelinnameeskond,n.levadiatallinn,n.nommekalju,n.tartutammeka,n.viljanditulevik,n.tjklegion,n.narvatrans,n.kuressaare,n.tallinnakalev],
    2019.0: [n.floratallinn,n.levadiatallinn,n.nommekalju,n.paidelinnameeskond,n.tartutammeka,n.narvatrans,n.viljanditulevik,n.tallinnakalev,n.kuressaare,n.maardulinnameeskond],
    2018.0: [n.nommekalju,n.levadiatallinn,n.floratallinn,n.narvatrans,n.paidelinnameeskond,n.tartutammeka,n.viljanditulevik,n.tallinnakalev,n.kuressaare,n.vaprus],
    2017.0: [n.floratallinn,n.levadiatallinn,n.nommekalju,n.fcitallinn,n.narvatrans,n.paidelinnameeskond,n.tartutammeka,n.viljanditulevik,n.vaprus,n.sillamaekalev],
    2016.0: [n.fcitallinn,n.levadiatallinn,n.nommekalju,n.floratallinn,n.sillamaekalev,n.paidelinnameeskond,n.merkuur,n.narvatrans,n.parnulinnameeskond,n.rakveretarvas],
    2015.0: [n.floratallinn,n.levadiatallinn,n.nommekalju,n.fcitallinn,n.sillamaekalev,n.narvatrans,n.paidelinnameeskond,n.parnulinnameeskond,n.tartutammeka,n.viljanditulevik],
    2014.0: [n.levadiatallinn,n.sillamaekalev,n.floratallinn,n.nommekalju,n.fcitallinn,n.paidelinnameeskond,n.tartutammeka,n.narvatrans,n.lokomotiv,n.tallinnakalev],
    2013.0: [n.levadiatallinn,n.nommekalju,n.sillamaekalev,n.floratallinn,n.paidelinnameeskond,n.fcitallinn,n.narvatrans,n.tallinnakalev,n.tartutammeka,n.kuressaare],
    2012.0: [n.nommekalju,n.levadiatallinn,n.floratallinn,n.narvatrans,n.sillamaekalev,n.paidelinnameeskond,n.viljanditulevik,n.kuressaare,n.tallinnakalev,n.tartutammeka],
    2011.0: [n.floratallinn,n.nommekalju,n.narvatrans,n.levadiatallinn,n.sillamaekalev,n.paidelinnameeskond,n.tartutammeka,n.viljanditulevik,n.kuressaare,n.ajaxlasnamae],
    2010.0: [n.floratallinn,n.levadiatallinn,n.narvatrans,n.nommekalju,n.sillamaekalev,n.tartutammeka,n.viljanditulevik,n.paidelinnameeskond,n.kuressaare,n.lootus],
    2009.0: [n.levadiatallinn,n.sillamaekalev,n.trans,n.floratallinn,n.nommekalju,n.viljanditulevik,n.tartutammeka,n.kuressaare,n.paidelinnameeskond,n.tallinnakalev],
    2008.0: [n.levadiatallinn,n.floratallinn,n.narvatrans,n.nommekalju,n.sillamaekalev,n.viljanditulevik,n.merkuur,n.tallinnakalev,n.vaprus,n.tvmk],
    2007.0: [n.levadiatallinn,n.floratallinn,n.tvmk,n.narvatrans,n.merkuur,n.tallinnakalev,n.viljanditulevik,n.vaprus,n.kuressaare,n.ajaxlasnamae],
    2006.0: [n.levadiatallinn,n.narvatrans,n.floratallinn,n.tvmk,n.merkuur,n.tartutammeka,n.vaprus,n.ajaxlasnamae,n.viljanditulevik,n.warrior],
    2005.0: [n.tvmk,n.levadiatallinn,n.narvatrans,n.floratallinn,n.viljanditulevik,n.merkuur,n.tartutammeka,n.valga,n.kuressaare,n.dunamo],
    2004.0: [n.levadiatallinn,n.tvmk,n.floratallinn,n.narvatrans,n.merkuur,n.viljanditulevik,n.valga,n.alutaguselootus],
    2003.0: [n.floratallinn,n.tvmk,n.levadiamaardu,n.narvatrans,n.viljanditulevik,n.levadiatallinn,n.valga,n.kuressaare],
    2002.0: [n.floratallinn,n.maardulevadia,n.tvmk,n.narvatrans,n.viljanditulevik,n.levadiatallinn,n.lootus,n.levadiaparnu],
    2001.0: [n.floratallinn,n.tvmk,n.maardulevadia,n.narvatrans,n.viljanditulevik,n.levadiatallinn,n.lootus,n.kuressaare],
    2000.0: [n.levadiatallinn,n.floratallinn,n.tvmk,n.viljanditulevik,n.narvatrans,n.lootus,n.kuressaare,n.valga],
    1999.0: [n.levadiatallinn,n.viljanditulevik,n.floratallinn,n.narvatrans,n.tvmk,n.lantana,n.lelle,n.eestipolevkivijohvi],
    1998.0: [n.floratallinn,n.tallinnasadam,n.lantana,n.narvatrans,n.viljanditulevik,n.tvmk,n.eestipolevkivijohvi,n.lelle],
    1997.0: [n.lantana,n.floratallinn,n.tallinnasadam,n.lelle,n.marlekor,n.narvatrans,n.eestipolevkivijohvi,n.vall,n.parnulinnameeskond,n.fclelle,n.tjk,n.sillamaekalev],
    1996.0: [n.lantana,n.floratallinn,n.tevaltemarlekor,n.tallinnasadam,n.narvatrans,n.tervis,n.eestipolevkivijohvi,n.vall,n.norma,n.pjkkalev,n.dunamo,n.tjk],
    1995.0: [n.floratallinn,n.lantanamarlekor,n.narvatrans,n.tallinnasadam,n.eestipolevkivijohvi,n.norma,n.tervis,n.pjkkalev,n.tjk,n.dunamo,n.lelle,n.dag],
    1994.0: [n.floratallinn,n.norma,n.nikol,n.narvatrans,n.tallinnasadam,n.eestipolevkivijohvi,n.esdag,n.tervis,n.dunamo,n.merkuur,n.sillamaekalev,n.tevalte],
    1993.0: [n.norma,n.floratallinn,n.nikol,n.eestipolevkivijohvi,n.vigri,n.narvatrans,n.kohtlajarvekeemik,n.esdag,n.dunamo,n.merkuur,n.sillamaekalev,n.viljanditulevik],
    1992.0: [n.norma,n.eestipolevkivijohvi,n.tvmv,n.floratallinn,n.vigri,n.tartukalev,n.narvatrans,n.parnulinnameeskond,n.dunamo,n.kohtlajarvekeemik,n.sillamaekalev,n.merkuur,n.viljanditulevik,n.maardu],
  },
  leagueName.letonia : {
    //2025.0: [],
    //2024.0: [],
    2023.0: [],
    2022.0: [n.valmiera,n.rigafc,n.rigasfs,n.liepaja,n.fkauda,n.tukums,n.bfcdaugavpils,n.spartaksjurmala,n.mettalu,n.supernova],
    2021.0: [n.rigasfs,n.valmiera,n.liepaja,n.rigafc,n.spartaksjurmala,n.bfcdaugavpils,n.mettalu,n.noahjurmala],
    2020.0: [n.rigafc,n.rigasfs,n.valmiera,n.ventspils,n.liepaja,n.spartaksjurmala,n.jelgava,n.bfcdaugavpils,n.mettalu,n.tukums],
    2019.0: [n.rigafc,n.rigasfs,n.ventspils,n.valmiera,n.spartaksjurmala,n.liepaja,n.jelgava,n.bfcdaugavpils,n.mettalu],
    2018.0: [n.rigafc,n.ventspils,n.rigasfs,n.liepaja,n.spartaksjurmala,n.jelgava,n.mettalu,n.valmiera],
    2017.0: [n.spartaksjurmala,n.liepaja,n.rigafc,n.ventspils,n.rigasfs,n.jelgava,n.mettalu,n.babite],
    2016.0: [n.spartaksjurmala,n.jelgava,n.ventspils,n.liepaja,n.rigafc,n.rigasfs,n.mettalu,n.bfcdaugavpils],
    2015.0: [n.liepaja,n.skonto,n.ventspils,n.jelgava,n.spartaksjurmala,n.bfcdaugavpils,n.mettalu,n.gulbene],
    2014.0: [n.ventspils,n.skonto,n.jelgava,n.liepaja,n.daugavadaugavpils,n.spartaksjurmala,n.daugavariga,n.bfcdaugavpils,n.mettalu,n.jurmala],
    2013.0: [n.ventspils,n.skonto,n.daugavadaugavpils,n.daugavariga,n.liepaja,n.jurmala,n.spartaksjurmala,n.jelgava,n.mettalu,n.ilukstesnss],
    2012.0: [n.daugavadaugavpils,n.skonto,n.ventspils,n.liepaja,n.spartaksjurmala,n.jurmala,n.jelgava,n.mettalu,n.daugavariga,n.gulbene],
    2011.0: [n.ventspils,n.liepaja,n.daugavadaugavpils,n.skonto,n.jurmala,n.jelgava,n.gulbene,n.jurmala,n.olimpsrfs],
    2010.0: [n.skonto,n.ventspils,n.liepaja,n.daugavadaugavpils,n.jurmala,n.jelgava,n.blazmarezekne,n.olimpsrfs,n.tranzitsventspils,n.jaunibariga],
    2009.0: [n.liepaja,n.ventspils,n.skonto,n.jurmala,n.olimpsrfs,n.blazmarezekne,n.tranzitsventspils,n.daugavariga,n.dinaburg],
    2008.0: [n.ventspils,n.liepaja,n.skonto,n.dinaburg,n.daugavadaugavpils,n.rigafc,n.jurmala,n.vindavaventspils,n.blazmarezekne,n.olimpsrfs],
    2007.0: [n.ventspils,n.liepaja,n.rigafc,n.skonto,n.daugavadaugavpils,n.jurmala,n.dinaburg,n.olimpsriga],
    2006.0: [n.ventspils,n.liepaja,n.skonto,n.dinaburg,n.ditton,n.jurmala,n.rigafc,n.dizvanagi],
    2005.0: [n.liepaja,n.skonto,n.ventspils,n.dinaburg,n.rigafc,n.jurmala,n.olimpsriga,n.venta],
    2004.0: [n.skonto,n.liepaja,n.ventspils,n.dinaburg,n.jurmala,n.rigafc,n.ditton,n.fkauda],
    2003.0: [n.skonto,n.liepaja,n.ventspils,n.dinaburg,n.rigafc,n.gauja,n.fkauda,n.rkbarma],
    2002.0: [n.skonto,n.ventspils,n.liepaja,n.dinaburg,n.valmiera,n.pfkdaugava,n.rigafc,n.fkauda],
    2001.0: [n.skonto,n.ventspils,n.liepaja,n.dinaburg,n.pfkdaugava,n.valmiera,n.rigafc,n.zibenszemessardze],
    2000.0: [n.skonto,n.ventspils,n.liepaja,n.dinaburg,n.rigafc,n.valmiera,n.policijas,n.torpedoriga],
    1999.0: [n.skonto,n.liepaja,n.ventspils,n.dinaburg,n.valmiera,n.rigafc,n.policijas,n.blazmarezekne],
    1998.0: [n.skonto,n.liepaja,n.ventspils,n.dinaburg,n.valmiera,n.torpedoriga,n.blazmarezekne,n.rantomiks],
    1997.0: [n.skonto,n.torpedoriga,n.dinaburg,n.ventspils,n.liepaja,n.jelgava,n.valmiera,n.lokomotive,n.blazmarezekne],
    1996.0: [n.skonto,n.torpedoriga,n.dinaburg,n.jelgava,n.liepaja,n.starts,n.lokomotive,n.blazmarezekne,n.skontometals,n.jurnieks],
    1995.0: [n.skonto,n.viland,n.rafjelgava,n.starts,n.torpedoriga,n.blazmarezekne,n.skontometals,n.liepaja,n.olimpijariga,n.kvadrats],
    1994.0: [n.skonto,n.rafjelgava,n.dagriga,n.olimpijariga,n.blazmarezekne,n.pardaugava,n.torpedoriga,n.interskonto,n.dinaburg,n.gemma,n.liepaja,n.kimikis],
    1993.0: [n.skonto,n.olimpijariga,n.rafjelgava,n.pardaugava,n.dinaburg,n.torpedoriga,n.olimpijaliepaja,n.dagriga,n.blazmarezekne,n.gauja],
    1992.0: [n.skonto,n.rafjelgava,n.vefriga,n.pardaugava,n.kompardaugava,n.olimpijaliepaja,n.dinaburg,n.torpedoriga,n.blazmarezekne,n.gauja,n.starts,n.dilar],
  },
  leagueName.lituania : {
    //2025.0: [],
    //2024.0: [],
    2023.0: [],
    2022.0: [n.zalgiris,n.kaunozalgiris,n.panevezys,n.hegelmann,n.riteriai,n.suduva,n.siauliai,n.bangakaunas,n.dziugas,n.jonava],
    2021.0: [n.zalgiris,n.suduva,n.kaunozalgiris,n.panevezys,n.hegelmann,n.riteriai,n.bangakaunas,n.dziugas,n.dainava,n.nevezis],
    2020.0: [n.zalgiris,n.suduva,n.kaunozalgiris,n.bangakaunas,n.panevezys,n.riteriai],
    2019.0: [n.suduva,n.zalgiris,n.riteriai,n.kaunozalgiris,n.panevezys,n.atlantas,n.palanga,n.stumbras],
    2018.0: [n.suduva,n.zalgiris,n.trakai,n.stumbras,n.kaunozalgiris,n.atlantas,n.palanga,n.jonava],
    2017.0: [n.suduva,n.zalgiris,n.trakai,n.jonava,n.atlantas,n.utenisutena,n.stumbras,n.kaunozalgiris],
    2016.0: [n.zalgiris,n.trakai,n.suduva,n.atlantas,n.stumbraskaunas,n.lietavajonava,n.utenisutena,n.kaunozalgiris],
    2015.0: [n.zalgiris,n.trakai,n.atlantas,n.suduva,n.kaunozalgiris,n.utenisutena,n.stumbraskaunas,n.klaipedosgranitas,n.siauliai,n.kruojapakruojis],
    2014.0: [n.zalgiris,n.kruojapakruojis,n.atlantas,n.trakai,n.suduva,n.ekranas,n.siauliai,n.klaipedosgranitas,n.bangakaunas,n.dainava],
    2013.0: [n.zalgiris,n.atlantas,n.ekranas,n.suduva,n.kruojapakruojis,n.bangakaunas,n.siauliai,n.dainava,n.tauras],
    2012.0: [n.ekranas,n.zalgiris,n.suduva,n.kruojapakruojis,n.siauliai,n.bangakaunas,n.dainava,n.atlantas,n.tauras,n.reo],
    2011.0: [n.ekranas,n.zalgiris,n.suduva,n.siauliai,n.kruojapakruojis,n.bangakaunas,n.tauras,n.dainava,n.mazeikiai,n.fbkkaunas,n.atlantas,n.klaipeda],
    2010.0: [n.ekranas,n.suduva,n.zalgiris,n.tauras,n.siauliai,n.bangakaunas,n.kruojapakruojis,n.klaipeda,n.mazeikiai,n.atletaskaunas,n.vetra],
    2009.0: [n.ekranas,n.vetra,n.suduva,n.siauliai,n.tauras,n.bangakaunas,n.lkkairteledema,n.kruojapakruojis],
    2008.0: [n.ekranas,n.fbkkaunas,n.vetra,n.suduva,n.zalgiris,n.atlantas,n.siauliai,n.silute],
    2007.0: [n.fbkkaunas,n.suduva,n.ekranas,n.zalgiris,n.vetra,n.atlantas,n.vilnius,n.siauliai,n.silute,n.interasae],
    2006.0: [n.fbkkaunas,n.ekranas,n.vetra,n.zalgiris,n.suduva,n.atlantas,n.vilnius,n.siauliai,n.silute,n.nevezis],
    2005.0: [n.ekranas,n.fbkkaunas,n.suduva,n.vetra,n.vilnius,n.silute,n.atlantas,n.zalgiris,n.siauliai,n.nevezis],
    2004.0: [n.fbkkaunas,n.ekranas,n.atlantas,n.zalgiris,n.vetra,n.silute,n.suduva,n.vilnius],
    2003.0: [n.fbkkaunas,n.ekranas,n.vetra,n.zalgiris,n.atlantas,n.suduva,n.sviesa,n.karedasiauliai],
    2002.0: [n.fbkkaunas,n.atlantas,n.ekranas,n.zalgiris,n.inkaraskaunas,n.suduva,n.karedasiauliai,n.gelezinisvilkas,n.nevezis],
    2001.0: [n.fbkkaunas,n.atlantas,n.zalgiris,n.ekranas,n.inkaraskaunas,n.gelezinisvilkas,n.nevezis,n.karedasiauliai,n.vetra,n.dainava],
    2000.0: [n.fbkkaunas,n.zalgiris,n.atlantas,n.ekranas,n.karedasiauliai,n.nevezis,n.dainava,n.polonija,n.inkaraskaunas,n.bangakaunas],
    1999.0: [n.fbkkaunas,n.zalgiris,n.atlantas,n.karedasiauliai,n.ekranas,n.inkaraskaunas,n.nevezis,n.bangakaunas,n.ardena,n.dainava],
    1998.0: [n.karedasiauliai,n.zalgiris,n.ekranas,n.inkaraskaunas,n.fbkkaunas,n.atlantas,n.lokomotyvas,n.rangapolitechnika,n.panerys,n.nevezis,n.mastis,n.gelezinisvilkas,n.bangakaunas,n.interasae,n.tauras,n.vienybe],
    1997.0: [n.karedasiauliai,n.zalgiris,n.inkaraskaunas,n.fbkkaunas,n.ekranas,n.panerys,n.atlantas,n.zalgirisvolmeta],
    1996.0: [n.inkaraskaunas,n.karedasiauliai,n.zalgiris,n.fbkkaunas,n.panerys,n.atlantas,n.ekranas,n.zalgiris2,n.bangakaunas,n.lokomotyvas,n.tauras,n.ukmerge,n.mastis,n.alsapanerys,n.jrklaipeda],
    1995.0: [n.inkaraskaunas,n.zalgiris,n.romar,n.panerys,n.atlantas,n.fbkkaunas,n.karedasiauliai,n.ekranas,n.bangakaunas,n.ukmerge,n.sirijus,n.interasae],
    1994.0: [n.romar,n.zalgiris,n.ekranas,n.panerys,n.fbkkaunas,n.atlantas,n.sirijus,n.inkaraskaunas,n.karedasiauliai,n.gelezinisvilkas,n.zydrius,n.tauraskarsuva],
    1993.0: [n.ekranas,n.zalgiris,n.panerys,n.sirijus,n.bangakaunas,n.romar,n.atlantas,n.gelezinisvilkas,n.inkaraskaunas,n.karedasiauliai,n.neris,n.tauraskarsuva,n.snaige,n.minija],
    1992.0: [n.zalgiris,n.panerys,n.sirijus,n.bangakaunas,n.ekranas,n.lietuvosmakabi,n.granitasklaipeda,n.karedasiauliai,n.mazeikiai,n.inkaraskaunas,n.snaige,n.elektronas,n.taurassiauliai,n.vienybe],
    1991.0: [n.zalgiris,n.bangakaunas,n.neris,n.ekranas,n.sirijus,n.vilija,n.granitasklaipeda,n.panerys,n.karedasiauliai,n.elektronas,n.vienybe,n.jovaras,n.taurassiauliai,n.inkaraskaunas,n.suduva],
  },

};
