import 'package:fifa/values/club_names.dart';
import 'package:fifa/values/league_names.dart';

ClubName n = ClubName();
LeagueOfficialNames leagueName = LeagueOfficialNames();

Map<String, dynamic> mapInternationals = {

  ///////////////////////////////////////////////////////////////
  // CONTINENTS CHAMPIONS
  ///////////////////////////////////////////////////////////////

  leagueName.championsLeague : {
    //2024.0: [],
    2023.0: [n.mancity,n.inter,n.realmadrid,n.milan,                  n.bayernmunique,n.benfica,n.chelsea,n.napoli,         n.psg,n.eintrachtfrankfurt,n.dortmund,n.tottenham,n.porto,n.rbleipzig,n.liverpool,n.brugge,             n.barcelona,n.sporting,n.shakhtardonetsk,n.rbsalzburg,n.ajax,n.leverkusen,n.sevilla,n.juventus,                   n.om,n.atleticomadrid,n.dinamozagreb,n.copenhague,n.maccabihaifa,n.celtic,n.viktoriaplzen,n.rangers],
    2022.0: [n.realmadrid,n.liverpool,n.mancity,n.villareal,          n.chelsea,n.benfica,n.atleticomadrid,n.bayernmunique,      n.psg,n.inter,n.sporting,n.juventus,n.lille,n.ajax,n.manutd,n.rbsalzburg,                          n.dortmund,n.rbleipzig,n.sherifftiraspol,n.barcelona,n.sevilla,n.atalanta,n.porto,n.zenit,                            n.youngboys,n.wolfsburg,n.milan,n.brugge,n.shakhtardonetsk,n.dinamokiev,n.malmo,n.besiktas,],
    2021.0: [n.chelsea,n.mancity,n.realmadrid,n.psg,                  n.porto,n.dortmund,n.liverpool,n.bayernmunique,          n.atleticomadrid,n.moenchengladbach,n.atalanta,n.barcelona,n.juventus,n.sevilla,n.rbleipzig,n.lazio, n.rbsalzburg,n.shakhtardonetsk,n.olympiacos,n.ajax,n.krasnodar,n.brugge,n.dinamokiev,n.manutd,       n.lokomotivMoscou,n.inter,n.om,n.midtjylland,n.rennes,n.zenit,n.ferencvaros,n.istanbulbasaksehir],
    2020.0: [n.bayernmunique,n.psg,n.lyon,n.rbleipzig,                n.barcelona,n.atalanta,n.mancity,n.atleticomadrid, n.chelsea,n.dortmund,n.juventus,n.tottenham,n.napoli,n.valencia,n.realmadrid,n.liverpool,                  n.brugge,n.olympiacos,n.shakhtardonetsk,n.leverkusen,n.rbsalzburg,n.inter,n.benfica,n.ajax,               n.galatasaray,n.estrelavermelha,n.dinamozagreb,n.lokomotivMoscou,n.genk,n.slaviapraha,n.zenit,n.lille],
    2019.0: [n.liverpool,n.tottenham,n.barcelona,n.ajax,              n.porto,n.mancity,n.manutd,n.juventus,   n.bayernmunique,n.dortmund,n.lyon,n.realmadrid,n.roma,n.schalke04,n.psg,n.atleticomadrid,                            n.brugge,n.inter,n.napoli,n.galatasaray,n.benfica,n.shakhtardonetsk,n.viktoriaplzen,n.valencia,                n.monaco,n.psv,n.estrelavermelha,n.lokomotivMoscou,n.aek,n.hoffenheim,n.cska,n.youngboys],
    2018.0: [n.realmadrid,n.liverpool,n.bayernmunique,n.roma,         n.sevilla,n.mancity,n.juventus,n.barcelona,      n.psg,n.porto,n.besiktas,n.shakhtardonetsk,n.manutd,n.basel,n.tottenham,n.chelsea,                           n.cska,n.celtic,n.atleticomadrid,n.sporting,n.spartakmoscou,n.napoli,n.rbleipzig,n.dortmund,          n.benfica,n.anderlecht,n.qarabag,n.olympiacos,n.maribor,n.feyenoord,n.monaco,n.apoel],
    2017.0: [n.realmadrid,n.juventus,n.atleticomadrid,n.monaco,       n.bayernmunique,n.barcelona,n.leicester,n.dortmund,     n.napoli,n.porto,n.leverkusen,n.mancity,n.arsenal,n.psg,n.sevilla,n.benfica,                          n.ludogorets,n.besiktas,n.moenchengladbach,n.rostov,n.tottenham,n.legiawarszawa,n.copenhague,n.lyon,          n.basel,n.dinamokiev,n.celtic,n.psv,n.cska,n.sporting,n.brugge,n.dinamozagreb],
    2016.0: [n.realmadrid,n.atleticomadrid,n.bayernmunique,n.mancity, n.wolfsburg,n.barcelona,n.benfica,n.psg,                n.roma,n.psv,n.juventus,n.dinamokiev,n.gent,n.arsenal,n.zenit,n.chelsea,                              n.shakhtardonetsk,n.manutd,n.galatasaray,n.sevilla,n.leverkusen,n.olympiacos,n.porto,n.valencia, n.malmo,n.cska,n.astana,n.moenchengladbach,n.bate,n.dinamozagreb,n.maccabitelaviv,n.lyon],
    2015.0: [n.barcelona,n.juventus,n.bayernmunique,n.realmadrid,     n.psg,n.monaco,n.porto,n.atleticomadrid,                n.mancity,n.dortmund,n.shakhtardonetsk,n.schalke04,n.chelsea,n.arsenal,n.basel,n.leverkusen,          n.olympiacos,n.liverpool,n.zenit,n.anderlecht,n.roma,n.ajax,n.sporting,n.athleticbilbao,                      n.malmo,n.ludogorets,n.benfica,n.galatasaray,n.cska,n.apoel,n.maribor,n.bate],
    2014.0: [n.realmadrid,n.atleticomadrid,n.bayernmunique,n.chelsea, n.dortmund,n.barcelona,n.manutd,n.psg,        n.schalke04,n.milan,n.arsenal,n.galatasaray,n.zenit,n.mancity,n.olympiacos,n.leverkusen,                        n.shakhtardonetsk,n.juventus,n.benfica,n.viktoriaplzen,n.basel,n.napoli,n.porto,n.ajax,                        n.realsociedad,n.copenhague,n.anderlecht,n.cska,n.steauabucuresti,n.om,n.austria,n.celtic],
    2013.0: [n.bayernmunique,n.dortmund,n.barcelona,n.realmadrid,     n.juventus,n.malaga,n.psg,n.galatasaray,                n.arsenal,n.shakhtardonetsk,n.milan,n.manutd,n.celtic,n.porto,n.valencia,n.schalke04,                 n.dinamokiev,n.olympiacos,n.zenit,n.ajax,n.chelsea,n.bate,n.benfica,n.cluj,                                   n.dinamozagreb,n.montpellier,n.anderlecht,n.mancity,n.nordsjaelland,n.lille,n.spartakmoscou,n.braga],
    2012.0: [n.chelsea,n.bayernmunique,n.barcelona,n.realmadrid,      n.benfica,n.om,n.milan,n.apoel,                         n.napoli,n.basel,n.leverkusen,n.cska,n.zenit,n.inter,n.arsenal,n.lyon,                                n.mancity,n.trabzonspor,n.manutd,n.ajax,n.valencia,n.olympiacos,n.porto,n.viktoriaplzen,     n.villareal,n.lille,n.otelul,n.dinamozagreb,n.genk,n.dortmund,n.shakhtardonetsk,n.bate],
    2011.0: [n.barcelona,n.manutd,n.realmadrid,n.schalke04,           n.shakhtardonetsk,n.chelsea,n.tottenham,n.inter,         n.arsenal,n.om,n.lyon,n.valencia,n.roma,n.copenhague,n.milan,n.bayernmunique,                        n.twente,n.benfica,n.rangers,n.rubinKazan,n.basel,n.spartakmoscou,n.ajax,n.braga,                             n.werderbremen,n.hapoeltelaviv,n.bursaspor,n.panathinaikos,n.cluj,n.zilina,n.auxerre,n.partizan],
    2010.0: [n.inter,n.bayernmunique,n.barcelona,n.lyon,              n.cska,n.manutd,n.arsenal,n.bordeaux,         n.chelsea,n.fiorentina,n.stuttgart,n.realmadrid,n.sevilla,n.milan,n.porto,n.olympiacos,                         n.juventus,n.wolfsburg,n.om,n.atleticomadrid,n.liverpool,n.rubinKazan,n.unirea,n.standardliege,               n.maccabihaifa,n.besiktas,n.zurich,n.apoel,n.debreceni,n.dinamokiev,n.rangers,n.az],
    2009.0: [n.barcelona,n.manutd,n.chelsea,n.arsenal,                n.bayernmunique,n.porto,n.liverpool,n.villareal,        n.lyon,n.inter,n.juventus,n.roma,n.sporting,n.atleticomadrid,n.realmadrid,n.panathinaikos,            n.bordeaux,n.werderbremen,n.shakhtardonetsk,n.om,n.aalborg,n.fiorentina,n.dinamokiev,n.zenit,                  n.cluj,n.anorthosis,n.basel,n.psv,n.celtic,n.steauabucuresti,n.fenerbahce,n.bate],
    2008.0: [n.manutd,n.chelsea,n.barcelona,n.liverpool,              n.roma,n.fenerbahce,n.schalke04,n.arsenal,              n.porto,n.celtic,n.realmadrid,n.lyon,n.milan,n.inter,n.sevilla,n.olympiacos,                          n.om,n.rosenborg,n.werderbremen,n.benfica,n.rangers,n.sporting,n.psv,n.slaviapraha,                           n.besiktas,n.valencia,n.lazio,n.shakhtardonetsk,n.stuttgart,n.dinamokiev,n.cska,n.steauabucuresti],
    2007.0: [n.milan,n.liverpool,n.chelsea,n.manutd,                  n.psv,n.bayernmunique,n.valencia,n.roma,                n.lyon,n.lille,n.celtic,n.realmadrid,n.porto,n.inter,n.arsenal,n.barcelona,                           n.werderbremen,n.spartakmoscou,n.bordeaux,n.shakhtardonetsk,n.steauabucuresti,n.benfica,n.cska,n.aek,          n.levskisofia,n.sporting,n.galatasaray,n.olympiacos,n.dinamokiev,n.copenhague,n.hamburgo,n.anderlecht],
    2006.0: [n.barcelona,n.arsenal,n.milan,n.villareal,                      n.benfica,n.juventus,n.lyon,n.inter,                    n.liverpool,n.chelsea,n.psv,n.bayernmunique,n.ajax,n.rangers,n.realmadrid,n.werderbremen,      n.brugge,n.thun,n.udinese,n.manutd,n.schalke04,n.rosenborg,n.realbetis,n.petrzalka,                 n.rapidwien,n.spartapraga,n.panathinaikos,n.lille,n.fenerbahce,n.olympiacos,n.anderlecht,n.porto],
    2005.0: [n.liverpool,n.milan,n.chelsea,n.psv,                            n.juventus,n.inter,n.bayernmunique,n.lyon,              n.manutd,n.porto,n.werderbremen,n.monaco,n.barcelona,n.arsenal,n.leverkusen,n.realmadrid,      n.olympiacos,n.dinamokiev,n.ajax,n.fenerbahce,n.panathinaikos,n.shakhtardonetsk,n.valencia,n.cska,             n.lacoruna,n.roma,n.maccabitelaviv,n.spartapraga,n.rosenborg,n.celtic,n.anderlecht,n.psg],
    2004.0: [n.porto,n.monaco,n.lacoruna,n.chelsea,                          n.lyon,n.realmadrid,n.milan,n.arsenal,                  n.celtavigo,n.bayernmunique,n.spartapraga,n.lokomotivMoscou,n.stuttgart,n.manutd,n.realsociedad,n.juventus, n.celtic,n.inter,n.psv,n.galatasaray,n.rangers,n.om,n.besiktas,n.brugge,                                    n.anderlecht,n.dinamokiev,n.aek,n.olympiacos,n.panathinaikos,n.partizan,n.lazio,n.ajax],
    2003.0: [n.milan,n.juventus,n.inter,n.realmadrid,                        n.ajax,n.barcelona,n.valencia,n.manutd,       n.newcastle,n.leverkusen,n.arsenal,n.roma,n.dortmund,n.lokomotivMoscou,n.lacoruna,n.basel,               n.auxerre,n.liverpool,n.aek,n.lyon,n.dinamokiev,n.maccabihaifa,n.lens,n.brugge,                               n.psv,n.spartakmoscou,n.genk,n.rosenborg,n.feyenoord,n.olympiacos,n.bayernmunique,n.galatasaray],
    2002.0: [n.realmadrid,n.leverkusen,n.barcelona,n.manutd,             n.bayernmunique,n.liverpool,n.panathinaikos,n.lacoruna, n.boavista,n.nantes,n.roma,n.galatasaray,n.spartapraga,n.porto,n.arsenal,n.juventus,               n.lokomotivMoscou,n.dortmund,n.mallorca,n.psv,n.celtic,n.lyon,n.lille,n.feyenoord,                            n.anderlecht,n.dinamokiev,n.schalke04,n.lazio,n.rosenborg,n.fenerbahce,n.olympiacos,n.spartakmoscou],
    2001.0: [n.bayernmunique,n.valencia,n.realmadrid,n.leeds,                n.manutd,n.arsenal,n.galatasaray,n.lacoruna,  n.sturmgraz,n.panathinaikos,n.milan,n.psg,n.lyon,n.spartakmoscou,n.anderlecht,n.lazio,                   n.leverkusen,n.shakhtardonetsk,n.olympiacos,n.rangers,n.hamburgo,n.rosenborg,n.psv,n.barcelona,                n.sporting,n.spartapraga,n.heerenveen,n.monaco,n.juventus,n.helsingborg,n.dinamokiev,n.besiktas],
    2000.0: [n.realmadrid,n.valencia,n.bayernmunique,n.barcelona,            n.manutd,n.porto,n.lazio,n.chelsea,           n.spartapraga,n.herthaberlim,n.fiorentina,n.bordeaux,n.dinamokiev,n.rosenborg,n.feyenoord,n.om,          n.leverkusen,n.arsenal,n.dortmund,n.sturmgraz,n.olympiacos,n.rangers,n.spartakmoscou,n.galatasaray, n.maribor,n.aik,n.boavista,n.dinamozagreb,n.molde,n.psv,n.willem,n.milan],
    1999.0: [n.manutd,n.bayernmunique,n.juventus,n.dinamokiev,           n.inter,n.olympiacos,n.kaiserslautern,n.realmadrid,     n.galatasaray,n.benfica,n.lens,n.dinamozagreb,n.arsenal,n.barcelona,n.spartakmoscou,n.rosenborg,   n.porto,n.psv,                     n.ajax,n.athleticbilbao,n.sturmgraz,n.brondby,n.panathinaikos,n.helsinki],
    1998.0: [n.realmadrid,n.juventus,n.dortmund,n.monaco,                    n.dinamokiev,n.bayernmunique,n.manutd,n.leverkusen,  n.psg,n.rosenborg,n.psv,n.parma,n.feyenoord,n.sporting,n.newcastle,n.besiktas,                    n.olympiacos,n.spartapraga,        n.galatasaray,n.kosice,n.barcelona,n.porto,n.ifkgoteborg,n.lierse],
    1997.0: [n.dortmund,n.juventus,n.manutd,n.ajax,                      n.porto,n.atleticomadrid,n.rosenborg,n.auxerre,            n.grasshoppers,n.rangers,n.widzewlodz,n.steauabucuresti,n.fenerbahce,n.rapidwien,n.milan,n.ifkgoteborg,                ],
    1996.0: [n.juventus,n.ajax,n.nantes,n.panathinaikos,                  n.spartakmoscou,n.realmadrid,n.legiawarszawa,n.dortmund,   n.porto,n.dinamokiev,n.rosenborg,n.blackburn,n.steauabucuresti,n.rangers,n.ferencvaros,n.grasshoppers,              ],
    1995.0: [n.ajax,n.milan,n.bayernmunique,n.psg,                        n.barcelona,n.ifkgoteborg,n.hajduksplit,n.benfica,         n.manutd,n.galatasaray,n.spartakmoscou,n.dinamokiev,n.steauabucuresti,n.anderlecht,n.rbsalzburg,n.aek,    ],
    1994.0: [n.milan,n.barcelona,n.monaco,n.porto,                        n.werderbremen,n.anderlecht,n.spartakmoscou,n.galatasaray, n.feyenoord,n.steauabucuresti,n.levskisofia,n.copenhague,n.spartapraga,n.manutd,n.lechpoznan,n.austria,        ],
    1993.0: [n.om,n.milan,n.rangers,n.ifkgoteborg,                        n.brugge,n.porto,n.cska,n.psv,                             n.lechpoznan,n.leeds,n.slovanbratislava,n.dinamobucuresti,n.austria,n.sion,n.aek,n.barcelona,                       ],
    1992.0: [n.barcelona,n.sampdoria,n.spartapraga,n.estrelavermelha,     n.benfica,n.anderlecht,n.dinamokiev,n.panathinaikos,       n.kaiserslautern,n.om,n.arsenal,n.brondby,n.ifkgoteborg,n.psv,n.apollonlimassol,n.honved,                                   ],
    1991.0: [n.estrelavermelha,n.om,n.bayernmunique,n.spartakmoscou,      n.porto,n.realmadrid,n.dynamodresden,n.milan,              n.cskasofia,n.dinamobucuresti,n.rangers,n.malmo,n.napoli,n.tirolinnsbruck,n.brugge,n.lechpoznan,                             ],
    1990.0: [n.milan,n.benfica,n.bayernmunique,n.om,                      n.mechelen,n.cskasofia,n.psv,n.dnipro,                     n.malmo,n.realmadrid,n.tirana,n.steauabucuresti,n.spartapraga,n.aek,n.honved,n.tirolinnsbruck,            ],
    1989.0: [n.milan,n.steauabucuresti,n.realmadrid,n.galatasaray,        n.werderbremen,n.ifkgoteborg,n.monaco,n.psv,               n.porto,n.gornikzabrze,n.celtic,n.estrelavermelha,n.tirana,n.spartakmoscou,n.brugge,n.neuchatel,                          ],
    1988.0: [n.psv,n.benfica,n.realmadrid,n.steauabucuresti,              n.bordeaux,n.anderlecht,n.bayernmunique,n.rangers,         n.neuchatel,n.porto,n.lillestrom,n.rapidwien,n.omonianicosia,n.gornikzabrze,n.aarhus,n.spartapraga,                       ],
    1987.0: [n.porto,n.bayernmunique,n.dinamokiev,n.realmadrid,           n.anderlecht,n.estrelavermelha,n.brondby,n.besiktas,       n.vitkovice,n.berliner,n.apoel,n.celtic,n.austria,n.steauabucuresti,n.rosenborg,n.juventus,                   ],
    1986.0: [n.steauabucuresti,n.barcelona,n.anderlecht,n.ifkgoteborg,    n.bayernmunique,n.aberdeen,n.juventus,n.kuusysi,           n.austria,n.omonianicosia,n.honved,n.zenit,n.servette,n.fenerbahce,n.porto,n.hellasverona,                           ],
    1985.0: [n.juventus,n.liverpool,n.bordeaux,n.panathinaikos,        n.dnipro,n.ifkgoteborg,n.austria,n.spartapraga,               n.grasshoppers,n.lyngby,n.dinamobucuresti,n.levskisofia,n.berliner,n.benfica,n.beveren,n.linfield,                 ],
    1984.0: [n.liverpool,n.roma,n.dinamobucuresti,n.dundee,            n.dinamominsk,n.rapidwien,n.berliner,n.benfica,              n.athleticbilbao,n.olympiacos,n.gyori,n.hamburgo,n.bohemians,n.standardliege,n.cskasofia,n.partizan,          ],
    1983.0: [n.hamburgo,n.juventus,n.realsociedad,n.widzewlodz,            n.sporting,n.liverpool,n.astonvilla,n.dinamokiev,             n.cskasofia,n.celtic,n.tirana,n.olympiacos,n.dinamobucuresti,n.standardliege,n.rapidwien,n.helsinki,         ],
    1982.0: [n.astonvilla,n.bayernmunique,n.anderlecht,n.newsaints,    n.estrelavermelha,n.liverpool,n.craiova,n.dinamokiev,         n.austria,n.berliner,n.juventus,n.zalgiris,n.az,n.glentoran,n.copenhague,n.benfica,                    ],
    1981.0: [n.liverpool,n.realmadrid,n.inter,n.bayernmunique,         n.banikostrava,n.estrelavermelha,n.spartakmoscou,n.dinamotbilisi,   n.aberdeen,n.szombierkibytom,n.ajax,n.berliner,n.esbjerg,n.honved,n.nantes,n.basel,                                ],
    1980.0: [n.nottinghamforest,n.hamburgo,n.realmadrid,n.ajax,        n.celtic,n.hajduksplit,n.strasbourg,n.berliner,               n.argespitesti,n.servette,n.dukla,n.omonianicosia,n.dundalk,n.porto,n.dinamotbilisi,n.vejle,                                    ],
    1979.0: [n.nottinghamforest,n.malmo,n.koln,n.austria,              n.rangers,n.wislakrakow,n.dynamodresden,n.grasshoppers,             n.aek,n.realmadrid,n.loksofia,n.psv,n.lillestrom,n.bohemian,n.brno,n.dinamokiev,                              ],
    1978.0: [n.liverpool,n.brugge,n.moenchengladbach,n.juventus,       n.ajax,n.atleticomadrid,n.benfica,n.innsbruck,                n.celtic,n.estrelavermelha,n.glentoran,n.levskisofia,n.panathinaikos,n.dynamodresden,n.nantes,n.b1903,             ],
    1977.0: [n.liverpool,n.moenchengladbach,n.zurich,n.dinamokiev,     n.brugge,n.saintetienne,n.dynamodresden,n.bayernmunique,      n.torino,n.psv,n.realmadrid,n.turku,n.banikostrava,n.ferencvaros,n.trabzonspor,n.paok,                        ],
    1976.0: [n.bayernmunique,n.saintetienne,n.realmadrid,n.psv,        n.benfica,n.dinamokiev,n.moenchengladbach,n.hajduksplit,      n.akraness,n.derbycount,n.juventus,n.molenbeek,n.malmo,n.rangers,n.ruchchorzow,n.ujpest,                      ],
    1975.0: [n.bayernmunique,n.leeds,n.saintetienne,n.barcelona,       n.atvidabergs,n.anderlecht,n.ruchchorzow,n.araratyerevan,           n.feyenoord,n.hajduksplit,n.magdeburg,n.helsinki,n.corkcity,n.olympiacos,n.ujpest,n.fenerbahce,                   ],
    1974.0: [n.bayernmunique,n.atleticomadrid,n.ujpest,n.celtic,       n.basel,n.cskasofia,n.estrelavermelha,n.trnava,               n.liverpool,n.zoryaluhansk,n.vejle,n.brugge,n.dinamobucuresti,n.dynamodresden,n.ajax,n.benfica,                      ],
    1973.0: [n.ajax,n.juventus,n.realmadrid,n.derbycount,              n.trnava,n.dinamokiev,n.bayernmunique,n.ujpest,               n.omonianicosia,n.celtic,n.anderlecht,n.gornikzabrze,n.magdeburg,n.argespitesti,n.benfica,n.cskasofia,                          ],
    1972.0: [n.ajax,n.inter,n.benfica,n.celtic,                        n.ujpest,n.standardliege,n.arsenal,n.feyenoord,               n.dinamobucuresti,n.cska,n.valencia,n.grasshoppers,n.sliemawanderers,n.om,n.cskasofia,n.moenchengladbach,              ],
    1971.0: [n.ajax,n.panathinaikos,n.atleticomadrid,n.estrelavermelha, n.everton,n.legiawarszawa,n.celtic,n.carlzeissjena,          n.sporting,n.moenchengladbach,n.cagliari,n.standardliege,n.basel,n.waterford,n.slovanbratislava,n.arad,       ],
    1970.0: [n.feyenoord,n.celtic,n.legiawarszawa,n.leeds,             n.fiorentina,n.galatasaray,n.vorwarts,n.standardliege,        n.dinamokiev,n.benfica,n.ferencvaros,n.trnava,n.saintetienne,n.milan,n.estrelavermelha,n.realmadrid,          ],
    1969.0: [n.milan,n.ajax,n.manutd,n.trnava,               n.benfica,n.celtic,n.aek,n.rapidwien,                        n.anderlecht,n.estrelavermelha,n.fenerbahce,n.realmadrid,n.ab,n.lahti,                                                ],
    1968.0: [n.manutd,n.benfica,n.realmadrid,n.juventus,     n.braunschweiger,n.gornikzabrze,n.vasas,n.spartapraga,     n.sarajevo,n.rapidwien,n.hvidovre,n.valur,n.saintetienne,n.dinamokiev,n.rapidbucuresti,n.anderlecht,         ],
    1967.0: [n.celtic,n.inter,n.dukla,n.cskasofia,                     n.realmadrid,n.linfield,n.ajax,n.vojvodina,                   n.valerenga,n.atleticomadrid,n.vasas,n.anderlecht,n.munich1860,n.gornikzabrze,n.nantes,n.liverpool,                ],
    1966.0: [n.realmadrid,n.partizan,n.inter,n.manutd,       n.benfica,n.anderlecht,n.ferencvaros,n.spartapraga,           n.werderbremen,n.panathinaikos,n.levskisofia,n.kilmarnock,n.vorwarts,n.derrycity,n.gornikzabrze,n.dinamobucuresti,           ],
    1965.0: [n.inter,n.benfica,n.liverpool,n.gyori,                    n.koln,n.rangers,n.dws,n.realmadrid,                       n.lyn,n.chauxdefonds,n.dinamobucuresti,n.panathinaikos,n.loksofia,n.dukla,n.rapidwien,n.anderlecht,          ],
    1964.0: [n.inter,n.realmadrid,n.dortmund,n.zurich,                 n.milan,n.partizan,n.psv,n.dukla,                             n.benfica,n.gornikzabrze,n.dinamobucuresti,n.galatasaray,n.monaco,n.norrkoping,n.spartakplovdiv,n.jeunesseesch,            ],
    1963.0: [n.milan,n.benfica,n.dundee,n.feyenoord,                   n.galatasaray,n.reims,n.dukla,n.anderlecht,                   n.austria,n.sporting,n.norrkoping,n.cskasofia,n.esbjerg,n.ipswich,n.vasas,n.poloniabytom,                 ],
    1962.0: [n.benfica,n.realmadrid,n.tottenham,n.standardliege,       n.nurnberg,n.rangers,n.juventus,n.dukla,                      n.fenerbahce,n.austria,n.feyenoord,n.servette,n.partizan,n.vorwarts,n.b1903,n.haka,                           ],
    1961.0: [n.benfica,n.barcelona,n.rapidwien,n.hamburgo,            n.aarhus,n.hradec,n.burnley,n.malmo,                          n.youngboys,n.panathinaikos,n.ujpest,n.realmadrid,n.reims,n.cskasofia,n.fredrikstad,n.erzgebirgeaue,          ],
    1960.0: [n.realmadrid,n.eintrachtfrankfurt,n.barcelona,n.rangers,  n.nice,n.wiener,n.wolves,n.spartarotterdam,                   n.jeunesseesch,n.ifkgoteborg,n.milan,n.estrelavermelha,n.fenerbahce,n.b1909,n.interbratislava,n.youngboys,    ],
    1959.0: [n.realmadrid,n.reims,n.atleticomadrid,n.youngboys,        n.standardliege,n.wiener,n.erzgebirgeaue,n.schalke04,         n.sporting,n.dukla,n.cskasofia,n.ifkgoteborg,n.wolves,n.besiktas,n.helsinki,n.mtk,                            ],
    1958.0: [n.realmadrid,n.milan,n.vasas,n.manutd,          n.estrelavermelha,n.sevilla,n.ajax,n.dortmund,                n.royalAntwerp,n.norrkoping,n.erzgebirgeaue,n.youngboys,n.steauabucuresti,n.aarhus,n.rangers,                     ],
    1957.0: [n.realmadrid,n.fiorentina,n.manutd,n.estrelavermelha, n.nice,n.grasshoppers,n.athleticbilbao,n.cskasofia,     n.dortmund,n.rapidwien,n.dinamobucuresti,n.slovanbratislava,n.rangers,n.norrkoping,n.honved,n.rapidjc,       ],
    1956.0: [n.realmadrid,n.reims,n.hibernian,n.milan,                 n.partizan,n.mtk,n.rapidwien,n.djurgardens,                    n.sporting,n.anderlecht,n.servette,n.rotweissessen,n.psv,n.aarhus,n.saarbrucken,n.gwardiawarsaw,                    ],
  },

  leagueName.libertadores : {
    //2024.0: [],
    //2023.0: [n.flamengo,n.palmeiras,n.bocajuniors,n.riverplate,       n.atleticomg,n.idelvalle,n.atleticopr,n.racing,n.bolivar,n.atleticonacional,n.argentinojuniors,n.pereira,n.internacional,n.nacional,n.olimpia,        n.imedellin,n.sportingcristal,n.corinthians,n.libertad,n.colocolo,n.nublense,n.barcelonaequ,          n.thestrongest,n.monagas,n.melgar,n.aucas,n.alianzalima,n.liverpoolURU,n.cerroporteno,n.metropolitanos,],
    2022.0: [n.flamengo,n.atleticopr,n.velez,n.palmeiras,             n.atleticomg,n.estudiantes,n.talleres,n.corinthians,             n.riverplate,n.cerroporteno,n.bocajuniors,n.fortaleza,n.colon,n.tolima,n.libertad,n.emelec,                  n.olimpia,n.deportivocali,n.idelvalle,n.nacional,n.colocolo,n.tachira,n.thestrongest,n.univcatolica,    n.caracas,n.bragantino,n.penarol,n.alwaysready,n.sportingcristal,n.americamg,n.alianzalima,n.indPetrolero],
    2021.0: [n.palmeiras,n.flamengo,n.atleticomg,n.barcelonaequ,      n.saopaulo,n.olimpia,n.riverplate,n.fluminense,                  n.cerroporteno,n.bocajuniors,n.racing,n.velez,n.univcatolica,n.defensayjusticia,n.argentinojuniors,n.internacional,  n.idelvalle,n.tachira,n.santos,n.junior,n.sportingcristal,n.nacional,n.ldu,n.americadecali,        n.universitario,n.alwaysready,n.thestrongest,n.santafe,n.rentistas,n.atleticonacional,n.lacalera,n.laguaira],
    2020.0: [n.palmeiras,n.santos,n.riverplate,n.bocajuniors,         n.libertad,n.gremio,n.nacional,n.racing,                         n.ldu,n.atleticopr,n.flamengo,n.delfin,n.idelvalle,n.jorge,n.guaraniPAR,n.internacional,                     n.junior,n.bolivar,n.penarol,n.saopaulo,n.univcatolica,n.estudiantesmerida,n.defensayjusticia,n.caracas,        n.barcelonaequ,n.tigre,n.colocolo,n.binacional,n.americadecali,n.alianzalima,n.olimpia,n.imedellin],
    2019.0: [n.flamengo,n.riverplate,n.gremio,n.bocajuniors,          n.palmeiras,n.ldu,n.internacional,n.cerroporteno,                n.cruzeiro,n.olimpia,n.godoycruz,n.sanlorenzo,n.nacional,n.atleticopr,n.emelec,n.libertad,                   n.palestino,n.deplara,n.sportingcristal,n.penarol,n.atleticomg,n.melgar,n.tolima,n.univcatolica,     n.alianzalima,n.huracan,n.concepcion,n.sanJoseBOL,n.zamora,n.junior,n.jorge,n.rosario],
    2018.0: [n.riverplate,n.bocajuniors,n.gremio,n.palmeiras,         n.atleticotucuman,n.independiente,n.cruzeiro,n.colocolo,         n.estudiantes,n.libertad,n.corinthians,n.flamengo,n.racing,n.atleticonacional,n.cerroporteno,n.santos,       n.defensor,n.bolivar,n.penarol,n.santafe,n.vasco,n.nacional,n.millonarios,n.junior,                  n.monagas,n.delfin,n.thestrongest,n.emelec,n.lau,n.cusco,n.deplara,n.alianzalima],
    2017.0: [n.gremio,n.lanus,n.barcelonaequ,n.riverplate,            n.sanlorenzo,n.santos,n.botafogo,n.jorge,                        n.godoycruz,n.guaraniPAR,n.atleticopr,n.atleticomg,n.palmeiras,n.thestrongest,n.emelec,n.nacional,           n.estudiantes,n.santafe,n.imedellin,n.flamengo,n.atleticotucuman,n.libertad,n.chapecoense,n.iquique,  n.atleticonacional,n.sportingcristal,n.melgar,n.univcatolica,n.penarol,n.sportboys,n.zulia,n.zamora],
    2016.0: [n.atleticonacional,n.idelvalle,n.saopaulo,n.bocajuniors, n.atleticomg,n.nacional,n.rosario,n.pumas,                n.huracan,n.tachira,n.racing,n.gremio,n.corinthians,n.riverplate,n.cerroporteno,n.toluca,           n.thestrongest,n.palmeiras,n.bolivar,n.penarol,n.colocolo,n.sanlorenzo,n.olimpia,n.santafe,          n.trujillanos,n.riverURU,n.deportivocali,n.sportingcristal,n.melgar,n.ldu,n.emelec,n.cobresal],
    2015.0: [n.riverplate,n.tigres,n.guaraniPAR,n.internacional,      n.emelec,n.santafe,n.racing,n.cruzeiro,                          n.sucre,n.estudiantes,n.corinthians,n.saopaulo,n.atleticomg,n.montwanderers,n.bocajuniors,n.atleticonacional,    n.colocolo,n.sanlorenzo,n.huracan,n.thestrongest,n.palestino,n.juanaurich,n.libertad,n.sportingcristal,   n.atlas,n.danubio,n.mineros,n.lau,n.zamora,n.sanJoseBOL,n.barcelonaequ,n.tachira],
    2014.0: [n.sanlorenzo,n.nacionalPAR,n.bolivar,n.defensor,         n.arsenalsarandi,n.cruzeiro,n.lanus,n.atleticonacional,          n.santoslaguna,n.leon,n.cerroporteno,n.thestrongest,n.velez,n.gremio,n.atleticomg,n.unionespanola,  n.atleticopr,n.idelvalle,n.deportivocali,n.zamora,n.lau,n.newells,n.flamengo,n.penarol,          n.universitario,n.botafogo,n.ohiggins,n.santafe,n.cusco,n.nacional,n.emelec,n.anzoategui],
    2013.0: [n.atleticomg,n.olimpia,n.newells,n.santafe,              n.cusco,n.fluminense,n.bocajuniors,n.tijuana,                n.velez,n.nacional,n.tigre,n.palmeiras,n.gremio,n.corinthians,n.saopaulo,n.emelec,                  n.toluca,n.libertad,n.arsenalsarandi,n.penarol,n.sanJoseBOL,n.tolima,n.lau,n.huachipato,             n.barcelonaequ,n.sportingcristal,n.thestrongest,n.iquique,n.millonarios,n.cerroporteno,n.deplara,n.caracas],
    2012.0: [n.corinthians,n.bocajuniors,n.santos,n.lau,              n.libertad,n.vasco,n.fluminense,n.velez,                n.bolivar,n.internacional,n.atleticonacional,n.cruzazul,n.unionespanola,n.emelec,n.lanus,n.depquito,         n.thestrongest,n.flamengo,n.junior,n.arsenalsarandi,n.nacional,n.nacionalPAR,n.defensor,n.godoycruz, n.juanaurich,n.olimpia,n.univcatolica,n.zamora,n.alianzalima,n.tachira,n.chivas,n.penarol],
    2011.0: [n.santos,n.penarol,n.cerroporteno,n.velez,      n.univcatolica,n.oncecaldas,n.libertad,n.jaguares,               n.gremio,n.ldu,n.estudiantes,n.junior,n.cruzeiro,n.americamex,n.internacional,n.fluminense,                  n.unisanmartin,n.orientepetrolero,n.nacional,n.caracas,n.colocolo,n.emelec,n.tolima,n.independiente, n.sanluis,n.leonhuanuco,n.argentinojuniors,n.unionespanola,n.tachira,n.jorge,n.guaraniPAR,n.godoycruz],
    2010.0: [n.internacional,n.chivas,n.saopaulo,n.lau,    n.libertad,n.flamengo,n.cruzeiro,n.estudiantes,                  n.sanluis,n.velez,n.universitario,n.banfield,n.corinthians,n.nacional,n.alianzalima,n.oncecaldas,   n.imedellin,n.monterrey,n.juanaurich,n.lanus,n.cerrouru,n.morelia,n.colocolo,n.univcatolica,         n.cerroporteno,n.nacionalPAR,n.bolivar,n.blooming,n.emelec,n.depcuenca,n.depitalia,n.caracas],
    2009.0: [n.estudiantes,n.cruzeiro,n.nacional,n.gremio,            n.caracas,n.saopaulo,n.defensor,n.palmeiras,                      n.sport,n.unisanmartin,n.depcuenca,n.libertad,n.lau,n.sanluis,n.chivas,n.bocajuniors,             n.colocolo,n.tachira,n.riverplate,n.imedellin,n.depquito,n.evertonchi,n.boyaca,n.universitario,  n.ldu,n.guaraniPAR,n.nacionalPAR,n.americadecali,n.sucre,n.lanus,n.aurora,n.sanlorenzo],
    2008.0: [n.ldu,n.fluminense,n.americamex,n.bocajuniors,           n.sanlorenzo,n.saopaulo,n.santos,n.atlas,                        n.lanus,n.estudiantes,n.cruzeiro,n.riverplate,n.flamengo,n.atleticonacional,n.nacional,n.cucuta,             n.caracas,n.depcuenca,n.colocolo,n.cienciano,n.univcatolica,n.chivas,n.luqueno,n.arsenalsarandi, n.realpotosi,n.danubio,n.maracaibo,n.coronel,n.unisanmartin,n.sanJoseBOL,n.audaxitaliano,n.libertad],
    2007.0: [n.bocajuniors,n.gremio,n.cucuta,n.santos,                n.nacional,n.defensor,n.americamex,n.libertad,                   n.caracas,n.colocolo,n.saopaulo,n.velez,n.flamengo,n.parana,n.necaxa,n.toluca,                      n.banfield,n.audaxitaliano,n.tolima,n.internacional,n.realpotosi,n.ldu,n.cienciano,n.gimnasia,               n.elnacional,n.alianzalima,n.cerroporteno,n.emelec,n.maracaibo,n.riverplate,n.bolivar,n.deppasto],
    2006.0: [n.internacional,n.saopaulo,n.libertad,n.chivas, n.velez,n.ldu,n.estudiantes,n.riverplate,             n.goias,n.atleticonacional,n.palmeiras,n.corinthians,n.santafe,n.nacional,n.newells,n.tigres,                n.caracas,n.sportingcristal,n.unionespanola,n.univcatolica,n.rocha,n.maracaibo,n.cerroporteno,n.elnacional,   n.cienciano,n.bolivar,n.thestrongest,n.deportivocali,n.universitario,n.pumas,n.rosario,n.paulista],
    2005.0: [n.saopaulo,n.atleticopr,n.riverplate,n.chivas,  n.santos,n.tigres,n.banfield,n.bocajuniors,                    n.cerroporteno,n.lau,n.pachuca,n.junior,n.palmeiras,n.oncecaldas,n.imedellin,n.ldu,                          n.americadecali,n.danubio,n.quilmes,n.santoandre,n.olmedo,n.alianzalima,n.cobreloa,n.sportingcristal,  n.libertad,n.bolivar,n.thestrongest,n.tachira,n.nacional,n.caracas,n.sanlorenzo,n.depcuenca],
    2004.0: [n.oncecaldas,n.bocajuniors,n.saopaulo,n.riverplate,     n.santos,n.tachira,n.deportivocali,n.saocaetano,         n.americamex,n.sportingcristal,n.santoslaguna,n.cruzeiro,n.rosario,n.nacional,n.ldu,n.barcelonaequ,   n.penarol,n.velez,n.caracas,n.alianzalima,n.cienciano,n.tolima,n.guaraniPAR,n.bolivar,       n.thestrongest,n.fenix,n.concepcion,n.cobreloa,n.elnacional,n.libertad,n.jorge,n.colocolo],
    2003.0: [n.bocajuniors,n.santos,n.americadecali,n.imedellin,     n.riverplate,n.cobreloa,n.cruzazul,n.gremio,                      n.pumas,n.paysandu,n.corinthians,n.racing,n.deportivocali,n.nacional,n.olimpia,n.cerroporteno,               n.libertad,n.sportingcristal,n.elnacional,n.gimnasia,n.bolivar,n.universitario,n.barcelonaequ,n.fenix,  n.emelec,n.univcatolica,n.octubre12,n.alianzalima,n.penarol,n.orientepetrolero,n.colocolo,n.thestrongest],
    2002.0: [n.olimpia,n.saocaetano,n.gremio,n.americamex,           n.bocajuniors,n.penarol,n.nacional,n.morelia,                     n.elnacional,n.cobreloa,n.riverplate,n.americadecali,n.montwanderers,n.univcatolica,n.olmedo,n.cienciano,        n.cerroporteno,n.octubre12,n.sanlorenzo,n.bolivar,n.velez,n.santiagowanderers,n.talleres,n.oncecaldas,   n.alianzalima,n.orientepetrolero,n.realpotosi,n.atleticopr,n.sportingcristal,n.emelec,n.cortulua,n.flamengo],
    2001.0: [n.bocajuniors,n.cruzazul,n.palmeiras,n.rosario,  n.americadecali,n.riverplate,n.vasco,n.cruzeiro,                  n.emelec,n.cerroporteno,n.cobreloa,n.nacional,n.concepcion,n.junior,n.saocaetano,n.elnacional,               n.velez,n.lau,n.sanlorenzo,n.olimpia,n.guaraniPAR,n.penarol,n.defensor,n.deportivocali,       n.universitario,n.sportboys,n.jorge,n.sportingcristal,n.thestrongest,n.tachira,n.olmedo,n.orientepetrolero],
    2000.0: [n.bocajuniors,n.palmeiras,n.americamex,n.corinthians,   n.riverplate,n.bolivar,n.atlas,n.atleticomg,                      n.cerroporteno,n.elnacional,n.americadecali,n.nacional,n.atleticopr,n.rosario,n.junior,n.penarol,     n.alianzalima,n.blooming,n.olimpia,n.lau,n.sanlorenzo,n.sportingcristal,n.juventude,n.bellavista,      n.emelec,n.univcatolica,n.ldu,n.atleticonacional,n.universitario,n.colegiales,n.thestrongest,n.cobreloa],
    1999.0: [n.palmeiras,n.deportivocali,n.riverplate,n.cerroporteno, n.corinthians,n.bellavista,n.estudiantesmerida,n.velez, n.colocolo,n.univcatolica,n.emelec,n.nacional,n.ldu,n.universitario,n.vasco,n.jorge,                         n.monterrey,n.oncecaldas,n.olimpia,n.sportingcristal,n.blooming],
    1998.0: [n.vasco,n.barcelonaequ,n.riverplate,n.cerroporteno,     n.bolivar,n.colon,n.penarol,n.gremio,                             n.nacional,n.cruzeiro,n.americamex,n.olimpia,n.bucaramanga,n.colocolo,n.alianzalima,n.americadecali,         n.depquito,n.chivas,n.univcatolica,n.orientepetrolero,n.sportingcristal],
    1997.0: [n.cruzeiro,n.sportingcristal,n.colocolo,n.racing,       n.univcatolica,n.bolivar,n.penarol,n.gremio,                      n.riverplate,n.millonarios,n.minerven,n.velez,n.elnacional,n.guaraniPAR,n.orientepetrolero,n.nacional,  n.cerroporteno,n.emelec,n.mineros,n.alianzalima,n.deportivocali],
    1996.0: [n.riverplate,n.americadecali,n.lau,n.gremio,            n.sanlorenzo,n.junior,n.barcelonaequ,n.corinthians,               n.botafogo,n.espoli,n.cerroporteno,n.minerven,n.defensor,n.sanJoseBOL,n.penarol,n.sportingcristal,           n.olimpia,n.universitario,n.guabira,n.univcatolica,n.caracas],
    1995.0: [n.gremio,n.atleticonacional,n.emelec,n.riverplate,      n.palmeiras,n.millonarios,n.velez,n.sportingcristal,     n.cerroporteno,n.caracas,n.olimpia,n.bolivar,n.penarol,n.alianzalima,n.univcatolica,n.independiente,         n.cerrouru,n.trujillanos,n.univcatolica,n.elnacional,n.jorge],
    1994.0: [n.velez,n.saopaulo,n.junior,n.olimpia,         n.minerven,n.bolivar,n.imedellin,n.unionespanola,                 n.universitario,n.colocolo,n.emelec,n.defensor,n.barcelonaequ,n.thestrongest,n.palmeiras,n.cruzeiro,         n.cerroporteno,n.bocajuniors,n.alianzalima,n.nacional,n.maritimoven],
    1993.0: [n.saopaulo,n.univcatolica,n.americadecali,n.cerroporteno, n.flamengo,n.barcelonaequ,n.olimpia,n.sportingcristal,          n.newells,n.universitario,n.elnacional,n.bolivar,n.cobreloa,n.nacional,n.minerven,n.atleticonacional,        n.minerven,n.sanJoseBOL,n.bellavista,n.internacional,n.riverplate],
    1992.0: [n.saopaulo,n.newells,n.barcelonaequ,n.americadecali,    n.sanlorenzo,n.atleticonacional,n.cerroporteno,n.criciuma,        n.defensor,n.valdez,n.maritimoven,n.univcatolica,n.nacional,n.sportingcristal,n.colocolo,n.bolivar,          n.soldeamerica,n.sportboys,n.ula,n.sanJoseBOL,n.coquimbo],
    1991.0: [n.colocolo,n.olimpia,n.bocajuniors,n.atleticonacional,  n.flamengo,n.cerroporteno,n.americadecali,n.nacional,             n.concepcion,n.ldu,n.orientepetrolero,n.colegiales,n.universitario,n.bolivar,n.tachira,n.corinthians, n.riverplate,n.barcelonaequ,n.bellavista,n.sportboys,n.maritimoven],
    1990.0: [n.olimpia,n.barcelonaequ,n.atleticonacional,n.riverplate, n.emelec,n.vasco,n.independiente,n.univcatolica,                n.progreso,n.unionhuaral,n.margarita,n.defensor,n.thestrongest,n.cerroporteno,n.colocolo,n.pepeganga,        n.orientepetrolero,n.mineros,n.sportingcristal,n.gremio],
    1989.0: [n.atleticonacional,n.olimpia,n.danubio,n.internacional, n.millonarios,n.bahia,n.cobreloa,n.soldeamerica,                  n.bocajuniors,n.tachira,n.penarol,n.universitario,n.depquito,n.nacional,n.racing,n.bolivar,         n.colocolo,n.maritimoven,n.emelec,n.sportingcristal,n.thestrongest],
    1988.0: [n.nacional,n.newells,n.americadecali,n.sanlorenzo,      n.orientepetrolero,n.penarol,                                        n.univcatolica,n.universitario,n.guarani,n.bolivar,n.colocolo,       n.maritimoven,n.barcelonaequ,n.millonarios,n.cerroporteno,n.sport,    n.tachira,n.filanbanco,n.montwanderers,n.olimpia,n.alianzalima],
    1987.0: [n.penarol,n.americadecali,n.riverplate,n.cobreloa,      n.independiente,n.barcelonaequ,           n.deportivocali,n.rosario,n.colocolo,n.elnacional,n.alianzalima,     n.tachira,n.thestrongest,n.guarani,n.elnacional,n.progreso,      n.estudiantesmerida,n.orientepetrolero,n.saopaulo,n.soldeamerica,n.sanagustin],
    1986.0: [n.riverplate,n.americadecali,n.argentinojuniors,n.olimpia, n.barcelonaequ,n.bolivar,              n.montwanderers,n.jorge,n.coritiba,n.deportivocali,n.nacionalPAR,               n.bocajuniors,n.universitario,n.depquito,n.cobresal,             n.penarol,n.cajamarca,n.bangu,n.univcatolica],
    1985.0: [n.argentinojuniors,n.americadecali,n.independiente,n.elnacional,  n.blooming,n.penarol,           n.ferro,n.orientepetrolero,n.cerroporteno,n.colocolo,n.universitario,       n.fluminense,n.tachira,n.millonarios,n.magallanes,n.octubre9,   n.vasco,n.depitalia,n.guaraniPAR,n.bellavista,n.sportboys],
    1984.0: [n.independiente,n.gremio,n.nacional,n.flamengo,         n.univcatolica,n.ula,                     n.olimpia,n.blooming,n.americadecali,n.elnacional,n.sportingcristal,                    n.luqueno,n.bolivar,n.junior,n.danubio,n.portuguesaven,                      n.estudiantes,n.ohiggins,n.santos,n.octubre9,n.melgar],
    1983.0: [n.gremio,n.penarol,n.estudiantes,n.nacional,            n.americadecali,n.sancristobal,           n.cobreloa,n.flamengo,n.tolima,n.elnacional,n.montwanderers,                    n.colocolo,n.bolivar,n.universitario,n.barcelonaequ,n.nacionalPAR,           n.ferro,n.blooming,n.alianzalima,n.tachira,n.olimpia],
    1982.0: [n.penarol,n.cobreloa,n.flamengo,n.olimpia,              n.riverplate,n.tolima,                    n.thestrongest,n.saopaulo,n.atleticonacional,n.colocolo,n.melgar,  n.bocajuniors,n.gremio,n.estudiantesmerida,n.ldu,n.soldeamerica,                           n.jorge,n.defensor,n.tachira,n.barcelonaequ,n.depmunicipal],
    1981.0: [n.flamengo,n.cobreloa,n.deportivocali,n.nacional,       n.jorge,n.penarol,                        n.riverplate,n.bellavista,n.atleticomg,n.jorge,n.sportingcristal,  n.rosario,n.estudiantesmerida,n.cerroporteno,n.barcelonaequ,n.lau,                  n.junior,n.portuguesaven,n.olimpia,n.tecnicoUniv,n.atltorino],
    1980.0: [n.nacional,n.internacional,n.olimpia,n.americadecali,   n.ohiggins,n.velez,              n.riverplate,n.thestrongest,n.vasco,n.uniequ,n.cerroporteno,       n.sportingcristal,n.defensor,n.depgalicia,n.santafe,n.colocolo,                 n.chalaco,n.orientepetrolero,n.tachira,n.emelec,n.soldeamerica],
    1979.0: [n.olimpia,n.bocajuniors,n.guarani,n.independiente,      n.palestino,n.penarol,                    n.deportivocali,n.bolivar,n.universitario,n.ohiggins,n.nacional,   n.millonarios,n.soldeamerica,n.palmeiras,n.portuguesaven,n.elnacional,          n.quilmes,n.jorge,n.alianzalima,n.depgalicia,n.tecnicoUniv],
    1978.0: [n.bocajuniors,n.deportivocali,n.riverplate,n.cerroporteno,  n.atleticomg,n.alianzalima,           n.independiente,n.sportingcristal,n.unionespanola,n.penarol,n.portuguesaven,    n.ldu,n.thestrongest,n.saopaulo,n.junior,n.estudiantesmerida,                 n.elnacional,n.orientepetrolero,n.palestino,n.danubio,n.libertad],
    1977.0: [n.bocajuniors,n.cruzeiro,n.deportivocali,n.internacional, n.libertad,n.portuguesaven,             n.riverplate,n.bolivar,n.elnacional,n.lau,n.unionhuaral,           n.defensor,n.orientepetrolero,n.corinthians,n.evertonchi,n.estudiantesmerida,              n.penarol,n.atleticonacional,n.depcuenca,n.olimpia,n.sportboys],
    1976.0: [n.cruzeiro,n.riverplate,n.ldu,n.independiente,          n.alianzalima,n.penarol,                  n.estudiantes,n.depcuenca,n.internacional,n.millonarios,n.unionespanola,   n.portuguesaven,n.bolivar,n.olimpia,n.ugarte,n.palestino,n.depgalicia,n.guabira,n.luqueno,n.santafe,n.nacional],
    1975.0: [n.independiente,n.unionespanola,n.rosario,n.universitario, n.cruzeiro,n.ldu,               n.newells,n.huachipato,n.deportivocali,n.portuguesaven,n.penarol,  n.olimpia,n.thestrongest,n.atleticonacional,n.depgalicia,n.montwanderers,           n.cerroporteno,n.jorge,n.vasco,n.elnacional,n.unionhuaral],
    1974.0: [n.independiente,n.saopaulo,n.millonarios,n.penarol,     n.huracan,n.defensorlima,                 n.rosario,n.palmeiras,n.atleticonacional,n.elnacional,n.cerroporteno,   n.unionespanola,n.depmunicipal,n.portuguesaven,n.uniequ,n.olimpia,   n.colocolo,n.jorge,n.valenciaven,n.sportingcristal,n.nacional],
    1973.0: [n.independiente,n.colocolo,n.sanlorenzo,n.cerroporteno,  n.botafogo,n.millonarios,                n.jorge,n.palmeiras,n.emelec,n.deportivocali,n.olimpia,            n.riverplate,n.nacional,n.elnacional,n.sportingcristal,                             n.orientepetrolero,n.penarol,n.unionespanola,n.universitario],
    1972.0: [n.independiente,n.universitario,n.nacional,n.saopaulo,   n.penarol,n.barcelonaequ,                n.rosario,n.americaquito,n.olimpia,n.lau,n.depitalia,       n.santafe,n.orientepetrolero,n.cerroporteno,n.alianzalima,n.valenciaven,        n.atleticonacional,n.chaco,n.atleticomg,n.sanfelipe,],
    1971.0: [n.nacional,n.estudiantes,n.palmeiras,n.barcelonaequ,     n.unionespanola,n.universitario,         n.rosario,n.penarol,n.fluminense,n.cerroporteno,n.emelec,   n.bocajuniors,n.chaco,n.depitalia,n.colocolo,n.deportivocali,                   n.sportingcristal,n.thestrongest,n.depgalicia,n.guaraniPAR,n.junior],
    1970.0: [n.estudiantes,n.penarol,n.riverplate,n.lau,             n.bocajuniors,n.guaraniPAR,n.nacional,n.universitario,n.ldu,            n.bolivar,n.valenciaven,n.deportivocali,n.arica,       n.sucre,n.depitalia,n.olimpia,n.americaquito,   n.americadecali,n.rangersCHI],
    1969.0: [n.estudiantes,n.nacional,n.univcatolica,n.penarol,       n.cerroporteno,n.deportivocali,n.olimpia,n.depitalia,n.santiagowanderers,     n.uMagdalena,n.sportingcristal,n.bolivar,n.depquito,       n.uCanarias,n.juanaurich,n.litoral,n.barcelonaequ],
    1968.0: [n.estudiantes,n.palmeiras,n.racing,n.penarol,            n.independiente,n.sportingcristal,n.guaraniPAR,    n.universitario,n.emelec,n.univcatolica,n.portugues,       n.elnacional,n.nacional,n.nautico,     n.lau,n.libertad,n.depgalicia],
    1967.0: [n.racing,n.nacional,n.universitario,n.cruzeiro,          n.riverplate,n.penarol,n.colocolo,             n.sportboys,n.santafe,n.univcatolica,             n.depgalicia,n.bolivar,n.guaraniPAR,    n.depitalia,n.imedellin,n.emelec,n.barcelonaequ,n.cerroporteno,n.octubre31],
    1966.0: [n.penarol,n.riverplate,n.univcatolica,n.independiente,   n.nacional,n.bocajuniors,n.guaraniPAR,n.olimpia,    n.universitario,n.jorge,n.depitalia,n.lau,n.depmunicipal,   n.alianzalima,n.emelec,n.laraFC,n.octubre9],
    1965.0: [n.independiente,n.penarol,n.bocajuniors,n.santos,        n.guaraniPAR,n.thestrongest,n.lau,             n.depquito,n.universitario,n.depgalicia],
    1964.0: [n.independiente,n.nacional,n.santos,n.colocolo,          n.millonarios,n.cerroporteno,n.barcelonaequ,   n.aurora,n.alianzalima,n.depitalia],
    1963.0: [n.santos,n.bocajuniors,n.botafogo,n.penarol,             n.olimpia,n.alianzalima,n.everestguayaquil,             n.millonarios,n.lau],
    1962.0: [n.santos,n.penarol,n.univcatolica,n.nacional,            n.cerroporteno,n.racing,n.emelec,              n.sportingcristal,n.depmunicipal,n.millonarios],
    1961.0: [n.penarol,n.palmeiras,n.olimpia,n.santafe,               n.universitario,n.independiente,n.colocolo,n.jorge,],
    1960.0: [n.penarol,n.olimpia,n.sanlorenzo,n.millonarios,          n.jorge,n.bahia,n.lau],
  },


  leagueName.concacaf : {
    //2025.0: [],
    //2024.0: [],
    2023.0: [n.leon,n.losangelesfc,n.tigres,n.philadelphia,          n.violette,n.motagua,n.vancouver,n.atlas,          n.austin,n.tauro,n.orlando,n.pachuca,n.rcdespana,n.alajuelense,n.olimpia,n.alianzaELS],
    2022.0: [n.seattle,n.pumas,n.nycity,n.cruzazul,                  n.leon,n.nerevolution,n.montreal,n.comunicaciones, n.depGuastatoya,n.motagua,n.coloradorapids,n.santosGuapiles,n.saprissa,n.cavaly,n.santoslaguna,n.forge],
    2021.0: [n.monterrey,n.americamex,n.cruzazul,n.philadelphia,     n.columbuscrew,n.portland,n.toronto,n.atlanta,     n.arcahaie,n.leon,n.pantoja,n.realEsteli,n.saprissa,n.alajuelense,n.olimpia,n.marathon],
    2020.0: [n.tigres,n.losangelesfc,n.olimpiaHON,n.americamex,      n.nycity,n.cruzazul,n.montreal,n.atlanta,          n.saprissa,n.seattle,n.sanCarlos,n.alianzaELS,n.leon,n.portmore,n.comunicaciones,n.motagua],
    2019.0: [n.monterrey,n.tigres,n.kansas,n.santoslaguna,           n.nyredbulls,n.houston,n.atlanta,n.independienteChorrera,   n.alianzaELS,n.herediano,n.toronto,n.toluca,n.depGuastatoya,n.saprissa,n.pantoja,n.marathon],
    2018.0: [n.chivas,n.toronto,n.nyredbulls,n.americamex,           n.tauro,n.tijuana,n.tigres,n.seattle,              n.saprissa,n.fcdallas,n.coloradorapids,n.herediano,n.motagua,n.olimpia,n.santatecla,n.cibao],
    2017.0: [n.pachuca,n.tigres,n.fcdallas,n.vancouver,              n.saprissa,n.nyredbulls,n.pumas,n.arabeunido,      n.hondurasprogreso,n.portland,n.kansas,n.monterrey,n.olimpia,n.alianzaELS,n.herediano,n.suchitepequez],
    2016.0: [n.americamex,n.tigres,n.santoslaguna,n.queretaro,       n.dcunited,n.seattle,n.realSaltLake,n.lagalaxy],
    2015.0: [n.americamex,n.montreal,n.herediano,n.alajuelense,      n.saprissa,n.pachuca,n.olimpiaHON,n.dcunited],
    2014.0: [n.cruzazul,n.toluca,n.tijuana,n.alajuelense,            n.kansas,n.sanJoseEarthquakes,n.lagalaxy,n.arabeunido],
    2013.0: [n.monterrey,n.santoslaguna,n.lagalaxy,n.seattle,        n.xelaju,n.houston,n.tigres,n.herediano],
    2012.0: [n.monterrey,n.santoslaguna,n.pumas,n.toronto,           n.morelia,n.seattle,n.lagalaxy,n.isidro],
    2011.0: [n.monterrey,n.realSaltLake,n.cruzazul,n.saprissa,         n.columbuscrew,n.santoslaguna,n.toluca,n.olimpiaHON],
    2010.0: [n.pachuca,n.cruzazul,n.toluca,n.pumas,                    n.comunicaciones,n.arabeunido,n.marathon,n.columbuscrew],
    2009.0: [n.atlante,n.cruzazul,n.santoslaguna,n.puertoRico,         n.houston,n.pumas,n.montreal,n.marathon],
    2008.0: [n.pachuca,n.saprissa,n.dcunited,n.houston,                n.motagua,n.atlante,n.harbourView,n.municipal],
    2007.0: [n.pachuca,n.chivas,n.houston,n.dcunited,                  n.marquense,n.wconnection,n.puntarenas,n.olimpiaHON],
    2006.0: [n.americamex,n.toluca,n.alajuelense,n.saprissa,           n.portmore,n.olimpiaHON,n.nerevolution,n.lagalaxy],
    2005.0: [n.saprissa,n.pumas,n.monterrey,n.dcunited,                n.kansas,n.olimpiaHON,n.municipal,n.harbourView],
    2004.0: [n.alajuelense,n.saprissa,n.chicago,n.monterrey,           n.sanJoseEarthquakes,n.pachuca,n.jabloteh,n.fas],
    2003.0: [n.toluca,n.morelia,n.americamex,n.necaxa,                 n.municipal,n.columbuscrew,n.alajuelense,n.lagalaxy],
    2002.0: [],
    2001.0: [n.pachuca,n.morelia,n.alajuelense,n.kansas,               n.sanJoseEarthquakes,n.chicago,n.comunicaciones,n.santoslaguna],
    2000.0: [n.lagalaxy,n.olimpiaHON,n.pachuca,n.dcunited,             n.rcdespana,n.toluca,n.joepublic,n.alajuelense],
    1999.0: [n.necaxa,n.alajuelense,n.chicago,n.dcunited,              n.saprissa,n.toluca,n.joepublic,n.olimpiaHON],
    1998.0: [n.dcunited,n.toluca,n.saprissa,n.leon,                    n.joepublic,n.alajuelense,n.cruzazul,n.firpo],
    1997.0: [n.cruzazul,n.lagalaxy,n.chivas,n.dcunited,                n.comunicaciones,n.firpo,n.cartagines,n.petrotrin],
    1996.0: [n.cruzazul,n.necaxa,n.comunicaciones,n.seattle,           ],
    1995.0: [n.saprissa,n.municipal,n.alajuelense,n.moulien],
    1994.0: [n.cartagines,n.atlante,n.usrobert,n.alianzaELS],
    1993.0: [n.saprissa,n.leon,n.municipal,n.robinhood],
    1992.0: [n.americamex,n.alajuelense,n.robinhood,n.aiglon],
    1991.0: [n.puebla,n.police,n.rcdespana,n.leonesnegros,              ],
    1990.0: [n.americamex,n.pinardelrio,n.olimpiaHON],
    1989.0: [n.pumas,n.pinardelrio,n.herediano,],
    1988.0: [n.olimpiaHON,n.defenseforce,n.alajuelense,n.robinhood],
    1987.0: [n.americamex,n.defenseforce,n.monterrey,n.trintoc],
    1986.0: [n.alajuelense,n.transvaal,],
    1985.0: [n.defenseforce,n.olimpiaHON],
    1984.0: [n.violette,n.guayanais],
    1983.0: [n.atlante,n.robinhood],
    1982.0: [n.pumas,n.robinhood,n.comunicaciones,n.defenseforce],
    1981.0: [n.transvaal,n.atleticomarte],
    1980.0: [n.pumas,n.unah,n.robinhood,],
    1979.0: [],
    1978.0: [n.cdfas,n.jongcolombia,n.tigres],
    1977.0: [n.americamex,n.robinhood,n.saprissa],
    1976.0: [n.aguila,n.robinhood,n.leon],
    1975.0: [n.atlEspanol,n.transvaal],
    1974.0: [n.municipal,n.transvaal,n.alianzaELS],
    1973.0: [n.transvaal,n.saprissa],
    1972.0: [n.olimpiaHON,n.robinhood,n.toluca],
    1971.0: [n.cruzazul,n.alajuelense,n.comunicaciones],
    1970.0: [n.cruzazul,n.transvaal,n.saprissa],
    1969.0: [n.cruzazul,n.comunicaciones,n.saprissa],
    1968.0: [n.toluca,n.transvaal,],
    1967.0: [n.alianzaELS,n.jongcolombia],
    1963.0: [n.racingHAITI,n.chivas,n.saprissa,n.xelaju]
  },
  leagueName.asia : {
    //2025.0: [],
    //2024.0: [],
    //2023.0: [],
    2022.0: [n.urawareddiamonds,n.alhilal,n.alduhail,n.jeonbuk,        n.pathum,n.foolad,n.visselkobe,n.alshabab,            n.alrayyan,n.nasafqarshi,n.alFaisalyARABIA,n.shababalahli,n.yokohamamarinos,n.daegu,n.johordarul,n.kitchee],
    2021.0: [n.alhilal,n.pohang,n.alnassr,n.ulsan,                     n.persepolis,n.nagoya,n.alwahda,n.jeonbuk],
    2020.0: [n.ulsan,n.persepolis,n.alnassr,n.visselkobe,              n.beijingguoan,n.pakhtakor,n.suwonsamsung,n.alahli],
    2019.0: [n.alhilal,n.urawareddiamonds,n.alsadd,n.ghuangzhou,       n.alIttihad,n.shanghaisipg,n.alnassr,n.kashimaantlers],
    2018.0: [n.kashimaantlers,n.persepolis,n.suwonsamsung,n.alsadd,    n.tianjin,n.alduhail,n.jeonbuk,n.esteghlal],
    2017.0: [n.urawareddiamonds,n.alhilal,n.shanghaisipg,n.persepolis, n.kawasakifrontale,n.alain,n.ghuangzhou,n.alahli],
    2016.0: [n.jeonbuk,n.alain,n.eljaish,n.fcseoul,                    n.shanghaisipg,n.loktashkent,n.alnasrEAU,n.shandong],
    2015.0: [n.ghuangzhou,n.alahli,n.alhilal,n.gambaOsaka,             n.kashiwaReysol,n.nafttehran,n.alduhail,n.jeonbuk],
    2014.0: [n.sydneywanderers,n.alhilal,n.fcseoul,n.alain,            n.ghuangzhou,n.alsadd,n.pohang,n.alIttihad],
    2013.0: [n.ghuangzhou,n.fcseoul,n.esteghlal,n.kashiwaReysol,       n.alduhail,n.alahli,n.buriram,n.alshabab],
    2012.0: [n.ulsan,n.alahli,n.bunyodkor,n.alIttihad,                 n.alhilal,n.sepahan,n.adelaide,n.ghuangzhou],
    2011.0: [n.alsadd,n.jeonbuk,n.suwonsamsung,n.alIttihad,            n.sepahan,n.cerezoOsaka,n.zobahan,n.fcseoul],
    2010.0: [n.seongnam,n.zobahan,n.alshabab,n.alhilal,                n.suwonsamsung,n.pohang,n.jeonbuk,n.algharafa],
    2009.0: [n.pohang,n.alIttihad,n.ummsalal,n.nagoya,                 n.bunyodkor,n.pakhtakor,n.fcseoul,n.kawasakifrontale],
    2008.0: [n.gambaOsaka,n.adelaide,n.urawareddiamonds,n.bunyodkor,   n.alkaramah,n.kashimaantlers,n.alQadisiya,n.saipa],
    2007.0: [n.urawareddiamonds,n.sepahan,n.seongnam,n.alwahda,        n.jeonbuk,n.kawasakifrontale,n.alkaramah,n.alhilal],
    2006.0: [n.jeonbuk,n.alkaramah,n.ulsan,n.alQadisiya,               n.shanghaishenhua,n.alIttihad,n.alshabab,n.alain],
    2005.0: [n.alIttihad,n.alain,n.shenzhen,n.busan,                   n.shandong,n.pastehran,n.alahli,n.alsadd],
    2004.0: [n.alIttihad,n.seongnam,n.jeonbuk,n.pakhtakor,             n.dalian,n.alsharjah,n.alain,n.alwahda],
    2003.0: [n.alain,n.policetero,n.dalian,n.pakhtakor,             n.alsadd,n.daejeon,n.seongnam,n.persepolis,],
    2002.0: [n.suwonsamsung,n.fcseoul,n.esteghlal,n.nasafqarshi,       n.dalian,n.kashimaantlers,n.alkuwait,n.alwahda],
    2001.0: [n.suwonsamsung,n.jubiloiwata,n.persepolis,n.irtysh,       n.shandong,n.psmMakassar,n.alIttihad,n.alhilal],
    2000.0: [n.alhilal,n.jubiloiwata,n.persepolis,n.suwonsamsung,      n.alShortaIRAQ,n.kashimaantlers,n.irtysh,n.sinthana],
    1999.0: [n.jubiloiwata,n.esteghlal,n.alain,n.dalian,               n.pohang,n.alhilal,n.busan,n.kopetdag],
    1998.0: [n.pohang,n.dalian,n.alhilal,n.persepolis,                 n.kashimaantlers,n.mountainlion,n.navbahor,n.alansar],
    1997.0: [n.pohang,n.seongnam,n.persepolis,n.alzawraa,              n.yokohamamarinos,n.newradiant,n.alnassr,n.alrayyan],
    1996.0: [n.seongnam,n.alnassr,n.thai,n.saipa,                      n.tokyoVerdy,n.alarabi,n.persib,n.kopetdag],
    1995.0: [n.thai,n.alarabi,n.neftchifargona,n.seongnam,             n.liaoning,n.alwasl,n.alansar,n.tokyoVerdy],
    1994.0: [n.thai,n.omanclub,n.tokyoVerdy,n.liaoning,                n.almuharraq,n.alansar,],
    1993.0: [n.pastehran,n.alshabab,n.alwasl,n.tokyoVerdy,             n.wohaib,n.almuharraq,n.arseto],
    1992.0: [n.alhilal,n.esteghlal,n.alrayyan,n.alshababEAU,           n.april25,n.portFC,n.mohammedan],
    1991.0: [n.esteghlal,n.liaoning,n.pelitaJaya,n.april25,            n.mohammedan,n.alnasrOMAN,n.bangkokBank],
    1990.0: [n.liaoning,n.yokohamamarinos,n.alRasheed,n.federalTerritory],
    1989.0: [n.alsadd,n.alRasheed,n.alettifaq,n.guangdong,             ],
    1988.0: [],
    1987.0: [n.tokyoVerdy,n.alhilal,n.federalTerritory,n.alRasheed,    ],
    1986.0: [n.jefUnited,n.alhilal,n.liaoning,n.alTalaba,              ],
    1985.0: [n.busan,n.alahli,n.palembang,n.alittihadSYR,                    ],
    1984.0: [],
    1983.0: [],
    1982.0: [],
    1981.0: [],
    1980.0: [],
    1979.0: [],
    1978.0: [],
    1977.0: [],
    1976.0: [],
    1975.0: [],
    1974.0: [],
    1973.0: [],
    1972.0: [],
    1971.0: [n.maccabitelaviv,n.alShortaIRAQ,n.esteghlal,n.rokArmy,        ],
    1970.0: [n.esteghlal,n.hapoeltelaviv,n.homenetmen,n.psmsMedan,     ],
    1969.0: [n.maccabitelaviv,n.yangzee,n.hiroshima,n.mysore,          ],
    1968.0: [],
    1967.0: [n.hapoeltelaviv,n.selangor,n.koreaTungsten,n.bangkokBank, ],
  },

  leagueName.africa : {
    //2025.0: [],
    //2024.0: [],
    2023.0: [n.alahly,n.wydad,n.esperance,n.mamelodi,                n.rajacasablanca,n.simba,n.jskabylie,n.belouizdad,      n.omdurman,n.zamalek,n.petroluanda,n.horoya,n.almerreikh,n.vita,n.vipers,n.cotonsport],
    2022.0: [n.wydad,n.alahly,n.petroluanda,n.essetif,               n.belouizdad,n.rajacasablanca,n.mamelodi,n.esperance,   n.amazulu,n.etoilesahel,n.zamalek,n.omdurman,n.almerrikh,n.horoya,n.sagradaesperanca,n.jwaneng,],
    2021.0: [n.alahly,n.kaizer,n.esperance,n.wydad,                  n.mamelodi,n.simba,n.belouizdad,n.mcalger,            n.horoya,n.zamalek,n.vita,n.mazembe,n.omdurman,n.teungueth,n.almerrikh,n.petroluanda],
    2020.0: [n.alahly,n.zamalek,n.rajacasablanca,n.wydad,            n.mamelodi,n.esperance,n.etoilesahel,n.mazembe,       n.omdurman,n.jskabylie,n.agosto,n.petroluanda,n.vita,n.usmalger,n.zesco,n.platinum],
    2019.0: [n.esperance,n.wydad,n.mazembe,n.mamelodi,               n.csconstantine,n.horoya,n.simba,n.alahly,              n.clubafricain,n.jssaoura,n.lobiStars,n.orlandopirates,n.asecmimosas,n.vita,n.platinum,n.ismaily],
    2018.0: [n.esperance,n.alahly,n.agosto,n.essetif,                n.etoilesahel,n.horoya,n.mazembe,n.wydad,             n.zesco,n.mamelodi,n.kampala,n.difaa,n.mcalger,n.togoport,n.township,n.mbabane,],
    2017.0: [n.wydad,n.alahly,n.usmalger,n.etoilesahel,              n.mamelodi,n.esperance,n.ferroviariomaputo,n.tripoliLIB,  n.zanaco,n.almerrikh,n.zamalek,n.stGeorge,n.caps,n.omdurman,n.vita,n.cotonsport],
    2016.0: [n.mamelodi,n.zamalek,n.zesco,n.wydad,                   n.enyimba,n.alahly,n.essetif,n.asecmimosas,           n.vita,n.almerrikh,n.mazembe,n.etoilesahel,n.stademalien,n.yanga,n.tripoliLIB,n.mobejaia,],
    2015.0: [n.mazembe,n.usmalger,n.almerrikh,n.omdurman,            n.moghrebtetouan,n.essetif,n.smouha,n.mceleulma,        n.kaloum,n.sangabalende,n.esperance,n.sfaxien,n.leopardsCON,n.alahly,n.rajacasablanca,n.stademalien,],
    2014.0: [n.essetif,n.vita,n.mazembe,n.sfaxien,                   n.esperance,n.omdurman,n.benghazi,n.zamalek,          n.alahly,n.realbamako,n.seweSport,n.horoya,n.cotonsport,n.leopardsCON,n.kaizer,n.nkana,],
    2013.0: [n.alahly,n.orlandopirates,n.cotonsport,n.esperance,     n.zamalek,n.seweSport,n.leopardsCON,n.libolo],
    2012.0: [n.alahly,n.esperance,n.sunshinestars,n.mazembe,         n.berekum,n.asochlef,n.zamalek,n.etoilesahel],
    2011.0: [n.esperance,n.wydad,n.omdurman,n.enyimba,               n.alahly,n.cotonsport,n.mcalger,n.rajacasablanca],
    2010.0: [n.mazembe,n.esperance,n.jskabylie,n.alahly,               n.essetif,n.ismaily,n.dynamos,n.heartland],
    2009.0: [n.mazembe,n.heartland,n.omdurman,n.kano,                n.zesco,n.etoilesahel,n.monomotapa,n.almerrikh],
    2008.0: [n.alahly,n.cotonsport,n.enyimba,n.dynamos,              n.mazembe,n.asecmimosas,n.omdurman,n.zamalek],
    2007.0: [n.etoilesahel,n.alahly,n.omdurman,                          n.asecmimosas,n.jskabylie,n.farrabat,n.esperance],
    2006.0: [n.alahly,n.sfaxien,n.asecmimosas,n.orlandopirates,      n.enyimba,n.asantekotoko,n.jskabylie,n.heartsoak],
    2005.0: [n.alahly,n.etoilesahel,n.zamalek,n.rajacasablanca,      n.enyimba,n.asecmimosas,n.esperance,n.capetownAjax],
    2004.0: [n.enyimba,n.etoilesahel,n.esperance,n.jeannedarc,       n.usmalger,n.africaSports,n.bakiliBullets,n.supersport],
    2003.0: [n.enyimba,n.ismaily,n.usmalger,n.esperance,            n.simba,n.canonYaounde,n.asecmimosas,n.aviacao],
    2002.0: [n.zamalek,n.rajacasablanca,n.mazembe,n.asecmimosas,    n.esperance,n.jeannedarc,n.alahly,n.costasol],
    2001.0: [n.alahly,n.mamelodi,n.esperance,n.petroluanda,         n.asecmimosas,n.juliusberger,n.mazembe,n.belouizdad],
    2000.0: [n.heartsoak,n.esperance,n.mamelodi,n.alahly,           n.africaSports,n.lobiStars,n.jeannedarc,n.sable],
    1999.0: [n.rajacasablanca,n.esperance,n.alahly,n.asecmimosas,   n.heartsoak,n.dynamos,n.shootingstars,n.saintLouisienne],
    1998.0: [n.asecmimosas,n.dynamos,n.manningRangers,n.heartsoak,  n.etoilesahel,n.rajacasablanca,n.dolphin,n.yanga],
    1997.0: [n.rajacasablanca,n.ashantiGold,n.usmalger,n.zamalek,   n.agosto,n.clubafricain,n.ferroviariomaputo,n.orlandopirates],
    1996.0: [n.zamalek,n.shootingstars,n.sfaxien,n.jskabylie,         n.meknes,n.orlandopirates,n.jaraaf,n.petroluanda],
    1995.0: [n.orlandopirates,n.asecmimosas,n.express,n.ismaily,    n.mbilinga,n.obuasi,n.dynamos,n.esperance],
    1994.0: [n.esperance,n.zamalek,n.nkana,n.mcoran,                n.heartland,n.sogara,n.simba,n.vita],
    1993.0: [n.zamalek,n.asantekotoko,n.asecmimosas,n.stationerystores, n.mcoran,n.nkana,n.villa,n.sogara],
    1992.0: [n.wydad,n.omdurman,n.asecmimosas,n.ismaily,            n.nkana,n.gorMahia,n.asantekotoko,n.clubafricain],
    1991.0: [n.clubafricain,n.villa,n.nkana,n.heartland,            n.wydad,n.alahly,n.douala,n.asecmimosas],
    1990.0: [n.jskabylie,n.nkana,n.asantekotoko,n.heartland,          n.leopardsQUE,n.bafoussam,n.omdurman,n.esperance],
    1989.0: [n.rajacasablanca,n.mcoran,n.nkana,n.tonnerre,          ],
    1988.0: [n.essetif,n.heartland,n.farrabat,n.alahly,             ],
    1987.0: [n.alahly,n.omdurman,n.canonYaounde,n.asantekotoko,     ],
    1986.0: [n.zamalek,n.africaSports,n.nkana,n.canonYaounde,       ],
    1985.0: [n.farrabat,n.dragons,n.zamalek,n.goree,                ],
    1984.0: [n.zamalek,n.shootingstars,n.jskabylie,n.semassi,         ],
    1983.0: [n.asantekotoko,n.alahly,n.jaraaf,n.nkana,              ],
    1982.0: [n.alahly,n.asantekotoko,n.rangersInt,n.lupopo,         ],
    1981.0: [n.jskabylie,n.vita,n.kaloum,n.alahly,                    ],
    1980.0: [n.canonYaounde,n.dragons,n.douala,n.bendel,            ],
    1979.0: [n.douala,n.heartsoak,n.goree,n.motema,                 ],
    1978.0: [n.canonYaounde,n.hafia,n.rangersInt,n.vita,            ],
    1977.0: [n.hafia,n.heartsoak,n.mufulira,n.lome,                 ],
    1976.0: [n.mcalger,n.hafia,n.rangersInt,n.asecmimosas],
    1975.0: [n.hafia,n.rangersInt,n.ghazlelmahalla,n.lome,],
    1974.0: [n.caraBrazaville,n.ghazlelmahalla,n.simba,n.jeannedarc],
    1973.0: [n.vita,n.asantekotoko,n.leopardsCAM,n.tusker],
    1972.0: [n.hafia,n.simba,n.mazembe,n.heartsoak],
    1971.0: [n.canonYaounde,n.asantekotoko,n.greatOlympics,n.asecmimosas],
    1970.0: [n.asantekotoko,n.mazembe,n.ismaily,n.kaloum],
    1969.0: [n.ismaily,n.mazembe,n.asantekotoko,n.hafia],
    1968.0: [n.mazembe,n.etoilefilante,n.leopardsQUE,n.farrabat],
    1967.0: [n.mazembe,n.asantekotoko,n.stGeorge,n.djoliba],
    1966.0: [n.stadeDAbidjan,n.realbamako,n.oryx,n.omdurman],
  },

  leagueName.mundial : {
    //2025.0: [],
    //2024.0: [],
    //2023.0: [n.mancity,n.leon,n.alahly,],
    2022.0: [n.realmadrid,n.alhilal,n.flamengo,n.alahly,n.seattle,n.wydad,n.auckland],
    2021.0: [n.chelsea,n.palmeiras,n.alahly,n.alhilal,n.monterrey],
    2020.0: [n.bayernmunique,n.tigres,n.alahly,n.palmeiras],
    2019.0: [n.liverpool,n.flamengo,n.monterrey,n.alhilal],
    2018.0: [n.realmadrid,n.alain,n.riverplate,n.kashimaantlers],
    2017.0: [n.realmadrid,n.gremio,n.pachuca,n.aljazira],
    2016.0: [n.realmadrid,n.kashimaantlers,n.atleticonacional,n.americamex],
    2015.0: [n.barcelona,n.riverplate,n.hiroshima,n.ghuangzhou],
    2014.0: [n.realmadrid,n.sanlorenzo,n.auckland,n.cruzazul],
    2013.0: [n.bayernmunique,n.rajacasablanca,n.atleticomg,n.ghuangzhou],
    2012.0: [n.corinthians,n.chelsea,n.monterrey,n.alahly],
    2011.0: [n.barcelona,n.santos,n.alsadd,n.kashiwaReysol],
    2010.0: [n.inter,n.mazembe,n.internacional,n.seongnam],
    2009.0: [n.barcelona,n.estudiantes,n.pohang,n.atlante],
    2008.0: [n.manutd,n.ldu,n.gambaOsaka,n.pachuca],
    2007.0: [n.milan,n.bocajuniors,n.urawareddiamonds,n.etoilesahel],
    2006.0: [n.internacional,n.barcelona,n.alahly,n.americamex],
    2005.0: [n.saopaulo,n.liverpool,n.saprissa,n.alIttihad],
    2004.0: [n.porto,n.oncecaldas,],
    2003.0: [n.bocajuniors,n.milan],
    2002.0: [n.realmadrid,n.olimpia],
    2001.0: [n.bayernmunique,n.bocajuniors],
    2000.0: [n.bocajuniors,n.realmadrid],
    1999.0: [n.manutd,n.palmeiras],
    1998.0: [n.realmadrid,n.vasco],
    1997.0: [n.dortmund,n.cruzeiro],
    1996.0: [n.juventus,n.riverplate],
    1995.0: [n.ajax,n.gremio],
    1994.0: [n.velez,n.milan],
    1993.0: [n.saopaulo,n.milan],
    1992.0: [n.saopaulo,n.barcelona],
    1991.0: [n.estrelavermelha,n.colocolo],
    1990.0: [n.milan,n.olimpia],
    1989.0: [n.milan,n.atleticonacional],
    1988.0: [n.nacional,n.psv],
    1987.0: [n.porto,n.penarol],
    1986.0: [n.riverplate,n.steauabucuresti],
    1985.0: [n.juventus,n.argentinojuniors],
    1984.0: [n.independiente,n.liverpool],
    1983.0: [n.gremio,n.hamburgo],
    1982.0: [n.penarol,n.astonvilla],
    1981.0: [n.flamengo,n.liverpool],
    1980.0: [n.nacional,n.nottinghamforest],
    1979.0: [n.olimpia,n.malmo],
    1978.0: [],
    1977.0: [n.bocajuniors,n.moenchengladbach],
    1976.0: [n.bayernmunique,n.cruzeiro],
    1975.0: [],
    1974.0: [n.atleticomadrid,n.independiente],
    1973.0: [n.independiente,n.juventus],
    1972.0: [n.ajax,n.independiente],
    1971.0: [n.nacional,n.panathinaikos],
    1970.0: [n.feyenoord,n.estudiantes],
    1969.0: [n.milan,n.estudiantes],
    1968.0: [n.estudiantes,n.manutd],
    1967.0: [n.racing,n.celtic],
    1966.0: [n.penarol,n.realmadrid],
    1965.0: [n.inter,n.independiente],
    1964.0: [n.inter,n.independiente],
    1963.0: [n.santos,n.milan],
    1962.0: [n.santos,n.benfica],
    1961.0: [n.penarol,n.benfica],
    1960.0: [n.realmadrid,n.penarol],
    1959.0: [],
    1958.0: [],
    1957.0: [],
    1956.0: [],
    1955.0: [],
    1954.0: [],
    1953.0: [],
    1952.0: [n.fluminense,n.corinthians,n.austria,n.penarol],
    1951.0: [n.palmeiras,n.juventus,n.vasco,n.austria],
  },

  leagueName.europaLeagueOficial : {
    //2025.0: [],
    //2024.0: [],
    2023.0: [n.sevilla,n.roma,n.juventus,n.leverkusen,              n.manutd,n.feyenoord,n.sporting,n.saintgilloise,      n.fenerbahce,n.realsociedad,n.freiburg,n.arsenal,n.realbetis,n.unionberlin,n.ferencvaros,n.shakhtardonetsk],
    2022.0: [n.eintrachtfrankfurt,n.rangers,n.westham,n.rbleipzig,  n.barcelona,n.braga,n.lyon,n.atalanta],
    2021.0: [n.villareal,n.manutd,n.arsenal,n.roma,       n.dinamozagreb,n.granada,n.slaviapraha,n.ajax],
    2020.0: [n.sevilla,n.inter,n.manutd,n.shakhtardonetsk, n.wolves,n.leverkusen,n.copenhague,n.basel],
    2019.0: [n.chelsea,n.arsenal,n.eintrachtfrankfurt,n.valencia,   n.slaviapraha,n.napoli,n.benfica,n.villareal],
    2018.0: [n.atleticomadrid,n.om,n.arsenal,n.rbsalzburg,          n.sporting,n.rbleipzig,n.cska,n.lazio],
    2017.0: [n.manutd,n.ajax,n.celtavigo,n.lyon,          n.anderlecht,n.schalke04,n.genk,n.besiktas],
    2016.0: [n.sevilla,n.liverpool,n.shakhtardonetsk,n.villareal,    n.athleticbilbao,n.dortmund,n.braga,n.spartapraga],
    2015.0: [n.sevilla,n.dnipro,n.fiorentina,n.napoli,              n.zenit,n.brugge,n.dinamokiev,n.wolfsburg],
    2014.0: [n.sevilla,n.benfica,n.valencia,n.juventus,             n.porto,n.az,n.basel,n.lyon],
    2013.0: [n.chelsea,n.benfica,n.basel,n.fenerbahce,              n.rubinKazan,n.newcastle,n.tottenham,n.lazio],
    2012.0: [n.atleticomadrid,n.athleticbilbao,n.valencia,n.sporting, n.hannover96,n.schalke04,n.az,n.metalistkharkiv],
    2011.0: [n.porto,n.braga,n.villareal,n.benfica,                   n.spartakmoscou,n.dinamokiev,n.twente,n.psv],
    2010.0: [n.atleticomadrid,n.fulham,n.liverpool,n.hamburgo,        n.valencia,n.wolfsburg,n.benfica,n.standardliege],
    2009.0: [n.shakhtardonetsk,n.werderbremen,n.dinamokiev,n.hamburgo, n.om,n.udinese,n.psg,n.mancity],
    2008.0: [n.zenit,n.rangers,n.bayernmunique,n.fiorentina,          n.leverkusen,n.sporting,n.getafe,n.psv],
    2007.0: [n.sevilla,n.espanyol,n.osasuna,n.werderbremen,           n.tottenham,n.benfica,n.leverkusen,n.az],
    2006.0: [n.sevilla,n.middlesbrough,n.schalke04,n.steauabucuresti, n.zenit,n.basel,n.levskisofia,n.rapidbucuresti],
    2005.0: [n.cska,n.sporting,n.parma,n.az,                          n.auxerre,n.newcastle,n.austria,n.villareal],
    2004.0: [n.valencia,n.om,n.villareal,n.newcastle,                 n.bordeaux,n.inter,n.celtic,n.psv],
    2003.0: [n.porto,n.celtic,n.lazio,n.boavista,                     n.panathinaikos,n.liverpool,n.besiktas,n.malaga],
    2002.0: [n.feyenoord,n.dortmund,n.inter,n.milan,               n.psv,n.slovanliberec,n.valencia,n.hapoeltelaviv],
    2001.0: [n.liverpool,n.alaves,n.barcelona,n.kaiserslautern,    n.porto,n.rayovallecano,n.celtavigo,n.psv],
    2000.0: [n.galatasaray,n.arsenal,n.leeds,n.lens,               n.mallorca,n.werderbremen,n.slaviapraha,n.celtavigo],
    1999.0: [n.parma,n.om,n.atleticomadrid,n.bologna,              n.bordeaux,n.celtavigo,n.roma,n.lyon],
    1998.0: [n.inter,n.lazio,n.spartakmoscou,n.atleticomadrid,     n.schalke04,n.auxerre,n.ajax,n.astonvilla],
    1997.0: [n.schalke04,n.inter,n.tenerife,n.monaco,              n.valencia,n.anderlecht,n.brondby,n.newcastle],
    1996.0: [n.bayernmunique,n.bordeaux,n.barcelona,n.slaviapraha, n.nottinghamforest,n.milan,n.psv,n.roma],
    1995.0: [n.parma,n.juventus,n.leverkusen,n.dortmund,           n.obodense,n.eintrachtfrankfurt,n.nantes,n.lazio],
    1994.0: [n.inter,n.rbsalzburg,n.cagliari,n.karlsruher,         n.dortmund,n.eintrachtfrankfurt,n.juventus,n.boavista],
    1993.0: [n.juventus,n.dortmund,n.psg,n.auxerre,                n.benfica,n.roma,n.realmadrid,n.ajax],
    1992.0: [n.ajax,n.torino,n.genoa,n.realmadrid,                 n.gent,n.b1903,n.liverpool,n.sigmaolomouc],
    1991.0: [n.inter,n.roma,n.sporting,n.brondby,                  n.atalanta,n.anderlecht,n.bologna,n.torpedo],
    1990.0: [n.juventus,n.fiorentina,n.koln,n.werderbremen,     n.hamburgo,n.auxerre,n.royalAntwerp,n.liegeois],
    1989.0: [n.napoli,n.stuttgart,n.bayernmunique,n.dynamodresden, n.juventus,n.realsociedad,n.hearts,n.victoriabuc],
    1988.0: [n.leverkusen,n.espanyol,n.werderbremen,n.brugge,      n.barcelona,n.vitkovice,n.hellasverona,n.panathinaikos],
    1987.0: [n.ifkgoteborg,n.dundee,n.tirolinnsbruck,n.moenchengladbach,    n.inter,n.barcelona,n.torino,n.vitoriaguimaraes],
    1986.0: [n.realmadrid,n.koln,n.inter,n.waregemKSV,          n.neuchatel,n.sporting,n.nantes,n.hajduksplit],
    1985.0: [n.realmadrid,n.fehervar,n.inter,n.zeljeznicar,        n.tottenham,n.manutd,n.koln,n.dinamominsk],
    1984.0: [n.tottenham,n.anderlecht,n.hajduksplit,n.nottinghamforest, n.austria,n.spartakmoscou,n.spartapraga,n.sturmgraz],
    1983.0: [n.anderlecht,n.benfica,n.bohemians,n.craiova,         n.valencia,n.roma,n.dundee,n.kaiserslautern,],
    1982.0: [n.ifkgoteborg,n.hamburgo,n.kaiserslautern,n.radnickinis, n.valencia,n.neuchatel,n.realmadrid,n.dundee],
    1981.0: [n.ipswich,n.az,n.koln,n.sochaux,               n.saintetienne,n.lokeren,n.standardliege,n.grasshoppers],
    1980.0: [n.eintrachtfrankfurt,n.moenchengladbach,n.bayernmunique,n.stuttgart, n.brno,n.saintetienne,n.kaiserslautern,n.loksofia],
    1979.0: [n.moenchengladbach,n.estrelavermelha,n.duisburg,n.herthaberlim, n.mancity,n.westbromwich,n.honved,n.dukla],
    1978.0: [n.psv,n.bastia,n.barcelona,n.grasshoppers,           n.magdeburg,n.carlzeissjena,n.astonvilla,n.eintrachtfrankfurt],
    1977.0: [n.juventus,n.athleticbilbao,n.aek,n.molenbeek,       n.magdeburg,n.barcelona,n.qpr,n.feyenoord],
    1976.0: [n.liverpool,n.brugge,n.barcelona,n.hamburgo,         n.dynamodresden,n.milan,n.levskisofia,n.stalmielec],
    1975.0: [n.moenchengladbach,n.twente,n.koln,n.juventus,    n.banikostrava,n.velezMostar,n.amsterdam,n.hamburgo],
    1974.0: [n.feyenoord,n.tottenham,n.stuttgart,n.lokleipzig,    n.ruchchorzow,n.koln,n.setubal,n.ipswich],
    1973.0: [n.liverpool,n.moenchengladbach,n.tottenham,n.twente, n.dynamodresden,n.kaiserslautern,n.setubal,n.ofkbelgrade],
    1972.0: [n.tottenham,n.wolves,n.milan,n.ferencvaros,          n.arad,n.juventus,n.lierse,n.zeljeznicar],

    //Taça das Feiras
    1971.0: [n.leeds,n.juventus,n.liverpool,n.koln,            n.setubal,n.twente,n.bayernmunique,n.arsenal],
    1970.0: [n.arsenal,n.anderlecht,n.ajax,n.inter,               n.bacau,n.newcastle,n.carlzeissjena,n.herthaberlim],
    1969.0: [n.newcastle,n.ujpest,n.rangers,n.goztepe,            n.setubal,n.leeds,n.setubal,n.hamburgo],
    1968.0: [n.leeds,n.ferencvaros,n.dundeefc,n.bologna,          n.rangers,n.athleticbilbao,n.zurich,n.vojvodina],
    1967.0: [n.dinamozagreb,n.leeds,n.eintrachtfrankfurt,n.kilmarnock,  n.juventus,n.bologna,n.burnley,n.lokleipzig],
    1966.0: [n.barcelona,n.zaragoza,n.chelsea,n.leeds,            n.espanyol,n.dunfermline,n.munich1860,n.ujpest],
    1965.0: [n.ferencvaros,n.juventus,n.manutd,n.atleticomadrid,  n.athleticbilbao,n.strasbourg,           n.roma,n.lokplovdiv,n.everton,n.liegeois,n.dunfermline,n.barcelona],
    1964.0: [n.zaragoza,n.valencia,n.liegeois,n.koln,          n.juventus,n.ujpest,n.brno,n.roma],
    1963.0: [n.valencia,n.dinamozagreb,n.roma,n.ferencvaros,      n.hibernian,n.bayernmunique,n.estrelavermelha,n.petrolul],
    1962.0: [n.valencia,n.barcelona,n.mtk,n.estrelavermelha,      n.inter,n.sheffieldwednesday,n.novisad,n.espanyol,],
    1961.0: [n.roma,n.birmigham,n.hibernian,n.inter,              n.koln,n.kb,n.barcelona,n.belgradoxi],
    1960.0: [n.barcelona,n.birmigham,n.belgradoxi,n.saintgilloise,             n.inter,n.zagrebxi,n.chelsea,n.roma],
  },

  leagueName.conferenceLeague:{
    //2025.0: [],
    //2024.0: [],
    //2023.0: [],
    2023.0: [n.westham,n.fiorentina,n.az,n.basel,],
    2022.0: [n.roma,n.feyenoord,n.leicester,n.om,],
  },

  leagueName.copaSulAmericana : {
    //2025.0: [],
    //2024.0: [],
    //2023.0: [],
    2022.0: [n.idelvalle,n.saopaulo,n.melgar,n.atleticogo,           n.tachira,n.ceara,n.internacional,n.nacional,          n.lanus,n.univcatolica,n.deportivocali,n.olimpia,n.santos,n.colocolo,n.unionsantafe,n.thestrongest],
    2021.0: [n.atleticopr,n.bragantino,n.penarol,n.libertad,         n.ldu,n.rosario,n.sportingcristal,n.santos,     n.americadecali,n.idelvalle,n.nacional,n.junior,n.arsenalsarandi,n.gremio,n.tachira,n.independiente],
    2020.0: [n.defensayjusticia,n.lanus,n.coquimbo,n.velez,          n.bahia,n.independiente,n.junior,n.univcatolica,       n.vasco,n.bolivar,n.deportivocali,n.riverURU,n.fenix,n.lacalera,n.huancayo,n.unionsantafe,                  ],
    2019.0: [n.idelvalle,n.colon,n.corinthians,n.atleticomg,         n.independiente,n.zulia,n.fluminense,n.laequidad,      n.caracas,n.argentinojuniors,n.montwanderers,n.penarol,n.univcatolica,n.sportingcristal,n.botafogo,n.royalpari],
    2018.0: [n.atleticopr,n.junior,n.fluminense,n.santafe,           n.bahia,n.defensayjusticia,n.nacional,n.deportivocali, n.caracas,n.colon,n.millonarios,n.ldu,n.banfield,n.botafogo,n.depcuenca,n.sanlorenzo],
    2017.0: [n.independiente,n.flamengo,n.libertad,n.junior,         n.nacionalPAR,n.fluminense,n.racing,n.sport,           n.atleticotucuman,n.chapecoense,n.santafe,n.corinthians,n.estudiantes,n.ldu,n.pontepreta,n.cerroporteno],
    2016.0: [n.chapecoense,n.atleticonacional,n.sanlorenzo,n.cerroporteno,  n.junior,n.coritiba,n.palestino,n.imedellin,    n.independiente,n.soldeamerica,n.santacruz,n.santafe,n.belgrano,n.laguaira,n.flamengo,n.montwanderers],
    2015.0: [n.santafe,n.huracan,n.luqueno,n.riverplate,             n.independiente,n.defensor,n.atleticopr,n.chapecoense, n.emelec,n.sport,n.ldu,n.libertad,n.lanus,n.brasilia,n.tolima,n.olimpia,],
    2014.0: [n.riverplate,n.atleticonacional,n.bocajuniors,n.saopaulo, n.estudiantes,n.cesarvallejo,n.cerroporteno,n.emelec, n.libertad,n.vitoria,n.bahia,n.huachipato,n.goias,n.capiata,n.lanus,n.penarol],
    2013.0: [n.lanus,n.pontepreta,n.libertad,n.saopaulo,             n.riverplate,n.velez,n.rionegroaguilas,n.atleticonacional,  n.lau,n.deppasto,n.univcatolica,n.bahia,n.laequidad,n.sport,n.coritiba,n.lduloja],
    2012.0: [n.saopaulo,n.tigre,n.univcatolica,n.millonarios,        n.lau,n.cerroporteno,n.independiente,n.gremio,          n.lduloja,n.depquito,n.colon,n.barcelonaequ,n.palmeiras,n.liverpoolURU,n.atleticogo,n.emelec],
    2011.0: [n.lau,n.ldu,n.vasco,n.velez,                            n.arsenalsarandi,n.libertad,n.universitario,n.santafe,  n.flamengo,n.independiente,n.saopaulo,n.botafogo,n.univcatolica,n.godoycruz,n.aurora,n.olimpia],
    2010.0: [n.independiente,n.goias,n.ldu,n.palmeiras,              n.tolima,n.avai,n.newells,n.atleticomg,                 n.defensor,n.penarol,n.emelec,n.santafe,n.sucre,n.sanJoseBOL,n.sanfelipe,n.banfield],
    2009.0: [n.ldu,n.fluminense,n.riverURU,n.cerroporteno,           n.velez,n.lau,n.sanlorenzo,n.botafogo,                  n.lanus,n.alianzasullana,n.vitoria,n.goias,n.cienciano,n.unionespanola,n.emelec,n.internacional],
    2008.0: [n.internacional,n.estudiantes,n.chivas,n.argentinojuniors,  n.bocajuniors,n.botafogo,n.riverplate,n.palmeiras,  n.univcatolica,n.arsenalsarandi,n.ancash,n.sanluis,n.americadecali,n.defensor,n.atleticopr,n.ldu],
    2007.0: [n.arsenalsarandi,n.americamex,n.riverplate,n.millonarios,   n.chivas,n.vasco,n.defensor,n.saopaulo,             n.goias,n.pachuca,n.botafogo,n.colocolo,n.dcunited,n.lanus,n.elnacional,n.bocajuniors],
    2006.0: [n.pachuca,n.colocolo,n.atleticopr,n.toluca,             n.lanus,n.gimnasia,n.nacional,n.sanlorenzo,             n.tolima,n.alajuelense,n.riverplate,n.elnacional,n.corinthians,n.fluminense,n.bocajuniors,n.santos],
    2005.0: [n.bocajuniors,n.pumas,n.univcatolica,n.velez,           n.internacional,n.corinthians,n.fluminense,n.americamex,  n.cerroporteno,n.thestrongest,n.atleticonacional,n.cruzeiro,n.riverplate,n.banfield,n.dcunited,n.rosario],
    2004.0: [n.bocajuniors,n.bolivar,n.internacional,n.ldu,          n.cerroporteno,n.arsenalsarandi,n.junior,n.santos,      n.sanlorenzo,n.concepcion,n.cruzeiro,n.aurora,n.penarol,n.riverplate,n.alianzasullana,n.saopaulo],
    2003.0: [n.cienciano,n.riverplate,n.atleticonacional,n.saopaulo, n.santos,n.libertad,n.bocajuniors,n.thestrongest,       n.univcatolica,n.independiente,n.colon,n.fluminense,n.saocaetano,n.sanlorenzo,n.ldu,n.nacional],
    2002.0: [n.sanlorenzo,n.atleticonacional,n.bolivar,n.nacional,   n.racing,n.santiagowanderers,n.gimnasia,n.alianzalima,  n.monagas,n.americadecali,n.libertad,n.danubio,n.riverplate,n.cobreloa,n.bocajuniors,n.barcelonaequ],
    //COPA CONMEBOL
    2001.0: [],
    2000.0: [],
    1999.0: [n.talleres,n.csa,n.concepcion,n.saoraimundo,            ],
    1998.0: [n.santos,n.rosario,n.sampaio,n.atleticomg,       ],
    1997.0: [n.atleticomg,n.lanus,n.universitario,n.colon,           ],
    1996.0: [n.lanus,n.santafe,n.rosario,n.vasco,             ],
    1995.0: [n.rosario,n.atleticomg,n.colegiales,n.americadecali,],
    1994.0: [n.saopaulo,n.penarol,n.corinthians,n.lau,               ],
    1993.0: [n.botafogo,n.penarol,n.atleticomg,n.sanlorenzo,         ],
    1992.0: [n.atleticomg,n.olimpia,n.elnacional,n.gimnasia,         ],
  },

};