import 'package:fifa/values/club_names.dart';
import 'package:fifa/values/league_names.dart';

ClubName _name = ClubName();
LeagueOfficialNames leagueName = LeagueOfficialNames();

Map<String,dynamic> mapInternationals = {

  /////////////////////////////////////////////////////////////////
  // CONTINENTS CHAMPIONS
  ///////////////////////////////////////////////////////////////

  leagueName.championsLeague : {
    2022.0: [_name.realmadrid,_name.liverpool,_name.manchestercity,_name.villareal,        _name.chelsea,_name.benfica,_name.atleticomadrid,_name.bayernmunique,      _name.psg,_name.inter,_name.sporting,_name.juventus,_name.lille,_name.ajax,_name.manchesterunited,_name.rbsalzburg,                                _name.dortmund,_name.rbleipzig,_name.sheriffTiraspol,_name.barcelona,_name.sevilla,_name.atalanta,_name.porto,_name.zenit,                            _name.youngBoys,_name.wolfsburg,_name.milan,_name.brugge,_name.shaktardonetsk,_name.dinamokiev,_name.malmo,_name.besiktas,],
    2021.0: [_name.chelsea,_name.manchestercity,_name.realmadrid,_name.psg,                  _name.porto,_name.dortmund,_name.liverpool,_name.bayernmunique,          _name.atleticomadrid,_name.moenchengladbach,_name.atalanta,_name.barcelona,_name.juventus,_name.sevilla,_name.rbleipzig,_name.lazio,               _name.rbsalzburg,_name.shaktardonetsk,_name.olympiacos,_name.ajax,_name.krasnodar,_name.brugge,_name.dinamokiev,_name.manchesterunited,       _name.lokomotivMoscou,_name.inter,_name.om,_name.midtjylland,_name.rennes,_name.zenit,_name.ferencvaros,_name.instanbul],
    2020.0: [_name.bayernmunique,_name.psg,_name.lyon,_name.rbleipzig,                       _name.barcelona,_name.atalanta,_name.manchestercity,_name.atleticomadrid, _name.chelsea,_name.dortmund,_name.juventus,_name.tottenham,_name.napoli,_name.valencia,_name.realmadrid,_name.liverpool,                         _name.brugge,_name.olympiacos,_name.shaktardonetsk,_name.leverkusen,_name.rbsalzburg,_name.inter,_name.benfica,_name.ajax,               _name.galatasaray,_name.estrelavermelha,_name.dinamozagreb,_name.lokomotivMoscou,_name.genk,_name.slaviaPraha,_name.zenit,_name.lille],
    2019.0: [_name.liverpool,_name.tottenham,_name.barcelona,_name.ajax,                     _name.porto,_name.manchestercity,_name.manchesterunited,_name.juventus,   _name.bayernmunique,_name.dortmund,_name.lyon,_name.realmadrid,_name.roma,_name.schalke04,_name.psg,_name.atleticomadrid,                         _name.brugge,_name.inter,_name.napoli,_name.galatasaray,_name.benfica,_name.shaktardonetsk,_name.viktoriaPlzen,_name.valencia,                _name.monaco,_name.psv,_name.estrelavermelha,_name.lokomotivMoscou,_name.aek,_name.hoffenheim,_name.cska,_name.youngBoys],
    2018.0: [_name.realmadrid,_name.liverpool,_name.bayernmunique,_name.roma,                _name.sevilla,_name.manchestercity,_name.juventus,_name.barcelona,      _name.psg,_name.porto,_name.besiktas,_name.shaktardonetsk,_name.manchesterunited,_name.basel,_name.tottenham,_name.chelsea,                         _name.cska,_name.celtic,_name.atleticomadrid,_name.sporting,_name.spartakmoscou,_name.napoli,_name.rbleipzig,_name.dortmund,          _name.benfica,_name.anderlecht,_name.qarabag,_name.olympiacos,_name.maribor,_name.feyenoord,_name.monaco,_name.apoel],
    2017.0: [_name.realmadrid,_name.juventus,_name.atleticomadrid,_name.monaco,              _name.bayernmunique,_name.barcelona,_name.leicester,_name.dortmund,     _name.napoli,_name.porto,_name.leverkusen,_name.manchestercity,_name.arsenal,_name.psg,_name.sevilla,_name.benfica,                                 _name.ludogorets,_name.besiktas,_name.moenchengladbach,_name.rostov,_name.tottenham,_name.legiaWarszawa,_name.copenhague,_name.lyon,          _name.basel,_name.dinamokiev,_name.celtic,_name.psv,_name.cska,_name.sporting,_name.brugge,_name.dinamozagreb],
    2016.0: [_name.realmadrid,_name.atleticomadrid,_name.bayernmunique,_name.manchestercity, _name.wolfsburg,_name.barcelona,_name.benfica,_name.psg,                _name.roma,_name.psv,_name.juventus,_name.dinamokiev,_name.gent,_name.arsenal,_name.zenit,_name.chelsea,                                            _name.shaktardonetsk,_name.manchesterunited,_name.galatasaray,_name.sevilla,_name.leverkusen,_name.olympiacos,_name.porto,_name.valencia, _name.malmo,_name.cska,_name.astana,_name.moenchengladbach,_name.bate,_name.dinamozagreb,_name.maccabiTelAviv,_name.lyon],
    2015.0: [_name.barcelona,_name.juventus,_name.bayernmunique,_name.realmadrid,            _name.psg,_name.monaco,_name.porto,_name.atleticomadrid,                _name.manchestercity,_name.dortmund,_name.shaktardonetsk,_name.schalke04,_name.chelsea,_name.arsenal,_name.basel,_name.leverkusen,                  _name.olympiacos,_name.liverpool,_name.zenit,_name.anderlecht,_name.roma,_name.ajax,_name.sporting,_name.athleticbilbao,                      _name.malmo,_name.ludogorets,_name.benfica,_name.galatasaray,_name.cska,_name.apoel,_name.maribor,_name.bate],
    2014.0: [_name.realmadrid,_name.atleticomadrid,_name.bayernmunique,_name.chelsea,        _name.dortmund,_name.barcelona,_name.manchesterunited,_name.psg,        _name.schalke04,_name.milan,_name.arsenal,_name.galatasaray,_name.zenit,_name.manchestercity,_name.olympiacos,_name.leverkusen,                     _name.shaktardonetsk,_name.juventus,_name.benfica,_name.viktoriaPlzen,_name.basel,_name.napoli,_name.porto,_name.ajax,                        _name.realsociedad,_name.copenhague,_name.anderlecht,_name.cska,_name.steauaBucuresti,_name.om,_name.austria,_name.celtic],
    2013.0: [_name.bayernmunique,_name.dortmund,_name.barcelona,_name.realmadrid,            _name.juventus,_name.malaga,_name.psg,_name.galatasaray,                _name.arsenal,_name.shaktardonetsk,_name.milan,_name.manchesterunited,_name.celtic,_name.porto,_name.valencia,_name.schalke04,                      _name.dinamokiev,_name.olympiacos,_name.zenit,_name.ajax,_name.chelsea,_name.bate,_name.benfica,_name.cluj,                                   _name.dinamozagreb,_name.montpellier,_name.anderlecht,_name.manchestercity,_name.nordsjaelland,_name.lille,_name.spartakmoscou,_name.braga],
    2012.0: [_name.chelsea,_name.bayernmunique,_name.barcelona,_name.realmadrid,             _name.benfica,_name.om,_name.milan,_name.apoel,                         _name.napoli,_name.basel,_name.leverkusen,_name.cska,_name.zenit,_name.inter,_name.arsenal,_name.lyon,                                              _name.manchestercity,_name.trabzonspor,_name.manchesterunited,_name.ajax,_name.valencia,_name.olympiacos,_name.porto,_name.viktoriaPlzen,     _name.villareal,_name.lille,_name.otelul,_name.dinamozagreb,_name.genk,_name.dortmund,_name.shaktardonetsk,_name.bate],
    2011.0: [_name.barcelona,_name.manchesterunited,_name.realmadrid,_name.schalke04,        _name.shaktardonetsk,_name.chelsea,_name.tottenham,_name.inter,         _name.arsenal,_name.om,_name.lyon,_name.valencia,_name.roma,_name.copenhague,_name.milan,_name.bayernmunique,                                       _name.twente,_name.benfica,_name.rangers,_name.rubinKazan,_name.basel,_name.spartakmoscou,_name.ajax,_name.braga,                             _name.werderbremen,_name.hapoelTelAviv,_name.bursaspor,_name.panathinaikos,_name.cluj,_name.zilina,_name.auxerre,_name.partizan],
    2010.0: [_name.inter,_name.bayernmunique,_name.barcelona,_name.lyon,                     _name.cska,_name.manchesterunited,_name.arsenal,_name.bordeaux,         _name.chelsea,_name.fiorentina,_name.stuttgart,_name.realmadrid,_name.sevilla,_name.milan,_name.porto,_name.olympiacos,                             _name.juventus,_name.wolfsburg,_name.om,_name.atleticomadrid,_name.liverpool,_name.rubinKazan,_name.unirea,_name.standardliege,               _name.maccabiHaifa,_name.besiktas,_name.zurich,_name.apoel,_name.debreceni,_name.dinamokiev,_name.rangers,_name.az],
    2009.0: [_name.barcelona,_name.manchesterunited,_name.chelsea,_name.arsenal,             _name.bayernmunique,_name.porto,_name.liverpool,_name.villareal,        _name.lyon,_name.inter,_name.juventus,_name.roma,_name.sporting,_name.atleticomadrid,_name.realmadrid,_name.panathinaikos,                          _name.bordeaux,_name.werderbremen,_name.shaktardonetsk,_name.om,_name.aalborg,_name.fiorentina,_name.dinamokiev,_name.zenit,                  _name.cluj,_name.anorthosis,_name.basel,_name.psv,_name.celtic,_name.steauaBucuresti,_name.fenerbahce,_name.bate],
    2008.0: [_name.manchesterunited,_name.chelsea,_name.barcelona,_name.liverpool,           _name.roma,_name.fenerbahce,_name.schalke04,_name.arsenal,              _name.porto,_name.celtic,_name.realmadrid,_name.lyon,_name.milan,_name.inter,_name.sevilla,_name.olympiacos,                                        _name.om,_name.rosenborg,_name.werderbremen,_name.benfica,_name.rangers,_name.sporting,_name.psv,_name.slaviaPraha,                           _name.besiktas,_name.valencia,_name.lazio,_name.shaktardonetsk,_name.stuttgart,_name.dinamokiev,_name.cska,_name.steauaBucuresti],
    2007.0: [_name.milan,_name.liverpool,_name.chelsea,_name.manchesterunited,               _name.psv,_name.bayernmunique,_name.valencia,_name.roma,                _name.lyon,_name.lille,_name.celtic,_name.realmadrid,_name.porto,_name.inter,_name.arsenal,_name.barcelona,                                         _name.werderbremen,_name.spartakmoscou,_name.bordeaux,_name.shaktardonetsk,_name.steauaBucuresti,_name.benfica,_name.cska,_name.aek,          _name.levskiSofia,_name.sporting,_name.galatasaray,_name.olympiacos,_name.dinamokiev,_name.copenhague,_name.hamburgo,_name.anderlecht],
    2006.0: [_name.barcelona,_name.arsenal,_name.milan,_name.villareal,                      _name.benfica,_name.juventus,_name.lyon,_name.inter,                    _name.liverpool,_name.chelsea,_name.psv,_name.bayernmunique,_name.ajax,_name.rangers,_name.realmadrid,_name.werderbremen,                           _name.brugge,_name.thun,_name.udinese,_name.manchesterunited,_name.schalke04,_name.rosenborg,_name.realbetis,_name.petrzalka,                 _name.rapidviena,_name.spartapraga,_name.panathinaikos,_name.lille,_name.fenerbahce,_name.olympiacos,_name.anderlecht,_name.porto],
    2005.0: [_name.liverpool,_name.milan,_name.chelsea,_name.psv,                            _name.juventus,_name.inter,_name.bayernmunique,_name.lyon,              _name.manchesterunited,_name.porto,_name.werderbremen,_name.monaco,_name.barcelona,_name.arsenal,_name.leverkusen,_name.realmadrid,                 _name.olympiacos,_name.dinamokiev,_name.ajax,_name.fenerbahce,_name.panathinaikos,_name.shaktardonetsk,_name.valencia,_name.cska,             _name.lacoruna,_name.roma,_name.maccabiTelAviv,_name.spartapraga,_name.rosenborg,_name.celtic,_name.anderlecht,_name.psg],
    2004.0: [_name.porto,_name.monaco,_name.lacoruna,_name.chelsea,                          _name.lyon,_name.realmadrid,_name.milan,_name.arsenal,                  _name.celtavigo,_name.bayernmunique,_name.spartapraga,_name.lokomotivMoscou,_name.stuttgart,_name.manchesterunited,_name.realsociedad,_name.juventus, _name.celtic,_name.inter,_name.psv,_name.galatasaray,_name.rangers,_name.om,_name.besiktas,_name.brugge,                                    _name.anderlecht,_name.dinamokiev,_name.aek,_name.olympiacos,_name.panathinaikos,_name.partizan,_name.lazio,_name.ajax],
    2003.0: [_name.milan,_name.juventus,_name.inter,_name.realmadrid,                        _name.ajax,_name.barcelona,_name.valencia,_name.manchesterunited,       _name.newcastle,_name.leverkusen,_name.arsenal,_name.roma,_name.dortmund,_name.lokomotivMoscou,_name.lacoruna,_name.basel,                          _name.auxerre,_name.liverpool,_name.aek,_name.lyon,_name.dinamokiev,_name.maccabiHaifa,_name.lens,_name.brugge,                               _name.psv,_name.spartakmoscou,_name.genk,_name.rosenborg,_name.feyenoord,_name.olympiacos,_name.bayernmunique,_name.galatasaray],
    2002.0: [_name.realmadrid,_name.leverkusen,_name.barcelona,_name.manchesterunited,       _name.bayernmunique,_name.liverpool,_name.panathinaikos,_name.lacoruna, _name.boavista,_name.nantes,_name.roma,_name.galatasaray,_name.spartapraga,_name.porto,_name.arsenal,_name.juventus,                                _name.lokomotivMoscou,_name.dortmund,_name.mallorca,_name.psv,_name.celtic,_name.lyon,_name.lille,_name.feyenoord,                            _name.anderlecht,_name.dinamokiev,_name.schalke04,_name.lazio,_name.rosenborg,_name.fenerbahce,_name.olympiacos,_name.spartakmoscou],
    2001.0: [_name.bayernmunique,_name.valencia,_name.realmadrid,_name.leeds,                _name.manchesterunited,_name.arsenal,_name.galatasaray,_name.lacoruna,  _name.sturmGraz,_name.panathinaikos,_name.milan,_name.psg,_name.lyon,_name.spartakmoscou,_name.anderlecht,_name.lazio,                              _name.leverkusen,_name.shaktardonetsk,_name.olympiacos,_name.rangers,_name.hamburgo,_name.rosenborg,_name.psv,_name.barcelona,                _name.sporting,_name.spartapraga,_name.heerenveen,_name.monaco,_name.juventus,_name.helsingborg,_name.dinamokiev,_name.besiktas],
    2000.0: [_name.realmadrid,_name.valencia,_name.bayernmunique,_name.barcelona,            _name.manchesterunited,_name.porto,_name.lazio,_name.chelsea,           _name.spartapraga,_name.herthaberlim,_name.fiorentina,_name.bordeaux,_name.dinamokiev,_name.rosenborg,_name.feyenoord,_name.om,                     _name.leverkusen,_name.arsenal,_name.dortmund,_name.sturmGraz,_name.olympiacos,_name.rangers,_name.spartakmoscou,_name.galatasaray, _name.maribor,_name.aik,_name.boavista,_name.dinamozagreb,_name.molde,_name.psv,_name.willem,_name.milan],
    1999.0: [_name.manchesterunited,_name.bayernmunique,_name.juventus,_name.dinamokiev,     _name.inter,_name.olympiacos,_name.kaiserslautern,_name.realmadrid,     _name.galatasaray,_name.benfica,_name.lens,_name.dinamozagreb,_name.arsenal,_name.barcelona,_name.spartakmoscou,_name.rosenborg,                    _name.porto,_name.psv,                     _name.ajax,_name.athleticbilbao,_name.sturmGraz,_name.brondby,_name.panathinaikos,_name.helsinki],
    1998.0: [_name.realmadrid,_name.juventus,_name.dortmund,_name.monaco,                    _name.dinamokiev,_name.bayernmunique,_name.manchesterunited,_name.leverkusen,  _name.psg,_name.rosenborg,_name.psv,_name.parma,_name.feyenoord,_name.sporting,_name.newcastle,_name.besiktas,                               _name.olympiacos,_name.spartapraga,        _name.galatasaray,_name.kosice,_name.barcelona,_name.porto,_name.ifkgoteborg,_name.lierse],
    1997.0: [_name.dortmund,_name.juventus,_name.manchesterunited,_name.ajax,             _name.porto,_name.atleticomadrid,_name.rosenborg,_name.auxerre,            _name.grasshoppers,_name.rangers,_name.widzew,_name.steauaBucuresti,_name.fenerbahce,_name.rapidviena,_name.milan,_name.ifkgoteborg,                ],
    1996.0: [_name.juventus,_name.ajax,_name.nantes,_name.panathinaikos,                  _name.spartakmoscou,_name.realmadrid,_name.legiaWarszawa,_name.dortmund,   _name.porto,_name.dinamokiev,_name.rosenborg,_name.blackburn,_name.steauaBucuresti,_name.rangers,_name.ferencvaros,_name.grasshoppers,              ],
    1995.0: [_name.ajax,_name.milan,_name.bayernmunique,_name.psg,                        _name.barcelona,_name.ifkgoteborg,_name.hadjuksplit,_name.benfica,         _name.manchesterunited,_name.galatasaray,_name.spartakmoscou,_name.dinamokiev,_name.steauaBucuresti,_name.anderlecht,_name.rbsalzburg,_name.aek,    ],
    1994.0: [_name.milan,_name.barcelona,_name.monaco,_name.porto,                        _name.werderbremen,_name.anderlecht,_name.spartakmoscou,_name.galatasaray, _name.feyenoord,_name.steauaBucuresti,_name.levskiSofia,_name.copenhague,_name.spartapraga,_name.manchesterunited,_name.lechPoznan,_name.austria,        ],
    1993.0: [_name.om,_name.milan,_name.rangers,_name.ifkgoteborg,                        _name.brugge,_name.porto,_name.cska,_name.psv,                             _name.lechPoznan,_name.leeds,_name.slovanBratislava,_name.dinamoBucuresti,_name.austria,_name.sion,_name.aek,_name.barcelona,                       ],
    1992.0: [_name.barcelona,_name.sampdoria,_name.spartapraga,_name.estrelavermelha,     _name.benfica,_name.anderlecht,_name.dinamokiev,_name.panathinaikos,       _name.kaiserslautern,_name.om,_name.arsenal,_name.brondby,_name.ifkgoteborg,_name.psv,_name.apollon,_name.honved,                                   ],
    1991.0: [_name.estrelavermelha,_name.om,_name.bayernmunique,_name.spartakmoscou,      _name.porto,_name.realmadrid,_name.dynamoDresden,_name.milan,              _name.cskaSofia,_name.dinamoBucuresti,_name.rangers,_name.malmo,_name.napoli,_name.tirol,_name.brugge,_name.lechPoznan,                             ],
    1990.0: [_name.milan,_name.benfica,_name.bayernmunique,_name.om,                      _name.mechelen,_name.cskaSofia,_name.psv,_name.dnipro,                     _name.malmo,_name.realmadrid,_name.tiranafk,_name.steauaBucuresti,_name.spartapraga,_name.aek,_name.honved,_name.tirol,                               ],
    1989.0: [_name.milan,_name.steauaBucuresti,_name.realmadrid,_name.galatasaray,        _name.werderbremen,_name.ifkgoteborg,_name.monaco,_name.psv,               _name.porto,_name.gornik,_name.celtic,_name.estrelavermelha,_name.tiranafk,_name.spartakmoscou,_name.brugge,_name.neuchatel,                          ],
    1988.0: [_name.psv,_name.benfica,_name.realmadrid,_name.steauaBucuresti,              _name.bordeaux,_name.anderlecht,_name.bayernmunique,_name.rangers,         _name.neuchatel,_name.porto,_name.lillestrom,_name.rapidviena,_name.omonia,_name.gornik,_name.aarhus,_name.spartapraga,                       ],
    1987.0: [_name.porto,_name.bayernmunique,_name.dinamokiev,_name.realmadrid,           _name.anderlecht,_name.estrelavermelha,_name.brondby,_name.besiktas,       _name.vitkovice,_name.berliner,_name.apoel,_name.celtic,_name.austria,_name.steauaBucuresti,_name.rosenborg,_name.juventus,                   ],
    1986.0: [_name.steauaBucuresti,_name.barcelona,_name.anderlecht,_name.ifkgoteborg,    _name.bayernmunique,_name.aberdeen,_name.juventus,_name.kuusysi,           _name.austria,_name.omonia,_name.honved,_name.zenit,_name.servette,_name.fenerbahce,_name.porto,_name.hellasVerona,                           ],
    1985.0: [_name.juventus,_name.liverpool,_name.bordeaux,_name.panathinaikos,        _name.dnipro,_name.ifkgoteborg,_name.austria,_name.spartapraga,               _name.grasshoppers,_name.lyngby,_name.dinamoBucuresti,_name.levskiSofia,_name.berliner,_name.benfica,_name.beveren,_name.linfield,                 ],
    1984.0: [_name.liverpool,_name.roma,_name.dinamoBucuresti,_name.dundee,            _name.dinamoMinsk,_name.rapidviena,_name.berliner,_name.benfica,              _name.athleticbilbao,_name.olympiacos,_name.gyori,_name.hamburgo,_name.bohemians,_name.standardliege,_name.cskaSofia,_name.partizan,          ],
    1983.0: [_name.hamburgo,_name.juventus,_name.realsociedad,_name.widzew,            _name.sporting,_name.liverpool,_name.astonvilla,_name.dinamokiev,             _name.cskaSofia,_name.celtic,_name.tiranafk,_name.olympiacos,_name.dinamoBucuresti,_name.standardliege,_name.rapidviena,_name.helsinki,         ],
    1982.0: [_name.astonvilla,_name.bayernmunique,_name.anderlecht,_name.newsaints,    _name.estrelavermelha,_name.liverpool,_name.craiova,_name.dinamokiev,         _name.austria,_name.berliner,_name.juventus,_name.zalgiris,_name.az,_name.glentoran,_name.copenhague,_name.benfica,                    ],
    1981.0: [_name.liverpool,_name.realmadrid,_name.inter,_name.bayernmunique,         _name.banikostrava,_name.estrelavermelha,_name.spartakmoscou,_name.tbilisi,   _name.aberdeen,_name.szombierki,_name.ajax,_name.berliner,_name.esbjerg,_name.honved,_name.nantes,_name.basel,                                ],
    1980.0: [_name.nottinghamforest,_name.hamburgo,_name.realmadrid,_name.ajax,        _name.celtic,_name.hadjuksplit,_name.strasbourg,_name.berliner,               _name.argesPitesti,_name.servette,_name.dukla,_name.omonia,_name.dundalk,_name.porto,_name.tbilisi,_name.vejle,                                    ],
    1979.0: [_name.nottinghamforest,_name.malmo,_name.colonia,_name.austria,           _name.rangers,_name.wislaKrakow,_name.dynamoDresden,_name.grasshoppers,             _name.aek,_name.realmadrid,_name.loksofia,_name.psv,_name.lillestrom,_name.bohemian,_name.brno,_name.dinamokiev,                              ],
    1978.0: [_name.liverpool,_name.brugge,_name.moenchengladbach,_name.juventus,       _name.ajax,_name.atleticomadrid,_name.benfica,_name.innsbruck,                _name.celtic,_name.estrelavermelha,_name.glentoran,_name.levskiSofia,_name.panathinaikos,_name.dynamoDresden,_name.nantes,_name.b1903,             ],
    1977.0: [_name.liverpool,_name.moenchengladbach,_name.zurich,_name.dinamokiev,     _name.brugge,_name.saintetienne,_name.dynamoDresden,_name.bayernmunique,      _name.torino,_name.psv,_name.realmadrid,_name.turku,_name.banikostrava,_name.ferencvaros,_name.trabzonspor,_name.paok,                        ],
    1976.0: [_name.bayernmunique,_name.saintetienne,_name.realmadrid,_name.psv,        _name.benfica,_name.dinamokiev,_name.moenchengladbach,_name.hadjuksplit,      _name.akraness,_name.derbycount,_name.juventus,_name.molenbeek,_name.malmo,_name.rangers,_name.ruchchorzow,_name.ujpest,                      ],
    1975.0: [_name.bayernmunique,_name.leeds,_name.saintetienne,_name.barcelona,       _name.atvidabergs,_name.anderlecht,_name.ruchchorzow,_name.araratYerevan,           _name.feyenoord,_name.hadjuksplit,_name.magdeburg,_name.helsinki,_name.cork,_name.olympiacos,_name.ujpest,_name.fenerbahce,                   ],
    1974.0: [_name.bayernmunique,_name.atleticomadrid,_name.ujpest,_name.celtic,       _name.basel,_name.cskaSofia,_name.estrelavermelha,_name.trnava,               _name.liverpool,_name.zorya,_name.vejle,_name.brugge,_name.dinamoBucuresti,_name.dynamoDresden,_name.ajax,_name.benfica,                      ],
    1973.0: [_name.ajax,_name.juventus,_name.realmadrid,_name.derbycount,              _name.trnava,_name.dinamokiev,_name.bayernmunique,_name.ujpest,               _name.omonia,_name.celtic,_name.anderlecht,_name.gornik,_name.magdeburg,_name.argesPitesti,_name.benfica,_name.cskaSofia,                          ],
    1972.0: [_name.ajax,_name.inter,_name.benfica,_name.celtic,                        _name.ujpest,_name.standardliege,_name.arsenal,_name.feyenoord,               _name.dinamoBucuresti,_name.cska,_name.valencia,_name.grasshoppers,_name.sliema,_name.om,_name.cskaSofia,_name.moenchengladbach,              ],
    1971.0: [_name.ajax,_name.panathinaikos,_name.atleticomadrid,_name.estrelavermelha, _name.everton,_name.legiaWarszawa,_name.celtic,_name.carlzeissjena,          _name.sporting,_name.moenchengladbach,_name.cagliari,_name.standardliege,_name.basel,_name.waterford,_name.slovanBratislava,_name.arad,       ],
    1970.0: [_name.feyenoord,_name.celtic,_name.legiaWarszawa,_name.leeds,             _name.fiorentina,_name.galatasaray,_name.vorwarts,_name.standardliege,        _name.dinamokiev,_name.benfica,_name.ferencvaros,_name.trnava,_name.saintetienne,_name.milan,_name.estrelavermelha,_name.realmadrid,          ],
    1969.0: [_name.milan,_name.ajax,_name.manchesterunited,_name.trnava,               _name.benfica,_name.celtic,_name.aek,_name.rapidviena,                        _name.anderlecht,_name.estrelavermelha,_name.fenerbahce,_name.realmadrid,_name.ab,_name.lahti,                                                ],
    1968.0: [_name.manchesterunited,_name.benfica,_name.realmadrid,_name.juventus,     _name.braunschweiger,_name.gornik,_name.vasas,_name.spartapraga,     _name.sarajevo,_name.rapidviena,_name.hvidovre,_name.valur,_name.saintetienne,_name.dinamokiev,_name.rapidBucuresti,_name.anderlecht,         ],
    1967.0: [_name.celtic,_name.inter,_name.dukla,_name.cskaSofia,                     _name.realmadrid,_name.linfield,_name.ajax,_name.vojvodina,                   _name.valerenga,_name.atleticomadrid,_name.vasas,_name.anderlecht,_name.munique1860,_name.gornik,_name.nantes,_name.liverpool,                ],
    1966.0: [_name.realmadrid,_name.partizan,_name.inter,_name.manchesterunited,       _name.benfica,_name.anderlecht,_name.ferencvaros,_name.spartapraga,           _name.werderbremen,_name.panathinaikos,_name.levskiSofia,_name.kilmarnock,_name.vorwarts,_name.derry,_name.gornik,_name.dinamoBucuresti,           ],
    1965.0: [_name.inter,_name.benfica,_name.liverpool,_name.gyori,                    _name.colonia,_name.rangers,_name.dws,_name.realmadrid,                       _name.lyn,_name.chauxdefonds,_name.dinamoBucuresti,_name.panathinaikos,_name.loksofia,_name.dukla,_name.rapidviena,_name.anderlecht,          ],
    1964.0: [_name.inter,_name.realmadrid,_name.dortmund,_name.zurich,                 _name.milan,_name.partizan,_name.psv,_name.dukla,                             _name.benfica,_name.gornik,_name.dinamoBucuresti,_name.galatasaray,_name.monaco,_name.norrkoping,_name.spartakPlovdiv,_name.jeunesseesch,            ],
    1963.0: [_name.milan,_name.benfica,_name.dundee,_name.feyenoord,                   _name.galatasaray,_name.reims,_name.dukla,_name.anderlecht,                   _name.austria,_name.sporting,_name.norrkoping,_name.cskaSofia,_name.esbjerg,_name.ipswichTown,_name.vasas,_name.poloniabytom,                 ],
    1962.0: [_name.benfica,_name.realmadrid,_name.tottenham,_name.standardliege,       _name.nurnberg,_name.rangers,_name.juventus,_name.dukla,                      _name.fenerbahce,_name.austria,_name.feyenoord,_name.servette,_name.partizan,_name.vorwarts,_name.b1903,_name.haka,                           ],
    1961.0: [_name.benfica,_name.barcelona,_name.rapidviena,_name.hamburgo,            _name.aarhus,_name.hradec,_name.burnley,_name.malmo,                          _name.youngBoys,_name.panathinaikos,_name.ujpest,_name.realmadrid,_name.reims,_name.cskaSofia,_name.fredrikstad,_name.erzgebirgeaue,          ],
    1960.0: [_name.realmadrid,_name.eintrachtfrankfurt,_name.barcelona,_name.rangers,  _name.nice,_name.wiener,_name.wolves,_name.spartarotterdam,                   _name.jeunesseesch,_name.ifkgoteborg,_name.milan,_name.estrelavermelha,_name.fenerbahce,_name.b1909,_name.interBratislava,_name.youngBoys,    ],
    1959.0: [_name.realmadrid,_name.reims,_name.atleticomadrid,_name.youngBoys,        _name.standardliege,_name.wiener,_name.erzgebirgeaue,_name.schalke04,         _name.sporting,_name.dukla,_name.cskaSofia,_name.ifkgoteborg,_name.wolves,_name.besiktas,_name.helsinki,_name.mtk,                            ],
    1958.0: [_name.realmadrid,_name.milan,_name.vasas,_name.manchesterunited,          _name.estrelavermelha,_name.sevilla,_name.ajax,_name.dortmund,                _name.royalAntwerp,_name.norrkoping,_name.erzgebirgeaue,_name.youngBoys,_name.steauaBucuresti,_name.aarhus,_name.rangers,                     ],
    1957.0: [_name.realmadrid,_name.fiorentina,_name.manchesterunited,_name.estrelavermelha, _name.nice,_name.grasshoppers,_name.athleticbilbao,_name.cskaSofia,     _name.dortmund,_name.rapidviena,_name.dinamoBucuresti,_name.slovanBratislava,_name.rangers,_name.norrkoping,_name.honved,_name.rapidjc,       ],
    1956.0: [_name.realmadrid,_name.reims,_name.hibernian,_name.milan,                 _name.partizan,_name.mtk,_name.rapidviena,_name.djurgarden,                   _name.sporting,_name.anderlecht,_name.servette,_name.rotWeissEssen,_name.psv,_name.aarhus,_name.saarbrucken,_name.gwardia,                    ],
  },

  leagueName.libertadores : {
    2022.0: [_name.atleticopr,_name.flamengo,_name.velez,_name.palmeiras,             _name.atleticomg,_name.estudiantes,_name.talleres,_name.corinthians,             _name.riverplate,_name.cerroporteno,_name.bocajuniors,_name.fortaleza,_name.colon,_name.tolima,_name.libertad,_name.emelec,                  _name.olimpia,_name.deportivocali,_name.idelvalle,_name.nacional,_name.colocolo,_name.tachira,_name.theStrongest,_name.univcatolica,    _name.caracas,_name.bragantino,_name.penarol,_name.alwaysReady,_name.sportingcristal,_name.americamg,_name.alianzalima,_name.indPetrolero],
    2021.0: [_name.palmeiras,_name.flamengo,_name.atleticomg,_name.barcelonaequ,      _name.saopaulo,_name.olimpia,_name.riverplate,_name.fluminense,                  _name.cerroporteno,_name.bocajuniors,_name.racing,_name.velez,_name.univcatolica,_name.defensayjusticia,_name.argentinojuniors,_name.internacional,  _name.idelvalle,_name.tachira,_name.santos,_name.junior,_name.sportingcristal,_name.nacional,_name.ldu,_name.americadecali,        _name.universitario,_name.alwaysReady,_name.theStrongest,_name.santafe,_name.rentistas,_name.atleticonacional,_name.laCalera,_name.laGuaira],
    2020.0: [_name.palmeiras,_name.santos,_name.riverplate,_name.bocajuniors,         _name.libertad,_name.gremio,_name.nacional,_name.racing,                         _name.ldu,_name.atleticopr,_name.flamengo,_name.delfin,_name.idelvalle,_name.jorge,_name.guaraniPAR,_name.internacional,                     _name.junior,_name.bolivar,_name.penarol,_name.saopaulo,_name.univcatolica,_name.estudiantesmerida,_name.defensayjusticia,_name.caracas,        _name.barcelonaequ,_name.tigre,_name.colocolo,_name.binacional,_name.americadecali,_name.alianzalima,_name.olimpia,_name.imedellin],
    2019.0: [_name.flamengo,_name.riverplate,_name.gremio,_name.bocajuniors,          _name.palmeiras,_name.ldu,_name.internacional,_name.cerroporteno,                _name.cruzeiro,_name.olimpia,_name.godoycruz,_name.sanlorenzo,_name.nacional,_name.atleticopr,_name.emelec,_name.libertad,                   _name.palestino,_name.deplara,_name.sportingcristal,_name.penarol,_name.atleticomg,_name.melgar,_name.tolima,_name.univcatolica,     _name.alianzalima,_name.huracan,_name.concepcion,_name.sanJoseBOL,_name.zamora,_name.junior,_name.jorge,_name.rosario],
    2018.0: [_name.riverplate,_name.bocajuniors,_name.gremio,_name.palmeiras,         _name.atleticoTucuman,_name.independiente,_name.cruzeiro,_name.colocolo,         _name.estudiantes,_name.libertad,_name.corinthians,_name.flamengo,_name.racing,_name.atleticonacional,_name.cerroporteno,_name.santos,       _name.defensor,_name.bolivar,_name.penarol,_name.santafe,_name.vasco,_name.nacional,_name.millonarios,_name.junior,                  _name.monagas,_name.delfin,_name.theStrongest,_name.emelec,_name.lau,_name.cusco,_name.deplara,_name.alianzalima],
    2017.0: [_name.gremio,_name.lanus,_name.barcelonaequ,_name.riverplate,            _name.sanlorenzo,_name.santos,_name.botafogo,_name.jorge,                        _name.godoycruz,_name.guaraniPAR,_name.atleticopr,_name.atleticomg,_name.palmeiras,_name.theStrongest,_name.emelec,_name.nacional,           _name.estudiantes,_name.santafe,_name.imedellin,_name.flamengo,_name.atleticoTucuman,_name.libertad,_name.chapecoense,_name.iquique,  _name.atleticonacional,_name.sportingcristal,_name.melgar,_name.univcatolica,_name.penarol,_name.sportboys,_name.zulia,_name.zamora],
    2016.0: [_name.atleticonacional,_name.idelvalle,_name.saopaulo,_name.bocajuniors, _name.atleticomg,_name.nacional,_name.rosario,_name.pumas,                _name.huracan,_name.tachira,_name.racing,_name.gremio,_name.corinthians,_name.riverplate,_name.cerroporteno,_name.toluca,           _name.theStrongest,_name.palmeiras,_name.bolivar,_name.penarol,_name.colocolo,_name.sanlorenzo,_name.olimpia,_name.santafe,          _name.trujillanos,_name.riverURU,_name.deportivocali,_name.sportingcristal,_name.melgar,_name.ldu,_name.emelec,_name.cobresal],
    2015.0: [_name.riverplate,_name.tigres,_name.guaraniPAR,_name.internacional,      _name.emelec,_name.santafe,_name.racing,_name.cruzeiro,                          _name.sucre,_name.estudiantes,_name.corinthians,_name.saopaulo,_name.atleticomg,_name.montWanderers,_name.bocajuniors,_name.atleticonacional,    _name.colocolo,_name.sanlorenzo,_name.huracan,_name.theStrongest,_name.palestino,_name.juanaurich,_name.libertad,_name.sportingcristal,   _name.atlas,_name.danubio,_name.mineros,_name.lau,_name.zamora,_name.sanJoseBOL,_name.barcelonaequ,_name.tachira],
    2014.0: [_name.sanlorenzo,_name.nacionalPAR,_name.bolivar,_name.defensor,         _name.arsenalsarandi,_name.cruzeiro,_name.lanus,_name.atleticonacional,          _name.santosLaguna,_name.leon,_name.cerroporteno,_name.theStrongest,_name.velez,_name.gremio,_name.atleticomg,_name.unionespanola,  _name.atleticopr,_name.idelvalle,_name.deportivocali,_name.zamora,_name.lau,_name.newells,_name.flamengo,_name.penarol,          _name.universitario,_name.botafogo,_name.ohiggins,_name.santafe,_name.cusco,_name.nacional,_name.emelec,_name.anzoategui],
    2013.0: [_name.atleticomg,_name.olimpia,_name.newells,_name.santafe,              _name.cusco,_name.fluminense,_name.bocajuniors,_name.tijuana,                _name.velez,_name.nacional,_name.tigre,_name.palmeiras,_name.gremio,_name.corinthians,_name.saopaulo,_name.emelec,                  _name.toluca,_name.libertad,_name.arsenalsarandi,_name.penarol,_name.sanJoseBOL,_name.tolima,_name.lau,_name.huachipato,             _name.barcelonaequ,_name.sportingcristal,_name.theStrongest,_name.iquique,_name.millonarios,_name.cerroporteno,_name.deplara,_name.caracas],
    2012.0: [_name.corinthians,_name.bocajuniors,_name.santos,_name.lau,              _name.libertad,_name.vasco,_name.fluminense,_name.velez,                _name.bolivar,_name.internacional,_name.atleticonacional,_name.cruzazul,_name.unionespanola,_name.emelec,_name.lanus,_name.depquito,         _name.theStrongest,_name.flamengo,_name.junior,_name.arsenalsarandi,_name.nacional,_name.nacionalPAR,_name.defensor,_name.godoycruz, _name.juanaurich,_name.olimpia,_name.univcatolica,_name.zamora,_name.alianzalima,_name.tachira,_name.chivas,_name.penarol],
    2011.0: [_name.santos,_name.penarol,_name.cerroporteno,_name.velez,      _name.univcatolica,_name.oncecaldas,_name.libertad,_name.jaguares,               _name.gremio,_name.ldu,_name.estudiantes,_name.junior,_name.cruzeiro,_name.americamex,_name.internacional,_name.fluminense,                  _name.unisanmartin,_name.orientePetrolero,_name.nacional,_name.caracas,_name.colocolo,_name.emelec,_name.tolima,_name.independiente, _name.sanluis,_name.leonhuanuco,_name.argentinojuniors,_name.unionespanola,_name.tachira,_name.jorge,_name.guaraniPAR,_name.godoycruz],
    2010.0: [_name.internacional,_name.chivas,_name.saopaulo,_name.lau,    _name.libertad,_name.flamengo,_name.cruzeiro,_name.estudiantes,                  _name.sanluis,_name.velez,_name.universitario,_name.banfield,_name.corinthians,_name.nacional,_name.alianzalima,_name.oncecaldas,   _name.imedellin,_name.monterrey,_name.juanaurich,_name.lanus,_name.cerrouru,_name.morelia,_name.colocolo,_name.univcatolica,         _name.cerroporteno,_name.nacionalPAR,_name.bolivar,_name.blooming,_name.emelec,_name.depcuenca,_name.depitalia,_name.caracas],
    2009.0: [_name.estudiantes,_name.cruzeiro,_name.nacional,_name.gremio,            _name.caracas,_name.saopaulo,_name.defensor,_name.palmeiras,                      _name.sport,_name.unisanmartin,_name.depcuenca,_name.libertad,_name.lau,_name.sanluis,_name.chivas,_name.bocajuniors,             _name.colocolo,_name.tachira,_name.riverplate,_name.imedellin,_name.depquito,_name.evertonchi,_name.boyaca,_name.universitario,  _name.ldu,_name.guaraniPAR,_name.nacionalPAR,_name.americadecali,_name.sucre,_name.lanus,_name.aurora,_name.sanlorenzo],
    2008.0: [_name.ldu,_name.fluminense,_name.americamex,_name.bocajuniors,           _name.sanlorenzo,_name.saopaulo,_name.santos,_name.atlas,                        _name.lanus,_name.estudiantes,_name.cruzeiro,_name.riverplate,_name.flamengo,_name.atleticonacional,_name.nacional,_name.cucuta,             _name.caracas,_name.depcuenca,_name.colocolo,_name.cienciano,_name.univcatolica,_name.chivas,_name.luqueno,_name.arsenalsarandi, _name.realpotosi,_name.danubio,_name.maracaibo,_name.coronel,_name.unisanmartin,_name.sanJoseBOL,_name.audaxItaliano,_name.libertad],
    2007.0: [_name.bocajuniors,_name.gremio,_name.cucuta,_name.santos,                _name.nacional,_name.defensor,_name.americamex,_name.libertad,                   _name.caracas,_name.colocolo,_name.saopaulo,_name.velez,_name.flamengo,_name.parana,_name.necaxa,_name.toluca,                      _name.banfield,_name.audaxItaliano,_name.tolima,_name.internacional,_name.realpotosi,_name.ldu,_name.cienciano,_name.gimnasia,               _name.elnacional,_name.alianzalima,_name.cerroporteno,_name.emelec,_name.maracaibo,_name.riverplate,_name.bolivar,_name.depPasto],
    2006.0: [_name.internacional,_name.saopaulo,_name.libertad,_name.chivas, _name.velez,_name.ldu,_name.estudiantes,_name.riverplate,             _name.goias,_name.atleticonacional,_name.palmeiras,_name.corinthians,_name.santafe,_name.nacional,_name.newells,_name.tigres,                _name.caracas,_name.sportingcristal,_name.unionespanola,_name.univcatolica,_name.rocha,_name.maracaibo,_name.cerroporteno,_name.elnacional,   _name.cienciano,_name.bolivar,_name.theStrongest,_name.deportivocali,_name.universitario,_name.pumas,_name.rosario,_name.paulista],
    2005.0: [_name.saopaulo,_name.atleticopr,_name.riverplate,_name.chivas,  _name.santos,_name.tigres,_name.banfield,_name.bocajuniors,                    _name.cerroporteno,_name.lau,_name.pachuca,_name.junior,_name.palmeiras,_name.oncecaldas,_name.imedellin,_name.ldu,                          _name.americadecali,_name.danubio,_name.quilmes,_name.santoandre,_name.olmedo,_name.alianzalima,_name.cobreloa,_name.sportingcristal,  _name.libertad,_name.bolivar,_name.theStrongest,_name.tachira,_name.nacional,_name.caracas,_name.sanlorenzo,_name.depcuenca],
    2004.0: [_name.oncecaldas,_name.bocajuniors,_name.saopaulo,_name.riverplate,     _name.santos,_name.tachira,_name.deportivocali,_name.saocaetano,         _name.americamex,_name.sportingcristal,_name.santosLaguna,_name.cruzeiro,_name.rosario,_name.nacional,_name.ldu,_name.barcelonaequ,   _name.penarol,_name.velez,_name.caracas,_name.alianzalima,_name.cienciano,_name.tolima,_name.guaraniPAR,_name.bolivar,       _name.theStrongest,_name.fenix,_name.concepcion,_name.cobreloa,_name.elnacional,_name.libertad,_name.jorge,_name.colocolo],
    2003.0: [_name.bocajuniors,_name.santos,_name.americadecali,_name.imedellin,     _name.riverplate,_name.cobreloa,_name.cruzazul,_name.gremio,                      _name.pumas,_name.paysandu,_name.corinthians,_name.racing,_name.deportivocali,_name.nacional,_name.olimpia,_name.cerroporteno,               _name.libertad,_name.sportingcristal,_name.elnacional,_name.gimnasia,_name.bolivar,_name.universitario,_name.barcelonaequ,_name.fenix,  _name.emelec,_name.univcatolica,_name.octubre12,_name.alianzalima,_name.penarol,_name.orientePetrolero,_name.colocolo,_name.theStrongest],
    2002.0: [_name.olimpia,_name.saocaetano,_name.gremio,_name.americamex,           _name.bocajuniors,_name.penarol,_name.nacional,_name.morelia,                     _name.elnacional,_name.cobreloa,_name.riverplate,_name.americadecali,_name.montWanderers,_name.univcatolica,_name.olmedo,_name.cienciano,        _name.cerroporteno,_name.octubre12,_name.sanlorenzo,_name.bolivar,_name.velez,_name.santiagowanderers,_name.talleres,_name.oncecaldas,   _name.alianzalima,_name.orientePetrolero,_name.realpotosi,_name.atleticopr,_name.sportingcristal,_name.emelec,_name.cortulua,_name.flamengo],
    2001.0: [_name.bocajuniors,_name.cruzazul,_name.palmeiras,_name.rosario,  _name.americadecali,_name.riverplate,_name.vasco,_name.cruzeiro,                  _name.emelec,_name.cerroporteno,_name.cobreloa,_name.nacional,_name.concepcion,_name.junior,_name.saocaetano,_name.elnacional,               _name.velez,_name.lau,_name.sanlorenzo,_name.olimpia,_name.guaraniPAR,_name.penarol,_name.defensor,_name.deportivocali,       _name.universitario,_name.sportboys,_name.jorge,_name.sportingcristal,_name.theStrongest,_name.tachira,_name.olmedo,_name.orientePetrolero],
    2000.0: [_name.bocajuniors,_name.palmeiras,_name.americamex,_name.corinthians,   _name.riverplate,_name.bolivar,_name.atlas,_name.atleticomg,                      _name.cerroporteno,_name.elnacional,_name.americadecali,_name.nacional,_name.atleticopr,_name.rosario,_name.junior,_name.penarol,     _name.alianzalima,_name.blooming,_name.olimpia,_name.lau,_name.sanlorenzo,_name.sportingcristal,_name.juventude,_name.bellavista,      _name.emelec,_name.univcatolica,_name.ldu,_name.atleticonacional,_name.universitario,_name.colegiales,_name.theStrongest,_name.cobreloa],
    1999.0: [_name.palmeiras,_name.deportivocali,_name.riverplate,_name.cerroporteno, _name.corinthians,_name.bellavista,_name.estudiantesmerida,_name.velez, _name.colocolo,_name.univcatolica,_name.emelec,_name.nacional,_name.ldu,_name.universitario,_name.vasco,_name.jorge,                         _name.monterrey,_name.oncecaldas,_name.olimpia,_name.sportingcristal,_name.blooming],
    1998.0: [_name.vasco,_name.barcelonaequ,_name.riverplate,_name.cerroporteno,     _name.bolivar,_name.colon,_name.penarol,_name.gremio,                             _name.nacional,_name.cruzeiro,_name.americamex,_name.olimpia,_name.bucaramanga,_name.colocolo,_name.alianzalima,_name.americadecali,         _name.depquito,_name.chivas,_name.univcatolica,_name.orientePetrolero,_name.sportingcristal],
    1997.0: [_name.cruzeiro,_name.sportingcristal,_name.colocolo,_name.racing,       _name.univcatolica,_name.bolivar,_name.penarol,_name.gremio,                      _name.riverplate,_name.millonarios,_name.minerven,_name.velez,_name.elnacional,_name.guaraniPAR,_name.orientePetrolero,_name.nacional,  _name.cerroporteno,_name.emelec,_name.mineros,_name.alianzalima,_name.deportivocali],
    1996.0: [_name.riverplate,_name.americadecali,_name.lau,_name.gremio,            _name.sanlorenzo,_name.junior,_name.barcelonaequ,_name.corinthians,               _name.botafogo,_name.espoli,_name.cerroporteno,_name.minerven,_name.defensor,_name.sanJoseBOL,_name.penarol,_name.sportingcristal,           _name.olimpia,_name.universitario,_name.guabira,_name.univcatolica,_name.caracas],
    1995.0: [_name.gremio,_name.atleticonacional,_name.emelec,_name.riverplate,      _name.palmeiras,_name.millonarios,_name.velez,_name.sportingcristal,     _name.cerroporteno,_name.caracas,_name.olimpia,_name.bolivar,_name.penarol,_name.alianzalima,_name.univcatolica,_name.independiente,         _name.cerrouru,_name.trujillanos,_name.univcatolica,_name.elnacional,_name.jorge],
    1994.0: [_name.velez,_name.saopaulo,_name.junior,_name.olimpia,         _name.minerven,_name.bolivar,_name.imedellin,_name.unionespanola,                 _name.universitario,_name.colocolo,_name.emelec,_name.defensor,_name.barcelonaequ,_name.theStrongest,_name.palmeiras,_name.cruzeiro,         _name.cerroporteno,_name.bocajuniors,_name.alianzalima,_name.nacional,_name.maritimoven],
    1993.0: [_name.saopaulo,_name.univcatolica,_name.americadecali,_name.cerroporteno, _name.flamengo,_name.barcelonaequ,_name.olimpia,_name.sportingcristal,          _name.newells,_name.universitario,_name.elnacional,_name.bolivar,_name.cobreloa,_name.nacional,_name.minerven,_name.atleticonacional,        _name.minerven,_name.sanJoseBOL,_name.bellavista,_name.internacional,_name.riverplate],
    1992.0: [_name.saopaulo,_name.newells,_name.barcelonaequ,_name.americadecali,    _name.sanlorenzo,_name.atleticonacional,_name.cerroporteno,_name.criciuma,        _name.defensor,_name.valdez,_name.maritimoven,_name.univcatolica,_name.nacional,_name.sportingcristal,_name.colocolo,_name.bolivar,          _name.soldeamerica,_name.sportboys,_name.ula,_name.sanJoseBOL,_name.coquimbo],
    1991.0: [_name.colocolo,_name.olimpia,_name.bocajuniors,_name.atleticonacional,  _name.flamengo,_name.cerroporteno,_name.americadecali,_name.nacional,             _name.concepcion,_name.ldu,_name.orientePetrolero,_name.colegiales,_name.universitario,_name.bolivar,_name.tachira,_name.corinthians, _name.riverplate,_name.barcelonaequ,_name.bellavista,_name.sportboys,_name.maritimoven],
    1990.0: [_name.olimpia,_name.barcelonaequ,_name.atleticonacional,_name.riverplate, _name.emelec,_name.vasco,_name.independiente,_name.univcatolica,                _name.progreso,_name.unionhuaral,_name.margarita,_name.defensor,_name.theStrongest,_name.cerroporteno,_name.colocolo,_name.pepeganga,        _name.orientePetrolero,_name.mineros,_name.sportingcristal,_name.gremio],
    1989.0: [_name.atleticonacional,_name.olimpia,_name.danubio,_name.internacional, _name.millonarios,_name.bahia,_name.cobreloa,_name.soldeamerica,                  _name.bocajuniors,_name.tachira,_name.penarol,_name.universitario,_name.depquito,_name.nacional,_name.racing,_name.bolivar,         _name.colocolo,_name.maritimoven,_name.emelec,_name.sportingcristal,_name.theStrongest],
    1988.0: [_name.nacional,_name.newells,_name.americadecali,_name.sanlorenzo,      _name.orientePetrolero,_name.penarol,                                        _name.univcatolica,_name.universitario,_name.guarani,_name.bolivar,_name.colocolo,       _name.maritimoven,_name.barcelonaequ,_name.millonarios,_name.cerroporteno,_name.sport,    _name.tachira,_name.filanbanco,_name.montWanderers,_name.olimpia,_name.alianzalima],
    1987.0: [_name.penarol,_name.americadecali,_name.riverplate,_name.cobreloa,      _name.independiente,_name.barcelonaequ,           _name.deportivocali,_name.rosario,_name.colocolo,_name.elnacional,_name.alianzalima,     _name.tachira,_name.theStrongest,_name.guarani,_name.elnacional,_name.progreso,      _name.estudiantesmerida,_name.orientePetrolero,_name.saopaulo,_name.soldeamerica,_name.sanagustin],
    1986.0: [_name.riverplate,_name.americadecali,_name.argentinojuniors,_name.olimpia, _name.barcelonaequ,_name.bolivar,              _name.montWanderers,_name.jorge,_name.coritiba,_name.deportivocali,_name.nacionalPAR,               _name.bocajuniors,_name.universitario,_name.depquito,_name.cobresal,             _name.penarol,_name.cajamarca,_name.bangu,_name.univcatolica],
    1985.0: [_name.argentinojuniors,_name.americadecali,_name.independiente,_name.elnacional,  _name.blooming,_name.penarol,           _name.ferro,_name.orientePetrolero,_name.cerroporteno,_name.colocolo,_name.universitario,       _name.fluminense,_name.tachira,_name.millonarios,_name.magallanes,_name.nueveoctubre,   _name.vasco,_name.depitalia,_name.guaraniPAR,_name.bellavista,_name.sportboys],
    1984.0: [_name.independiente,_name.gremio,_name.nacional,_name.flamengo,         _name.univcatolica,_name.ula,                     _name.olimpia,_name.blooming,_name.americadecali,_name.elnacional,_name.sportingcristal,                    _name.luqueno,_name.bolivar,_name.junior,_name.danubio,_name.portuguesaven,                      _name.estudiantes,_name.ohiggins,_name.santos,_name.nueveoctubre,_name.melgar],
    1983.0: [_name.gremio,_name.penarol,_name.estudiantes,_name.nacional,            _name.americadecali,_name.sancristobal,           _name.cobreloa,_name.flamengo,_name.tolima,_name.elnacional,_name.montWanderers,                    _name.colocolo,_name.bolivar,_name.universitario,_name.barcelonaequ,_name.nacionalPAR,           _name.ferro,_name.blooming,_name.alianzalima,_name.tachira,_name.olimpia],
    1982.0: [_name.penarol,_name.cobreloa,_name.flamengo,_name.olimpia,              _name.riverplate,_name.tolima,                    _name.theStrongest,_name.saopaulo,_name.atleticonacional,_name.colocolo,_name.melgar,  _name.bocajuniors,_name.gremio,_name.estudiantesmerida,_name.ldu,_name.soldeamerica,                           _name.jorge,_name.defensor,_name.tachira,_name.barcelonaequ,_name.depmunicipal],
    1981.0: [_name.flamengo,_name.cobreloa,_name.deportivocali,_name.nacional,       _name.jorge,_name.penarol,                        _name.riverplate,_name.bellavista,_name.atleticomg,_name.jorge,_name.sportingcristal,  _name.rosario,_name.estudiantesmerida,_name.cerroporteno,_name.barcelonaequ,_name.lau,                  _name.junior,_name.portuguesaven,_name.olimpia,_name.tecnicoUniv,_name.atltorino],
    1980.0: [_name.nacional,_name.internacional,_name.olimpia,_name.americadecali,   _name.ohiggins,_name.velez,              _name.riverplate,_name.theStrongest,_name.vasco,_name.uniequ,_name.cerroporteno,       _name.sportingcristal,_name.defensor,_name.depgalicia,_name.santafe,_name.colocolo,                 _name.chalaco,_name.orientePetrolero,_name.tachira,_name.emelec,_name.soldeamerica],
    1979.0: [_name.olimpia,_name.bocajuniors,_name.guarani,_name.independiente,      _name.palestino,_name.penarol,                    _name.deportivocali,_name.bolivar,_name.universitario,_name.ohiggins,_name.nacional,   _name.millonarios,_name.soldeamerica,_name.palmeiras,_name.portuguesaven,_name.elnacional,          _name.quilmes,_name.jorge,_name.alianzalima,_name.depgalicia,_name.tecnicoUniv],
    1978.0: [_name.bocajuniors,_name.deportivocali,_name.riverplate,_name.cerroporteno,  _name.atleticomg,_name.alianzalima,           _name.independiente,_name.sportingcristal,_name.unionespanola,_name.penarol,_name.portuguesaven,    _name.ldu,_name.theStrongest,_name.saopaulo,_name.junior,_name.estudiantesmerida,                 _name.elnacional,_name.orientePetrolero,_name.palestino,_name.danubio,_name.libertad],
    1977.0: [_name.bocajuniors,_name.cruzeiro,_name.deportivocali,_name.internacional, _name.libertad,_name.portuguesaven,             _name.riverplate,_name.bolivar,_name.elnacional,_name.lau,_name.unionhuaral,           _name.defensor,_name.orientePetrolero,_name.corinthians,_name.evertonchi,_name.estudiantesmerida,              _name.penarol,_name.atleticonacional,_name.depcuenca,_name.olimpia,_name.sportboys],
    1976.0: [_name.cruzeiro,_name.riverplate,_name.ldu,_name.independiente,          _name.alianzalima,_name.penarol,                  _name.estudiantes,_name.depcuenca,_name.internacional,_name.millonarios,_name.unionespanola,   _name.portuguesaven,_name.bolivar,_name.olimpia,_name.ugarte,_name.palestino,_name.depgalicia,_name.guabira,_name.luqueno,_name.santafe,_name.nacional],
    1975.0: [_name.independiente,_name.unionespanola,_name.rosario,_name.universitario, _name.cruzeiro,_name.ldu,               _name.newells,_name.huachipato,_name.deportivocali,_name.portuguesaven,_name.penarol,  _name.olimpia,_name.theStrongest,_name.atleticonacional,_name.depgalicia,_name.montWanderers,           _name.cerroporteno,_name.jorge,_name.vasco,_name.elnacional,_name.unionhuaral],
    1974.0: [_name.independiente,_name.saopaulo,_name.millonarios,_name.penarol,     _name.huracan,_name.defensorlima,                 _name.rosario,_name.palmeiras,_name.atleticonacional,_name.elnacional,_name.cerroporteno,   _name.unionespanola,_name.depmunicipal,_name.portuguesaven,_name.uniequ,_name.olimpia,   _name.colocolo,_name.jorge,_name.valenciaven,_name.sportingcristal,_name.nacional],
    1973.0: [_name.independiente,_name.colocolo,_name.sanlorenzo,_name.cerroporteno,  _name.botafogo,_name.millonarios,                _name.jorge,_name.palmeiras,_name.emelec,_name.deportivocali,_name.olimpia,            _name.riverplate,_name.nacional,_name.elnacional,_name.sportingcristal,                             _name.orientePetrolero,_name.penarol,_name.unionespanola,_name.universitario],
    1972.0: [_name.independiente,_name.universitario,_name.nacional,_name.saopaulo,   _name.penarol,_name.barcelonaequ,                _name.rosario,_name.americaquito,_name.olimpia,_name.lau,_name.depitalia,       _name.santafe,_name.orientePetrolero,_name.cerroporteno,_name.alianzalima,_name.valenciaven,        _name.atleticonacional,_name.chaco,_name.atleticomg,_name.sanfelipe,],
    1971.0: [_name.nacional,_name.estudiantes,_name.palmeiras,_name.barcelonaequ,     _name.unionespanola,_name.universitario,         _name.rosario,_name.penarol,_name.fluminense,_name.cerroporteno,_name.emelec,   _name.bocajuniors,_name.chaco,_name.depitalia,_name.colocolo,_name.deportivocali,                   _name.sportingcristal,_name.theStrongest,_name.depgalicia,_name.guaraniPAR,_name.junior],
    1970.0: [_name.estudiantes,_name.penarol,_name.riverplate,_name.lau,             _name.bocajuniors,_name.guaraniPAR,_name.nacional,_name.universitario,_name.ldu,            _name.bolivar,_name.valenciaven,_name.deportivocali,_name.arica,       _name.sucre,_name.depitalia,_name.olimpia,_name.americaquito,   _name.americadecali,_name.rangersCHI],
    1969.0: [_name.estudiantes,_name.nacional,_name.univcatolica,_name.penarol,       _name.cerroporteno,_name.deportivocali,_name.olimpia,_name.depitalia,_name.santiagowanderers,     _name.uMagdalena,_name.sportingcristal,_name.bolivar,_name.depquito,       _name.uCanarias,_name.juanaurich,_name.litoral,_name.barcelonaequ],
    1968.0: [_name.estudiantes,_name.palmeiras,_name.racing,_name.penarol,            _name.independiente,_name.sportingcristal,_name.guaraniPAR,    _name.universitario,_name.emelec,_name.univcatolica,_name.portugues,       _name.elnacional,_name.nacional,_name.nautico,     _name.lau,_name.libertad,_name.depgalicia],
    1967.0: [_name.racing,_name.nacional,_name.universitario,_name.cruzeiro,          _name.riverplate,_name.penarol,_name.colocolo,             _name.sportboys,_name.santafe,_name.univcatolica,             _name.depgalicia,_name.bolivar,_name.guaraniPAR,    _name.depitalia,_name.imedellin,_name.emelec,_name.barcelonaequ,_name.cerroporteno,_name.octubre31],
    1966.0: [_name.penarol,_name.riverplate,_name.univcatolica,_name.independiente,   _name.nacional,_name.bocajuniors,_name.guaraniPAR,_name.olimpia,    _name.universitario,_name.jorge,_name.depitalia,_name.lau,_name.depmunicipal,   _name.alianzalima,_name.emelec,_name.laraFC,_name.nueveoctubre],
    1965.0: [_name.independiente,_name.penarol,_name.bocajuniors,_name.santos,        _name.guaraniPAR,_name.theStrongest,_name.lau,             _name.depquito,_name.universitario,_name.depgalicia],
    1964.0: [_name.independiente,_name.nacional,_name.santos,_name.colocolo,          _name.millonarios,_name.cerroporteno,_name.barcelonaequ,   _name.aurora,_name.alianzalima,_name.depitalia],
    1963.0: [_name.santos,_name.bocajuniors,_name.botafogo,_name.penarol,             _name.olimpia,_name.alianzalima,_name.everestGuayaquil,             _name.millonarios,_name.lau],
    1962.0: [_name.santos,_name.penarol,_name.univcatolica,_name.nacional,            _name.cerroporteno,_name.racing,_name.emelec,              _name.sportingcristal,_name.depmunicipal,_name.millonarios],
    1961.0: [_name.penarol,_name.palmeiras,_name.olimpia,_name.santafe,               _name.universitario,_name.independiente,_name.colocolo,_name.jorge,],
    1960.0: [_name.penarol,_name.olimpia,_name.sanlorenzo,_name.millonarios,          _name.jorge,_name.bahia,_name.lau],
  },


  leagueName.concacaf : {
    2022.0: [_name.seattle,_name.pumas,_name.nycity,_name.cruzazul,                     _name.leon,_name.nerevolution,_name.montreal,_name.comunicaciones],
    2021.0: [_name.monterrey,_name.americamex,_name.cruzazul,_name.philadelphia,        _name.columbuscrew,_name.portland,_name.toronto,_name.atlanta],
    2020.0: [_name.tigres,_name.losangelesfc,_name.olimpiaHON,_name.americamex,         _name.nycity,_name.cruzazul,_name.montreal,_name.atlanta],
    2019.0: [_name.monterrey,_name.tigres,_name.kansas,_name.santosLaguna,  _name.nyredbulls,_name.houston,_name.atlanta,_name.independienteChorrera],
    2018.0: [_name.chivas,_name.toronto,_name.nyredbulls,_name.americamex, _name.tauro,_name.tijuana,_name.tigres,_name.seattle],
    2017.0: [_name.pachuca,_name.tigres,_name.fcdallas,_name.vancouver,                 _name.saprissa,_name.nyredbulls,_name.pumas,_name.arabeunido, ],
    2016.0: [_name.americamex,_name.tigres,_name.santosLaguna,_name.queretaro,          _name.dcunited,_name.seattle,_name.realSaltLake,_name.lagalaxy],
    2015.0: [_name.americamex,_name.montreal,_name.herediano,_name.alajuelense,        _name.saprissa,_name.pachuca,_name.olimpiaHON,_name.dcunited],
    2014.0: [_name.cruzazul,_name.toluca,_name.tijuana,_name.alajuelense,              _name.kansas,_name.sanJoseEarthquakes,_name.lagalaxy,_name.arabeunido],
    2013.0: [_name.monterrey,_name.santosLaguna,_name.lagalaxy,_name.seattle,          _name.xelaju,_name.houston,_name.tigres,_name.herediano],
    2012.0: [_name.monterrey,_name.santosLaguna,_name.pumas,_name.toronto,           _name.morelia,_name.seattle,_name.lagalaxy,_name.isidro],
    2011.0: [_name.monterrey,_name.realSaltLake,_name.cruzazul,_name.saprissa,         _name.columbuscrew,_name.santosLaguna,_name.toluca,_name.olimpiaHON],
    2010.0: [_name.pachuca,_name.cruzazul,_name.toluca,_name.pumas,                    _name.comunicaciones,_name.arabeunido,_name.marathon,_name.columbuscrew],
    2009.0: [_name.atlante,_name.cruzazul,_name.santosLaguna,_name.puertoRico,         _name.houston,_name.pumas,_name.montreal,_name.marathon],
    2008.0: [_name.pachuca,_name.saprissa,_name.dcunited,_name.houston,                ],
    2007.0: [_name.pachuca,_name.chivas,_name.houston,_name.dcunited,       ],
    2006.0: [_name.americamex,_name.toluca,_name.alajuelense,_name.saprissa,           ],
    2005.0: [_name.saprissa,_name.pumas,_name.monterrey,_name.dcunited,                ],
    2004.0: [_name.alajuelense,_name.saprissa,_name.chicago,_name.monterrey,           ],
    2003.0: [_name.toluca,_name.morelia,_name.americamex,_name.necaxa,                 ],
    2002.0: [],
    2001.0: [_name.pachuca,_name.morelia,_name.alajuelense,_name.kansas,   ],
    2000.0: [_name.lagalaxy,_name.olimpiaHON,_name.pachuca,_name.dcunited,                ],
    1999.0: [_name.necaxa,_name.alajuelense,_name.chicago,_name.dcunited,              ],
    1998.0: [_name.dcunited,_name.toluca,_name.saprissa,_name.leon,                    ],
    1997.0: [_name.cruzazul,_name.lagalaxy,_name.chivas,_name.dcunited,     ],
    1996.0: [_name.cruzazul,_name.necaxa,_name.comunicaciones,_name.seattle,           ],
    1995.0: [_name.saprissa,_name.municipal,_name.alajuelense,_name.moulien],
    1994.0: [_name.cartagines,_name.atlante,_name.usrobert,_name.alianzaELS],
    1993.0: [_name.saprissa,_name.leon,_name.municipal,_name.robinhood],
    1992.0: [_name.americamex,_name.alajuelense,_name.robinhood,_name.aiglon],
    1991.0: [_name.puebla,_name.police,_name.rcdespana],
    1990.0: [_name.americamex,_name.pinardelrio,_name.olimpiaHON],
    1989.0: [_name.pumas,_name.pinardelrio,_name.herediano,],
    1988.0: [_name.olimpiaHON,_name.defenseforce,_name.alajuelense,_name.robinhood],
    1987.0: [_name.americamex,_name.defenseforce,_name.monterrey,_name.trintoc],
    1986.0: [_name.alajuelense,_name.transvaal,],
    1985.0: [_name.defenseforce,_name.olimpiaHON],
    1984.0: [_name.violette,_name.guayanais],
    1983.0: [_name.atlante,_name.robinhood],
    1982.0: [_name.pumas,_name.robinhood,_name.comunicaciones,_name.defenseforce],
    1981.0: [_name.transvaal,_name.atleticomarte],
    1980.0: [_name.pumas,],
    1979.0: [],
    1978.0: [_name.cdfas,_name.jongcolombia,_name.tigres],
    1977.0: [_name.americamex,_name.robinhood,_name.saprissa],
    1976.0: [_name.aguila,_name.robinhood,_name.leon],
    1975.0: [_name.atlEspanol,_name.transvaal],
    1974.0: [_name.municipal,_name.transvaal,_name.alianzaELS],
    1973.0: [_name.transvaal,_name.saprissa],
    1972.0: [_name.olimpiaHON,_name.robinhood,_name.toluca],
    1971.0: [_name.cruzazul,_name.alajuelense,_name.comunicaciones],
    1970.0: [_name.cruzazul,_name.transvaal,_name.saprissa],
    1969.0: [_name.cruzazul,_name.comunicaciones,_name.saprissa],
    1968.0: [_name.toluca,_name.transvaal,],
    1967.0: [_name.alianzaELS,_name.jongcolombia],
  },
  leagueName.asia : {
    2022.0: [],
    2021.0: [_name.alhilal,_name.pohang,_name.alnassr,_name.ulsan,                     _name.persepolis,_name.nagoya,_name.alWahda,_name.jeonbuk],
    2020.0: [_name.ulsan,_name.persepolis,_name.alnassr,_name.visselkobe,              _name.beijingguoan,_name.pakhtakor,_name.suwonsamsung,_name.alahli],
    2019.0: [_name.alhilal,_name.urawareddiamonds,_name.alsadd,_name.ghuangzhou,       _name.alIttihad,_name.shanghaisipg,_name.alnassr,_name.kashimaantlers],
    2018.0: [_name.kashimaantlers,_name.persepolis,_name.suwonsamsung,_name.alsadd,    _name.tianjin,_name.alduhail,_name.jeonbuk,_name.esteghlal],
    2017.0: [_name.urawareddiamonds,_name.alhilal,_name.shanghaisipg,_name.persepolis, _name.kawasakifrontale,_name.alain,_name.ghuangzhou,_name.alahli],
    2016.0: [_name.jeonbuk,_name.alain,_name.eljaish,_name.fcseoul,                    _name.shanghaisipg,_name.tashkent,_name.alnasrEAU,_name.shandong],
    2015.0: [_name.ghuangzhou,_name.alahli,_name.alhilal,_name.gambaOsaka,             _name.kashiwaReysol,_name.naftTehran,_name.alduhail,_name.jeonbuk],
    2014.0: [_name.sydneywanderers,_name.alhilal,_name.fcseoul,_name.alain,            _name.ghuangzhou,_name.alsadd,_name.pohang,_name.alIttihad],
    2013.0: [_name.ghuangzhou,_name.fcseoul,_name.esteghlal,_name.kashiwaReysol,       _name.alduhail,_name.alahli,_name.buriram,_name.alShabab],
    2012.0: [_name.ulsan,_name.alahli,_name.bunyodkor,_name.alIttihad,                 _name.alhilal,_name.sepahan,_name.adelaide,_name.ghuangzhou],
    2011.0: [_name.alsadd,_name.jeonbuk,_name.suwonsamsung,_name.alIttihad,            _name.sepahan,_name.cerezoOsaka,_name.zobahan,_name.fcseoul],
    2010.0: [_name.seongnam,_name.zobahan,_name.alShabab,_name.alhilal,                _name.suwonsamsung,_name.pohang,_name.jeonbuk,_name.algharafa],
    2009.0: [_name.pohang,_name.alIttihad,_name.ummSalal,_name.nagoya,                 _name.bunyodkor,_name.pakhtakor,_name.fcseoul,_name.kawasakifrontale],
    2008.0: [_name.gambaOsaka,_name.adelaide,_name.urawareddiamonds,_name.bunyodkor,   _name.alKaramah,_name.kashimaantlers,_name.alQadisiya,_name.saipa],
    2007.0: [_name.urawareddiamonds,_name.sepahan,_name.seongnam,_name.alWahda,        _name.jeonbuk,_name.kawasakifrontale,_name.alKaramah,_name.alhilal],
    2006.0: [_name.jeonbuk,_name.alKaramah,_name.ulsan,_name.alQadisiya,               _name.shanghaishenhua,_name.alIttihad,_name.alShabab,_name.alain],
    2005.0: [_name.alIttihad,_name.alain,_name.shenzhen,_name.busan,                   _name.shandong,_name.pastehran,_name.alahli,_name.alsadd],
    2004.0: [_name.alIttihad,_name.seongnam,_name.jeonbuk,_name.pakhtakor,             _name.dalian,_name.alsharjah,_name.alain,_name.alWahda],
    2003.0: [_name.alain,_name.becToroSasana,_name.dalian,_name.pakhtakor,             _name.alsadd,_name.daejeon,_name.seongnam,_name.persepolis,],
    2002.0: [_name.suwonsamsung,_name.fcseoul,_name.esteghlal,_name.nasafQarshi,       ],
    2001.0: [_name.suwonsamsung,_name.jubiloiwata,_name.persepolis,_name.irtysh,       ],
    2000.0: [_name.alhilal,_name.jubiloiwata,_name.persepolis,_name.suwonsamsung,      ],
    1999.0: [_name.jubiloiwata,_name.esteghlal,_name.alain,_name.dalian,               ],
    1998.0: [_name.pohang,_name.dalian,_name.alhilal,_name.persepolis,                 ],
    1997.0: [_name.pohang,_name.seongnam,_name.persepolis,_name.alzawraa,              ],
    1996.0: [_name.seongnam,_name.alnassr,_name.thai,_name.saipa,                      ],
    1995.0: [_name.thai,_name.alarabi,_name.neftchiFargona,_name.seongnam,             ],
    1994.0: [_name.thai,_name.omanClub,_name.tokyoVerdy,_name.liaoning,                ],
    1993.0: [_name.pastehran,_name.alShabab,_name.alwasl,_name.tokyoVerdy,             ],
    1992.0: [_name.alhilal,_name.esteghlal,_name.alrayyan,_name.alShababEAU,           ],
    1991.0: [_name.esteghlal,_name.liaoning,_name.pelitaJaya,_name.april25,            ],
    1990.0: [_name.liaoning,_name.yokohamamarinos,_name.alRasheed,_name.federalTerritory],
    1989.0: [_name.alsadd,_name.alRasheed,_name.alettifaq,_name.guangdong,             ],
    1988.0: [],
    1987.0: [_name.tokyoVerdy,_name.alhilal,_name.federalTerritory,_name.alRasheed,    ],
    1986.0: [_name.jefUnited,_name.alhilal,_name.liaoning,_name.alTalaba,              ],
    1985.0: [_name.busan,_name.alahli,_name.palembang,_name.aleppo,                    ],
    1984.0: [],
    1983.0: [],
    1982.0: [],
    1981.0: [],
    1980.0: [],
    1979.0: [],
    1978.0: [],
    1977.0: [],
    1976.0: [],
    1975.0: [],
    1974.0: [],
    1973.0: [],
    1972.0: [],
    1971.0: [_name.maccabiTelAviv,_name.alShortaIRAQ,_name.esteghlal,_name.rokArmy,        ],
    1970.0: [_name.esteghlal,_name.hapoelTelAviv,_name.homenetmen,_name.psmsMedan,     ],
    1969.0: [_name.maccabiTelAviv,_name.yangzee,_name.hiroshima,_name.mysore,          ],
    1968.0: [],
    1967.0: [_name.hapoelTelAviv,_name.selangor,_name.koreaTungsten,_name.bangkokBank, ],
  },

  leagueName.africa : {
    2022.0: [_name.wydad,_name.alahly,_name.petroluanda,_name.essetif],
    2021.0: [_name.alahly,_name.kaizer,_name.esperance,_name.wydad,                  _name.mamelodi,_name.simba,_name.belouizdad,_name.mcalger,         _name.horoya,_name.zamalek,_name.vita,_name.mazembe,_name.omdurman,_name.teungueth,_name.almerrikh,_name.petroluanda],
    2020.0: [_name.alahly,_name.zamalek,_name.rajacasablanca,_name.wydad,            _name.mamelodi,_name.esperance,_name.etoilesahel,_name.mazembe,    _name.omdurman,_name.kabylie,_name.agosto,_name.petroluanda,_name.vita,_name.usmAlger,_name.zesco,_name.platinum],
    2019.0: [_name.esperance,_name.wydad,_name.mazembe,_name.mamelodi,               _name.constantine,_name.horoya,_name.simba,_name.alahly,           _name.clubAfricain,_name.saoura,_name.lobiStars,_name.orlandopirates,_name.asecmimosas,_name.vita,_name.platinum,_name.ismaily],
    2018.0: [_name.esperance,_name.alahly,_name.agosto,_name.essetif,                _name.etoilesahel,_name.horoya,_name.mazembe,_name.wydad,          ],
    2017.0: [_name.wydad,_name.alahly,_name.usmAlger,_name.etoilesahel,              _name.mamelodi,_name.esperance,_name.ferroviarioMOZ,_name.tripoliLIB],
    2016.0: [_name.mamelodi,_name.zamalek,_name.zesco,_name.wydad,                   _name.enyimba,_name.alahly,_name.essetif,_name.asecmimosas],
    2015.0: [_name.mazembe,_name.usmAlger,_name.almerrikh,_name.omdurman,            _name.moghrebTetouan,_name.essetif,_name.smouha,_name.elEulma],
    2014.0: [_name.essetif,_name.vita,_name.mazembe,_name.sfaxien,                   _name.esperance,_name.omdurman,_name.benghazi,_name.zamalek],
    2013.0: [_name.alahly,_name.orlandopirates,_name.cotonsport,_name.esperance,     _name.zamalek,_name.seweSport,_name.leopardsCON,_name.libolo],
    2012.0: [_name.alahly,_name.esperance,_name.sunshinestars,_name.mazembe,         _name.berekum,_name.asoChlef,_name.zamalek,_name.etoilesahel],
    2011.0: [_name.esperance,_name.wydad,_name.omdurman,_name.enyimba,               _name.alahly,_name.cotonsport,_name.mcalger,_name.rajacasablanca],
    2010.0: [_name.mazembe,_name.esperance,_name.kabylie,_name.alahly,               _name.essetif,_name.ismaily,_name.dynamos,_name.heartland],
    2009.0: [_name.mazembe,_name.heartland,_name.omdurman,_name.kano,                _name.zesco,_name.etoilesahel,_name.monomotapa,_name.almerrikh],
    2008.0: [_name.alahly,_name.cotonsport,_name.enyimba,_name.dynamos,              _name.mazembe,_name.asecmimosas,_name.omdurman,_name.zamalek],
    2007.0: [_name.etoilesahel,_name.alahly,_name.omdurman,                          _name.asecmimosas,_name.kabylie,_name.farRabat,_name.esperance],
    2006.0: [_name.alahly,_name.sfaxien,_name.asecmimosas,_name.orlandopirates,      _name.enyimba,_name.asantekotoko,_name.kabylie,_name.heartsoak],
    2005.0: [_name.alahly,_name.etoilesahel,_name.zamalek,_name.rajacasablanca,      _name.enyimba,_name.asecmimosas,_name.esperance,_name.capetownAjax],
    2004.0: [_name.enyimba,_name.etoilesahel,_name.esperance,_name.jeannedarc,       _name.usmAlger,_name.africaSports,_name.bakiliBullets,_name.supersport],
    2003.0: [_name.enyimba,_name.ismaily,_name.usmAlger,_name.esperance,            _name.simba,_name.canonYaounde,_name.asecmimosas,_name.aviacao],
    2002.0: [_name.zamalek,_name.rajacasablanca,_name.mazembe,_name.asecmimosas,    _name.esperance,_name.jeannedarc,_name.alahly,_name.costaDoSol],
    2001.0: [_name.alahly,_name.mamelodi,_name.esperance,_name.petroluanda,         _name.asecmimosas,_name.juliusBerger,_name.mazembe,_name.belouizdad],
    2000.0: [_name.heartsoak,_name.esperance,_name.mamelodi,_name.alahly,           _name.africaSports,_name.lobiStars,_name.jeannedarc,_name.sable],
    1999.0: [_name.rajacasablanca,_name.esperance,_name.alahly,_name.asecmimosas,   _name.heartsoak,_name.dynamos,_name.shootingstars,_name.saintLouisienne],
    1998.0: [_name.asecmimosas,_name.dynamos,_name.manningRangers,_name.heartsoak,  _name.etoilesahel,_name.rajacasablanca,_name.dolphin,_name.yanga],
    1997.0: [_name.rajacasablanca,_name.ashantiGold,_name.usmAlger,_name.zamalek,   _name.agosto,_name.clubAfricain,_name.ferroviarioMOZ,_name.orlandopirates],
    1996.0: [_name.zamalek,_name.shootingstars,_name.sfaxien,_name.kabylie,         _name.meknes,_name.orlandopirates,_name.diaraf,_name.petroluanda],
    1995.0: [_name.orlandopirates,_name.asecmimosas,_name.express,_name.ismaily,    _name.mbilinga,_name.obuasi,_name.dynamos,_name.esperance],
    1994.0: [_name.esperance,_name.zamalek,_name.nkana,_name.mcOran,                _name.heartland,_name.sogara,_name.simba,_name.vita],
    1993.0: [_name.zamalek,_name.asantekotoko,_name.asecmimosas,_name.stationeryStores, _name.mcOran,_name.nkana,_name.villa,_name.sogara],
    1992.0: [_name.wydad,_name.omdurman,_name.asecmimosas,_name.ismaily,            _name.nkana,_name.gorMahia,_name.asantekotoko,_name.clubAfricain],
    1991.0: [_name.clubAfricain,_name.villa,_name.nkana,_name.heartland,            _name.wydad,_name.alahly,_name.douala,_name.asecmimosas],
    1990.0: [_name.kabylie,_name.nkana,_name.asantekotoko,_name.heartland,          _name.leopardsQUE,_name.bafoussam,_name.omdurman,_name.esperance],
    1989.0: [_name.rajacasablanca,_name.mcOran,_name.nkana,_name.tonnerre,          ],
    1988.0: [_name.essetif,_name.heartland,_name.farRabat,_name.alahly,             ],
    1987.0: [_name.alahly,_name.omdurman,_name.canonYaounde,_name.asantekotoko,     ],
    1986.0: [_name.zamalek,_name.africaSports,_name.nkana,_name.canonYaounde,       ],
    1985.0: [_name.farRabat,_name.dragons,_name.zamalek,_name.goree,                ],
    1984.0: [_name.zamalek,_name.shootingstars,_name.kabylie,_name.semassi,         ],
    1983.0: [_name.asantekotoko,_name.alahly,_name.diaraf,_name.nkana,              ],
    1982.0: [_name.alahly,_name.asantekotoko,_name.rangersInt,_name.lupopo,         ],
    1981.0: [_name.kabylie,_name.vita,_name.kaloum,_name.alahly,                    ],
    1980.0: [_name.canonYaounde,_name.dragons,_name.douala,_name.bendel,            ],
    1979.0: [_name.douala,_name.heartsoak,_name.goree,_name.motema,                 ],
    1978.0: [_name.canonYaounde,_name.hafia,_name.rangersInt,_name.vita,            ],
    1977.0: [_name.hafia,_name.heartsoak,_name.mufulira,_name.lome,                 ],
    1976.0: [_name.mcalger,_name.hafia,_name.rangersInt,_name.asecmimosas],
    1975.0: [_name.hafia,_name.rangersInt,_name.ghazl,_name.lome,],
    1974.0: [_name.caraBrazaville,_name.ghazl,_name.simba,_name.jeannedarc],
    1973.0: [_name.vita,_name.asantekotoko,_name.leopardsCAM,_name.tusker],
    1972.0: [_name.hafia,_name.simba,_name.mazembe,_name.heartsoak],
    1971.0: [_name.canonYaounde,_name.asantekotoko,_name.greatOlympics,_name.asecmimosas],
    1970.0: [_name.asantekotoko,_name.mazembe,_name.ismaily,_name.kaloum],
    1969.0: [_name.ismaily,_name.mazembe,_name.asantekotoko,_name.hafia],
    1968.0: [_name.mazembe,_name.etoileFilante,_name.leopardsQUE,_name.farRabat],
    1967.0: [_name.mazembe,_name.asantekotoko,_name.stGeorge,_name.djoliba],
    1966.0: [_name.stadeDAbidjan,_name.realBamako,_name.oryx,_name.omdurman],
  },

  leagueName.mundial : {
    //2022.0: [_name.realmadrid,_name.flamengo,_name.seattle,_name.wydad],
    2021.0: [_name.chelsea,_name.palmeiras,_name.alahly,_name.alhilal,_name.monterrey],
    2020.0: [_name.bayernmunique,_name.tigres,_name.alahly,_name.palmeiras],
    2019.0: [_name.liverpool,_name.flamengo,_name.monterrey,_name.alhilal],
    2018.0: [_name.realmadrid,_name.alain,_name.riverplate,_name.kashimaantlers],
    2017.0: [_name.realmadrid,_name.gremio,_name.pachuca,_name.aljazira],
    2016.0: [_name.realmadrid,_name.kashimaantlers,_name.atleticonacional,_name.americamex],
    2015.0: [_name.barcelona,_name.riverplate,_name.hiroshima,_name.ghuangzhou],
    2014.0: [_name.realmadrid,_name.sanlorenzo,_name.auckland,_name.cruzazul],
    2013.0: [_name.bayernmunique,_name.rajacasablanca,_name.atleticomg,_name.ghuangzhou],
    2012.0: [_name.corinthians,_name.chelsea,_name.monterrey,_name.alahly],
    2011.0: [_name.barcelona,_name.santos,_name.alsadd,_name.kashiwaReysol],
    2010.0: [_name.inter,_name.mazembe,_name.internacional,_name.seongnam],
    2009.0: [_name.barcelona,_name.estudiantes,_name.pohang,_name.atlante],
    2008.0: [_name.manchesterunited,_name.ldu,_name.gambaOsaka,_name.pachuca],
    2007.0: [_name.milan,_name.bocajuniors,_name.urawareddiamonds,_name.etoilesahel],
    2006.0: [_name.internacional,_name.barcelona,_name.alahly,_name.americamex],
    2005.0: [_name.saopaulo,_name.liverpool,_name.saprissa,_name.alIttihad],
    2004.0: [_name.porto,_name.oncecaldas,],
    2003.0: [_name.bocajuniors,_name.milan],
    2002.0: [_name.realmadrid,_name.olimpia],
    2001.0: [_name.bayernmunique,_name.bocajuniors],
    2000.0: [_name.bocajuniors,_name.realmadrid],
    1999.0: [_name.manchesterunited,_name.palmeiras],
    1998.0: [_name.realmadrid,_name.vasco],
    1997.0: [_name.dortmund,_name.cruzeiro],
    1996.0: [_name.juventus,_name.riverplate],
    1995.0: [_name.ajax,_name.gremio],
    1994.0: [_name.velez,_name.milan],
    1993.0: [_name.saopaulo,_name.milan],
    1992.0: [_name.saopaulo,_name.barcelona],
    1991.0: [_name.estrelavermelha,_name.colocolo],
    1990.0: [_name.milan,_name.olimpia],
    1989.0: [_name.milan,_name.atleticonacional],
    1988.0: [_name.nacional,_name.psv],
    1987.0: [_name.porto,_name.penarol],
    1986.0: [_name.riverplate,_name.steauaBucuresti],
    1985.0: [_name.juventus,_name.argentinojuniors],
    1984.0: [_name.independiente,_name.liverpool],
    1983.0: [_name.gremio,_name.hamburgo],
    1982.0: [_name.penarol,_name.astonvilla],
    1981.0: [_name.flamengo,_name.liverpool],
    1980.0: [_name.nacional,_name.nottinghamforest],
    1979.0: [_name.olimpia,_name.malmo],
    1978.0: [],
    1977.0: [_name.bocajuniors,_name.moenchengladbach],
    1976.0: [_name.bayernmunique,_name.cruzeiro],
    1975.0: [],
    1974.0: [_name.atleticomadrid,_name.independiente],
    1973.0: [_name.independiente,_name.juventus],
    1972.0: [_name.ajax,_name.independiente],
    1971.0: [_name.nacional,_name.panathinaikos],
    1970.0: [_name.feyenoord,_name.estudiantes],
    1969.0: [_name.milan,_name.estudiantes],
    1968.0: [_name.estudiantes,_name.manchesterunited],
    1967.0: [_name.racing,_name.celtic],
    1966.0: [_name.penarol,_name.realmadrid],
    1965.0: [_name.inter,_name.independiente],
    1964.0: [_name.inter,_name.independiente],
    1963.0: [_name.santos,_name.milan],
    1962.0: [_name.santos,_name.benfica],
    1961.0: [_name.penarol,_name.benfica],
    1960.0: [_name.realmadrid,_name.penarol],

    1952.0: [_name.fluminense,_name.corinthians,_name.austria,_name.penarol],
    1951.0: [_name.palmeiras,_name.juventus,_name.vasco,_name.austria],
  },


  leagueName.ligaEuropa : {
    2022.0: [_name.eintrachtfrankfurt,_name.rangers,_name.westham,_name.rbleipzig,  ],
    2021.0: [_name.villareal,_name.manchesterunited,_name.arsenal,_name.roma,       ],
    2020.0: [_name.sevilla,_name.inter,_name.manchesterunited,_name.shaktardonetsk, ],
    2019.0: [_name.chelsea,_name.arsenal,_name.eintrachtfrankfurt,_name.valencia,   ],
    2018.0: [_name.atleticomadrid,_name.om,_name.arsenal,_name.rbsalzburg,          ],
    2017.0: [_name.manchesterunited,_name.ajax,_name.celtavigo,_name.lyon,          ],
    2016.0: [_name.sevilla,_name.liverpool,_name.shaktardonetsk,_name.villareal,    ],
    2015.0: [_name.sevilla,_name.dnipro,_name.fiorentina,_name.napoli,              ],
    2014.0: [_name.sevilla,_name.benfica,_name.valencia,_name.juventus,             ],
    2013.0: [_name.chelsea,_name.benfica,_name.basel,_name.fenerbahce,              ],
    2012.0: [_name.atleticomadrid,_name.athleticbilbao,_name.valencia,_name.sporting, ],
    2011.0: [_name.porto,_name.braga,_name.villareal,_name.benfica,                   ],
    2010.0: [_name.atleticomadrid,_name.fulham,_name.liverpool,_name.hamburgo,        ],
    2009.0: [_name.shaktardonetsk,_name.werderbremen,_name.dinamokiev,_name.hamburgo, ],
    2008.0: [_name.zenit,_name.rangers,_name.bayernmunique,_name.fiorentina,          ],
    2007.0: [_name.sevilla,_name.espanyol,_name.osasuna,_name.werderbremen,           ],
    2006.0: [_name.sevilla,_name.middlesbrough,_name.schalke04,_name.steauaBucuresti, ],
    2005.0: [_name.cska,_name.sporting,_name.parma,_name.az,                          ],
    2004.0: [_name.valencia,_name.om,_name.villareal,_name.newcastle,                 ],
    2003.0: [_name.porto,_name.celtic,_name.lazio,_name.boavista,                     ],
    2002.0: [_name.feyenoord,_name.dortmund,_name.inter,_name.milan,               ],
    2001.0: [_name.liverpool,_name.alaves,_name.barcelona,_name.kaiserslautern,    ],
    2000.0: [_name.galatasaray,_name.arsenal,_name.leeds,_name.lens,               ],
    1999.0: [_name.parma,_name.om,_name.atleticomadrid,_name.bologna,              ],
    1998.0: [_name.inter,_name.lazio,_name.spartakmoscou,_name.atleticomadrid,     ],
    1997.0: [_name.schalke04,_name.inter,_name.tenerife,_name.monaco,              ],
    1996.0: [_name.bayernmunique,_name.bordeaux,_name.barcelona,_name.slaviaPraha, ],
    1995.0: [_name.parma,_name.juventus,_name.leverkusen,_name.dortmund,           ],
    1994.0: [_name.inter,_name.rbsalzburg,_name.cagliari,_name.karlsruher,         ],
    1993.0: [_name.juventus,_name.dortmund,_name.psg,_name.auxerre,                ],
    1992.0: [_name.ajax,_name.torino,_name.genoa,_name.realmadrid,                 ],
    1991.0: [_name.inter,_name.roma,_name.sporting,_name.brondby,                  ],
    1990.0: [_name.juventus,_name.fiorentina,_name.colonia,_name.werderbremen,     ],
    1989.0: [_name.napoli,_name.stuttgart,_name.bayernmunique,_name.dynamoDresden, ],
    1988.0: [_name.leverkusen,_name.espanyol,_name.werderbremen,_name.brugge,      ],
    1987.0: [_name.ifkgoteborg,_name.dundee,_name.tirol,_name.moenchengladbach,    ],
    1986.0: [_name.realmadrid,_name.colonia,_name.inter,_name.waregemKSV,          ],
    1985.0: [_name.realmadrid,_name.fehervar,_name.inter,_name.zeljeznicar,        ],
    1984.0: [_name.tottenham,_name.anderlecht,_name.hadjuksplit,_name.nottinghamforest,],
    1983.0: [_name.anderlecht,_name.benfica,_name.bohemians,_name.craiova,         ],
    1982.0: [_name.ifkgoteborg,_name.hamburgo,_name.kaiserslautern,_name.radnicki, ],
    1981.0: [_name.ipswichTown,_name.az,_name.colonia,_name.sochaux,               ],
    1980.0: [_name.eintrachtfrankfurt,_name.moenchengladbach,_name.bayernmunique,_name.stuttgart,],
    1979.0: [_name.moenchengladbach,_name.estrelavermelha,_name.duisburg,_name.herthaberlim, ],
    1978.0: [_name.psv,_name.bastia,_name.barcelona,_name.grasshoppers,           ],
    1977.0: [_name.juventus,_name.athleticbilbao,_name.aek,_name.molenbeek,       ],
    1976.0: [_name.liverpool,_name.brugge,_name.barcelona,_name.hamburgo,         ],
    1975.0: [_name.moenchengladbach,_name.twente,_name.colonia,_name.juventus,    ],
    1974.0: [_name.feyenoord,_name.tottenham,_name.stuttgart,_name.lokleipzig,    ],
    1973.0: [_name.liverpool,_name.moenchengladbach,_name.tottenham,_name.twente, ],
    1972.0: [_name.tottenham,_name.wolves,_name.milan,_name.ferencvaros,          ],
  },


  leagueName.sulamericano : {
    2022.0: [_name.idelvalle,_name.saopaulo,_name.melgar,_name.atleticogo,           _name.tachira,_name.ceara,_name.internacional,_name.nacional,          _name.lanus,_name.univcatolica,_name.deportivocali,_name.olimpia,_name.santos,_name.colocolo,_name.unionSantaFe,_name.theStrongest],
    2021.0: [_name.atleticopr,_name.bragantino,_name.penarol,_name.libertad,         _name.ldu,_name.rosario,_name.sportingcristal,_name.santos,     _name.americadecali,_name.idelvalle,_name.nacional,_name.junior,_name.arsenalsarandi,_name.gremio,_name.tachira,_name.independiente],
    2020.0: [_name.defensayjusticia,_name.lanus,_name.coquimbo,_name.velez,          _name.bahia,_name.independiente,_name.junior,_name.univcatolica,       _name.vasco,_name.bolivar,_name.deportivocali,_name.riverURU,_name.fenix,_name.laCalera,_name.huancayo,_name.unionSantaFe,                  ],
    2019.0: [_name.idelvalle,_name.colon,_name.corinthians,_name.atleticomg,         _name.independiente,_name.zulia,_name.fluminense,_name.laequidad,      _name.caracas,_name.argentinojuniors,_name.montWanderers,_name.penarol,_name.univcatolica,_name.sportingcristal,_name.botafogo,_name.royalpari],
    2018.0: [_name.atleticopr,_name.junior,_name.fluminense,_name.santafe,           _name.bahia,_name.defensayjusticia,_name.nacional,_name.deportivocali, _name.caracas,_name.colon,_name.millonarios,_name.ldu,_name.banfield,_name.botafogo,_name.depcuenca,_name.sanlorenzo],
    2017.0: [_name.independiente,_name.flamengo,_name.libertad,_name.junior,         _name.nacionalPAR,_name.fluminense,_name.racing,_name.sport,           _name.atleticoTucuman,_name.chapecoense,_name.santafe,_name.corinthians,_name.estudiantes,_name.ldu,_name.pontepreta,_name.cerroporteno],
    2016.0: [_name.chapecoense,_name.atleticonacional,_name.sanlorenzo,_name.cerroporteno,  _name.junior,_name.coritiba,_name.palestino,_name.imedellin,    _name.independiente,_name.soldeamerica,_name.santacruz,_name.santafe,_name.belgrano,_name.laGuaira,_name.flamengo,_name.montWanderers],
    2015.0: [_name.santafe,_name.huracan,_name.luqueno,_name.riverplate,             _name.independiente,_name.defensor,_name.atleticopr,_name.chapecoense, _name.emelec,_name.sport,_name.ldu,_name.libertad,_name.lanus,_name.brasilia,_name.tolima,_name.olimpia,],
    2014.0: [_name.riverplate,_name.atleticonacional,_name.bocajuniors,_name.saopaulo, _name.estudiantes,_name.cesarvallejo,_name.cerroporteno,_name.emelec, _name.libertad,_name.vitoria,_name.bahia,_name.saopaulo,_name.goias,_name.capiata,_name.lanus,_name.penarol],
    2013.0: [_name.lanus,_name.pontepreta,_name.libertad,_name.saopaulo,             _name.riverplate,_name.velez,_name.rioNegroAguilas,_name.atleticonacional,  _name.lau,_name.depPasto,_name.univcatolica,_name.bahia,_name.laequidad,_name.sport,_name.coritiba,_name.lduLoja],
    2012.0: [_name.saopaulo,_name.tigre,_name.univcatolica,_name.millonarios,        _name.lau,_name.cerroporteno,_name.independiente,_name.gremio,          _name.lduLoja,_name.depquito,_name.colon,_name.barcelonaequ,_name.palmeiras,_name.liverpoolURU,_name.atleticogo,_name.emelec],
    2011.0: [_name.lau,_name.ldu,_name.vasco,_name.velez,                            _name.arsenalsarandi,_name.libertad,_name.universitario,_name.santafe,  _name.flamengo,_name.independiente,_name.saopaulo,_name.botafogo,_name.univcatolica,_name.godoycruz,_name.aurora,_name.olimpia],
    2010.0: [_name.independiente,_name.goias,_name.ldu,_name.palmeiras,              _name.tolima,_name.avai,_name.newells,_name.atleticomg,                 _name.defensor,_name.penarol,_name.emelec,_name.santafe,_name.sucre,_name.sanJoseBOL,_name.sanfelipe,_name.banfield],
    2009.0: [_name.ldu,_name.fluminense,_name.riverURU,_name.cerroporteno,           _name.velez,_name.lau,_name.sanlorenzo,_name.botafogo,                  _name.lanus,_name.alianzaSullana,_name.vitoria,_name.goias,_name.cienciano,_name.unionespanola,_name.emelec,_name.internacional],
    2008.0: [_name.internacional,_name.estudiantes,_name.chivas,_name.argentinojuniors,  _name.bocajuniors,_name.botafogo,_name.riverplate,_name.palmeiras,  _name.univcatolica,_name.arsenalsarandi,_name.ancash,_name.sanluis,_name.americadecali,_name.defensor,_name.atleticopr,_name.ldu],
    2007.0: [_name.arsenalsarandi,_name.americamex,_name.riverplate,_name.millonarios,   _name.chivas,_name.vasco,_name.defensor,_name.saopaulo,             _name.goias,_name.pachuca,_name.botafogo,_name.colocolo,_name.dcunited,_name.lanus,_name.elnacional,_name.bocajuniors],
    2006.0: [_name.pachuca,_name.colocolo,_name.atleticopr,_name.toluca,             _name.lanus,_name.gimnasia,_name.nacional,_name.sanlorenzo,             _name.tolima,_name.alajuelense,_name.riverplate,_name.elnacional,_name.corinthians,_name.fluminense,_name.bocajuniors,_name.santos],
    2005.0: [_name.bocajuniors,_name.pumas,_name.univcatolica,_name.velez,           _name.internacional,_name.corinthians,_name.fluminense,_name.americamex,  _name.cerroporteno,_name.theStrongest,_name.atleticonacional,_name.cruzeiro,_name.riverplate,_name.banfield,_name.dcunited,_name.rosario],
    2004.0: [_name.bocajuniors,_name.bolivar,_name.internacional,_name.ldu,          _name.cerroporteno,_name.arsenalsarandi,_name.junior,_name.santos,      _name.sanlorenzo,_name.concepcion,_name.cruzeiro,_name.santos,_name.penarol,_name.riverplate,_name.alianzaSullana,_name.saopaulo],
    2003.0: [_name.cienciano,_name.riverplate,_name.atleticonacional,_name.saopaulo, _name.santos,_name.libertad,_name.bocajuniors,_name.theStrongest,       _name.univcatolica,_name.independiente,_name.colon,_name.fluminense,_name.saocaetano,_name.sanlorenzo,_name.ldu,_name.nacional],
    2002.0: [_name.sanlorenzo,_name.atleticonacional,_name.bolivar,_name.nacional,   _name.racing,_name.santiagowanderers,_name.gimnasia,_name.alianzalima,  _name.monagas,_name.americadecali,_name.libertad,_name.danubio,_name.riverplate,_name.cobreloa,_name.bocajuniors,_name.barcelonaequ],
    //COPA CONMEBOL
    2001.0: [],
    2000.0: [],
    1999.0: [_name.talleres,_name.csa,_name.concepcion,_name.saoraimundo,            ],
    1998.0: [_name.santos,_name.rosario,_name.sampaio,_name.atleticomg,       ],
    1997.0: [_name.atleticomg,_name.lanus,_name.universitario,_name.colon,           ],
    1996.0: [_name.lanus,_name.santafe,_name.rosario,_name.vasco,             ],
    1995.0: [_name.rosario,_name.atleticomg,_name.colegiales,_name.americadecali,],
    1994.0: [_name.saopaulo,_name.penarol,_name.corinthians,_name.lau,               ],
    1993.0: [_name.botafogo,_name.penarol,_name.atleticomg,_name.sanlorenzo,         ],
    1992.0: [_name.atleticomg,_name.olimpia,_name.elnacional,_name.gimnasia,         ],
  },

};