import 'package:fifa/values/club_names.dart';
import 'package:fifa/values/league_names.dart';


ClubName n = ClubName();
LeagueOfficialNames leagueName = LeagueOfficialNames();

Map<String,dynamic> mapOrienteMedio = {

  leagueName.arabia : {
    2022.0: [n.alhilal,n.alIttihad,n.alnassr,n.alShabab,n.damac,],
    2021.0: [n.alhilal,n.alShabab,n.alIttihad,n.altaawoun,n.alettifaq,   n.alnassr],
    2020.0: [n.alhilal,n.alnassr,n.alahli,n.alwehda,n.alFaisalyARABIA,   n.alraed],
    2019.0: [n.alnassr,n.alhilal,n.altaawoun,n.alahli,n.alShabab,        n.alFaisalyARABIA,],
    2018.0: [n.alhilal,n.alahli,n.alnassr,n.alettifaq,n.alfateh,         n.alFaisalyARABIA,],
    2017.0: [n.alhilal,n.alahli,n.alnassr,n.alIttihad,n.alraed,          n.alShabab,],
    2016.0: [n.alahli,n.alhilal,n.alIttihad,n.altaawoun,n.alfateh,       n.alShabab,],
    2015.0: [n.alnassr,n.alahli,n.alhilal,n.alIttihad,n.alShabab,        n.alfateh,],
    2014.0: [n.alnassr,n.alhilal,n.alahli,n.alShabab,n.altaawoun,        n.alFaisalyARABIA,],
    2013.0: [n.alfateh,n.alhilal,n.alShabab,n.alnassr,n.alahli,          n.alettifaq,],
    2012.0: [n.alShabab,n.alahli,n.alhilal,n.alettifaq,n.alIttihad,      n.alfateh],
    2011.0: [n.alhilal,n.alIttihad,n.alettifaq,n.alShabab,n.alnassr,     n.alahli,],
    2010.0: [n.alhilal,n.alIttihad,n.alnassr,n.alShabab,n.alwehda,       n.alahli,],
    2009.0: [n.alIttihad,n.alhilal,n.alahli,n.alShabab,n.alnassr,        n.alettifaq,],
    2008.0: [n.alhilal,n.alIttihad,n.alShabab,n.alettifaq,n.alnassr,     n.alwehda,],
    2007.0: [n.alIttihad,n.alhilal,n.alwehda,n.alShabab,n.alahli,        n.alettifaq,],
    2006.0: [n.alShabab,n.alhilal,n.alIttihad,n.alahli,n.alettifaq,      n.alnassr,],
    2005.0: [n.alhilal,n.alShabab,n.alIttihad,n.alnassr,n.alahli,        n.alwehda,],
    2004.0: [n.alShabab,n.alIttihad,n.alhilal,n.alahli,n.alettifaq,      n.alnassr,],
    2003.0: [n.alIttihad,n.alahli,n.alQadisiya,n.alnassr,n.alhilal,  n.alShabab,n.altai,],
    2002.0: [n.alhilal,n.alIttihad,n.alnassr,n.alahli,n.alriad,      n.alshoulla,n.alnajma,],
    2001.0: [n.alIttihad,n.alnassr,n.alahli,n.alhilal,n.alriad,      n.alansarARABIA,n.alShabab],
    2000.0: [n.alIttihad,n.alahli,n.alShabab,n.alnassr,n.alhilal,    n.alriad,n.alettifaq,],
    1999.0: [n.alIttihad,n.alahli,n.alhilal,n.alShabab,n.alnassr,    n.alettifaq,n.alriad,],
    1998.0: [n.alhilal,n.alShabab,n.alahli,n.alnajma,n.alnassr,      n.alettifaq,n.alIttihad,],
    1997.0: [n.alIttihad,n.alhilal,n.alnassr,n.alShabab,n.alahli,    n.alriad,n.alettifaq,],
    1996.0: [n.alhilal,n.alahli,n.alIttihad,n.alnassr,n.alettifaq,   n.alnajma,n.altai,],
    1995.0: [n.alnassr,n.alhilal,n.alriad,n.alettifaq,n.alShabab,    n.alahli,n.alIttihad,],
    1994.0: [n.alnassr,n.alriad,n.alhilal,n.alShabab,n.alQadisiya,   n.alahli,n.alIttihad,],
    1993.0: [n.alShabab,n.alhilal,n.alIttihad,n.alettifaq,n.alahli,  n.alriad,n.alraed,],
    1992.0: [n.alShabab,n.alettifaq,n.alahli,n.alnassr,n.alIttihad,  n.alQadisiya,n.alhilal,],
    1991.0: [n.alShabab,n.alnassr,n.alhilal,n.alettifaq,n.alIttihad, n.alriad,n.alahli,],
    1990.0: [n.alhilal,n.alahli,n.alnassr,n.altai,n.alShabab,        n.alQadisiya,n.alettifaq,],
    1989.0: [n.alnassr,n.alShabab,n.alhilal,n.alahli,n.alettifaq,    n.alIttihad,n.altai,],
    1988.0: [n.alhilal,n.alettifaq,n.alnassr,n.alIttihad,n.alShabab, n.altai,],
    1987.0: [n.alettifaq,n.alhilal,n.alnassr,n.altai,n.alShabab,     n.alahli,],
    1986.0: [n.alhilal,n.alIttihad,n.alnassr,n.alwehda,n.altai,      n.alahli,],
    1985.0: [n.alhilal,n.alShabab,n.alahli,n.alettifaq,n.alnassr,    n.alIttihad,],
    1984.0: [n.alahli,n.alIttihad,n.alettifaq,n.alQadisiya,n.alnassr, n.alhilal,],
    1983.0: [n.alettifaq,n.alhilal,n.alShabab,n.alnassr,n.alahli,    n.alIttihad,n.alQadisiya,n.alnahda,n.alrawdhah,n.ohod],
    1982.0: [n.alIttihad,n.alShabab,n.alhilal,n.alnassr,  ],
    1981.0: [n.alnassr,n.alhilal,n.alQadisiya,n.alahli,n.alettifaq,   n.alIttihad,],
    1980.0: [n.alnassr,n.alhilal,n.alIttihad,n.alahli,n.alShabab,     n.alettifaq,n.alnahda,n.alQadisiya,n.alwehda,n.ohod],
    1979.0: [n.alhilal,n.alnassr,n.alIttihad,n.alahli,n.alQadisiya,    n.alettifaq,n.alnahda,n.alwehda,n.altai,n.alriad],
    1978.0: [n.alahli,n.alnassr,n.alettifaq,n.alIttihad,n.alQadisiya,  n.alhilal,n.alnahda,n.alwehda,n.alShabab,n.ohod],
    1977.0: [n.alhilal,n.alnassr,n.alahli,n.alIttihad,n.alwehda,   n.alQadisiya,n.alShabab,n.alriad],
    1976.0: [],
    1975.0: [n.alnassr,],
  },

  leagueName.qatar : {
    2022.0: [n.alsadd,n.alduhail,n.alwakrah,n.alarabi,n.algharafa,    ],
    2021.0: [n.alsadd,n.alduhail,n.alrayyan,n.algharafa,n.alahliQAT,  ],
    2020.0: [n.alduhail,n.alrayyan,n.alsadd,n.algharafa,n.alsailiya,  ],
    2019.0: [n.alsadd,n.alduhail,n.alsailiya,n.alrayyan,n.alahliQAT,  ],
    2018.0: [n.alduhail,n.alsadd,n.alrayyan,n.algharafa,n.ummSalal,   ],
    2017.0: [n.alduhail,n.alsadd,n.alrayyan,n.eljaish,n.algharafa,    ],
    2016.0: [n.alrayyan,n.eljaish,n.alsadd,n.alduhail,n.ummSalal,     ],
    2015.0: [n.alduhail,n.alsadd,n.eljaish,n.qatar,n.alahliQAT,       ],
    2014.0: [n.alduhail,n.eljaish,n.alsadd,n.alsailiya,n.alarabi,     ],
    2013.0: [n.alsadd,n.alduhail,n.eljaish,n.alrayyan,n.ummSalal,     ],
    2012.0: [n.alduhail,n.eljaish,n.alrayyan,n.alsadd,n.alkhor,       ],
    2011.0: [n.alduhail,n.algharafa,n.alrayyan,n.alarabi,n.qatar,     ],
    2010.0: [n.algharafa,n.alsadd,n.alarabi,n.qatar,n.alrayyan,       ],
    2009.0: [n.algharafa,n.alsadd,n.alrayyan,n.qatar,n.alkhor,        ],
    2008.0: [n.algharafa,n.alsadd,n.ummSalal,n.qatar,n.alrayyan,      ],
    2007.0: [n.alsadd,n.algharafa,n.ummSalal,n.alrayyan,n.alwakrah,   ],
    2006.0: [n.alsadd,n.qatar,n.alarabi,n.alrayyan,n.alahliQAT,       ],
    2005.0: [n.algharafa,n.alrayyan,n.alkhor,n.qatar,n.alarabi,       ],
    2004.0: [n.alsadd,n.qatar,n.alarabi,n.alahliQAT,n.alrayyan,       ],
    2003.0: [n.qatar,n.alsadd,n.alkhor,n.algharafa,n.alahliQAT,       ],
    2002.0: [n.algharafa,n.qatar,n.alrayyan,n.alsadd,n.alwakrah,      ],
    2001.0: [n.alwakrah,n.alarabi,n.altaawoun,n.alrayyan,n.algharafa, ],
    2000.0: [n.alsadd,n.alrayyan,n.alarabi,n.algharafa,n.alahliQAT,   ],
    1999.0: [n.alrayyan,n.algharafa,n.alsadd,n.alarabi,n.alwakrah,    ],
    1998.0: [n.algharafa,n.alrayyan,n.alsadd,n.alarabi,n.alahliQAT,   ],
    1997.0: [n.alarabi,n.alrayyan,n.algharafa,n.alwakrah,n.alsadd,    ],
    1996.0: [n.alarabi,n.alrayyan,n.alwakrah,n.alsadd,n.algharafa,    ],
    1995.0: [n.alrayyan,],
    1994.0: [n.alarabi,n.alrayyan,],
    1993.0: [n.alarabi,],
    1992.0: [n.algharafa,n.qatar,n.alsadd,n.alarabi,n.alrayyan,n.alahliQAT,n.alwakrah,n.altaawoun,n.alshamal],
    1991.0: [n.alarabi,],
    1990.0: [n.alrayyan,],
    1989.0: [n.alsadd,],
    1988.0: [n.alsadd,],
    1987.0: [n.alsadd,],
    1986.0: [n.alrayyan,],
    1985.0: [n.alarabi,n.qatar,n.alrayyan,n.alahliQAT,n.alsadd,n.altaawoun,n.algharafa],
    1984.0: [n.alrayyan,n.alahliQAT,n.alarabi,n.qatar,n.alsadd,n.altaawoun,n.alwakrah],
    1983.0: [n.alarabi,],
    1982.0: [n.alrayyan,],
    1981.0: [n.alsadd,n.alarabi],
    1980.0: [n.alsadd,],
    1979.0: [n.alsadd,],
    1978.0: [n.alrayyan,],
    1977.0: [n.qatar,],
    1976.0: [n.alrayyan,],
    1975.0: [],
    1974.0: [n.alsadd,],
    1973.0: [n.qatar,],
  },

  leagueName.eau : {
    2022.0: [],
    2021.0: [n.aljazira,n.baniyas,],
    2020.0: [],
    2019.0: [n.alsharjah,n.shababalahli,n.alWahda,n.alain,n.aljazira, ],
    2018.0: [n.alain,n.alWahda,n.alwasl,n.alnasrEAU,n.shababalahli,   ],
    2017.0: [n.aljazira,n.alwasl,n.alahli,n.alain,n.alWahda,          ],
    2016.0: [n.shababalahli,n.alain,n.alWahda,n.alnasrEAU,n.alShababEAU,],
    2015.0: [n.alain,n.aljazira,n.alShababEAU,n.alWahda,n.alnasrEAU,  ],
    2014.0: [n.shababalahli,n.alWahda,n.aljazira,n.alShababEAU,n.alnasrEAU,],
    2013.0: [n.alain,n.shababalahli,n.aljazira,n.baniyas,n.alShababEAU,  n.alnasrEAU,n.alWahda,],
    2012.0: [n.alain,n.alnasrEAU,n.alShababEAU,n.aljazira,n.shababalahli,  n.alWahda,n.ajman,],
    2011.0: [n.aljazira,n.baniyas,n.alnasrEAU,n.alShababEAU,n.alWahda,   n.alwasl,n.alsharjah,],
    2010.0: [n.alWahda,n.aljazira,n.alain,n.baniyas,n.alwasl,        n.alsharjah,n.alShababEAU,n.shababalahli,n.aldhafra,n.alnasrEAU,],
    2009.0: [n.shababalahli,n.aljazira,n.alain,n.alWahda,n.alShababEAU, n.alnasrEAU,n.alwasl,n.aldhafra,n.ajman,n.alsharjah,],
    2008.0: [n.alShababEAU,n.aljazira,n.shababalahli,n.alsharjah,n.alshaab,  n.alain,n.alwasl,n.alWahda,n.alnasrEAU,n.aldhafra,],
    2007.0: [n.alwasl,n.alWahda,n.aljazira,n.alsharjah,n.alshaab,    n.alShababEAU,n.shababalahli,n.alnasrEAU,n.alain,],
    2006.0: [n.shababalahli,n.alWahda,n.aljazira,n.alain,n.alnasrEAU, n.alShababEAU,n.alsharjah,n.alwasl,n.alshaab,n.emirates,     n.baniyas],
    2005.0: [n.alWahda,n.alain,n.aljazira,n.alnasrEAU,n.alsharjah,    n.alShababEAU,n.shababalahli,n.alwasl,n.alshaab,n.emirates,  n.dubai,],
    2004.0: [n.alain,n.shababalahli,n.alShababEAU,n.alwasl,],
    2003.0: [n.alain,n.alWahda,n.shababalahli,n.alnasrEAU,n.alshaab,   n.aljazira,n.alsharjah,n.alwasl,n.alShababEAU,],
    2002.0: [n.alain,n.aljazira,n.alshaab,n.alWahda,n.shababalahli,    n.alwasl,n.alsharjah,n.alnasrEAU,],
    2001.0: [n.alWahda,n.alain,],
    2000.0: [n.alain,n.alnasrEAU,],
    1999.0: [n.alWahda,n.alain,],
    1998.0: [n.alain,n.alsharjah,],
    1997.0: [n.alwasl,n.alnasrEAU,],
    1996.0: [n.alsharjah,n.alwasl,],
    1995.0: [n.alShababEAU,n.alwasl,],
    1994.0: [n.alsharjah,n.alain,],
    1993.0: [n.alain,n.alwasl,],
    1992.0: [n.alwasl,n.alsharjah],
    1991.0: [],
    1990.0: [n.alShababEAU,n.alwasl,],
    1989.0: [n.alsharjah,n.alwasl,],
    1988.0: [n.alwasl,n.alsharjah,],
    1987.0: [n.alsharjah,n.alwasl,],
    1986.0: [n.alnasrEAU,n.alwasl,],
    1985.0: [n.alwasl,n.alShababEAU,],
    1984.0: [n.alain,n.alwasl,],
    1983.0: [n.alwasl,n.alsharjah,],
    1982.0: [n.alwasl,n.alsharjah,],
    1981.0: [n.alain,n.alnasrEAU,],
    1980.0: [n.shababalahli,],
    1979.0: [n.alnasrEAU,n.alsharjah,],
    1978.0: [n.alnasrEAU,n.alain,],
    1977.0: [n.alain,n.alsharjah,],
    1976.0: [n.shababalahli,n.alain,],
    1975.0: [n.shababalahli,n.alsharjah,],
    1974.0: [n.alsharjah,n.shababalahli,],
  },

  leagueName.iran : {
    2022.0: [n.esteghlal,n.persepolis,n.sepahan,],
    2021.0: [n.persepolis,n.sepahan,n.esteghlal,],
    2020.0: [n.persepolis,n.esteghlal,n.foolad,],
    2019.0: [n.persepolis,n.sepahan,n.esteghlal,],
    2018.0: [n.persepolis,n.zobahan,n.esteghlal,],
    2017.0: [n.persepolis,n.esteghlal,n.tractor,],
    2016.0: [n.esteghlalKhuzestan,n.persepolis,n.esteghlal,],
    2015.0: [n.sepahan,n.tractor,n.naftTehran,],
    2014.0: [n.foolad,n.persepolis,n.naftTehran,],
    2013.0: [n.esteghlal,n.tractor,n.sepahan,],
    2012.0: [n.sepahan,n.tractor,n.esteghlal,],
    2011.0: [n.sepahan,n.esteghlal,n.zobahan,],
    2010.0: [n.sepahan,n.zobahan,n.esteghlal,],
    2009.0: [n.esteghlal,n.zobahan,],
    2008.0: [n.persepolis,n.sepahan,],
    2007.0: [n.saipa,n.esteghlal,n.persepolis],
    2006.0: [n.esteghlal,n.pastehran,n.saipa],
    2005.0: [n.foolad,n.zobahan,n.esteghlal,],
    2004.0: [n.pastehran,n.esteghlal,n.foolad,],
    2003.0: [n.sepahan,n.pastehran,n.persepolis,],
    2002.0: [n.persepolis,n.esteghlal,n.foolad,],
    2001.0: [n.esteghlal,n.persepolis,n.saipa,],
    2000.0: [n.persepolis,n.esteghlal,],
    1999.0: [n.persepolis,n.esteghlal,n.sepahan,],
    1998.0: [n.esteghlal,n.pastehran,n.zobahan,],
    1997.0: [n.persepolis,n.bahman,n.sepahan,],
    1996.0: [n.persepolis,n.bahman,n.esteghlal,],
    1995.0: [n.saipa,n.esteghlal,],
    1994.0: [n.saipa,n.persepolis,],
    1993.0: [n.pastehran,n.persepolis,n.keshavarz,],
    1992.0: [n.pastehran,n.esteghlal,n.persepolis,],
    1991.0: [],
    1990.0: [n.esteghlal,n.persepolis,n.malavan,],
    1989.0: [],
    1988.0: [],
    1987.0: [],
    1986.0: [],
    1985.0: [],
    1984.0: [],
    1983.0: [],
    1982.0: [],
    1981.0: [],
    1980.0: [],
    1979.0: [],
    1978.0: [n.pastehran,n.persepolis,n.malavan],
    1977.0: [n.pastehran,n.persepolis,],
    1976.0: [n.persepolis,n.homa,n.pastehran],
    1975.0: [n.esteghlal,n.persepolis,n.homa],
    1974.0: [n.persepolis,n.esteghlal,n.pastehran,],
    1973.0: [],
    1972.0: [],
    1971.0: [],
    1970.0: [],
    1969.0: [],
    1968.0: [],
    1967.0: [],
    1966.0: [],
    1965.0: [],
    1964.0: [],
    1963.0: [],
    1962.0: [],
    1961.0: [],
    1960.0: [],
  },
  leagueName.iraque : {
    2022.0: [n.alShortaIRAQ,n.alQuwaAlJawiya,n.alTalaba,],
    2021.0: [n.alQuwaAlJawiya,n.alzawraa,n.alnajaf],
    2020.0: [],
    2019.0: [n.alShortaIRAQ,n.alQuwaAlJawiya,n.alzawraa,],
    2018.0: [n.alzawraa,n.alQuwaAlJawiya,n.alnaft,],
    2017.0: [n.alQuwaAlJawiya,n.alnaft,n.alShortaIRAQ,],
    2016.0: [n.alzawraa,n.naftAlwasat,n.alTalaba,],
    2015.0: [n.naftAlwasat,n.alQuwaAlJawiya,n.alShortaIRAQ,],
    2014.0: [],
    2013.0: [n.alShortaIRAQ,n.erbil,n.alQuwaAlJawiya,],
    2012.0: [n.erbil,n.duhok,n.alQuwaAlJawiya,],
    2011.0: [n.alzawraa,n.erbil,n.alsinaa,],
    2010.0: [n.duhok,n.alTalaba,n.alzawraa,],
    2009.0: [n.erbil,n.alnajaf,n.duhok,],
    2008.0: [n.erbil,n.alzawraa,n.alQuwaAlJawiya,],
    2007.0: [n.erbil,n.alQuwaAlJawiya,n.alnajaf],
    2006.0: [n.alzawraa,n.alnajaf,n.erbil,],
    2005.0: [n.alQuwaAlJawiya,n.alminaa,n.alTalaba],
    2004.0: [],
    2003.0: [],
    2002.0: [n.alTalaba,n.alQuwaAlJawiya,n.alShortaIRAQ,],
    2001.0: [n.alzawraa,n.alQuwaAlJawiya,n.alShortaIRAQ,],
    2000.0: [n.alzawraa,n.alQuwaAlJawiya,n.alShortaIRAQ,],
    1999.0: [n.alzawraa,n.alTalaba,n.alQuwaAlJawiya,],
    1998.0: [n.alShortaIRAQ,n.alQuwaAlJawiya,n.alzawraa,],
    1997.0: [n.alQuwaAlJawiya,n.alzawraa,n.alTalaba,],
    1996.0: [n.alzawraa,n.alnajaf,n.alShortaIRAQ,],
    1995.0: [n.alzawraa,n.alQuwaAlJawiya,n.alnajaf,],
    1994.0: [n.alzawraa,n.alQuwaAlJawiya,n.alTalaba,],
    1993.0: [n.alTalaba,n.alzawraa,n.alQuwaAlJawiya,],
    1992.0: [n.alQuwaAlJawiya,n.alzawraa,],
    1991.0: [n.alzawraa,n.alTalaba,n.alShortaIRAQ,],
    1990.0: [n.alQuwaAlJawiya,n.alRasheed,n.alShortaIRAQ,],
    1989.0: [n.alRasheed,n.alTalaba,],
    1988.0: [n.alRasheed,n.aljaishIRAQ,],
    1987.0: [n.alRasheed,n.aljaishIRAQ,],
    1986.0: [n.alTalaba,n.alRasheed,],
    1985.0: [],
    1984.0: [n.aljaishIRAQ,n.alTalaba,],
    1983.0: [n.salahaddin,n.alTalaba,],
    1982.0: [n.alTalaba,],
    1981.0: [n.alTalaba,n.alShortaIRAQ,],
    1980.0: [n.alShortaIRAQ,n.alzawraa,],
    1979.0: [n.alzawraa,n.alShortaIRAQ,],
    1978.0: [n.alminaa,n.alzawraa,],
    1977.0: [n.alzawraa,],
    1976.0: [n.alzawraa],
    1975.0: [n.alQuwaAlJawiya,],
    1974.0: [n.alQuwaAlJawiya,],
    1973.0: [],
    1972.0: [],
    1971.0: [],
    1970.0: [],
    1969.0: [],
    1968.0: [],
    1967.0: [],
    1966.0: [],
    1965.0: [],
    1964.0: [],
    1963.0: [],
    1962.0: [],
    1961.0: [],
    1960.0: [],
  },
  leagueName.siria : {
    2022.0: [n.tishreen,n.alWathba,n.alJaish,],
    2021.0: [n.tishreen,n.alJaish,n.alkaramah,],
    2020.0: [n.tishreen,n.alWathba,n.hutteen,],
    2019.0: [n.alJaish,n.tishreen,n.alwahdaSYR,],
    2018.0: [n.alJaish,n.alittihadSYR,n.alwahdaSYR,],
    2017.0: [n.alJaish,n.tishreen,n.alwahdaSYR,],
    2016.0: [n.alJaish,n.alwahdaSYR,n.alittihadSYR,],
    2015.0: [n.alJaish,n.alwahdaSYR,n.alShortaDamascus,],
    2014.0: [n.alwahdaSYR,n.alJaish,],
    2013.0: [n.alJaish,n.alShortaDamascus,n.alhurriya,],
    2012.0: [n.alShortaDamascus,n.alJaish,n.alwahdaSYR,],
    2011.0: [],
    2010.0: [n.alJaish,n.alkaramah,n.tishreen,],
    2009.0: [n.alkaramah,n.alittihadSYR,],
    2008.0: [n.alkaramah,n.almajd,n.alittihadSYR,],
    2007.0: [n.alkaramah,n.alittihadSYR,],
    2006.0: [n.alkaramah,n.alJaish,n.alwahdaSYR,],
    2005.0: [n.alittihadSYR,n.alkaramah,n.alwahdaSYR,],
    2004.0: [n.alwahdaSYR,n.alkaramah,n.tishreen,],
    2003.0: [n.alJaish,n.alittihadSYR,],
    2002.0: [n.alJaish,n.alittihadSYR,n.alwahdaSYR,],
    2001.0: [n.alJaish,n.alkaramah,],
    2000.0: [n.jableh,n.hutteen,n.tishreen,],
    1999.0: [n.alJaish,n.alkaramah,n.alwahdaSYR,],
    1998.0: [n.alJaish,n.alkaramah,n.hutteen,],
    1997.0: [n.tishreen,n.alJaish,n.alkaramah,],
    1996.0: [n.alkaramah,n.hutteen,n.alhurriya],
    1995.0: [n.alittihadSYR,n.alkaramah,n.jableh,],
    1994.0: [n.alhurriya,n.jableh,n.alittihadSYR,],
    1993.0: [n.alittihadSYR,n.alkaramah,n.alhurriya,],
    1992.0: [n.alhurriya,n.jableh,n.alittihadSYR,],
    1991.0: [n.alfutowa,n.jableh,n.alShortaDamascus,],
    1990.0: [n.alfutowa,n.alkaramah,n.alWathba,],
    1989.0: [n.jableh,n.alShortaDamascus,n.alittihadSYR,],
    1988.0: [n.jableh,n.alittihadSYR,n.alfutowa,],
    1987.0: [n.jableh,n.alkaramah,n.alShortaDamascus,],
    1986.0: [n.alJaish,n.jableh,n.alfutowa,],
    1985.0: [n.alJaish,n.alkaramah,n.jableh,],
    1984.0: [n.alkaramah,n.jableh,n.alittihadSYR,],
    1983.0: [n.alkaramah,n.alittihadSYR,n.alfutowa,],
    1982.0: [n.tishreen,n.alWathba,n.alittihadSYR,],
    1981.0: [],
    1980.0: [n.alShortaDamascus,n.alhurriya,n.alittihadSYR,],
  },
};