import 'package:fifa/classes/countries/words.dart';
import 'package:fifa/values/league_names.dart';


var w = Words.country;
LeagueOfficialNames leagueName = LeagueOfficialNames();

Map<String,dynamic> mapSelecoes = {
  /////////////////////////////////////////////////////////////////
  // AMERICA DO NORTE
  ///////////////////////////////////////////////////////////////
  leagueName.copamundo : {
    2022.0: [w.argentina,w.france,    w.croatia,w.morocco,         w.netherlands,w.england,w.brazil,w.portugal,  w.japan,w.senegal,w.australia,w.switzerland,w.spain,w.unitedstates,w.poland,w.southkorea,    w.germany,w.ecuador,w.cameroon,w.uruguay,w.tunisia,w.mexico,w.belgium,w.ghana,      w.saudiarabia,w.iran,w.costarica,w.denmark,w.serbia,w.wales,w.canada,w.qatar],
    2018.0: [w.france,w.croatia,      w.belgium,w.england,         w.uruguay,w.russia,w.brazil,w.sweden,       w.argentina,w.portugal,w.mexico,w.japan,w.spain,w.denmark,w.switzerland,w.colombia],
    2014.0: [w.germany,w.argentina,   w.netherlands,w.brazil,      w.france,w.belgium,w.colombia,w.costarica,  w.algeria,w.switzerland,w.mexico,w.chile,w.nigeria,w.unitedstates,w.uruguay,w.greece],
    2010.0: [w.spain,w.netherlands,   w.germany,w.uruguay,         w.paraguay,w.brazil,w.argentina,w.ghana,    w.portugal,w.japan,w.england,w.southkorea,w.mexico,w.chile,w.slovakia,w.unitedstates],
    2006.0: [w.italy,w.france,        w.germany,w.portugal,        w.ukraine,w.brazil,w.argentina,w.england,   w.sweden,w.mexico,w.australia,w.switzerland,w.ecuador,w.netherlands,w.ghana,w.spain],
    2002.0: [w.brazil,w.germany,      w.turkey,w.southkorea,       w.england,w.unitedstates,w.senegal,w.spain, w.belgium,w.paraguay,w.japan,w.italy,w.denmark,w.mexico,w.sweden,w.ireland],
    1998.0: [w.france,w.brazil,       w.croatia,w.netherlands,     w.italy,w.denmark,w.germany,w.argentina,           ],
    1994.0: [w.brazil,w.italy,        w.sweden,w.bulgaria,         w.netherlands,w.spain,w.romania,w.germany,         ],
    1990.0: [w.germany,w.argentina,   w.italy,w.england,           w.czechrepublic,w.iuguslavia,w.ireland,w.cameroon, ],
    1986.0: [w.argentina,w.germany,   w.france,w.belgium,          ],
    1982.0: [w.italy,w.germany,       w.poland,w.france,           w.urss,w.brazil,w.england,w.austria,            w.northernIreland,w.spain,w.argentina,w.belgium],
    1978.0: [w.argentina,w.netherlands, w.brazil,w.italy,          w.germany,w.poland,w.austria,w.peru,            ],
    1974.0: [w.germany,w.netherlands, w.poland,w.brazil,           ],
    1970.0: [w.brazil,w.italy,        w.germany,w.uruguay,         w.peru,w.mexico,w.england,w.urss,               ],
    1966.0: [w.england,w.germany,     w.portugal,w.urss,           w.argentina,w.uruguay,w.northKorea,w.hungary,   ],
    1962.0: [w.brazil,w.czechrepublic, w.chile,w.iuguslavia,       w.england,w.hungary,w.urss,w.germany,           ],
    1958.0: [w.brazil,w.sweden,       w.france,w.germany,          w.wales,w.urss,w.northernIreland,w.iuguslavia,  w.hungary,w.england,w.czechrepublic,w.paraguay,  w.argentina,w.scotland,w.austria,w.mexico,],
    1954.0: [w.germany,w.hungary,     w.austria,w.uruguay,         w.iuguslavia,w.brazil,w.switzerland,w.england,  ],
    1950.0: [w.uruguay,w.brazil,      w.sweden,w.spain,            w.iuguslavia,w.italy,w.switzerland,w.england,w.chile,w.unitedstates,w.paraguay,w.mexico,w.bolivia],
    1938.0: [w.italy,w.hungary,       w.brazil,w.sweden,           w.france,w.switzerland,w.czechrepublic,w.cuba,  w.norway,w.belgium,w.poland,w.netherlands,w.indonesia,w.germany,w.romania],
    1934.0: [w.italy,w.czechrepublic, w.germany,w.austria,         w.spain,w.switzerland,w.sweden,w.hungary,  w.unitedstates,w.brazil,w.france,w.egypt,w.romania,w.netherlands,w.belgium,w.argentina],
    1930.0: [w.uruguay,w.argentina,   w.iuguslavia,w.unitedstates, w.chile,w.paraguay,w.romania,w.brazil,     w.france,w.peru,w.belgium,w.bolivia],
    1928.0: [w.uruguay,w.argentina,   w.italy,w.egypt,             w.germany,w.belgium,w.spain,w.portugal],
    1924.0: [w.uruguay,w.switzerland, w.sweden,w.netherlands,      w.france,w.italy,w.egypt,w.ireland],
  },

  leagueName.copaconfederacoes : {
    2022.0: [w.argentina,w.italy,],
    2017.0: [w.germany,w.chile,w.portugal,w.italy,],
    2013.0: [w.brazil,w.spain,w.italy,w.uruguay,],
    2009.0: [w.brazil,w.unitedstates,w.spain,w.southafrica,],
    2005.0: [w.brazil,w.argentina,w.germany,w.mexico,],
    2001.0: [w.france,w.japan,w.australia,w.brazil,],
    1999.0: [w.mexico,w.brazil,w.unitedstates,w.saudiarabia,],
    1997.0: [w.brazil,w.australia,w.czechrepublic,w.uruguay,],
    1995.0: [w.denmark,w.argentina,w.mexico,w.nigeria,],
    1993.0: [w.argentina,w.denmark,],
    1992.0: [w.argentina,w.saudiarabia,w.unitedstates,w.ivorycoast,],
    1985.0: [w.france,w.uruguay,],
  },
  
  leagueName.eurocopa : {
    2020.0: [w.italy,w.england,w.spain,w.denmark,           w.belgium,w.ukraine,w.switzerland,w.czechrepublic,    w.austria,w.germany,w.portugal,w.france,w.croatia,w.switzerland,w.netherlands,w.wales],
    2016.0: [w.portugal,w.france,w.wales,w.germany,         w.poland,w.iceland,w.belgium,w.italy,                 w.croatia,w.ireland,w.switzerland,w.croatia,w.northernIreland,w.hungary,w.slovakia,w.spain,w.england],
    2012.0: [w.spain,w.italy,w.germany,w.portugal,          w.france,w.england,w.greece,w.czechrepublic,          w.russia,w.croatia,w.denmark,w.ukraine,        w.sweden,w.ireland,w.poland,w.netherlands,],
    2008.0: [w.spain,w.germany,w.russia,w.turkey,           w.italy,w.portugal,w.netherlands,w.croatia,           w.sweden,w.czechrepublic,w.romania,w.austria,  w.switzerland,w.poland,w.france,w.greece],
    2004.0: [w.greece,w.portugal,w.czechrepublic,w.netherlands,  w.france,w.england,w.denmark,w.sweden,           w.italy,w.spain,w.croatia,w.germany,           w.russia,w.switzerland,w.latvia,w.bulgaria],
    2000.0: [w.france,w.italy,w.netherlands,w.portugal,     w.spain,w.romania,w.iuguslavia,w.turkey,              w.norway,w.czechrepublic,w.england,w.belgium,  w.slovenia,w.germany,w.sweden,w.denmark],
    1996.0: [w.germany,w.czechrepublic,w.england,w.france,  w.croatia,w.portugal,w.spain,w.netherlands,           w.italy,w.denmark,w.bulgaria,w.scotland,       w.switzerland,w.russia,w.turkey,w.romania],
    1992.0: [w.denmark,w.germany,w.netherlands,w.sweden,    w.scotland,w.france,w.england,w.russia],
    1988.0: [w.netherlands,w.urss,w.germany,w.italy,        w.ireland,w.spain,w.england,w.denmark],
    1984.0: [w.france,w.spain,w.denmark,w.portugal,         w.germany,w.belgium,w.romania,w.iuguslavia],
    1980.0: [w.germany,w.belgium,w.czechrepublic,w.italy,   w.netherlands,w.england,w.spain,w.greece],
    1976.0: [w.czechrepublic,w.germany,w.netherlands,w.iuguslavia,],
    1972.0: [w.germany,w.urss,w.belgium,w.hungary,          ],
    1968.0: [w.italy,w.iuguslavia,w.england,w.urss,         ],
    1964.0: [w.spain,w.urss,w.hungary,w.denmark,            ],
    1960.0: [w.urss,w.iuguslavia,w.czechrepublic,w.france,  ],
  },

  leagueName.copaamerica : {
    2021.0: [w.argentina,w.brazil,w.colombia,w.peru,],
    2019.0: [w.brazil,w.peru,w.argentina,w.chile,],
    2016.0: [w.chile,w.argentina,w.colombia,w.unitedstates,],
    2015.0: [w.chile,w.argentina,w.peru,w.paraguay,],
    2011.0: [w.uruguay,w.paraguay,w.peru,w.venezuela,],
    2007.0: [w.brazil,w.argentina,w.mexico,w.uruguay,],
    2004.0: [w.brazil,w.argentina,w.uruguay,w.colombia,],
    2001.0: [w.colombia,w.mexico,w.honduras,w.uruguay,],
    1999.0: [w.brazil,w.uruguay,w.mexico,w.chile,],
    1997.0: [w.brazil,w.bolivia,w.mexico,w.peru,],
    1995.0: [w.uruguay,w.brazil,w.colombia,w.unitedstates,],
    1993.0: [w.argentina,w.mexico,w.colombia,w.ecuador,],
    1991.0: [w.argentina,w.brazil,w.chile,w.colombia,],
    1989.0: [w.brazil,w.uruguay,w.argentina,w.paraguay,],
    1987.0: [w.uruguay,w.chile,w.colombia,w.argentina,],
    1983.0: [w.uruguay,w.brazil,w.peru,w.paraguay,],
    1979.0: [w.paraguay,w.chile,w.brazil,w.peru,],
    1975.0: [w.peru,w.colombia,w.brazil,w.uruguay,],
    1967.0: [w.uruguay,w.argentina,w.chile,w.paraguay,],
    1963.0: [w.bolivia,w.paraguay,w.argentina,w.brazil,],
    1959.5: [w.uruguay,w.argentina,w.brazil,w.ecuador],
    1959.0: [w.uruguay,w.argentina,w.brazil,w.ecuador],
    1957.0: [w.argentina,w.brazil,w.uruguay,w.peru],
    1956.0: [w.uruguay,w.chile,w.argentina,w.brazil,],
    1955.0: [w.argentina,w.chile,w.peru,w.uruguay,],
    1953.0: [w.paraguay,w.brazil,w.uruguay,w.chile,],
    1949.0: [w.brazil,w.paraguay,w.peru,w.bolivia,],
    1947.0: [w.argentina,w.paraguay,w.uruguay,w.chile,],
    1946.0: [w.argentina,w.brazil,w.paraguay,w.uruguay,],
    1945.0: [w.argentina,w.brazil,w.chile,w.uruguay,],
    1942.0: [w.uruguay,w.argentina,w.brazil,w.paraguay,],
    1941.0: [w.argentina,w.uruguay,w.chile,w.peru,],
    1939.0: [w.peru,w.uruguay,w.paraguay,w.chile,],
    1937.0: [w.argentina,w.brazil,w.uruguay,w.paraguay,],
    1935.0: [w.uruguay,w.argentina,w.peru,w.chile,],
    1929.0: [w.argentina,w.paraguay,w.uruguay,w.peru,],
    1927.0: [w.argentina,w.uruguay,w.peru,w.bolivia,],
    1926.0: [w.uruguay,w.argentina,w.chile,w.paraguay,],
    1925.0: [w.argentina,w.brazil,w.paraguay,],
    1924.0: [w.uruguay,w.argentina,w.paraguay,w.chile,],
    1923.0: [w.uruguay,w.argentina,w.paraguay,w.brazil,],
    1922.0: [w.brazil,w.paraguay,w.uruguay,w.argentina,],
    1921.0: [w.argentina,w.brazil,w.uruguay,w.paraguay,],
    1920.0: [w.uruguay,w.argentina,w.brazil,w.chile,],
    1919.0: [w.brazil,w.uruguay,w.argentina,w.chile,],
    1917.0: [w.uruguay,w.argentina,w.brazil,w.chile,],
    1916.0: [w.uruguay,w.argentina,w.brazil,w.chile,],
  },

  leagueName.copaasia : {
    2019.0: [w.qatar,w.japan,w.iran,w.uae,                  w.southkorea,w.vietnam,w.australia,w.china,],
    2015.0: [w.australia,w.southkorea,w.uae,w.iraq,         w.china,w.uzbekistan,w.japan,w.iran,           w.saudiarabia,w.jordan,w.bahrein,w.oman,       w.northKorea,w.qatar,w.kuwait,w.palestine],
    2011.0: [w.japan,w.australia,w.southkorea,w.uzbekistan, w.qatar,w.iraq,w.iran,w.jordan,                w.china,w.bahrein,w.syria,w.northKorea,        w.uae,w.kuwait,w.saudiarabia,w.india,],
    2007.0: [w.iraq,w.saudiarabia,w.southkorea,w.japan,     w.vietnam,w.uzbekistan,w.iran,w.australia,     ],
    2004.0: [w.japan,w.china,w.iran,w.bahrein,],
    2000.0: [w.japan,w.saudiarabia,w.southkorea,w.china,],
    1996.0: [w.saudiarabia,w.uae,w.iran,w.kuwait,],
    1992.0: [w.japan,w.saudiarabia,w.china,w.uae,],
    1988.0: [w.saudiarabia,w.southkorea,w.iran,w.china,],
    1984.0: [w.saudiarabia,w.china,w.kuwait,w.iran,],
    1980.0: [w.kuwait,w.southkorea,w.iran,w.northKorea,],
    1976.0: [w.iran,w.kuwait,w.china,w.iraq,],
    1972.0: [w.iran,w.southkorea,w.thailand,w.cambodia,],
    1968.0: [w.iran,w.myanmar,w.israel,w.taiwan,],
    1964.0: [w.israel,w.india,w.southkorea],
    1960.0: [w.southkorea,w.israel,w.taiwan,w.vietnam,],
    1956.0: [w.southkorea,w.israel,],
  },

  leagueName.copaafrica : {
    2021.0: [w.senegal,w.egypt,w.cameroon,w.burkina],
    2019.0: [w.algeria,w.senegal,w.nigeria,w.tunisia,],
    2017.0: [w.cameroon,w.egypt,w.burkina,w.ghana,],
    2015.0: [w.ivorycoast,w.ghana,w.congoRD,w.guineaEquatorial,],
    2013.0: [w.nigeria,w.burkina,w.mali,w.ghana,],
    2012.0: [w.zambia,w.ivorycoast,w.mali,w.ghana,],
    2010.0: [w.egypt,w.ghana,w.nigeria,w.algeria,],
    2008.0: [w.egypt,w.cameroon,w.ghana,w.ivorycoast,],
    2006.0: [w.egypt,w.ivorycoast,w.nigeria,w.senegal,],
    2004.0: [w.tunisia,w.morocco,w.nigeria,w.mali,],
    2002.0: [w.cameroon,w.senegal,w.nigeria,w.mali,],
    2000.0: [w.cameroon,w.nigeria,w.southafrica,w.tunisia,],
    1998.0: [w.egypt,w.southafrica,w.congoRD,w.burkina,],
    1996.0: [w.southafrica,w.tunisia,w.zambia,w.ghana,],
    1994.0: [w.nigeria,w.zambia,w.ivorycoast,w.mali,],
    1992.0: [w.ivorycoast,w.ghana,w.nigeria,w.cameroon,],
    1990.0: [w.algeria,w.nigeria,w.zambia,w.senegal,],
    1988.0: [w.cameroon,w.nigeria,w.zambia,w.senegal,],
    1986.0: [w.egypt,w.cameroon,w.ivorycoast,w.morocco,],
    1984.0: [w.cameroon,w.nigeria,w.algeria,w.egypt,],
    1982.0: [w.ghana,w.libya,w.zambia,w.algeria,],
    1980.0: [w.nigeria,w.algeria,w.morocco,w.egypt,],
    1978.0: [w.ghana,w.uganda,w.nigeria,w.tunisia,],
    1976.0: [w.morocco,w.guinea,w.nigeria,w.egypt,],
    1974.0: [w.congoRD,w.zambia,w.egypt,w.congo,],
    1972.0: [w.congo,w.mali,w.cameroon,w.congoRD,],
    1970.0: [w.sudan,w.ghana,w.egypt,w.ivorycoast,],
    1968.0: [w.congoRD,w.ghana,w.ivorycoast,w.ethiopia,],
    1965.0: [w.ghana,w.tunisia,w.ivorycoast,w.senegal],
    1963.0: [w.ghana,w.sudan,w.egypt,w.ethiopia,],
    1962.0: [w.ethiopia,w.egypt,w.tunisia,w.uganda,],
    1959.0: [w.egypt,w.sudan,w.ethiopia,],
    1957.0: [w.egypt,w.ethiopia,w.sudan,],
  },

  //COPA OURO
  leagueName.copaconcacaf : {
    2023.0: [w.mexico,w.panama,w.jamaica,w.panama,],
    2021.0: [w.unitedstates,w.mexico,w.canada,w.qatar,],
    2019.0: [w.mexico,w.unitedstates,w.haiti,w.jamaica,],
    2017.0: [w.unitedstates,w.jamaica,w.costarica,w.mexico,],
    2015.0: [w.mexico,w.jamaica,w.panama,w.unitedstates,],
    2013.0: [w.unitedstates,w.panama,w.honduras,w.mexico,],
    2011.0: [w.mexico,w.unitedstates,w.honduras,w.panama,],
    2009.0: [w.mexico,w.unitedstates,w.costarica,w.honduras,],
    2007.0: [w.unitedstates,w.mexico,w.canada],
    2005.0: [w.unitedstates,w.panama,w.colombia,w.honduras,],
    2003.0: [w.mexico,w.brazil,w.unitedstates,w.costarica,],
    2002.0: [w.unitedstates,w.costarica,w.canada,w.southkorea,],
    2000.0: [w.canada,w.colombia,w.peru,w.trinidadtobago,],
    1998.0: [w.mexico,w.unitedstates,w.brazil,w.jamaica,],
    1996.0: [w.mexico,w.brazil,w.unitedstates,w.guatemala,],
    1993.0: [w.mexico,w.unitedstates,w.costarica,w.jamaica,],
    1991.0: [w.unitedstates,w.honduras,w.mexico,w.costarica,],
  },

  //COPA DO MUNDO FEMININA
    leagueName.copamundoFem : {
      2023.0: [w.spain,w.england,w.sweden,w.australia,],
      2019.0: [w.unitedstates,w.netherlands,w.sweden,w.england,],
      2015.0: [w.unitedstates,w.japan,w.england,w.germany,],
      2011.0: [w.japan,w.unitedstates,w.sweden,w.france,],
      2007.0: [w.germany,w.brazil,w.unitedstates,w.norway,],
      2003.0: [w.germany,w.sweden,w.unitedstates,w.canada,],
      1999.0: [w.unitedstates,w.china,w.brazil,w.norway,],
      1995.0: [w.norway,w.germany,w.unitedstates,w.china,],
      1991.0: [w.unitedstates,w.norway,w.sweden,w.germany,],
    },

};