
class ClubName{

  String arsenal = "Arsenal";
  String astonvilla = "Aston Villa";
  String chelsea = "Chelsea";
  String crystalpalace = "Crystal Palace";
  String everton = "Everton";
  String leeds = "Leeds United";
  String leicester = "Leicester";
  String liverpool = "Liverpool";
  String manchestercity = "Manchester City";
  String manchesterunited= "Manchester United";
  String newcastle   = "Newcastle";
  String tottenham   = "Tottenham";
  String southampton = "Southampton";
  String westbromwich= "West Bromwich";
  String westham   = "West Ham";
  String wolves    = "Wolves";

  String birmigham = "Birmingham";
  String blackburn = "Blackburn";
  String bournemouth = "Bournemouth";
  String burnley = "Burnley";
  String brighton = "Brighton";
  String derbycount = "Derby County";
  String fulham = "Fulham";
  String middlesbrough = "Middlesbrough";
  String norwich = "Norwich";
  String nottinghamforest = "Nottingham Forest";
  String qpr = "QPR";
  String reading = "Reading";
  String sheffieldunited = "Sheffield United";
  String stoke = "Stoke City";
  String swansea = "Swansea";
  String watford = "Watford";

  String accrington = "Accrington";
  String barnsley = "Barnsley";
  String barrow = "Barrow";
  String bolton = "Bolton";
  String blackpool = "Blackpool";
  String bradford = "Bradford";
  String brentford = "Brentford";
  String bristol = "Bristol City";
  String bristolrovers = "Bristol Rovers";
  String burton = "Burton Albion";
  String bury = "Bury";
  String cambridge = "Cambridge";
  String cardiffCity = "Cardiff City";
  String carlisle = "Carlisle United";
  String colchester = "Colchester United";
  String cheltenham = "Cheltenham";
  String charlton = "Charlton Athletic";
  String coventry = "Coventry";
  String crewe = "Crewe Alexandra";
  String doncaster = "Doncaster Rovers";
  String dover = "Dover Athletic";
  String exeter = "Exeter City";
  String fleetwood = "Fleetwood";
  String forestgreen = "Forest Green";
  String gillingham = "Gillingham";
  String grimsby = "Grimsby";
  String hartlepool = "Hartlepool United";
  String huddersfield = "Huddersfield Town";
  String hullcity = "Hull City";
  String ipswichTown = "Ipswich Town";
  String leyton = "Leyton Orient";
  String lincoln = "Lincoln City";
  String luton = "Luton Town";
  String mansfield = "Mansfield";
  String millwall = "Millwall";
  String mkdons = "Milton Keynes Dons";
  String morecambe = "Morecambe";
  String newport = "Newport County";
  String notts = "Notts County";
  String northampton = "Northampton Town";
  String oldham = "Oldham";
  String oxford = "Oxford";
  String orient = "Orient";
  String portsmouth = "Portsmouth";
  String peterborough = "Peterborough";
  String portvale = "Port Vale";
  String plymouth = "Plymouth Argyle";
  String prestonNorthEnd = "Preston North End";
  String rochdale = "Rochdale";
  String rotherham = "Rotherham United";
  String salford = "Salford City";
  String scunthorpe = "Scunthorpe United";
  String shrewsbury = "Shrewsbury";
  String sheffieldWednesday = "Sheffield Wednesday";
  String southend = "Southend United";
  String sunderland = "Sunderland";
  String stevenage = "Stevenage";
  String stockport = "Stockport County";
  String swindon = "Swindon";
  String tranmere = "Tranmere Rovers";
  String walsall = "Walsall";
  String wigan = "Wigan Athletic";
  String wimbledon = "Wimbledon";
  String wycombe = "Wycombe";
  String wrexham = "Wrexham";
  String yeovil = "Yeovil Town";
  String york = "York City";

  //ITALIA
  String atalanta  = "Atalanta";
  String bologna   = "Bologna";
  String cagliari  = "Cagliari";
  String fiorentina= "Fiorentina";
  String genoa     = "Genoa";
  String inter     = "Inter";
  String juventus  = "Juventus";
  String milan     = "Milan";
  String lazio     = "Lazio";
  String napoli    = "Napoli";
  String parma     = "Parma";
  String roma      = "Roma";
  String sampdoria = "Sampdoria";
  String sassuolo  = "Sassuolo";
  String torino    = "Torino";
  String udinese   = "Udinese";

  String alessandria = "Alessandria";
  String ancona = "Ancona";
  String ascoli = "Ascoli";
  String avellino = "Avellino";
  String bari = "Bari";
  String benevento = "Benevento";
  String brescia = "Brescia";
  String carpi = "Carpi";
  String catania = "Catania";
  String catanzaro = "Catanzaro";
  String cittadella = "Cittadella";
  String cremonese = "Cremonese";
  String cesena = "Cesena";
  String chievo  = "Chievo";
  String como = "Como";
  String cosenza = "Cosenza";
  String crotone = "Crotone";
  String empoli  = "Empoli";
  String foggia  = "Foggia";
  String frosinone = "Frosinone";
  String grosseto = "Grosseto";
  String hellasVerona = "Hellas Verona";
  String lecce = "Lecce";
  String lecco = "Lecco";
  String livorno = "Livorno";
  String mantova = "Mantova";
  String messina = "Messina";
  String modena = "Modena";
  String monza = "Monza";
  String novara = "Novara";
  String pisa    = "Pisa";
  String padova  = "Padova";
  String palermo = "Palermo";
  String perugia = "Perugia";
  String pescara = "Pescara";
  String piacenza = "Piacenza";
  String pistoiese = "Pistoiese";
  String pordenone = "Pordenone";
  String provercelli = "Pro Vercelli";
  String reggina = "Reggina";
  String reggiana = "Reggiana";
  String salernitana  = "Salernitana";
  String siena  = "Siena";
  String spal = "SPAL";
  String spezia  = "Spezia";
  String sudtirol  = "Süd Tirol";
  String ternana  = "Ternana";
  String treviso  = "Treviso";
  String triestina  = "Triestina";
  String varese = "Varese";
  String venezia = "Venezia FC";
  String vicenza = "Vicenza";
  String virtusentella = "Virtus Entella";

  //ESPANHA
  String athleticbilbao = "Athletic Bilbao";
  String atleticomadrid = "Atlético Madrid";
  String barcelona = "Barcelona";
  String celtavigo = "Celta de Vigo";
  String espanyol  = "Espanyol";
  String getafe    = "Getafe";
  String lacoruna  = "La Coruna";
  String levante   = "Levante";
  String osasuna   = "Osasuna";
  String realbetis = "Real Betis";
  String realmadrid = "Real Madrid";
  String realsociedad = "Real Sociedad";
  String sevilla    = "Sevilla";
  String valencia   = "Valencia";
  String valladolid = "Valladolid";
  String villareal  = "Villarreal";

  String alaves = "Deportivo Alavés";
  String albacete = "Albacete";
  String alcorcon = "Alcorcon";
  String algeciras = "Algeciras";
  String alcoyano = "Alcoyano";
  String alicante = "Alicante";
  String almeria = "Almería";
  String amorebieta = "Amorebieta";
  String andorra = "FC Andorra";
  String atleticomadridB = "Atlético Madrid B";
  String athleticbilbaoB = "Bilbao Athletic";
  String aviles = "Real Avilés";
  String badajoz = "Badajoz";
  String barakaldo = "Barakaldo";
  String barcelonaB = "Barcelona B";
  String burgos = "Burgos";
  String castellon = "Castellón";
  String ciudadmurcia = "Ciudad Murcia";
  String culturalleonesa = "Cultural Leonesa";
  String cadiz = "Cádiz";
  String cartagena = "Cartagena";
  String ceuta = "Ceuta";
  String compostela = "Compostela";
  String cordoba = "Córdoba";
  String eibar = "Eibar";
  String elche = "Elche";
  String extremadura = "Extremadura";
  String ferrol = "Ferrol";
  String figueres = "Figueres";
  String fuenlabrada = "Fuenlabrada";
  String girona = "Girona FC";
  String granada = "Granada";
  String tarragona = "Gimnàstic de Tarragona";
  String hercules = "Hércules";
  String huelva = "Recreativo de Huelva";
  String huesca = "Huesca";
  String ibiza = "Ibiza";
  String jaen = "Jaen";
  String lasPalmas = "Las Palmas";
  String lleida = "Lleida Esportiu";
  String leganes = "Leganés";
  String linares = "Linares";
  String llagostera = "Llagostera";
  String logrones = "Logroñés";
  String lorca1 = "Lorca";
  String lugo = "Lugo";
  String malaga = "Málaga";
  String mallorca = "Mallorca";
  String marbella = "Marbella";
  String mirandes = "Mirandes";
  String merida = "Mérida";
  String mestalla = "Mestalla";
  String majadahonda = "Rayo Majadahonda";
  String murcia = "Real Murcia";
  String numancia = "Numancia";
  String orihuela = "Orihuela";
  String realOviedo = "Real Oviedo";
  String palamos = "Palamós";
  String palencia = "Palencia";
  String poli = "Poli Ejido";
  String pontevedra = "Pontevedra";
  String ponferradina = "Ponferradina";
  String puertollano = "Puertollano"; //antigo calvo sotelo
  String racingSantander = "Racing Santander";
  String rayoVallecano = "Rayo Vallecano";
  String realmadridB = "Real Madrid Castilla";
  String realsociedadB = "Real Sociedad B";
  String rayomajadahonda = "Rayo Majadahonda";
  String realunion = "Real Unión";
  String reus = "Reus";
  String salamanca = "Salamanca";
  String sestao = "Sestao";
  String sabadell = "Sabadell";
  String sanandres = "San Andrés";
  String sevillaAtl = "Sevilla Atletico";
  String sportingGijon = "Sporting de Gijón";
  String tenerife = "Tenerife";
  String tarrassa = "Tarrassa";
  String unionistas = "Unionistas";
  String toledo = "Toledo";
  String villarrealB = "Villarreal B";
  String xerez = "Xerez";
  String zaragoza = "Real Zaragoza";

  //ALEMANHA
  String moenchengladbach = "Moenchengladbach";
  String dortmund = "Borussia Dortmund";
  String bayernmunique = "Bayern Munique";
  String leverkusen = "Bayer Leverkusen";
  String colonia = "Colonia";
  String eintrachtfrankfurt = "Eintracht Frankfurt";
  String freiburg = "Freiburg";
  String hamburgo = "Hamburgo";
  String augsburg = "Augsburg";
  String herthaberlim = "Hertha Berlim";
  String hoffenheim = "Hoffenheim";
  String rbleipzig = "RB Leipzig";
  String schalke04 = "Schalke-04";
  String stuttgart = "Stuttgart";
  String werderbremen = "Werder Bremen";
  String wolfsburg = "Wolfsburg";

  String aachen = "Aachen";
  String arminiaBiefeld = "Arminia Bielefeld";
  String berliner = "BFC Dynamo";
  String bochum = "Bochum 1848";
  String carlzeissjena = "Carl Zeiss Jena";
  String darmstadt = "Darmstadt";
  String duisburg = "Duisburg";
  String dynamoDresden = "Dynamo Dresden";
  String erzgebirgeaue = "Erzgebirge Aue";
  String energieCottbus = "Energie Cottbus";
  String eintrachtBraunschweiger = "Eintracht Braunschweiger";
  String fortunakoln = "Fortuna Koln";
  String fortunaDusseldorf = "Fortuna Dusseldorf";
  String greutherFurth = "Greuther Fürth";
  String hansaRostock = "Hansa Rostock";
  String heidenheim = "Heidenheim";
  String ingolstadt = "Ingolstadt";
  String hannover96 = "Hannover 96";
  String homburg = "Homburg";
  String holsteinkiel = "Holstein Kiel";
  String jahnregensburg = "SSV Jahn Regensburg";
  String kaiserslautern = "Kaiserslautern";
  String kickersOffenbach = "Kickers Offenbach";
  String karlsruher = "Karlsruher";
  String lokLeipzig = "Lokomotiv Leipzig";
  String mainz05 = "Mainz 05";
  String meidericher = "Meidericher";
  String magdeburg = "Magdeburg";
  String munique1860 = "Munique 1860";
  String neunkirchen = "Neunkirchen";
  String nurnberg = "Nurnberg";
  String oberhausen = "Oberhausen";
  String paderborn = "Paderborn";
  String rotWeissEssen = "Rot-Weiss Essen";
  String sandhausen = "Sandhausen";
  String saarbrucken = "Saarbrucken";
  String stPauli = "St. Pauli";
  String stutKickers = "Stuttgarter Kickers";
  String tasmania = "Tasmania 1900 Berlin";
  String uerdigen = "Uerdigen";
  String unionBerlin = "Union Berlin";
  String ulm = "Ulm";
  String unterhaching = "Unterhaching";
  String vorwarts = "Vorwärts Berlin";
  String waldhofMannheim = "Waldhof Mannheim";
  String wattenscheid = "Wattenscheid";
  String wuppertaler = "Wuppertaler";
  //FRANÇA
  String bordeaux = "Bordeaux";
  String lille = "Lille";
  String lyon = "Lyon";
  String monaco = "Monaco";
  String montpellier = "Montpellier";
  String nantes = "Nantes";
  String nice = "Nice";
  String om= "Olympique Marselha";
  String psg = "PSG";
  String reims = "Reims";
  String rennes = "Rennes";
  String saintetienne= "Saint-Etienne";
  String metz = "Metz";
  String nimes = "Nimes";
  String racingParis = "Racing Club Paris";
  String lens = "Lens";
  String strasbourg = "Strasbourg";
  String parisFC = "Paris FC";

  String ajaccio = "Ajaccio";
  String amiens = "Amiens";
  String angers = "Angers";
  String angouleme = "Angoulême";
  String annecy = "Annecy FC";
  String auxerre = "Auxerre";
  String bastia = "Bastia";
  String boulogne = "Boulogne";
  String brest = "Stade Brestois";
  String calais = "Calais";
  String cannes = "Cannes";
  String chamois = "Chamois Niortais";
  String chateauroux = "Châteauroux";
  String caen = "Caen";
  String clermont = "Clermont";
  String dijon = "Dijon";
  String evian = "Evian";
  String gueugnon = "Gueugnon";
  String guingamp = "Guingamp";
  String grenoble = "Grenoble";
  String lavallois = "Lavallois";
  String lehavre = "Le Havre";
  String lemans = "Le Mans";
  String limoges = "Limoges FC";
  String lorient = "FC Lorient";
  String martigues = "Martigues";
  String nancy = "Nancy";
  String orleans = "Orléans";
  String pau = "Pau FC";
  String quevilly = "Quevilly-Rouen";
  String redstar = "Red Star";
  String rodez = "Rodez Aveyron";
  String rouen = "Rouen";
  String sedan = "Sedan";
  String sochaux = "Sochaux";
  String stadeFrancais = "Stade Français";
  String tours = "Tours";
  String toulon = "Toulon";
  String troyes = "Troyes";
  String toulouse = "Toulouse";
  String valenciennes = "Valenciennes";
  String vendee = "Vendée Les Herbiers";
  String villefranche = "Villefranche";
  //PORTUGAL
  String benfica = "Benfica";
  String porto = "Porto";
  String sporting = "Sporting";
  String braga = "Braga";
  String benficab = "Benfica";
  String portob = "Porto";
  String alverca = "Alverca";
  String agueda = "Águeda";
  String amora = "Amora FC";
  String aves = "Desportivo das Aves";
  String arouca = "Arouca";
  String atleticoPT = "Atlético de Portugal";
  String barreirense = "Barreirense";
  String beiramar = "Beira-Mar";
  String belenenses = "Belenenses";
  String boavista = "Boavista";
  String campomaiorense = "Campomaiorense";
  String casapia = "Casa Pia";
  String coimbra = "Coimbra";
  String covilha = "Covilhã";
  String chaves = "Chaves";
  String cuf = "Fabril Barreiro";
  String elvas = "O Elvas";
  String evora = "Lusitano Évora";
  String estoril = "Estoril";
  String espinho = "Espinho";
  String estrelaamadora = "Estrela Amadora";
  String fafe = "Fafe";
  String famalicao = "Famalicão";
  String farense = "Farense";
  String feirense = "Feirense";
  String felgueiras = "Felgueiras";
  String gilVicente = "Gil Vicente";
  String leca = "Leça FC";
  String leixoes = "Leixões";
  String mafra = "CD Mafra";
  String maritimo = "Marítimo";
  String moreirense = "Moreirense";
  String montijo = "Montijo";
  String naval = "Naval";
  String nacionalMadeira = "Nacional Madeira";
  String pacosDeFerreira = "Paços de Ferreira";
  String penafiel = "Penafiel";
  String portimonense = "Portimonense";
  String olhanense = "Olhanense";
  String oriental = "Oriental";
  String rioAve = "Rio Ave";
  String riopele = "Riopele";
  String salgueiros = "Salgueiros";
  String santaClara = "Santa Clara";
  String seixal = "Seixal FC";
  String tirsense = "Tirsense";
  String torreense = "Torreense";
  String tondela = "Tondela";
  String trofense = "Trofense";
  String uniaocoimbra= "União Coimbra";
  String leiria = "União de Leiria";
  String uniaomadeira= "União da Madeira";
  String sanjoanense = "Sanjoanense";
  String tomar= "União Tomar";
  String varzim = "Varzim";
  String vilafranquense = "Vilafranquense";
  String vizela = "Vizela";
  String viseu = "Viseu";
  String vitoriaguimaraes = "Vitória Guimarães";
  String setubal = "Vitória de Setúbal";
  //HOLANDA
  String ajax = "Ajax";
  String feyenoord = "Feyenoord";
  String psv = "PSV";
  String amsterdam = "FC Amsterdam"; //1972-1982
  String az = "AZ Alkmaar";
  String cambuur = "Cambuur";
  String denhaag = "ADO Den Haag";
  String dos = "VV DOS";
  String emmen = "FC Emmen";
  String enschede = "Enschede";
  String excelsior = "Excelsior";
  String fortunasittard = "Fortuna Sittard";
  String goaheadeagles = "Go Ahead Eagles";
  String groningen = "Groningen";
  String haarlem = "HFC Haarlem";
  String heracles = "Heracles";
  String heerenveen = "Heerenveen";
  String mvv = "MVV Maastricht";
  String nacbreda = "NAC Breda";
  String necnijmegen = "NEC Nijmegen";
  String rapidjc = "Rapid JC";
  String roda = "Roda JC";
  String spartarotterdam = "Sparta Rotterdam";
  String telstar = "Telstar";
  String twente = "Twente";
  String vitesse = "Vitesse";
  String volendam = "Volendam";
  String vvv = "VVV Venlo";
  String utrecht = "Utrecht";
  String waalwijk = "RJK Waalwijk";
  String willem = "Willem II";
  String zwolle = "PEC Zwolle";
  String dws = "AFC DWS";

  //////////////////////////////////////////////////////////////////////////////
  //BÉLGICA
  String anderlecht = "Anderlecht";
  String beringen = "Beringen";
  String berchem = "Berchem Sport";
  String beerschot = "Beerschot";
  String brugge = "Brugge";
  String genk = "Genk";
  String gent = "Gent";
  String beveren = "Beveren";
  String charleroi = "Charleroi";
  String cerclebrugge = "Cercle Brugge";
  String daring = "	Daring Club Bruxelles";
  String diest = "Diest";
  String eendrachtAalst = "Eendracht Aalst";
  String kaseupen = "KAS Eupen";
  String kortrijk = "KV Kortrijk";
  String leuven = "Leuven";
  String liegeois = "Royal FC de Liège";
  String lierse = "Lierse";
  String lokeren = "Lokeren";
  String mechelen = "Mechelen";
  String molenbeek = "Molenbeek";
  String mouscron = "Mouscron";
  String oostende = "Oostende";
  String royalAntwerp = "Royal Antwerp";
  String saintgilloise = "Union Saint-Gilloise";
  String seraing = "RFC Seraing"; //EXTINTO
  String standardliege = "Standard Liege";
  String sttruidense = "St. Truidense";
  String tilleur = "Tilleur-Saint-Nicolas";
  String tongeren = "Tongeren";
  String waregemKSV = "KSV waregem"; //EXTINTO 1925-2001
  String waterschei = "Waterschei";
  String westerlo = "Westerlo";
  String winterslag = "Winterslag";
  String zulteWaregem = "Zulte Waregem";

  //ESCÓCIA
  String celtic = "Celtic";
  String rangers = "Glasgow Rangers";
  String aberdeen = "Aberdeen";
  String clyde = "Clyde";
  String dundee = "Dundee United";
  String dundeefc = "Dundee FC";
  String dunfermline = "Dunfermline Athletic";
  String falkirk = "Falkirk";
  String hamilton = "Hamilton";
  String hearts = "Hearts";
  String hibernian = "Hibernian";
  String inverness = "Inverness";
  String kilmarnock = "Kilmarnock";
  String livingston = "Livingston";
  String motherwell = "Motherwell";
  String partick = "Partick Thistle";
  String rossCounty = "Ross County";
  String stjohnstone = "St. Johnstone";
  String stmirren = "St. Mirren";
  String thirdLanark = "Third Lanark"; //EXTINTO 1872-1967

  //NORTHERN IRELAND
  String coleraine = "Coleraine";
  String linfield = "Linfield";
  String glentoran = "Glentoran";
  String crusaders = "Crusaders";
  String cliftonville = "Cliftonville";
  //WALES
  String balatown = "Bala Town";
  String newsaints = "The New Saints";
  String newtown = "Newtown Association";
  String connahs = "Connah's Quay Nomads";
  //IRLANDA
  String bohemian = "Bohemian";
  String cork = "Cork City";
  String derry = "Derry City";
  String dundalk = "Dundalk";
  String longford = "Longford Town";
  String stpatricks = "St. Patricks";
  String sligo = "Sligo Rovers";
  String shamrock = "Shamrock Rovers";
  String waterford = "Waterford";


  //NORDICOS
  //NORUEGA
  String rosenborg = "Rosenborg";
  String molde = "Molde";
  String aalesund = "Aalesund";
  String brann = "Brann";
  String bryne = "Bryne";
  String fredrikstad = "Fredrikstad";
  String glimt = "Bodø/Glimt";
  String haugesund = "Haugesund";
  String kristiansud = "Kristiansud";
  String kongsvinger = "Kongsvinger";
  String lillestrom = "Lillestrøm";
  String lyn = "LYN";
  String odd = "Odds BK";
  String mjondalen = "Mjondalen";
  String moss = "Moss";
  String sanderfjord = "Sanderfjord";
  String sarpsborg = "Sarpsborg 08";
  String skeid = "Skeid";
  String sogndal = "Sogndal";
  String stabaek = "Stabæk";
  String start = "Start";
  String steinkjer = "Steinkjer";
  String stromsgodset = "Strømsgodset";
  String tonsberg = "Eik-Tønsberg";
  String tromso = "Tromsø IL";
  String valerenga = "Valerenga";
  String viking = "Viking";
  //SUÉCIA
  String aik = "AIK";
  String atvidabergs = "Atvidabergs";
  String djurgarden = "Djurgarden";
  String elfsborg = "Elfsborg";
  String hammarby = "Hammarby";
  String halmstads = "Halmstads";
  String hacken = "Häcken";
  String helsingborg = "Helsingborg";
  String kalmar = "Kalmar";
  String ifkgoteborg = "IFK Goteborg";
  String malmo = "Malmo";
  String mjallby = "Mjällby";
  String norrkoping = "Norrköping";
  String orebro = "Örebro SK";
  String orgryte = "Örgryte IS";
  String osters = "Östers IF";
  String sirius = "Sirius";
  String sundsvall = "Sundsvall";
  String varberg = "Varberg";
  //DINAMARCA
  String copenhague = "Copenhague";
  String midtjylland = "Midtjylland";
  String aalborg = "Aalborg";
  String aarhus = "Aarhus";
  String brondby = "Brondby";
  String esbjerg = "Esbjerg";
  String frem = "Frem";
  String herfolge = "Herfølge";
  String holbaek = "Holbaek";
  String horsens = "Horsens";
  String hobro = "Hobro";
  String hvidovre = "Hvidovre";
  String ikast = "Ikast FS";
  String koge = "Koge";
  String lyngby = "Lyngby";
  String naestved = "Næstved";
  String nordsjaelland = "Nordsjaelland";
  String obodense = "OB Odense";
  String randers = "Randers";
  String silkeborg = "Silkeborg";
  String sonderjysk = "SønderjyskE";
  String vestjaelland = "Vestsjælland";
  String vejle = "Vejle";
  String viborg = "Viborg";
  String ab = "AB";
  String b1909 = "B1909";
  String b1913 = "B1913";
  String kb = "Kjøbenhavns Boldklub"; //virou o copenhague
  String b1903 = "B1903"; //virou o copenhague
  //FINLANDIA
  String helsinki = "Helsinki";
  String haka = "Haka";
  String ilves = "Ilves";
  String kups = "KuPS";
  String kuusysi = "Kuusysi";
  String lahti = "Reipas Lahti";
  String turku = "Inter Turku";
  String sjk = "SJK";
  //ISLANDIA
  String akraness = "Akraness";
  String breidablik = "Breiðablik Kópavogur";
  String stjarnan = "Stjarnan Garðabaer";
  String valur = "Valur";
  String vikingur = "Vikingur Reykjavik";
  String hafnarfjardar = "Hafnarfjarðar";
  String reykjavik = "KR Reykjavik";
  //ILHAS FAROE
  String b36 = "B36 Tórshavn";
  String hb = "Havnar Bóltfelag";
  String klaksvik = "KÍ Klaksvík";
  String vikingurFaroe = "Víkingur Gøta";

  //AUSTRIA/SUIÇA/POLONIA
  String admira = "Admira";
  String altach = "Altach";
  String austriaKlagenfurt = "Austria Klagenfurt";
  String austriaLustenau = "Austria Lustenau";
  String austria = "Austria Viena";
  String bregenz = "Bregenz";
  String firstViena = "First Viena";
  String grazer = "Grazer AK";
  String grodig = "Grodig";
  String hartberg = "Hartberg";
  String innsbruck = "Innsbruck";
  String kapfenberger = "Kapfenberger";
  String karnten = "Karnten";
  String laskLinz = "LASK Linz";
  String mattersburg = "Mattersburg";
  String pasching = "Pasching";
  String rbsalzburg = "RB Salzburg";
  String rapidviena = "Rapid Viena";
  String ried = "SV Ried";
  String sturmGraz = "Sturm Graz";
  String stpolten = "St. Polten";
  String tirol = "Swarovski Tirol";
  String wiener = "Wiener Sportclub";
  String wolfsberger = "Wolfsberger AC";
  String wackerInnsbruck = "Wacker Innsbruck"; //1915-1999
  String stahlLinz = "Stahl Linz"; //1946-1997
  //SUIÇA
  String aarau = "Aarau";
  String basel = "Basel";
  String baden = "Baden";
  String bellinzona = "Bellinzona";
  String bielBienne = "Biel-Bienne";
  String bulle = "Bulle";
  String chauxdefonds = "Chaux-de-Fonds";
  String chenois = "Chênois";
  String chiasso = "Chiasso";
  String delemont = "Delémont";
  String fribourg = "Fribourg";
  String grasshoppers = "Grasshoppers";
  String grenchen = "Grenchen";
  String kriens = "Kriens";
  String lausanne = "Lausanne";
  String lugano = "Lugano";
  String luzern = "Luzern";
  String neuchatel = "Neuchâtel Xamax";
  String nordsternBasel = "Nordstern Basel";
  String schaffhausen = "Schaffhausen";
  String servette = "Servette";
  String sion = "Sion";
  String stgallen = "St. Gallen";
  String thun = "FC Thun";
  String vevey = "Vevey";
  String wettingen = "Wettingen";
  String wil = "Wil";
  String winterthur = "Winterthur";
  String yverdon = "Yverdon-Sport";
  String youngBoys = "Young Boys";
  String youngFellows = "Young Fellows Zurich";
  String zug = "Zug";
  String zurich = "Zurich";
  //POLONIA
  String amica = "Amica Wronki";
  String cracovia = "Cracovia";
  String dyskobolia = "Dyskobolia Grodzisk"; //EXTINTO 1922-2015
  String gornik = "Górnik Zabrze";
  String gksBelchatow = "GKS Bełchatów";
  String hutnik = "Hutnik Kraków";
  String katowice = "GKS Katowice";
  String gwardia = "Gwardia";
  String jagiellonia = "Jagiellonia";
  String korona = "Korona Kielce";
  String legiaWarszawa = "Legia Warszawa";
  String lechPoznan = "Lech Poznan";
  String lksLodz = "ŁKS Łódź";
  String lechiagdansk = "Lechia Gdańsk";
  String naprzod = "Naprzód Janów";
  String odraWodzislaw = "Odra Wodzisław Śląski";
  String olimpiaPoznan = "Olimpia Poznań";
  String piastGliwice = "Piast Gliwice";
  String podhale = "Podhale Nowy Targ";
  String poloniaWarsaw = "Polonia Warsaw";
  String poloniabytom = "Polonia Bytom";
  String pogon = "Pogon Szczecin";
  String radomiak = "Radomiak Radom";
  String rakow = "Raków Częstochowa";
  String ruchchorzow = "Ruch Chorzów";
  String stalmielec = "Stal Mielec";
  String slaskwrocklaw = "Śląsk Wrocław";
  String stoczniowiec = "Stoczniowiec Gdansk";
  String szombierki = "Szombierki Bytom";
  String wislaPlock = "Wisla Plock";
  String wislaKrakow = "Wisla Kraków";
  String wartaPoznan = "Warta Poznan";
  String widzew = "Widzew Lodz";
  String zaglebieLubin = "Zagłębie Lubin";
  String zawiszaBydgoszcz = "Zawisza Bydgoszcz";
  //TURQUIA
  String galatasaray= "Galatasaray";
  String fenerbahce = "Fenerbahce";
  String instanbul = "Instanbul Basaksehir";
  String adanaspor = "Adanaspor";
  String akhisar = "Akhisar Belediyespor";
  String ankaragucu = "Ankaragücü";
  String adanaDemispor = "Adana Demispor";
  String ankaraspor = "Ankaraspor Kulübü";
  String antalyaspor = "Antalyaspor";
  String alanyaspor = "Alanyaspor";
  String altay = "Altay Kulübü";
  String aydinspor = "Aydınspor";
  String besiktas = "Besiktas";
  String beykozpor = "Beykozpor 1908";
  String boluspor = "Boluspor";
  String bursaspor = "Bursaspor";
  String denizlispor = "Denizlispor";
  String eskisehirspor = "Eskisehirspor";
  String hatayspor = "Hatayspor";
  String gaziantepspor = "Gaziantepspor";
  String gaziantep = "Gaziantep";
  String genclerbirligi = "Gençlerbirliği";
  String goztepe = "Göztepe";
  String istanbulspor = "İstanbulspor";
  String karabukspor = "Karabükspor";
  String karagumruk = "Karagümrük";
  String kayserispor = "Kayserispor";
  String karsiyaka = "Karşıyaka";
  String kasimpasa = "Kasımpaşa";
  String kocaelispor = "Kocaelispor";
  String konyaspor = "Konyaspor";
  String kirikkalespor = "Kirikkalespor";
  String malatyaspor = "Malatyaspor";
  String mersin = "Mersin İdmanyurdu";
  String osmanlispor = "Osmanlispor";
  String rizespor = "Rizespor";
  String sakaryaspor = "	Sakaryaspor";
  String samsunspor = "Samsunspor";
  String sariyer = "Sarıyer";
  String sivasspor = "Sivasspor";
  String trabzonspor = "Trabzonspor";
  String zonguldakspor = "	Zonguldakspor";
  //GRECIA
  String olympiacos = "Olympiacos";
  String paok = "PAOK";
  String aek = "AEK";
  String panathinaikos = "Panathinaikos";
  String aris = "ARIS Tessalônica";
  String atromitos = "Atromitos";
  String apollonKalamarias = "Apollon Kalamarias";
  String apollonAthens = "Apollon Smyrnis";
  String asteras = "Asteras Tripolis";
  String chalkidona = "Chalkidona";
  String egaleo = "Egaleo";
  String ergotelis = "Ergotelis Crete";
  String ionikos = "Ionikos Nikeas";
  String kalloni = "AEL Kalloni";
  String kavala = "Kavala";
  String kallithea = "Kallithea";
  String kerkyra = "Kerkyra";
  String lamia = "PAS Lamia 1964";
  String larissa = "AEL Larissa";
  String levadiakos = "Levadiakos";
  String ofi = "OFI Crete";
  String panionios = "Panionios";
  String platanias = "Platanias";
  String iraklis = "Iraklis";
  String panachaiki = "Panachaiki";
  String panthrakikos = "Panthrakikos";
  String pasGiannina = "PAS Giannina";
  String panetolikos = "Panetolikos";
  String volosOlympiacos = "Olympiacos Volos";
  String volos = "Volos NFC";
  String xanthi = "Xanthi";
  //CHIPRE
  String apoel = "APOEL";
  String apollon = "Apollon Limassol";
  String omonia = "Omonia";
  String anorthosis = "Anorthosis";
  String aeklarnaca = "AEK Larnaca";
  //ISRAEL
  String ashdod = "Ashdod SC";
  String bneiSakhnin = "Bnei Sakhnin";
  String bneiYehuda = "Bnei Yehuda";
  String beitarTelAviv = "Beitar Tel-Avi";
  String beitarJerusalem = "Beitar Jerusalem";
  String hapoelTelAviv = "Hapoel Tel Aviv";
  String hapoelBerSheva = "Hapoel Be'er Sheva";
  String hapoelHaifa = "Hapoel Haifa";
  String hapoelHadera = "Hapoel Hadera";
  String hapoelKfar = "Hapoel Kfar";
  String hapoelPetah = "Hapoel Petah";
  String hapoelRaanana = "Hapoel Ra'anana";
  String hapoelTiberias = "Hapoel Tiberias";
  String kiryatShmona = "Kiryat Shmona";
  String maccabiJaffa = "Maccabi Jaffa";
  String maccabiHaifa = "Maccabi Haifa";
  String maccabiNetanya = "Maccabi Netanya";
  String maccabiPetach = "Maccabi Petach";
  String maccabiTelAviv = "Maccabi Tel Aviv";
  String ramatGan = "Ramat Gan";
  //RUSSIA
  String zenit = "Zenit";
  String cska = "CSKA";
  String dinamoMoscou= "Dinamo Moscou";
  String krasnodar = "Krasnodar";
  String lokomotivMoscou= "Locomotiv Moscou";
  String rubinKazan= "Rubin Kazan";
  String rostov = "Rostov";
  String spartakmoscou= "Spartak Moscou";
  String sochi = "Sochi";

  String admiralteet = "Admiralteet Leningrad";
  String akhmatGrozny = "Akhmat Grozny";
  String alania = "Alania Vladikavkaz";
  String amkar = "Amkar";
  String anzhi = "Anzhi";
  String tula = "Arsenal Tula";
  String baltika = "Baltika Kaliningrad";
  String chernomorets = "Chernomorets Novorossiysk";
  String dinamoStPetersburg = "Dinamo St Petersburg";
  String fakel = "Fakel Voronezh";
  String kamaz = "KAMAZ Chelny";
  String kamyshin = "Tekstilshchik Kamyshin"; //1958-2008
  String khimki = "FK Khimki";
  String krylyaSovetov = "Krylya Sovetov";
  String kubanKrasnodar = "Kuban Krasnodar";
  String moskva = "FK Moskva"; //1997-2010
  String mordovia = "Mordovia Saransk";
  String nizhnyNovgorod = "Nizhny Novgorod";
  String okean = "Okean Nakhodka";//1986-2015
  String orenburg = "Orenburg";
  String presnyaMoscow = "Presnya Moscow"; //1978-2006
  String ufa = "Ufa";
  String ural = "Ural";
  String rotor= "Rotor Volgograd";
  String tambov = "Tambov";
  String tomtomsk = "Tom Tomsk";
  String torpedo = "Torpedo";
  String torpedoZil = "Torpedo-ZIL Moscow"; //1997-2004
  String tosno = "Tosno"; //2013-2018
  String tyumen = "Tyumen";
  String uralan = "Uralan Elista";
  String saturn = "Saturn";
  String shinnikYaroslavl = "Shinnik Yaroslavl";
  String ska = "SKA";
  String skaRostov = "SKA Rostov";
  String sokol = "Sokol Saratov";
  String spartakNalchik = "Spartak Nalchik";
  String stavropol = "Dynamo Stavropol";
  String vladivostok = "Luch-Energiya Vladivostok"; //1958-2020
  String volga = "Volga Nizhny Novgorod"; //Extinto 2016
  String yenisey = "Yenisey Krasnoyarsk";
  String zhemchuzhinaSochi = "Zhemchuzhina Sochi";//Extinto 2012
  //UKRAINE
  String shaktardonetsk = "Shaktar Donetsk";
  String dinamokiev = "Dinamo Kiev";
  String odesa = "Chornomorets Odesa";
  String desna = "Desna Chernihiv";
  String dnipro = "Dnipro";
  String dnipro1 = "Dnipro-1";
  String karpatyLviv = "Karpaty Lviv";
  String kolosKovalivka = "Kolos Kovalivka";
  String kryvbasKryvyi = "Kryvbas Kryvyi Rih";
  String metalist = "Metalist";
  String metalurh = "Metalurh Zaporizhzhia";
  String lviv = "Lviv";
  String oleksandriya = "Oleksandriya";
  String rukhLviv = "Rukh Lviv";
  String tavria = "Tavria Simferopol";
  String scOdesa = "SC Odesa";
  String veresRivne = "Veres Rivne";
  String vorskla = "Vorskla";
  String zorya = "Zorya";
  //EX-URSS
  //MOLDOVA
  String sheriffTiraspol = "Sheriff Tiraspol";
  String zimbru = "Zimbru Chișinău";//MOLDOVA
  String milsami = "Milsami Orhei";//MOLDOVA
  //BELARUS
  String bate = "BATE";
  String dinamoBrest = "Dinamo Brest";//BELARUS
  String dinamoMinsk = "Dinamo Minsk";//BELARUS
  String gomel = "Gomel";
  String soligorsk = "Shakhtyor Soligorsk";//BELARUS
  //AZERBAIJAN
  String baku = "Neftchi Baku";
  String kapaz = "Kapaz PFK";//AZERBAIJAN
  String qabala = "Qabala";//AZERBAIJAN
  String qarabag = "Qarabag";//AZERBAIJAN
  String zira = "Zira";//AZERBAIJAN
  //KAZAKHSTAN
  String aktobe = "Aktobe";
  String akzhayik = "Akzhayik";
  String aksu = "Aksu";
  String almaata = "Alma-Ata"; //VIROU ASTANA FC - 2008
  String astana = "Astana";//KAZAKHSTAN
  String atyrau = "Atyrau";//KAZAKHSTAN
  String bolat = "Bolat";
  String caspiy = "Caspiy";
  String dostyk = "Dostyk";
  String ekibastuzets = "Ekibastuzets";
  String esilBogatyr = "Esil Bogatyr";
  String kairat = "Kairat";//KAZAKHSTAN
  String kaisar = "Kaisar";
  String kyzylzhar = "Kyzylzhar";
  String gornyak = "Gornyak";
  String irtysh = "Irtysh";//KAZAKHSTAN
  String megasport = "Megasport";  //VIROU ASTANA FC - 2008
  String ordabasy = "Ordabasy Shymkent";//KAZAKHSTAN
  String okzhetpes = "Okzhetpes";//KAZAKHSTAN
  String semey = "Spartak Semey";//KAZAKHSTAN
  String shakhter = "Shakhter Karagandy";//KAZAKHSTAN
  String sunkar = "Sunkar";//KAZAKHSTAN
  String taraz = "Taraz";//KAZAKHSTAN
  String tobol = "Tobol Kostanay";//KAZAKHSTAN
  String turan = "Turan";//KAZAKHSTAN
  String vostok = "Vostok";//KAZAKHSTAN
  String zhenis = "Zhenis";//KAZAKHSTAN
  String zhetysu = "Zhetysu";//KAZAKHSTAN
  //GEORGIA
  String tbilisi = "Dinamo Tbilisi";
  String batumi = "Dinamo Batumi";//GEORGIA
  String dila = "FC Dila";//GEORGIA
  String guria = "Guria Lanchkhuti";//GEORGIA
  String kutaisi = "Torpedo Kutaisi";//GEORGIA
  String saburtalo = "Saburtalo Tbilisi";
  //ARMENIA
  String alashkent = "FC Alashkent";
  String araratArmenia = "Ararat Armenia";//ARMENIA
  String araratYerevan = "Ararat Yerevan";//ARMENIA
  String pyunikyerevan = "Pyunik Yerevan";//ARMENIA
  //LETONIA
  String daugavaRiga = "Daugava Riga";
  String rigaRFS = "Rigas Futbola Skola";
  String rigafc = "Riga FC";
  String liepaja = "FK Liepaja";
  String valmiera = "Valmiera";
  //LITUANIA
  String suduva = "Suduva Marijampole";
  String kaunu = "Kaunu Zalgiris";
  String zalgiris = "Zalgiris Vilnius";
  //ESTONIA
  String kalev = "Kalev Tallinn";
  String floratallinn = "Flora Tallinn";
  String levadiatallinn = 'Levadia Talinn';
  String paide = 'Paide Linnameeskond';

  //LESTE EUROPEU
  //SERBIA
  String estrelavermelha = "Estrela Vermelha";
  String partizan = "Partizan";
  String backaTopola = "Bačka Topola";
  String borakCacak = "Borac Čačak";
  String cukaricki = "Čukarički";
  String jagodina = "Jagodina";
  String obilic = "Obilic";
  String mladostLucani = "Mladost Lucani";
  String napredakKrusevac = "Napredak Krusevac";
  String noviPazar = "Novi Pazar";
  String ofkBelgrade = "OFK Belgrade";
  String radnicki = "Radnicki";
  String radnik = "Radnik";
  String subotica = "Spartak Subotica";
  String vojvodina = "Vojvodina";
  String vozdovac = "Voždovac";
  //ROMENIA
  String steauaBucuresti = "Steaua Bucareste";
  String dinamoBucuresti = "Dinamo Bucareste";
  String rapidBucuresti = "Rapid Bucareste";
  String argesPitesti = "Argeş Piteşti";
  String clinceni = "Academica Clinceni";
  String apulum = "Apulum";
  String astragiurgiu = "Astra Giurgiu";
  String botosani = "Botosani";
  String brasov = "Brasov";
  String ceahlaul = "Ceahlaul";
  String corvinul = "Corvinul";
  String craiova = "Universitatea Craiova";
  String cluj = "CFR Cluj";
  String farul = "Farul";
  String gazmetan = "Gaz Metan";
  String gloriabuzau = "Gloria Buzau";
  String gloriabistrita = "Gloria Bistrita";
  String aerostarBacau = "Aerostar Bacau";
  String arad = "UTA Arad";
  String flacara = "Flacara Moreni";
  String intersibiu = "Inter Sibiu";
  String jiul = "Jiul";
  String nationalbuc = "National Bucuresti";
  String pandurii = "Pandurii";
  String petrolul = "Petrolul";
  String progresul = "Progresul Bucuresti";
  String otelul = "Otelul";
  String oltscornicesti = "Olt Scornicesti";
  String sepsi = "Sepsi OSK";
  String sportul = "Sportul Studenţesc";
  String targoviste = "Târgovişte";
  String targuMures = "Targu Mures";
  String timisoara = "Timisoara";
  String unirea = "Unirea Urziceni"; //1954-2015
  String vaslui = "Vaslui";
  String victoriabuc = "Victoria Bucuresti";
  String vitorul = "Vitorul";
  //BULGARIA
  String beroe = "Beroe Stara Zagora";
  String botevPlovdiv = "Botev Plovdiv";
  String cskaSofia = "CSKA Sofia";
  String levskiSofia = "Levski Sofia";
  String lokplovdiv = "Lokomotiv Plovdiv";
  String loksofia = "Lokomotiv Sofia";
  String ludogorets = "Ludogorets";
  String litexLovech = "Litex Lovech";
  String slaviaSofia = "Slavia Sofia";
  String spartakPlovdiv = "Spartak Plovdiv";
  //CROACIA
  String dinamozagreb = "Dinamo Zagreb";
  String hadjuksplit = "Hadjuk Split";
  String rijeka = "Rijeka";
  String gorica = "Gorica";
  String nkzagreb = "NK Zagreb";
  String osijek = "Osijek";
  String varteks = "Varteks";
  String slavenBelupo = "Slaven Belupo";
  String lokZagreb = "NK Lokomotiva Zagreb";
  String zapresic = "Inter Zaprešić";
  //REP. TCHECA
  String spartapraga = "Sparta Praga";
  String slaviaPraha = "Slavia Praha";
  String banikostrava = "Banik Ostrava";
  String bobyBrno = "Boby Brno";
  String bohemians = "Bohemians";
  String brno = "Zbrojovka Brno";
  String drnovice = "Drnovice";
  String hradec = "Hradec Králové";
  String dukla = "Dukla Praha";
  String mladaBoleslav = "Mladá Boleslav";
  String jablonec = "Jablonec";
  String teplice = "Teplice";
  String pardubice = "Pardubice";
  String sigmaOlomouc = "Sigma Olomouc";
  String slovacko = "Slovácko";
  String slovanLiberec = "Slovan Liberec";
  String vitkovice = "Vitkovice";
  String viktoriaPlzen = "Viktoria Plzen";
  String viktoriaZizkov = "Viktoria Žižkov";
  //HUNGRIA
  String balmazujvaros = "Balmazújváros";
  String bekescsaba = "Békéscsaba";
  String budafok = "Budafok";
  String csepel = "Csepel";
  String debreceni = "Debreceni";
  String diosgyor = "Diósgyőr";
  String dunaujvaros = "Dunaújváros";
  String egri = "Egri";
  String fehervar = "Fehérvár";
  String ferencvaros = "Ferencvaros";
  String gyori = "Gyori";
  String gyirmot = "Gyitmot";
  String haladas = "Haladás";
  String honved = "Honved";
  String kaposvar = "Kaposvár";
  String kecskemet = "Kecskemét";
  String kisvarda = "Kisvárda";
  String komloiBanyasz = "Komlói Bányász";
  String mezokovesd = "Mezőkövesd";
  String mtk = "MTK";
  String nyiregyhaza = "Nyíregyháza";
  String ozdiKohasz = "Ózdi Kohász";
  String papa = "Pápa";
  String paks = "Paks";
  String pecsi = "Pecsi";
  String rakospalota = "Rákospalota";
  String salgotarjani = "Salgótarjáni";
  String siofok = "Siófok";
  String sopron = "Sopron";
  String szegedi = "Szegedi";
  String szolnok = "Szolnok";
  String szombathely = "Szombathely";
  String tatabanya = "Tatabánya";
  String vasas = "Vasas";
  String vasutas = "Vasutas";
  String vorosMeteor = "Vörös Meteor Egyetértés";
  String vac = "Vác";
  String ujpest = "Ujpest";
  String puskas = "Puskás Akadémia FC";
  String zalaegerszeg = "Zalaegerszeg";
  //ESLOVAQUIA
  String petrzalka = "Petrzalka 1898";
  String slovanBratislava = "Slovan Bratislava";
  String interBratislava = "Inter Bratislava";
  String jednotaTrencin = "Jednota Trenčín"; //EXTINTO
  String nitra = "Plastika Nitra";
  String trnava = "Spartak Trnava";
  String trencin = "AS Trencin";
  String kosice = "VSS Kosice";
  String lokKosice = "Lokomotiva Kosice";
  String tatranPresov = "Tatran Prešov";
  String zilina = "MSK Zilina";
  String dac1904 = "DAC 1904";
  //OUTROS
  //ALBANIA
  String partizanitirane = "FK Partizani Tiranë";//ALBANIA
  String kukesi = "KF Laçi";//ALBANIA
  String laci = "KF Laçi";//ALBANIA
  String teutaDurres = "Teuta Durrës";//ALBANIA
  String tiranafk = "KF Tirana";//ALBANIA
  String vllaznia = "Vllaznia";//ALBANIA
  //ESLOVENIA
  String ljublijana = "Olimpia Ljubljana";//ESLOVENIA
  String maribor = "Maribor";//ESLOVENIA
  String mura = "NS Mura";//ESLOVENIA
  String domzale = "Domzale";//ESLOVENIA
  String celje = "Celje";//ESLOVENIA
  //BOSNIA
  String posusje = "Posusje";//BOSNIA
  String sarajevo = "Sarajevo";//BOSNIA
  String zrinjski = "HSK Zrinjski";//BOSNIA
  String zeljeznicar = "Željezničar";//BOSNIA
  String slobodaTuzla = "Sloboda Tuzla";
  String velezMostar = "Velež Mostar";
  //KOSOVO
  String ballkani = "KF Ballkani";//KOSOVO
  String llapi = "KF Llapi";//KOSOVO
  String prishtina = "Prishtina";//KOSOVO
  String drita = "Drita";//KOSOVO
  //MONTENEGRO
  String decic = "Decic";
  String iskra = "Iskra Danilovgrad";
  String podgorica = "Buducnost Podgorica";
  String sutjeska = "Sutjeska Nikšić";
  String zeta = "Zeta";
  //MACEDONIA
  String akaPandev = "Akademija Pandev";
  String shkupi = "KF Shkupi";
  String makedonija = "Makedonija Gjorče Petrov";
  String shkendija = "FK Shkendija";
  String silekskratovo = "Sileks Kratovo";
  String vardar = "FK Vardar";
  //MALTA
  String sliema = "Sliema Wanderers";//MALTA
  String hiberniansMALTA = "Hibernians-Malta";//MALTA
  String valletta = "Valletta";//MALTA
  String floriana = "Floriana";//MALTA
  //LUXEMBURGO
  String dudelange = "F91 Dudelange";//LUXEMBURGO
  String jeunesseesch = "Jeunesse Esch";//LUXEMBURGO
  String folaeesch = "Fola Esch";//LUXEMBURGO
  //LIECHSTEIN
  String balzers = "FC Balzers";//LIECHSTEIN
  String rugell = "FC Rugell";//LIECHSTEIN
  String eschenMauren = "Eschen-Mauren";//LIECHSTEIN
  String vaduz = "Vaduz";//LIECHSTEIN
  //SAN MARINO
  String domagnano = "Domagnano";//SAN MARINO
  String folgore = "Folgore Falciano";//SAN MARINO
  String lafiorita = "La Fiorita";//SAN MARINO
  String trepenne = "Tre Penne";//SAN MARINO
  String trefiori = "Tre Fiori";//SAN MARINO
  String libertas = "Libertas";//SAN MARINO
  //GIBRALTAR
  String europa = "Europa FC";
  String lincolnRedImps = "Lincoln Red Imps";
  String stJosephs = "St Joseph's";
  //ANDORRA
  String santacoloma = "Santa Coloma";//ANDORRA


  //////////////////////////////////////////////////////////////////////////////
  //////////////////////////////////////////////////////////////////////////////
  //BRASIL
  String atleticogo = "Atlético-GO";
  String atleticomg = "Atlético-MG";
  String atleticopr = "Atlético-PR";
  String bahia = "Bahia";
  String bragantino = "Bragantino";
  String ceara = "Ceará";
  String corinthians = "Corinthians";
  String flamengo = "Flamengo";
  String fluminense = "Fluminense";
  String fortaleza= "Fortaleza";
  String gremio= "Grêmio";
  String internacional = "Internacional";
  String palmeiras = "Palmeiras";
  String santos = "Santos";
  String saopaulo = "São Paulo";
  String sport = "Sport";

  String americamg= "América-MG";
  String botafogo = "Botafogo";
  String chapecoense = "Chapecoense";
  String coritiba = "Coritiba";
  String cuiaba = "Cuiabá";
  String criciuma= "Criciúma";
  String cruzeiro = "Cruzeiro";
  String figueirense = "Figueirense";
  String goias = "Goiás";
  String guarani = "Guarani";
  String juventude = "Juventude";
  String nautico = "Naútico";
  String parana = "Paraná";
  String pontepreta = "Ponte Preta";
  String vasco = "Vasco";
  String vitoria = "Vitória";

  String julho4 = "4 de julho";
  String novembro15 = "15 de novembro";
  String abc = "ABC";
  String adesg = "Adesg";
  String aguasanta = "Água Santa";
  String aguiamaraba = "Águia de Marabá";
  String aimore = "Aimoré";
  String altos = "Altos";
  String alagoinhas = "Alagoinhas";
  String amazonas = "Amazonas";
  String asa = "ASA";
  String americaRN = "América-RN";
  String americaRJ= "América-RJ";
  String americaSP= "América-SP";
  String americanoRJ= "Americano";
  String anapolina = "Anapolina";
  String audaxSP = "Grêmio Osasco Audax";
  String audaxRJ = "Audax";
  String autoesporte = "Auto Esporte-PI";
  String atleticoCE = "Atlético-CE";
  String atleticoAC = "Atlético Acreano";
  String aparecidense = "Aparecidense";
  String avai = "Avaí";
  String azuriz = "Azuriz";
  String bahiafeira = "Bahia de Feira";
  String bangu = "Bangu";
  String boavistaRJ = "Boavista-RJ";
  String botafogoSP = "Botafogo-SP";
  String botafogoPB = "Botafogo-PB";
  String boaesporte = "Boa Esporte";
  String bragantinoPR = "Bragantino Clube do Pará";
  String brasilPelotas = "Brasil de Pelotas";
  String brasilia = "Brasília";
  String brasiliense = "Brasiliense";
  String brusque = "Brusque";
  String cabofriense = "Cabofriense";
  String caldense = "Caldense";
  String camboriu = "Camboriú";
  String campograndeRJ = "Campo Grande-RJ";
  String campinense = "Campinense";
  String capivariano = "Capivariano";
  String cascavel = "Cascavel";
  String castanhal = "Castanhal";
  String catuense = "Catuense";
  String caxias = "Caxias do Sul";
  String ceilandia = "Ceilândia";
  String central = "Central";
  String ceov = "CEOV";
  String cianorte = "Cianorte";
  String comercial = "Comercial";
  String confianca = "Confiança";
  String corumbaense = "Corumbaense";
  String crb = "CRB";
  String csa = "CSA";
  String democrata = "Democrata MG";
  String desportiva = "Desportiva";
  String desportivobrasil = "Desportivo Brasil";
  String duque = "Duque de Caxias";
  String fast = "Fast";
  String ferroviaria = "Ferroviária";
  String ferroviario = "Ferroviário";
  String floresta = "Floresta";
  String fluminenseFeira = "Fluminense de Feira";
  String francana = "Francana";
  String friburguense = "Friburguense";
  String galvez = "Galvez";
  String gama = "Gama";
  String gremioBarueri = "Grêmio Barueri";
  String goytacaz = "Goytacaz";
  String guarany = "Guarany";
  String hercilioluz = "Hercílio Luz";
  String humaita = "Humaita";
  String maringa = "Grêmio Maringá";
  String galicia = "Galícia";
  String guaratingueta = "Guaratinguetá";
  String goiania = "Goiânia";
  String goianesia = "Goianésia";
  String globo = "Globo";
  String gremioNovorizontino = "Grêmio Novorizontino";
  String ibis = "Íbis";
  String icasa = "Icasa";
  String imperatriz = "Imperatriz";
  String interLimeira = "Inter de Limeira";
  String ituano = "Ituano";
  String itumbiara = "Itumbiara";
  String itabaiana = "Itabaiana";
  String itabuna = "Itabuna";
  String ipatinga = "Ipatinga";
  String jacuipense = "Jacuipense";
  String joinville = "Joinville";
  String juazeirense = "Juazeirense";
  String juventusMooca = "Juventus Mooca";
  String juventusSC = "Juventus SC";
  String lagarto = "Lagarto-SE";
  String limoeiro = "Limoeiro";
  String linense = "Linense";
  String linhares = "Linhares";
  String londrina = "Londrina";
  String luverdense = "Luverdense";
  String macae = "Macaé";
  String madureira = "Madureira";
  String malutrom = "Malutrom";
  String maranhao = "Maranhão";
  String marciliodias = "Marcílio Dias";
  String marilia = "Marília";
  String maringaFC = "Maringa FC";
  String manaus = "Manaus";
  String mirassol = "Mirassol";
  String mixto = "Mixto";
  String mogimirim = "Mogi Mirim";
  String monteazul = "Monte Azul";
  String motoclub = "Moto Club";
  String nacionalAM = "Nacional AMAZ";
  String nacionalSP = "Nacional SP";
  String noroeste = "Noroeste";
  String novaiguacu = "Nova Iguaçu";
  String novohamburgo = "Novo Hamburgo";
  String operarioPR = "Operário-PR";
  String operarioms = "Operário-MS";
  String operarioMT = "Operário-MT";
  String oeste = "Oeste";
  String pacajus = "Pacajus";
  String palmas = "Palmas";
  String patrocinense = "Patrocinense";
  String paulista = "Paulista Jundiaí";
  String paysandu = "Paysandu";
  String penapolense = "Penapolense";
  String portoPE = "Porto-PE";
  String portuguesa = "Portuguesa";
  String portuguesaRJ = "Portuguesa-RJ";
  String portuguesasantista = "Portuguesa Santista";
  String pousoalegre = "Pouso Alegre";
  String portovelho = "Porto Velho";
  String primavera = "Primavera";
  String princesasolimoes = "Princesa dos Solimões";
  String remo = "Remo";
  String realArquimedes = "Real Arquimedes";
  String realNoroeste = "Real Noroeste-ES";
  String resende = "Resende";
  String retro = "Retrô";
  String riverPI = "River-PI";
  String riobrancoAC = "Rio Branco-AC";
  String riobrancoES = "Rio Branco-ES";
  String riobrancoSP = "Rio Branco-SP";
  String rioclaro = "Rio Claro";
  String rionegro = "Rio Negro";
  String riopreto = "Rio Preto";
  String salgueiro = "Salgueiro";
  String santacruz = "Santa Cruz";
  String saocaetano = "São Caetano";
  String santoandre = "Santo André";
  String saobento = "São Bento";
  String saobernardo = "São Bernardo";
  String saojose = "São José";
  String saojoseRS = "São José RS";
  String saoraimundo = "São Raimundo";
  String saoraimundoRR = "São Raimundo-RR";
  String sampaio = "Sampaio Corrêa";
  String santamaria = "Inter Santa Maria";
  String serra = "Serra";
  String sergipe = "Sergipe";
  String sertaozinho = "Sertãozinho";
  String sinop = "Sport Sinop";
  String sobradinho = "Sobradinho";
  String sousa = "Sousa PB";
  String taubate = "Taubaté";
  String taguatinga = "Taguatinga";
  String tiradentes = "Tiradentes";
  String tocantinopolis = "Tocantinópolis";
  String tombense = "Tombense";
  String trem = "Trem-AP";
  String treze = "Treze";
  String tunaluso = "Tuna Luso";
  String tupi = "Tupi";
  String uniaoSaoJoao = "Uniao São João";
  String uberaba = "Uberaba";
  String uberlandia = "Uberlândia";
  String urt = "URT";
  String uniaobarbarense = "União Barbarense";
  String veloclube = "Velo Clube";
  String vilanova = "Vila Nova";
  String villanova = "Villa Nova MG";
  String vitoriaES = "Vitória-ES";
  String voltaredonda = "Volta Redonda";
  String xvjau = "XV Jaú";
  String xvpiracicaba = "XV Piracicaba";
  String ypirangaAP = "Ypiranga AP";
  String ypirangaRS = "Ypiranga RS";


  //////////////////////////////////////////////////////////////////////////////
  String aldosivi = "Aldosivi";
  String allboys = "All Boys";
  String almagro = "Almagro";
  String atlantaARG = "Atlanta";
  String argentinojuniors = "Argentinos Juniors";
  String argentinoFirmat = "Argentino Firmat";
  String rafaela = "Atlético Rafaela";
  String arsenalsarandi = "Arsenal Sarandí";
  String atleticoTucuman = "Atlético Tucumán";
  String banfield = "Banfield";
  String barracas = "Barracas Central";
  String belgrano = "Belgrano";
  String bocajuniors = "Boca Juniors";
  String centralCordoba = "Central Córdoba";
  String centralNorte = "Central Norte";
  String chacarita = "Chacarita Juniors";
  String chaco = "Chaco For Ever";
  String colon = "Colón";
  String defensayjusticia = "Defensa y Justicia";
  String depEspanol = "Deportivo Español";
  String depArmenio = "Deportivo Armenio";
  String desamparados = "Desamparados";
  String mandiyu = "Deportivo Mandiyú";
  String estudiantes = "Estudiantes";
  String estudiantesBA = "Estudiantes de Buenos Aires";
  String riocuarto = "Estudiantes de Río Cuarto";
  String ferro = "Ferro Carril Oeste";
  String gimnasia = "Gimnasia y Esgrima";
  String gimJujuy = "Gimnasia Jujuy";
  String gimTiro = "Gimnasia y Tiro";
  String godoycruz = "Godoy Cruz";
  String antonioFranco = "Guaraní Antonio Franco";
  String huracan = "Huracán";
  String huracanCorrientes = "Huracán Corrientes";
  String lasHeras = "Huracán de Las Heras";
  String ingenieroWhite = "Huracán Ingeniero White";
  String independiente = "Independiente";
  String instituto = "Instituto Córdoba";
  String kimberley = "Kimberley";
  String lanus = "Lanús";
  String losandes = "Los Andes";
  String newells = "Newell's Old Boys";
  String nuevachicago = "Nueva Chicago";
  String olimpo = "Olimpo";
  String patronato = "Patronato";
  String platense = "Platense";
  String quilmes = "Quilmes";
  String racing = "Racing";
  String rivadavia = "Ind. Rivadavia";
  String riverplate = "River Plate";
  String rosariocentral = "Rosario Central";
  String sanlorenzo = "San Lorenzo";
  String slMarPlata = "San Lorenzo Mar del Plata";
  String sarmiento = "Sarmiento";
  String sanmartinmendoza = "San Martin Mendoza";
  String sanmartintucuman = "San Martin Tucumán";
  String sanmartin = "San Martin San Juan";
  String santamarina = "Ramón Santamarin";
  String santelmo = "San Telmo";
  String talleres= "Talleres";
  String temperley= "Temperley";
  String tigre = "Tigre";
  String tiroFederal = "Tiro Federal";
  String velez = "Vélez Sarsfield";
  String unionSantaFe = "Unión de Santa Fe";
  //URU
  String penarol = "Peñarol";
  String nacional = "Nacional";
  String atenas = "Atenas";
  String bellavista = "Bella Vista";
  String bostonriver = "Boston River";
  String cerrito = "Cerrito";
  String cerrouru = "Cerro-URU";
  String cerroLargo = "Cerro Largo";
  String centralespanol = "Central Español";
  String danubio = "Danubio";
  String defensor = "Defensor";
  String depMaldonado = "Deportivo Maldonado";
  String eltanque = "El Tanque Sisley";
  String juventud = "Juventud";
  String montevideoCity = "Montevideo City";
  String fenix = "Fenix";
  String liverpoolURU = "Liverpool-URU";
  String miramar = "Miramar Misiones";
  String plazacolonia = "Plaza Colonia";
  String progreso = "Progreso";
  String racingMontevideo = "Racing Montevideo";
  String rampla = "Rampla Juniors";
  String rentistas = "Rentistas";
  String riverURU = "River Plate-URU";
  String rocha = "Rocha";
  String sudamerica = "Sud América";
  String tacuarembo = "Tacuarembó";
  String montWanderers = "Montevideo Wanderers";
  //PARAGUAI
  String olimpia = "Olimpia";
  String cerroporteno = "Cerro Porteño";
  String cerroportenoPF = "Cerro Porteño PF";
  String libertad = "Libertad";
  String guaraniPAR = "Club Guaraní";
  String nacionalPAR = "Club Nacional";
  String capiata = "Deportivo Capiatá";
  String carapegua = "Sportivo Carapeguá";
  String cerrocora = "Cerro Corá";
  String colegiales = "Atlético Colegiales";
  String recoleta = "Dep. Recoleta";
  String encarnacion = "Universal Encarnación";
  String febrero3 = "3 de Febrero";
  String generalCaballero = "General Caballero";
  String generalDiaz = "General Díaz";
  String guairena = "Guaireña";
  String independientePAR = "independiente";
  String luqueno = "Sportivo Luqueño";
  String mayo2 = "2 de Mayo";
  String octubre12 = "12 de Octubre";
  String presidenteHayes = "Presidente Hayes";
  String resistencia = "Resistencia";
  String riverPAR = "River-PAR";
  String rubionu = "Rubio Ñu";
  String santani = "Deportivo Santaní";
  String sanlorenzoPAR = "San Lorenzo PAR";
  String soldeamerica = "Sol de América";
  String sportcolombia = "Sport Colombia";
  String tacuary = "Tacuary";
  String tembetary = "Tembetary";
  String trinidense = "Trinidense";
  //CHILE
  String colocolo = "Colo-Colo";
  String lau = "LaU";
  String univcatolica = "Univ. Católica";
  String antofagasta = "Antofagasta";
  String audaxItaliano = "Audax Italiano";
  String arturo = "Arturo Fernández Vial";
  String aviacion = "Aviación";
  String badminton = "Badminton"; //EXTINTO 1912-1973
  String cobreloa = "Cobreloa";
  String cobresal = "Cobresal";
  String concepcion = "Deportes Concepción";
  String puertoMontt = "Deportes Puerto Montt";
  String temuco = "Deportes Temuco";
  String coquimbo = "Coquimbo Unido";
  String curico = "Curicó Unido";
  String greenCross = "Green Cross"; //EXTINTO 1916-1965
  String melipilla = "Deportes Melipilla";
  String evertonchi = "Everton-CHI";
  String huachipato = "Huachipato";
  String iquique = "Deportes Iquique";
  String laCalera = "La Calera";
  String laserena = "La Serena";
  String lotaSchwager = "Lota Schwager";
  String magallanes = "Magallanes";
  String navalTalcahuano = "Naval de Talcahuano";
  String nublense = "Ñublense";
  String palestino = "Palestino";
  String rangersCHI = "Rangers CHI";
  String ohiggins = "O'Higgins";
  String unionespanola = "Unión Española";
  String sanluisCHI = "San Luis de Quillota";
  String santiagowanderers = "Santiago Wanderers";
  String santiagoMorning = "Santiago Morning";
  String sanfelipe = "Unión San Felipe";
  //BOLIVIA
  String alwaysReady = "Always Ready";
  String aurora = "Aurora";
  String blooming = "Blooming";
  String bolivar = "Bolívar";
  String chacoPetrolero = "Chaco Petrolero";
  String destroyers = "Destroyers";
  String guabira = "Guabirá";
  String jorge = "Jorge Wilstermann";
  String indPetrolero = "Independiente Petrolero";
  String lapaz = "La Paz";
  String litoral = "Litoral";
  String municipalBOL = "CD Municipal";
  String nacionalpotosi = "Nacional Potosí";
  String orientePetrolero = "Oriente Petrolero";
  String palmaflor = "Palmaflor";
  String octubre31 = "31 de Octubre";
  String realpotosi = "Real Potosí";
  String realsantacruz = "Real Santa Cruz";
  String realtomayapo = "Real Tomayapo";
  String royalpari = "Royal Pari";
  String sanJoseBOL = "San José";
  String theStrongest = "The Strongest";
  String sucre = "Universitario Sucre";
  String univVinto = "Universitario de Vinto";
  //PERU
  String universitario = "Universitario";
  String sportingcristal = "Sporting Cristal";
  String alianzalima = "Alianza Lima";
  String alianzaSullana = "Alianza Atlético de Sullana";
  String atlGrau = "Atlético Grau";
  String tarma = "AD Tarma";
  String chalaco = "Atlético Chalaco";
  String atltorino = "Atlético Torino";
  String ayacucho = "Ayacucho";
  String binacional = "Binacional";
  String cantolao = "Cantolao";
  String carlosStein = "Carlos Stein";
  String cesarvallejo = "César Vallejo";
  String iqueno = "Centro Iqueño";
  String carlosmanucci = "Carlos Manucci";
  String cienciano = "Cienciano";
  String coronel = "Coronel Bolognesi";
  String cusco = "Cusco";
  String arica = "Defensor Arica";
  String defensorlima = "Defensor Lima";
  String depmunicipal = "Dep. Municipal";
  String depWanka = "Deportivo Wanka";
  String huancayo = "Sport Huancayo";
  String juanaurich = "Juan Aurich";
  String leonhuanuco = "León de Huánuco";
  String losEspartanos = "Los Espartanos";
  String melgar = "Melgar";
  String sanagustin = "San Agustín";
  String ancash = "Sport Ancash";
  String sportboys = "Sport Boys";
  String ugarte = "Alfonso Ugarte";
  String unisanmartin = "Univ. San Martín";
  String cajamarca = "Univ. Técnica Cajamarca";
  String unionhuaral = "Union Huaral";
  //EQUADOR
  String idelvalle = "I. Del Valle";
  String barcelonaequ= "Barcelona-EQU";
  String depcuenca = "Deportivo Cuenca";
  String emelec = "Emelec";
  String ldu = "LDU";
  String americaquito = "América de Quito";
  String aucas = "Aucas";
  String audazOctubrino = "Audaz Octubrino";
  String azogues = "Azogues";
  String clanJuvenil = "Clan Juvenil";
  String delfin = "Delfín";
  String depquito = "Deportivo Quito";
  String elnacional = "El Nacional";
  String everestGuayaquil = "Everest Guayaquil";
  String esmeraldas = "Esmeraldas Petrolero";
  String espoli = "Espoli";
  String filanbanco = "Filanbanco";
  String fuerzaAmarilla = "Fuerza Amarilla";
  String guayaquil = "Guayaquil City";
  String imbabura = "Imbabura";
  String lduLoja = "LDU Loja";
  String portoviejo = "LDU de Portoviejo";
  String octubre9 = "9 de Octubre";
  String macara = "Macara";
  String manta = "Manta Sport";
  String mushucruna = "Mushuc Runa";
  String nueveoctubre = "Nueve Octubre";
  String olmedo = "Olmedo";
  String orense = "Orense";
  String patria = "Patria";
  String politecnico = "Politécnico";
  String quevedo = "Quevedo";
  String tecnicoUniv = "Técnico Univ.";
  String uniequ = "Universidad Católica";
  String valdez = "Valdez";
  //COLOMBIA
  String americadecali = "América de Cali";
  String atleticonacional = "Atlético Nacional";
  String deportivocali = "Deportivo Cali";
  String junior = "Junior";
  String imedellin = "I. Medellín";
  String oncecaldas = "Once Caldas";
  String millonarios = "Millonarios";
  String santafe = "Santa Fé";
  String tolima = "Tolima";
  String alianzaPetrolera = "Alianza Petrolera";
  String huila = "Atlético Huila";
  String boyaca = "Boyacá Chicó";
  String bucaramanga = "Bucaramanga";
  String cucuta = "Cúcuta";
  String cortulua = "Cortuluá";
  String depPasto = "Deportivo Pasto";
  String envigado = "Envigado";
  String jaguaresCOL = "Jaguares-COL";
  String laequidad = "La Equidad";
  String patriotas = "Patriotas";
  String pereira = "Deportivo Pereira";
  String quindio = "Deportes Quindio";
  String rioNegroAguilas = "Rio Negro Aguilas";
  String uMagdalena = "Unión Magdalena";

  //VENEZUELA
  String aragua = "Aragua";
  String atlVenezuela = "Atlético Venezuela";
  String carabobo = "Carabobo";
  String caracas = "Caracas";
  String tachira = "Deportivo Táchira";
  String laGuaira = "La Guaira";
  String deplara = "Deportivo Lara";
  String depgalicia = "Deportivo Galícia";
  String depitalia = "Deportivo Italia";
  String deppetare = "Deportivo Petare";
  String italchacao = "Deportivo Italchacao";
  String estudiantesmerida = "Estudiantes de Mérida";
  String hermanosColmenarez = "Hermanos Colmenarez";
  String laraFC = "Lara FC";
  String llaneros = "Llaneros";
  String maracaibo = "Maracaibo";
  String maritimoven = "Marítimo de Venezuela";
  String metropolitanos = "Metropolitanos";
  String minerven = "Minervén";
  String mineros = "Mineros";
  String anzoategui = "Anzoátegui";
  String margarita = "Margarita";
  String monagas = "Monagas";
  String nacTachira = "Nacional Táchira";
  String pepeganga = "Pepeganga";
  String portugues = "CD Portugués";
  String portuguesaven = "Portuguesa-VEN";
  String puertoCabello = "Puerto Cabello";
  String realesppor = "Real Esppor";
  String sancristobal = "Atlético San Cristóbal";
  String tucanes = "Tucanes";
  String trujillanos = "Trujillanos";
  String ula = "Universidad Los Andes";
  String uCanarias = "Unión Canarias";
  String ucv = "Universidad Central de Venezuela";
  String valenciaven = "Valencia-VEN";
  String yaracuyanos = "Yaracuyanos";
  String zamora = "Zamora";
  String zulia = "Zulia";

  //////////////////////////////////////////////////////////////////////////////
  //MEXICO
  String alebrijes = "Alebrijes";
  String americamex= "América-MEX";
  String atlas = "Atlas";
  String atlante = "Atlante";
  String atlPotosino = "Atlético Potosino";
  String celaya = "Atlético Celaya";
  String cancun = "Cancún";
  String chivas= "Chivas Guadalajara";
  String cimarrones = "Cimarrones";
  String leon = "Club León";
  String correcaminos = "Correcaminos";
  String cobras = "Cobras";
  String cruzazul = "Cruz Azul";
  String dorados = "Dorados Sinaloa";
  String irapuato = "Irapuato";
  String jaguares = "Jaguares Chiapas";
  String juarez = "Juárez";
  String leonesNegros = "Leones Negros";
  String lapiedad = "La Piedad";
  String lobos = "Lobos BUAP";
  String mazatlan = "Mazatlán";
  String minerosZacatecas = "Mineros de Zacatecas";
  String monterrey = "Monterrey";
  String morelia = "Morelia";
  String necaxa = "Necaxa";
  String queretaro = "Querétaro";
  String pachuca = "Pachuca";
  String puebla = "Puebla";
  String pumas = "Pumas";
  String sanluis = "San Luis";
  String santosLaguna = "Santos Laguna";
  String tampico = "Tampico Madero";
  String tecos = "Tecos";
  String tepatitlan = "Tepatítlan de Morelos";
  String torosNeza = "Toros Neza";
  String tigres = "Tigres";
  String tijuana = "Tijuana";
  String toluca = "Toluca";
  String venados = "Venados";
  String veracruz = "Veracruz";
  String zacatepec = "Zacatepec";

  String atlEspanol = "Atlético Español";
  String cdfas = "CD FAS";
  String depNeza = "Deportivo Neza";
  String indios = "Indios";
  String jalisco = "Club Jalisco";
  String jongcolombia = "Jong Colombia";
  String madero = "Ciudad Madero";
  String nuevoLeon = "Jabatos de Nuevo León";
  String oro = "Club Deportivo Oro";
  String torreon = "Torreón";
  String curtidores = "Unión de Curtidores";
  String sanLuisPotosi = "San Luis Potosi";

  //MLS
  String atlanta = "Atlanta United";
  String austin = "Austin FC";
  String charleston = "Charleston Battery";
  String charlotte = "Charlotte FC";
  String chicago = "Chicago Fire";
  String chivasUSA = "Chivas USA";
  String cincinnati = "Cincinnati FC";
  String colorado = "Colorado Rapids";
  String switchbacks = "Colorado Springs Switchbacks";
  String columbuscrew = "Columbus Crew";
  String detroit  = "Detroit City FC";
  String dcunited  = "DC United";
  String elpaso  = "El Paso Lokomotiv";
  String fcdallas = "FC Dallas";
  String houston = "Houston Dynamo";
  String intermiami = "Inter Miami";
  String indyeleven = "Indy Eleven";
  String lasvegas = "Las Vegas Lights";
  String losangelesfc = "Los Angeles FC";
  String lagalaxy = "LA Galaxy";
  String louisville = "Louisville City";
  String newmexico = "New Mexico United";
  String miamifc = "Miami FC";
  String miamiFusion = "Miami Fusion"; //EXTINTO
  String memphis = "Memphis 901";
  String minnesota = "Minnesota United";
  String montreal = "Montreal Impact";
  String nashville = "Nashville SC";
  String nerevolution = "NE Revolution";
  String nycity = "NY City";
  String nycosmos = "NY Cosmos";
  String nyredbulls = "NY Red Bulls";
  String oakland = "Oakland Roots";
  String orlando = "Orlando City";
  String pittsburgh = "Pittsburgh Riverhounds";
  String philadelphia = "Philadelphia Union";
  String phoenix = "Phoenix Rising";
  String portland = "Portland Timbers";
  String realSaltLake = "Real Salt Lake";
  String riogrande = "Rio Grande Valley";
  String sacramento = "Sacramento Republic";
  String sanantonio = "San Antonio FC";
  String sandiego = "San Diego Loyals";
  String sanJoseEarthquakes = "San Jose Earthquakes";
  String seattle = "Seattle Sounders";
  String kansas = "Sporting Kansas City";
  String tampabay = "Tampa Bay Rowdies";
  String tampaBayMutiny = "Tampa Bay Mutiny"; //EXTINTO
  String toronto = "Toronto FC";
  String tulsa = "FC Tulsa";
  String vancouver = "Vancouver Whitecaps";

  //CANANDA
  String cavalry = "Cavalry";
  String forge = "Forge FC";
  String pacific = "Pacific";

  //COSTA RICA
  String saprissa = "Saprissa";
  String alajuelense = "Alajuelense";
  String herediano = "Herediano";
  String barrioMexico = "Barrio México";
  String brujas = "Brujas";
  String cartagines = "Cartaginés";
  String guadalupe = "Guadalupe";
  String sanCarlos = "San Carlos";
  String limonense = "Limonense";
  String orion = "Orión";
  String uruguay = "Uruguay";
  String perezZeledon = "Pérez Zeledón";
  String puntarenas = "Puntarenas";
  String santosGuapiles = "Santos Guápiles";
  String sptSanJose = "Sporting San José";
  //EL SALVADOR
  String alianzaELS = "Alianza El Salvador";
  String atleticomarte = "Atlético Marte";
  String aguila = "Águila";
  String fas = "CD FAS";
  String firpo = "CD Luis Ángel Firpo";
  String isidro = "Isidro Metapán";
  String santaTecla = "Santa Tecla";
  //GUATEMALA
  String antiguaGuatemala = "Antigua Guatemala";
  String comunicaciones = "Comunicaciones";
  String municipal = "Municipal";
  String xelaju = "Xelajú";
  String depGuastatoya = "Deportivo Guastatoya";
  //HONDURAS
  String olimpiaHON = "Olimpia-HON";
  String marathon = "Marathón";
  String motagua = "Motagua";
  String rcdespana = "RCD España";
  //NICARAGUA
  String diriangen = "Diriangén";
  String managua = "Managua";
  String realEsteli = "Real Estelí";
  //PANAMA
  String independienteChorrera = "Independiente de La Chorrera";
  String tauro = "Tauro-PAN";
  String arabeunido = "Árabe Unido";
  String alianzaPAN = "Alianza FC";
  String plazaAmador = "Plaza Amador";
  String sanMiguelito = "San Miguelito";

  //CARIBE
  //BELIZE
  String altitude = "Altitude";
  String bandits = "Belmopan Bandits";
  String sanPedroPirates = "San Pedro Pirates";
  String verdes = "Verdes FC";
  //CUBA
  String pinardelrio = "Pinar del Rio";
  String santiagoCuba = "Santiago de Cuba";
  String villaclara = "FC Villa Clara";
  //HAITI
  String arcahaie = "Arcahaie";
  String cavaly = "Cavaly";
  String donBosco = "Don Bosco FC";
  String fica = "FICA";
  String racingHAITI = "Racing Haiti";
  String violette = "Violette";
  //JAMAICA
  String arnettGardens = "Arnett Gardens";
  String harbourView = "Harbour View"; //JAMAICA
  String portmore = "Portmore United"; //JAMAICA
  String tivoliGardens = "Tivoli Gardens"; //JAMAICA
  String waterhouse = "Waterhouse"; //JAMAICA
  //MARTINICA
  String usrobert = "U. S. Robert";
  String aiglon = "L'Aiglon du Lamentin";
  //GUADALUPE
  String moulien = "Moulien";
  //GUIANA
  String guayanais = "Guayanais";
  //PORTO RICO
  String puertoRico = "Puerto Rico Islanders";
  //REP. DOMINICANA
  String cibao = "Cibao";
  String omFC = "O&M FC";
  String pantoja = "CA Pantoja";
  //SURINAME
  String interMoengotapoe = "Inter Moengotapoe";
  String robinhood = "SV Robinhood";
  String transvaal = "Transvaal";
  //TRINIDAD & TOBAGO
  String centralFC = "Central FC";
  String connection = "Connection";
  String defenseforce = "Defense Force";
  String police = "Police FC";
  String stAnnRangers = "St. Ann's Rangers";
  String trintoc = "United Petrotrin";

  //////////////////////////////////////////////////////////////////////////////
  //ASIA
  //CHINA
  String beijingguoan = "Beijing Guoan";
  String chengfeng = "Beijing Chengfeng"; //1995-2021
  String chengdu = "Chengdu";
  String changchun = "Changchun Yatai";
  String dalian = "Dalian"; //1955-2012
  String jiangsu = "Jiangsu Suning"; //1958-2020
  String guangdong = "Guangdong Winnerway"; //EXTINTO
  String ghuangzhou = "Ghuangzhou";
  String hebei = "Hebei FC";
  String henan = "Henan S. Longmen";
  String liaoning = "Liaoning Hongyun";
  String meizhou = "Meizhou Hakka";
  String nantong = "Nantong Zhiyun";
  String qingdao = "Qingdao";
  String shandong = "Shandong Luneng";
  String shanghaisipg = "Shanghai SIPG";
  String shanghaishenhua = "Shanghai Shenhua";
  String shenzhen = "Shenzhen";
  String tianjin = "Tianjin Jinmen Tigers";
  String wuhan3towns = "Wuhan Three Towns";
  String wuhan = "Wuhan";
  String zhejiang = "Zhejiang";
  //HONG KONG
  String kitchee = "Kitchee";
  String easternSC = "Eastern SC";
  String leeMan = "Lee Man";
  //TAIWAN
  String tainanCity = "Tainan City";
  String taiPower = "Tai Power";


  //JAPAO
  String albirex = "Albirex Niigata";
  String avispa = "Avispa Fukuoka";
  String cerezoOsaka = "Cerezo Osaka";
  String fcTokyo = "FC Tokyo";
  String gambaOsaka = "Gamba Osaka";
  String jefUnited = "JEF United";
  String jubiloiwata = "Jubilo Iwata";
  String kashiwaReysol = "Kashiwa Reysol";
  String kawasakifrontale = "Kawasaki Frontale";
  String kashimaantlers = "Kashima Antlers";
  String kyoto = "Kyoto Sanga";
  String hiroshima = "Sanfrecce Hiroshima";
  String nagoya = "Nagoya Grampus";
  String sapporo = "Hokkaido Consadole Sapporo";
  String sagantosu = "Sagan Tosu";
  String shimizuSPulse = "Shimizu S-Pulse";
  String shonanbellmare = "Shonan Bellmare";
  String tokyoVerdy = "Tokyo Verdy";
  String urawareddiamonds = "Urawa Red Diamonds";
  String vegaltaSendai = "Vegalta Sendai";
  String visselkobe = "Vissel Kobe";
  String yokohamamarinos = "Yokohama F. Marinos";
  String yokohamaFC = "Yokohama FC";
  String flugels = "Yokohama Flügels"; //Merged 1998 to form Yokohama F. Marinos
  //COREIA
  String busan = "Busan";
  String daegu = "Daegu FC";
  String daejeon = "Daejeon Citizen";
  String jeju = "Jeju United";
  String jeonbuk = "Jeonbuk Hyundai";
  String jeonnam = "Jeonnam Dragons";
  String gangwon = "Gangwon FC";
  String gimcheon = "Gimcheon";
  String gyeongnam = "Gyeongnam FC";
  String gwangju = "Gwangju";
  String hallelujah = "Hallelujah FC"; //1980-1998
  String incheon = "Incheon United FC";
  String pohang = "Pohang Steelers";
  String fcseoul = "FC Seoul";
  String seongnam = "Seongnam";
  String suwonsamsung = "Suwon Samsung";
  String suwonFC = "Suwon FC";
  String ulsan = "Ulsan Hyundai";
  String koreaTungsten = "Korea Tungsten Company";//EXTINTO
  String rokArmy = "ROK Army";//EXTINTO
  String yangzee = "Yangzee";//EXTINTO

  //RESTO ASIA
  //BANGLADESH
  String bashundhara = "Bashundhara Kings";
  String dhakaAbahani = "Dhaka Abahani";
  String saif = "Saif";
  String sheikhJamal = "Sheikh Jamal";
  //BRUNEI
  String brunei = "Brunei DMPP";
  //CAMBOJA
  String boeungKet = "Boeung Ket";
  String nagaworld = "Nagaworld";
  String preahKhan = "Preah Khan Reach FC";
  String visakha = "Visakha";
  String phnomPenhCrown = "Phnom Penh Crown";
  //SINGAPORE
  String albirexSINGAPORE = "Albirex Niigata Singapore";
  String lionSitySailors = "Lion City Sailors";
  String tampines = "Tampines Rovers";
  String warriors = "Warriors";
  //INDIA
  String aizawl = "Aizawl";
  String bengaluru = "Bengaluru FC";
  String chennai = "Chennai City";
  String chennaiyin = "Chennaiyin";
  String churchill = "Churchill Brothers";
  String delhi = "Delhi Dynamos";
  String dempo = "Dempo";
  String goa = "FC Goa";
  String hyderabad = "Hyderabad";
  String jamshedpur = "Jamshedpur";
  String jct = "JCT";
  String kerala = "Kerala Blasters";
  String mahindra = "Mahindra United";
  String mohunBagan = "Mohun Bagan";
  String mumbai = "Mumbai City";
  String northeast = "Northeast United";
  String eastBengal = "SC East Bengal";
  String pune = "Pune City";
  String odisha = "Odisha FC";
  String salgaocar = "Salgaocar";
  String sportingGoa = "Sporting Goa";
  String vascoIND = "Vasco";
  String mysore = "Mysore State";//EXTINTO
  //INDONESIA
  String bali = "Bali United";
  String borneo = "Borneo";
  String palembang = "KTB Palembang";//EXTINTO 84-91
  String madura = "Madura United";
  String pelitaJaya = "Pelita Jaya";
  String persib = "Persib Bandung";
  String persebaya = "Persebaya Surabaya";
  String persipura = "Persipura Jayapura";
  String psmMakassar = "PSM Makassar";
  String psmsMedan = "PSMS Medan";
  //LAOS
  String chanthabouly = "Chanthabouly";
  String youngElephants = "Young Elephants";
  //MALASIA
  String johorDarul = "Johor Darul Ta'zim";
  String kedah = "Kedah Darul Aman";
  String kualaLumpur = "Kuala Lumpur";
  String federalTerritory = "Federal Territory";
  String penang = "Penang";
  String sabah = "Sabah";
  String sriPahang = "Sri Pahang";
  String selangor = "Selangor";
  //MALDIVES
  String maziya = "Maziya S&RC";
  //MONGOLIA
  String athletic220 = "Athletic 220";
  String erchim = "Khaan Khuns-Erchim";
  String khoromkhon = "Khoromkhon";
  String ulaanbaatar = "Ulaanbaatar City";
  //MYANMAR
  String ayeyawady = "Ayeyawady United";
  String shanUnited = "Shan United";
  String yadanarbon = "Yadanarbon";
  String yangon = "Yangon United";
  //NORTH KOREA
  String april25 = "April 25";
  String kigwancha = "Kigwancha";
  String pyongyang = "Pyongyang Sports Club";
  String ryomyong = "Ryomyong";
  //NEPAL
  String machhindra = "Machhindra";
  String manangMarshyangdi = "Manang Marshyangdi";
  String himalayan = "Himalayan Sherpa Club";
  String nepalPolice = "Nepal Police";
  //PHILIPPINNES
  String globalCebu = "Global Cebu";
  String kaya = "Kaya-Iloilo";
  String lionsPHI = "Lions FC";
  String maharlikaManila = "Maharlika Manila";
  String stallionLaguna = "Stallion Laguna";
  String unitedCity = "United City";
  // TAILANDIA
  String bangkok = "Bangkok United";
  String bangkokBank = "Bangkok Bank"; //1955-2008
  String buriram = "Buriram United";
  String chainat = "Chainat Hornbill";
  String chiangrai = "Chiangrai United";
  String chonburi = "Chonburi";
  String khonkaen = "Khonkaen United";
  String muangthong = "Muangthong United";
  String nakhon = "Nakhon Ratchasima";
  String nongbuaPitchaya = "Nongbua Pitchaya";
  String pattaya = "Pattaya United";
  String pathum = "Pathum United";
  String policeTero = "Police Tero";
  String portFC = "Port FC";
  String prachuap = "Prachuap";
  String ratchaburi = "Ratchaburi Mitr Phol";
  String thaiAirForce = "Royal Thai Air Force";
  String samutPrakan = "Samut Prakan City";
  String sinthana = "Sinthana";
  String sukhothai = "Sukhothai";
  String suphanburi = "Suphanburi";
  String thai = "Thai Farmers Bank"; //1987-2000
  String becToroSasana = "BEC Tero Sasana";
  //VIETNA
  String becamex = "Becamex Binh Duong";
  String danang = "Danang";
  String haiphong = "Haiphong";
  String hanoi = "Hanoi";
  String giaLai = "Hoàng Anh Gia Lai";
  String hochiminh = "Ho Chi Minh City";
  String quangNam = "Quang Nam";
  String thanhoa = "Thanh Hoa";
  String saigon = "Saigon";
  String songLam = "Song Lam Nghe An";
  String viettel = "Viettel";

  //ORIENTE MÉDIO
  //ARABIA SAUDITA
  String alnassr = "Al Nassr";
  String alahli = "Al Ahli";
  String alhilal = "Al Hilal";
  String alFaisalyARABIA = "Al-Faisaly";
  String alIttihad = "Al Ittihad";
  String alShabab = "Al Shabab";
  String alettifaq = "Al Ettifaq";
  String alfateh = "Al Fateh";
  String alQadisiya = "Al Qadisiya";
  String alraed = "Al Raed";
  String altaawoun = "Al Taawoun";
  String altai = "Al Tai";
  String damac = "Damac";
  //EAU
  String alain = "Al Ain-EAU";
  String aljazira = "Al Jazira";
  String alWahda = "Al Wahda";
  String alnasrEAU = "Al-Nasr Dubai";
  String alsharjah = "Al Sharjah";
  String alwasl = "Al Wasl";
  String ajman = "Ajman";
  String baniyas = "Baniyas";
  String shababalahli = "Shabab Al-Ahli";
  String alShababEAU = "Al Shabab Al Arabi";
  //QATAR
  String alduhail = "Al Duhail";
  String alsadd = "Al Sadd";
  String alahliQAT = "Al Ahli";
  String alarabi = "Al Arabi";
  String alrayyan = "Al Rayyan";
  String algharafa = "Al Gharafa";
  String alkhor = "Al Khor";
  String alwakrah = "Al Wakrah";
  String eljaish = "El-Jaish";
  String alsailiya = "Al-Sailiya";
  String qatar = "Qatar Sports Club";
  String ummSalal = "Umm Salal";
  //BAHREIN
  String alhidd = "Al-Hidd";
  String alMuharraq = "Al-Muharraq";
  String alRiffa = "Al-Riffa";
  String eastRiffa = "East Riffa";
  String manama = "Manama";
  //IRÃ
  String naftTehran = "Naft Tehran";
  String esteghlal = "Esteghlal";
  String esteghlalKhuzestan = "Esteghlal Khuzestan";
  String foolad = "Foolad";
  String pastehran = "Pas Tehran"; //EXTINTO
  String persepolis = "Persepolis";
  String saipa = "Saipa";
  String sepahan = "Sepahan";
  String tractor = "Tractor";
  String zobahan = "Zob Ahan";
  //IRAQUE
  String alzawraa = "Al-Zawraa";
  String alQuwaAlJawiya = "Al-Quwa Al-Jawiya";
  String alRasheed = "Al-Rasheed"; //EXTINTO
  String alTalaba = "Al-Talaba";
  String alShortaIRAQ = "Al-Shorta";
  //JORDANIA
  String alFaisalyJORD = "Al-Faisaly Amã";
  String alRamtha = "Al-Ramtha";
  String alSalt = "Al-Salt";
  String alWehdat = "Al-Wehdat";
  String shababAlOrdon = "Shabab Al-Ordon";
  //KUWAIT
  String alArabiKUW = "Al Arabi Kuwait";
  String alQadsia = "Al-Qadsia";
  String alKuwait = "Al-Kuwait";
  String kazma = "Kazma";
  //LEBANON
  String alAhed = "Al-Ahed";
  String alAnsar = "Al Ansar";
  String alSafa = "Al-Safa";
  String nejmeh = "Nejmeh";
  String homenetmen = "Homenetmen";
  String tripoliLEB = "TripoliLEB";
  //OMAN
  String alorouba = "Al Orouba";
  String alseeb = "Al Seeb";
  String alsuwaiq = "Al Suwaiq";
  String dhofar = "Dhofar Club";
  String fanja = "Fanja SC";
  String omanClub = "Oman Club";
  //PALESTINE
  String shababAlKhalil = "Shabab Al-Khalil";
  String hilalAlQuds = "Hilal Al-Quds";
  //SYRIA
  String alKaramah = "Al-Karamah";
  String alJaish = "Al-Jaish";
  String alWathba = "Al-Wathba";
  String alShortaDamascus = "Al Shorta Damascus";
  String aleppo = "Al-Ittihad Aleppo";
  String jableh = "Jableh";
  String tishreen = "Tishreen";

  //ASIA CENTRAL
  //KYRGYSTAN
  String algaBishkek = "Alga Bishkek";
  String abdyshAtaKant = "Abdysh-Ata Kant";
  String alay = "Alay";
  String dordoiBishkek = "Dordoi Bishkek";
  //TAJIKISTAN
  String pamirDushanbe = "CSKA Pamir Dushanbe";
  String istiklol = "Istiklol";
  String khujand = "Khujand";
  //TURCOMENISTAN
  String altynAsyr = "Altyn Asyr";
  String ahalAnew = "Ahal Änew";
  String nebitci = "Nebitçi";
  String nisaAshgabat = "Nisa Ashgabat";
  String kopetdag = "Köpetdag Aşgabat";
  String sagadam = "Şagadam";
  String yedigen = "Ýedigen Ashgabat";
  //UZBEQUISTAN
  String agmk = "AGMK Olmaliq";
  String bunyodkor = "Bunyodkor";
  String tashkent = "Lokomotiv Tashkent";
  String nasafQarshi = "Nasaf Qarshi";
  String neftchiFargona = "Neftchi Fargona";
  String pakhtakor = "Pakhtakor";
  String sogdiyona = "Sogdiyona Jizzakh";


  //////////////////////////////////////////////////////////////////////////////
  //OCEANIA
  //NEW ZEALAND
  String auckland = "Auckland City";
  String easternsuburbs = "Eastern Suburbs";
  String hamiltonWnaderers = "Hamilton Wanderers";
  String teamwellington = "Team Wellington"; //EXTINTO 2021
  String waitakere = "Waitakere United";
  String wellingtonphoenix = "Wellington Phoenix";

  //AUSTRALIA
  String adelaide = "Adelaide United";
  String brisbane = "Brisbane Roar";
  String centralcoast = "Central Coast Mariners";
  String macarthur = "Macarthur FC";
  String melbournecity = "Melbourne City";
  String melbournevictory = "Melbourne Victory";
  String newcastlejets = "Newcastle Jets";
  String perth = "Perth Glory";
  String sydneyFC = "Sydney FC";
  String sydneywanderers = "Sydney Wanderers";
  String westernunited = "Western United";

  String goldCoast = "Gold Coast";
  String queensland = "North Queensland Fury";

  //Antigos
  String sydneyOlympic = "Sydney Olympic";
  String sydneyUtd = "Sydney United";
  String brunswick = "Brunswick Juventus";
  String carlton = "Carlton";
  String maccabiHakoah = "Maccabi Hakoah Sydney City";
  String newZealandKnights = "New Zealand Knights";
  String wollongongWolves = "Wollongong Wolves";
  String southMelbourne = "South Melbourne";
  String melbourneKnights = "Melbourne Knights";
  String adelaideCity = "Adelaide City";
  String brisbaneStrikers = "Brisbane Strikers";
  String marconiStallions = "Marconi Stallions";
  String parramattaPower = "Parramatta Power";
  String prestonLions = "Preston Lions";
  String westAdelaide = "West Adelaide";
  String stGeorgeAUS = "St. George";
  String apiaLeichhardt = "APIA Leichhardt";

  //////////////////////////////////////////////////////////////////////////////
  //AFRICA

  //NORTE AFRICA
  //EGYPT
  String alahly = "Al Ahly";
  String zamalek = "Zamalek";
  String alexandria = "Al Ittihad Alexandria";
  String almasry = "Al Masry";
  String almokawloon = "Al Mokawloon";
  String cleopatra = "Ceramica Cleopatra";
  String elgaish = "El Gaish";
  String elmansoura = "El Mansoura";
  String elolympi = "El Olympi";
  String enppi = "ENPPI";
  String ghazl = "Ghazl El-Mehalla";
  String haras = "Haras El Hodoud";
  String ismaily = "Ismaily";
  String future = "Future FC";
  String makkasa = "Misr Lel Makkasa";
  String petrojet = "Petrojet";
  String pyramids = "Pyramids";
  String smouha = "Smouha";
  String tersana = "Tersana";
  //ARGELIA
  String saoura = "JS Saoura";
  String asoChlef = "ASO Chlef";
  String essetif = "ES Sétif";//ALGERIA
  String belouizdad = "Belouizdad";//ALGERIA
  String constantine = "CS Constantine";//ALGERIA
  String usmAlger = "USM Alger";//ALGERIA
  String mcalger = "MC Alger";//ALGERIA
  String elEulma = "MC El-Eulma";//ALGERIA
  String mcOran = "MC Oran";//ALGERIA
  String kabylie = "JS Kabylie";//ALGERIA
  //LYBIA
  String benghazi = "Al Ahly Benghazi";//LIBYA
  String alakhdar = "Al Akhdar";//LIBYA
  String alNasrLIB = "Al Nasr-LIB";//LIBYA
  String alIttihadLIB = "Al Ittihad-LIB";//LIBYA
  String tripoliLIB = "Al Ahly Tripoli";//LIBYA
  //MARROCOS
  String difaa = "Beni Mellal";
  String beniMellal = "Difaa El Jadida";
  String chababMohammedia = "Chabab Mohammédia";
  String chababRifHoceima = "Chabab Rif Hoceima";
  String rajacasablanca = "Raja Casablanca";
  String wydad = "Wydad Casablanca";//MARROCOS
  String farRabat = "FAR Rabat";//MARROCOS
  String fusRabat = "FUS Rabat";
  String jeunesseMassira = "Jeunesse Massira";
  String hassaniaAgadir = "Hassania Agadir";
  String irTanger = "IR Tanger";
  String kenitra = "KAC Kenitra";
  String khemisset = "IZK Khemisset";
  String kawkab = "Kawkab Marrakech";
  String meknes = "CODM de Meknès";
  String moulodiaOujda = "Mouloudia Oujda";
  String oCasablanca = "Olympique Casablanca";
  String sale = "AS Salé";
  String safi = "Olympique Safi";
  String khouribga = "Olympique Khouribga";
  String renBerkane = "Renaissance de Berkane";
  String settat = "Renaissance de Settat";
  String racingCasablanca = "Racing de Casablanca";
  String maghreb = "Maghreb de Fès";//MARROCOS
  String moghrebTetouan = "Moghreb de Tétouan";//MARROCOS
  //TUNISI
  String bizertin = "Bizertin";//TUNISIA
  String clubAfricain = "Club Africain";//TUNISIA
  String transports = "CO Transports";//TUNISIA
  String esperance = "Espérance de Tunis";//TUNISIA
  String etoilesahel = "Étoile du Sahel";//TUNISIA
  String jskairouan = "JS Kairouan";//TUNISIA
  String monastir = "US Monastir";//TUNISIA
  String sfaxien = "Sfaxien";//TUNISIA
  String sfax = "Sfax Railway Sports";//TUNISIA
  String stadeTunisien = "Stade Tunisien";//TUNISIA

  //AFRICA NEGRA
  String amazulu = "AmaZulu FC";
  String baroka = "Baroka";
  String bidvestWits = "Bidvest Wits";
  String blackLeopards = "Black Leopards";
  String capetown = "Cape Town City";
  String capetownAjax = "Cape Town Spurs";
  String chippa = "Chippa United";
  String goldenarrows = "Golden Arrows";
  String freestate = "Free State Stars";
  String highlandspark = "Highlands Park";
  String kaizer = "Kaizer Chiefs";
  String mamelodi = "Mamelodi Sundowns";
  String marumo = "Marumo Gallants";
  String manningRangers = "Manning Rangers";
  String maritzburg = "Maritzburg United";
  String morokaSwallows = "Moroka Swallows";
  String mpulamanga = "Mpulamanga Black Aces";
  String orlandopirates = "Orlando Pirates";
  String platinumAFS = "Platinum Stars";
  String polokwane = "Polokwane";
  String pretoria = "Pretoria University";
  String royalAM = "Royal AM";
  String santosAfrica = "Santos";
  String sekhukhune = "Sekhukhune United";
  String stellenbosch = "Stellenbosch";
  String supersport = "Supersport United";
  String tsgalaxy = "TS Galaxy";
  //ANGOLA
  String agosto = "1º de Agosto";
  String huilaANG = "Huila";
  String aviacao = "Atlético Sport Aviação";
  String petroluanda = "Petro de Luanda";//ANGOLA
  String sagradaesperanca = "Sagrada Esperança";//ANGOLA
  String interclube = "Interclube";//ANGOLA
  String libolo = "Libolo";//ANGOLA
  String sptCabinda = "Sporting Cabinda";//ANGOLA
  //BOTSWANA
  String jwanengGalaxy = "Jwaneng Galaxy FC";
  String gaborone = "Gaborone United";
  String mochudi = "Mochudi Centre Chiefs";
  String orapa = "Orapa United";
  String township = "Township Rollers";
  //CAMARÕES
  String bafoussam = "Bafoussam";
  String cotonsport = "Cotonsport";
  String canonYaounde = "Canon Yaoundé";//CAMARÕES
  String leopardsCAM = "Léopards";//CAMARÕES
  String oryx = "Oryx";//CAMARÕES
  String douala = "Union Douala";//CAMARÕES
  String loum = "USM de Loum";//CAMARÕES
  String sable = "Sable FC";
  String tonnerre = "Tonnerre";//CAMARÕES
  //CAPE VERDE
  String mindelense = "Mindelense";
  String sptClubePraia = "Sporting Clube da Praia";
  //CENTRAL AFRICAN REPUBLIC
  String dfc8 = "DFC 8";
  String bangui = "Olympic Real de Bangui";
  String tempeteMocaf = "Tempête Mocaf";
  //CONGO
  String caraBrazaville = "Cara Brazzaville";
  String diablesNoirs = "Diables Noirs";//CONGO
  String leopardsCON = "AC Léopards";//CONGO
  String otoho = "Otohô";//CONGO
  String talangai = "Talangai";//CONGO
  //RD CONGO
  String dragons = "Dragons";
  String lupopo = "Saint-Éloi Lupopo";//RD CONGO
  String mazembe = "Mazembe";//RD CONGO
  String motema = "Motema Pembe";//RD CONGO
  String vita = "Vita Club";//RD CONGO
  String maniema = "Maniema Union";//RD CONGO
  //COSTA DO MARFIM
  String asecmimosas = "ASEC Mimosas";
  String africaSports = "Africa Sports";//COSTA DO MARFIM
  String gagnoa = "Gagnoa";//COSTA DO MARFIM
  String omnisport = "Omnisport";//COSTA DO MARFIM
  String sanPedro = "San Pedro";//COSTA DO MARFIM
  String seweSport = "Séwé Sport";//COSTA DO MARFIM
  String stadeDAbidjan = "Stade d'Abidjan";//COSTA DO MARFIM
  //ETHIOPIA
  String fasil = "Fasil Kenema";
  String stGeorge = "Saint George";
  //GABON
  String bitam = "Bitam";
  String cercleMberi = "Cercle Mbéri Sportif";
  String libreville = "Libreville";
  String mangasport = "Mangasport";
  String mbilinga = "Mbilinga";
  String mounana = "Mounana";
  String sogara = "Sogara";
  //GAMBIA
  String gamtel = "GAMTEL";
  String fortuneFC = "Fortune FC";
  String brikama = "Brikama United";
  String realBanjul = "Real de Banjul";
  //GANA
  String asantekotoko = "Asante Kotoko";
  String ashantiGold = "Ashanti Gold";
  String berekum = "Berekum Chelsea";
  String greatOlympics = "Great Olympics";
  String heartsoak = "Hearts Of Oak";
  String obuasi = "Obuasi Goldfields";
  //GUINÉ
  String hafia = "Hafia FC";
  String horoya = "Horoya";
  String kaloum = "Kaloum Star";
  //KHENYA
  String bandare = "Bandare";
  String gorMahia = "Gor Mahia";
  String kakamega = "Kakamega Homeboyz";
  String leopardsQUE = "Leopards";
  String mathare = "Mathare United";
  String tusker = "Tusker";
  String ulinzi = "Ulinzi Stars";
  //MADAGASCAR
  String adema = "AS Adema";
  String cnapsSport = "CNaPS Sport";
  //MALAWI
  String bakiliBullets = "Bakili Bullets";
  //MALI
  String djoliba = "Djoliba";
  String realBamako = "Real Bamako";
  String stadeMalien = "Stade Malien";
  //MAURITANIA
  String nouadhibou = "Nouadhibou";
  String tevraghZeina = "Tevragh-Zeina";
  //MOZAMBIQUE
  String blackBulls = "Black Bulls";
  String costaDoSol = "Costa do Sol";
  String ferroviarioMOZ = "Ferroviario-MOZ";
  String ldMaputo = "Liga Desportiva de Maputo";
  //NAMIBIA
  String blackAfrica = "Black Africa";
  String africanStars = "African Stars";
  String civics = "Civics";
  //NIGERIA
  String akwa = "Akwa United";
  String bayelsa = "Bayelsa United";
  String bendel = "Bendel Insurance";
  String dolphin = "Dolphin FC";
  String enyimba = "Enyimba";
  String heartland = "Heartland";
  String juliusBerger = "Julius Berger";
  String ifeanyi = "Ifeanyi Ubah";
  String kano = "Kano Pillars";
  String kwaraUtd = "Kwara Utd";
  String lobiStars = "Lobi Stars";
  String mfm = "MFM FC";
  String nasarawa = "Nasarawa United";
  String nigerTornadoes = "Niger Tornadoes";
  String oceanBoys = "Ocean Boys";
  String rangersInt = "Enugu Rangers International";
  String plateau = "Plateau United";
  String remoStars = "Remo Stars";
  String riversUtd = "Rivers United";
  String stationeryStores = "Stationery Stores";
  String shootingstars = "Shooting Stars";
  String sunshinestars = "Sunshine Stars";
  String warriWolves = "Warri Wolves";
  String wikki = "Wikki Tourist";
  //RWANDA
  String apr = "APR";
  String rayonSports = "RayonSports";
  //SENEGAL
  String douanes = "AS Douanes";
  String diaraf = "Diaraf";
  String genefoot = "Gene Foot";
  String goree = "Gorée";
  String jaraaf = "Jaraaf";
  String jeannedarc = "Jeanne D'Arc";
  String teungueth = "Teungueth";
  //SUDÃO
  String omdurman = "Al-Hilal Omdurman";
  String almerrikh = "Al-Merrikh";
  //TANZANIA
  String simba = "Simba";
  String yanga = "Young Africans";
  //TOGO
  String askoKara = "ASKO Kara";
  String etoileFilante = "Étoile Filante";
  String lome = "Lomé I";
  String semassi = "Semassi";
  //UGANDA
  String express = "Express FC";
  String kampala = "Kampala Capital City";
  String villa = "Villa";
  String vipers = "Vipers SC";
  //ZAMBIA
  String greenEagles = "Green Eagles";
  String nkana = "Nkana";//ZAMBIA
  String mufulira = "Mufulira Wanderers";//ZAMBIA
  String redArrows = "Red Arrows";//ZAMBIA
  String zesco = "Zesco United";//ZAMBIA
  //ZIMBABWE
  String chickenInn = "Chicken Inn";
  String dynamos = "Dynamos FC"; //ZIMBABWE
  String manicaDiamonds = "Manica Diamonds"; //ZIMBABWE
  String monomotapa = "Monomotapa United"; //ZIMBABWE
  String platinum = "FC Platinum"; //ZIMBABWE
 //ISLES SAINT REUNION
  String saintLouisienne = "Saint-Louisienne";

}
