import 'package:fifa/values/club_names.dart';
import 'package:fifa/values/league_names.dart';


ClubName _clubName = ClubName();

  Map mapChampions(String leagueName){
    Map champions = {};
    if(leagueName == LeagueOfficialNames().inglaterra1){
      champions = {
        2021: [_clubName.manchestercity,_clubName.manchesterunited,_clubName.liverpool,_clubName.chelsea],
        2020: [_clubName.liverpool,_clubName.manchestercity,_clubName.manchesterunited,_clubName.chelsea],
        2019: [_clubName.manchestercity,_clubName.liverpool,_clubName.chelsea,_clubName.tottenham],
        2018: [_clubName.manchestercity,_clubName.manchesterunited,_clubName.tottenham,_clubName.liverpool],
        2017: [_clubName.chelsea,_clubName.tottenham,_clubName.manchestercity,_clubName.liverpool],
        2016: [_clubName.leicester,_clubName.arsenal,_clubName.tottenham,_clubName.manchestercity],
        2015: [_clubName.chelsea,_clubName.manchestercity,_clubName.arsenal,_clubName.manchesterunited],
        2014: [_clubName.manchestercity,_clubName.liverpool,_clubName.chelsea,_clubName.arsenal],
        2013: [_clubName.manchesterunited,_clubName.manchestercity,_clubName.chelsea,_clubName.arsenal],
        2012: [_clubName.manchestercity,_clubName.manchesterunited,_clubName.arsenal,_clubName.tottenham],
        2011: [_clubName.manchesterunited,_clubName.chelsea,_clubName.manchestercity,_clubName.arsenal],
        2010: [_clubName.chelsea,_clubName.manchesterunited,_clubName.arsenal,_clubName.tottenham],
        2009: [_clubName.manchesterunited,_clubName.liverpool,_clubName.chelsea,_clubName.arsenal],
        2008: [_clubName.manchesterunited,_clubName.chelsea,_clubName.arsenal,_clubName.liverpool],
        2007: [_clubName.manchesterunited,_clubName.chelsea,_clubName.liverpool,_clubName.arsenal],
        2006: [_clubName.chelsea,_clubName.manchesterunited,_clubName.liverpool,_clubName.arsenal],
        2005: [_clubName.chelsea,_clubName.arsenal,_clubName.manchesterunited,_clubName.everton],
        2004: [_clubName.arsenal,_clubName.chelsea,_clubName.manchesterunited,_clubName.liverpool],
        2003: [_clubName.manchesterunited,_clubName.arsenal,_clubName.newcastle,_clubName.chelsea],
        2002: [_clubName.arsenal,_clubName.liverpool,_clubName.manchesterunited,_clubName.newcastle],
        2001: [_clubName.manchesterunited,_clubName.arsenal,_clubName.liverpool,_clubName.leedsunited],
        2000: [],
      };
    }
    if(leagueName == LeagueOfficialNames().inglaterra2){
      champions = {
        2021: [_clubName.norwich],
        2020: [_clubName.leedsunited],
        2019: [_clubName.norwich],
        2018: [_clubName.wolves],
        2017: [_clubName.newcastle],
        2016: [_clubName.burnley],
        2015: [_clubName.bournemouth],
        2014: [_clubName.leicester],
        2013: [],
        2012: [_clubName.reading],
        2011: [_clubName.qpr],
        2010: [_clubName.newcastle],
        2009: [_clubName.wolves],
        2008: [_clubName.westbromwich],
        2007: [_clubName.sunderland],
        2006: [_clubName.reading],
        2005: [_clubName.sunderland],
        2004: [_clubName.norwich],
        2003: [_clubName.portsmouth],
        2002: [_clubName.manchestercity],
        2001: [_clubName.fulham],
        2000: [],
      };
    }
    if(leagueName == LeagueOfficialNames().espanha1){
      champions = {
        //2022: [_clubName.realmadrid,_clubName.sevilla],
        2021: [_clubName.atleticomadrid,_clubName.realmadrid,_clubName.barcelona,_clubName.sevilla,_clubName.realsociedad,_clubName.realbetis,_clubName.villareal,_clubName.athleticbilbao],
        2020: [_clubName.realmadrid,_clubName.barcelona,_clubName.atleticomadrid,_clubName.sevilla,_clubName.villareal,_clubName.realsociedad],
        2019: [_clubName.barcelona,_clubName.atleticomadrid,_clubName.realmadrid,_clubName.valencia,_clubName.getafe,_clubName.realsociedad],
        2018: [_clubName.barcelona,_clubName.atleticomadrid,_clubName.realmadrid,_clubName.valencia,_clubName.villareal,_clubName.realbetis],
        2017: [_clubName.realmadrid,_clubName.barcelona,_clubName.atleticomadrid,_clubName.sevilla,_clubName.villareal,_clubName.realsociedad],
        2016: [_clubName.barcelona,_clubName.realmadrid,_clubName.atleticomadrid,_clubName.villareal,_clubName.athleticbilbao,_clubName.celtavigo],
        2015: [_clubName.barcelona,_clubName.realmadrid,_clubName.atleticomadrid,_clubName.valencia,_clubName.sevilla,_clubName.villareal],
        2014: [_clubName.atleticomadrid,_clubName.barcelona,_clubName.realmadrid,_clubName.athleticbilbao,_clubName.sevilla,_clubName.villareal],
        2013: [_clubName.barcelona,_clubName.realmadrid,_clubName.atleticomadrid,_clubName.realsociedad],
        2012: [_clubName.realmadrid,_clubName.barcelona,_clubName.valencia,_clubName.malaga],
        2011: [_clubName.barcelona,_clubName.realmadrid,_clubName.valencia,_clubName.villareal],
        2010: [_clubName.barcelona,_clubName.realmadrid,_clubName.valencia,_clubName.sevilla],
        2009: [_clubName.barcelona,_clubName.realmadrid,_clubName.sevilla,_clubName.atleticomadrid],
        2008: [_clubName.realmadrid,_clubName.villareal,_clubName.barcelona,_clubName.atleticomadrid],
        2007: [_clubName.realmadrid,_clubName.barcelona,_clubName.sevilla,_clubName.valencia],
        2006: [_clubName.barcelona,_clubName.realmadrid,_clubName.valencia,_clubName.osasuna],
        2005: [_clubName.barcelona,_clubName.realmadrid,_clubName.villareal,_clubName.realbetis],
        2004: [_clubName.valencia,_clubName.barcelona,_clubName.lacoruna,_clubName.realmadrid],
        2003: [_clubName.realmadrid,_clubName.realsociedad,_clubName.lacoruna,_clubName.celtavigo],
        2002: [_clubName.valencia,_clubName.lacoruna,_clubName.realmadrid,_clubName.barcelona],
        2001: [_clubName.realmadrid,_clubName.lacoruna,_clubName.mallorca,_clubName.barcelona],
        2000: [],
      };
    }
    if(leagueName == LeagueOfficialNames().italia1){
      champions = {
        2021: [_clubName.inter,_clubName.milan,_clubName.atalanta,_clubName.juventus,_clubName.napoli,_clubName.lazio,_clubName.roma,_clubName.sassuolo,_clubName.sampdoria],
        2020: [_clubName.juventus,_clubName.inter,_clubName.lazio,_clubName.atalanta,_clubName.roma],
        2019: [_clubName.juventus,_clubName.napoli,_clubName.atalanta,_clubName.inter,_clubName.milan],
        2018: [_clubName.juventus,_clubName.napoli,_clubName.roma,_clubName.inter,_clubName.lazio],
        2017: [_clubName.juventus,_clubName.roma,_clubName.napoli,_clubName.atalanta,_clubName.lazio],
        2016: [_clubName.juventus,_clubName.napoli,_clubName.roma,_clubName.inter,_clubName.fiorentina],
        2015: [_clubName.juventus,_clubName.roma,_clubName.lazio,_clubName.fiorentina],
        2014: [_clubName.juventus,_clubName.roma,_clubName.napoli,_clubName.fiorentina],
        2013: [_clubName.juventus,_clubName.napoli,_clubName.milan,_clubName.fiorentina],
        2012: [_clubName.juventus,_clubName.milan,_clubName.udinese,_clubName.lazio],
        2011: [_clubName.milan,_clubName.inter,_clubName.napoli,_clubName.udinese],
        2010: [_clubName.inter,_clubName.roma,_clubName.milan,_clubName.sampdoria],
        2009: [_clubName.inter,_clubName.juventus,_clubName.milan,_clubName.fiorentina],
        2008: [_clubName.inter,_clubName.roma,_clubName.juventus,_clubName.fiorentina],
        2007: [_clubName.inter,_clubName.roma,_clubName.lazio],
        2006: [_clubName.inter,_clubName.roma,_clubName.milan],
        2005: [],
        2004: [_clubName.milan,_clubName.roma,_clubName.juventus],
        2003: [_clubName.juventus,_clubName.inter,_clubName.milan],
        2002: [_clubName.juventus,_clubName.roma,_clubName.inter],
        2001: [_clubName.roma,_clubName.juventus,_clubName.lazio],
        2000: [],
      };
    }
    if(leagueName == LeagueOfficialNames().alemanha1){
      champions = {
        2021: [_clubName.bayernmunique,_clubName.rbleipzig,_clubName.borussiadortmund,_clubName.wolfsburg],
        2020: [_clubName.bayernmunique,_clubName.borussiadortmund,_clubName.rbleipzig,_clubName.moenchengladbach],
        2019: [_clubName.bayernmunique,_clubName.borussiadortmund,_clubName.rbleipzig,_clubName.bayerleverkusen],
        2018: [_clubName.bayernmunique,_clubName.schalke04,_clubName.hoffenheim,_clubName.borussiadortmund],
        2017: [_clubName.bayernmunique,_clubName.rbleipzig,_clubName.borussiadortmund,_clubName.hoffenheim],
        2016: [_clubName.bayernmunique,_clubName.borussiadortmund,_clubName.bayerleverkusen,_clubName.moenchengladbach],
        2015: [_clubName.bayernmunique,_clubName.wolfsburg,_clubName.moenchengladbach,_clubName.bayerleverkusen],
        2014: [_clubName.bayernmunique,_clubName.borussiadortmund,_clubName.schalke04,_clubName.bayerleverkusen],
        2013: [_clubName.bayernmunique,_clubName.borussiadortmund,_clubName.bayerleverkusen,_clubName.schalke04],
        2012: [_clubName.borussiadortmund,_clubName.bayernmunique,_clubName.schalke04,_clubName.moenchengladbach],
        2011: [_clubName.borussiadortmund,_clubName.bayerleverkusen,_clubName.bayernmunique],
        2010: [_clubName.bayernmunique,_clubName.schalke04,_clubName.werderbremen],
        2009: [_clubName.wolfsburg,_clubName.bayernmunique,_clubName.stuttgart],
        2008: [_clubName.bayernmunique,_clubName.werderbremen],
        2007: [_clubName.stuttgart,_clubName.schalke04],
        2006: [_clubName.bayernmunique,_clubName.werderbremen],
        2005: [_clubName.bayernmunique,_clubName.schalke04],
        2004: [_clubName.werderbremen,_clubName.bayernmunique],
        2003: [_clubName.bayernmunique,_clubName.stuttgart],
        2002: [_clubName.borussiadortmund,_clubName.bayerleverkusen],
        2001: [_clubName.bayernmunique,_clubName.schalke04],
        2000: [],
      };
    }
    if(leagueName == LeagueOfficialNames().franca1){
      champions = {
        2021: [_clubName.lille,_clubName.psg,_clubName.monaco,_clubName.lyon],
        2020: [_clubName.psg,_clubName.olympiquemarselha,_clubName.rennes,_clubName.lille],
        2019: [_clubName.psg,_clubName.lille,_clubName.lyon,_clubName.saintetienne],
        2018: [_clubName.psg,_clubName.monaco,_clubName.lyon,_clubName.olympiquemarselha],
        2017: [_clubName.monaco,_clubName.psg,_clubName.nice,_clubName.lyon],
        2016: [_clubName.psg,_clubName.lyon],
        2015: [_clubName.psg,_clubName.lyon],
        2014: [_clubName.psg,_clubName.monaco],
        2013: [_clubName.psg,_clubName.olympiquemarselha],
        2012: [_clubName.montpellier,_clubName.psg],
        2011: [_clubName.lille,_clubName.olympiquemarselha],
        2010: [_clubName.olympiquemarselha],
        2009: [_clubName.bordeaux,_clubName.olympiquemarselha],
        2008: [_clubName.lyon,_clubName.bordeaux],
        2007: [_clubName.lyon,_clubName.olympiquemarselha],
        2006: [_clubName.lyon,_clubName.bordeaux],
        2005: [_clubName.lyon,_clubName.lille],
        2004: [_clubName.lyon,_clubName.psg],
        2003: [_clubName.lyon,_clubName.monaco],
        2002: [_clubName.lyon,_clubName.lens],
        2001: [_clubName.nantes,_clubName.lyon],
        2000: [],
      };
    }
    if(leagueName == LeagueOfficialNames().brasil1){
      champions = {
        2021: [_clubName.atleticomg,_clubName.flamengo,_clubName.palmeiras,_clubName.fortaleza,_clubName.corinthians,_clubName.bragantino,_clubName.fluminense,_clubName.americamg,_clubName.atleticogo,_clubName.santos],
        2020: [_clubName.flamengo,_clubName.internacional,_clubName.atleticomg,_clubName.saopaulo,_clubName.fluminense,_clubName.palmeiras,_clubName.gremio,_clubName.santos,_clubName.atleticopr,_clubName.bragantino],
        2019: [_clubName.flamengo,_clubName.santos,_clubName.palmeiras,_clubName.gremio,_clubName.atleticopr,_clubName.saopaulo,_clubName.internacional,_clubName.corinthians,_clubName.fortaleza,_clubName.goias],
        2018: [_clubName.palmeiras,_clubName.flamengo,_clubName.internacional,_clubName.gremio,_clubName.saopaulo,_clubName.atleticomg,_clubName.atleticopr,_clubName.cruzeiro,_clubName.botafogo,_clubName.santos],
        2017: [_clubName.corinthians,_clubName.palmeiras,_clubName.gremio,_clubName.saopaulo],
        2016: [_clubName.palmeiras,_clubName.flamengo,_clubName.santos,_clubName.atleticomg],
        2015: [_clubName.corinthians,_clubName.atleticomg,_clubName.gremio,_clubName.saopaulo],
        2014: [_clubName.cruzeiro,_clubName.saopaulo,_clubName.internacional,_clubName.corinthians],
        2013: [_clubName.cruzeiro,_clubName.gremio,_clubName.atleticopr,_clubName.botafogo],
        2012: [_clubName.fluminense,_clubName.atleticomg,_clubName.gremio,_clubName.saopaulo],
        2011: [_clubName.corinthians,_clubName.vasco,_clubName.fluminense,_clubName.flamengo],
        2010: [_clubName.fluminense,_clubName.cruzeiro,_clubName.corinthians,_clubName.gremio],
        2009: [_clubName.flamengo,_clubName.internacional,_clubName.saopaulo,_clubName.cruzeiro],
        2008: [_clubName.saopaulo,_clubName.gremio,_clubName.cruzeiro,_clubName.palmeiras],
        2007: [_clubName.saopaulo,_clubName.santos,_clubName.flamengo,_clubName.fluminense],
        2006: [_clubName.saopaulo,_clubName.internacional,_clubName.gremio,_clubName.santos],
        2005: [_clubName.corinthians,_clubName.internacional,_clubName.goias,_clubName.palmeiras],
        2004: [_clubName.santos,_clubName.atleticopr,_clubName.saopaulo,_clubName.palmeiras],
        2003: [_clubName.cruzeiro,_clubName.santos,_clubName.saopaulo],
        2002: [_clubName.santos,_clubName.corinthians,_clubName.gremio,_clubName.fluminense],
        2001: [_clubName.atleticopr,_clubName.alahly,_clubName.fluminense,_clubName.atleticomg],
        2000: [_clubName.vasco,_clubName.alahly,_clubName.cruzeiro,_clubName.gremio],
        1999: [_clubName.corinthians,_clubName.atleticomg,_clubName.vitoria,_clubName.saopaulo],
        1998: [_clubName.corinthians,_clubName.cruzeiro,_clubName.santos,_clubName.portuguesa],
        1997: [_clubName.vasco,_clubName.palmeiras,_clubName.internacional,_clubName.atleticomg],
        1996: [_clubName.gremio,_clubName.portuguesa,_clubName.atleticomg,_clubName.goias],
        1995: [_clubName.botafogo,_clubName.santos,_clubName.cruzeiro,_clubName.fluminense],
        1994: [_clubName.palmeiras,_clubName.corinthians,_clubName.guarani,_clubName.atleticomg],
        1993: [_clubName.palmeiras,_clubName.vitoria,_clubName.corinthians,_clubName.saopaulo],
        1992: [_clubName.flamengo,_clubName.botafogo,_clubName.vasco,_clubName.bragantino],
        1991: [_clubName.saopaulo,_clubName.bragantino,_clubName.atleticomg,_clubName.fluminense],
        1990: [_clubName.corinthians,_clubName.saopaulo,_clubName.gremio,_clubName.bahia],
        1989: [_clubName.vasco,_clubName.saopaulo],
        1988: [_clubName.bahia,_clubName.internacional],
        1987: [_clubName.sport,_clubName.guarani],
        1986: [_clubName.saopaulo,_clubName.guarani],
        1985: [_clubName.coritiba],
        1984: [_clubName.fluminense,_clubName.vasco],
        1983: [_clubName.flamengo],
        1982: [_clubName.flamengo],
        1981: [_clubName.gremio],
        1980: [_clubName.flamengo],
        1979: [_clubName.internacional],
        1978: [_clubName.guarani],
        1977: [_clubName.saopaulo],
        1976: [_clubName.internacional],
        1975: [_clubName.internacional],
        1974: [_clubName.vasco],
        1973: [_clubName.palmeiras],
        1972: [_clubName.palmeiras],
        1971: [_clubName.atleticomg],
        1970: [_clubName.fluminense],
        1969: [_clubName.palmeiras],
        1968: [_clubName.santos],
        1967: [_clubName.palmeiras],
      };
    }
    if(leagueName == LeagueOfficialNames().brasil2){
      champions = {
        2021: [_clubName.botafogo,_clubName.goias],
        2020: [_clubName.chapecoense,_clubName.americamg],
        2019: [_clubName.bragantino,_clubName.sport],
        2018: [_clubName.fortaleza,_clubName.csa],
        2017: [_clubName.americamg,_clubName.internacional],
        2016: [_clubName.atleticogo,_clubName.avai],
        2015: [_clubName.botafogo,_clubName.santacruz],
        2014: [],
        2013: [_clubName.palmeiras,_clubName.chapecoense],
        2012: [_clubName.goias,_clubName.criciuma],
        2011: [_clubName.portuguesa,_clubName.nautico],
        2010: [_clubName.coritiba,_clubName.figueirense],
        2009: [_clubName.vasco,_clubName.guarani],
        2008: [_clubName.corinthians],
        2007: [_clubName.coritiba],
        2006: [_clubName.atleticomg,_clubName.sport],
        2005: [_clubName.gremio,_clubName.santacruz],
        2004: [],
        2003: [_clubName.palmeiras,_clubName.botafogo],
        2002: [_clubName.criciuma,_clubName.fortaleza],
        2001: [_clubName.paysandu,_clubName.figueirense],
        2000: [_clubName.parana],
      };
    }
    if(leagueName == LeagueOfficialNames().brasil3){
      champions = {
        2021: [_clubName.ituano],
        2020: [_clubName.vilaNova],
        2019: [_clubName.nautico],
        2018: [_clubName.operarioPR],
        2017: [_clubName.csa],
        2016: [],
        2015: [_clubName.vilaNova],
        2014: [],
        2013: [_clubName.santacruz],
        2012: [],
        2011: [],
        2010: [_clubName.abc],
        2009: [],
        2008: [_clubName.atleticogo],
        2007: [_clubName.bragantino],
        2006: [_clubName.criciuma],
        2005: [_clubName.remo],
        2004: [],
        2003: [_clubName.ituano],
        2002: [],
        2001: [],
        2000: [],
        1999: [_clubName.fluminense],
        1998: [_clubName.avai],
        1997: [_clubName.sampaio],
      };
    }
    if(leagueName == LeagueOfficialNames().argentina){
      champions = {
        2021: [_clubName.riverplate,_clubName.defensayjusticia,_clubName.talleres,_clubName.bocajuniors],
        2020: [_clubName.bocajuniors,_clubName.riverplate,_clubName.velezsarsfield,_clubName.racing],
        2019: [_clubName.racing,_clubName.defensayjusticia,_clubName.bocajuniors,_clubName.riverplate],
        2018: [_clubName.bocajuniors],
        2017: [_clubName.bocajuniors,_clubName.riverplate],
        2016: [_clubName.lanus,_clubName.sanlorenzo],
        2015: [_clubName.bocajuniors,_clubName.sanlorenzo],
        2014: [_clubName.racing,_clubName.riverplate],
        2013: [],
        2012: [],
        2011: [],
        2010: [],
        2009: [],
        2008: [],
        2007: [],
        2006: [],
        2005: [],
        2004: [],
        2003: [],
        2002: [],
        2001: [],
        2000: [],
      };
    }

    if(leagueName == LeagueOfficialNames().estadosUnidos){
      champions = {
        2021: [_clubName.nycity,_clubName.portland],
        2020: [_clubName.columbuscrew,_clubName.seattle],
        2019: [_clubName.seattle,_clubName.torontofc],
        2018: [_clubName.atlantaunited,_clubName.portland],
        2017: [_clubName.torontofc,_clubName.seattle],
        2016: [_clubName.seattle,_clubName.torontofc],
        2015: [_clubName.portland,_clubName.columbuscrew],
        2014: [_clubName.lagalaxy,_clubName.nerevolution],
        2013: [],
        2012: [_clubName.lagalaxy],
        2011: [_clubName.lagalaxy],
        2010: [],
        2009: [],
        2008: [_clubName.columbuscrew],
        2007: [],
        2006: [],
        2005: [_clubName.lagalaxy,_clubName.nerevolution],
        2004: [_clubName.dcunited],
        2003: [],
        2002: [],
        2001: [],
        2000: [],
      };
    }
    if(leagueName == LeagueOfficialNames().asia){
      champions = {
        2021: [_clubName.alhilal],
        2020: [_clubName.ulsan,_clubName.persepolis],
        2019: [_clubName.alhilal,_clubName.urawareddiamonds],
        2018: [_clubName.kashimaantlers,_clubName.persepolis],
        2017: [_clubName.urawareddiamonds,_clubName.alhilal],
        2016: [_clubName.jeonbuk,_clubName.alain],
        2015: [_clubName.ghuagzhouevergrande,_clubName.alahli],
        2014: [],
        2013: [_clubName.ghuagzhouevergrande,_clubName.fcSeoul],
        2012: [_clubName.ulsan,_clubName.alahli],
        2011: [_clubName.alsadd,_clubName.jeonbuk],
        2010: [],
        2009: [_clubName.pohang,_clubName.alIttihad],
        2008: [_clubName.gambaOsaka],
        2007: [_clubName.urawareddiamonds],
        2006: [_clubName.jeonbuk],
        2005: [_clubName.alIttihad],
        2004: [_clubName.alIttihad],
        2003: [_clubName.alain],
        2002: [_clubName.suwonSamsung],
        2001: [_clubName.suwonSamsung],
        2000: [],
      };
    }
    if(leagueName == LeagueOfficialNames().africa){
      champions = {
        2021: [_clubName.alahly,_clubName.kaizer,_clubName.esperance,_clubName.wydad],
        2020: [_clubName.alahly,_clubName.zamalek,_clubName.rajacasablanca,_clubName.wydad],
        2019: [_clubName.esperance,_clubName.wydad,_clubName.mazembe,_clubName.mamelodi],
        2018: [_clubName.esperance,_clubName.alahly,_clubName.agosto],
        2017: [_clubName.wydad,_clubName.alahly],
        2016: [_clubName.mamelodi,_clubName.zamalek],
        2015: [_clubName.mazembe],
        2014: [],
        2013: [_clubName.alahly,_clubName.orlandoPirates],
        2012: [_clubName.alahly,_clubName.esperance],
        2011: [_clubName.esperance,_clubName.wydad],
        2010: [_clubName.mazembe,_clubName.esperance],
        2009: [_clubName.mazembe],
        2008: [_clubName.alahly],
        2007: [],
        2006: [_clubName.alahly],
        2005: [_clubName.alahly],
        2004: [],
        2003: [],
        2002: [_clubName.zamalek],
        2001: [_clubName.alahly],
        2000: [],
      };
    }
    if(leagueName == LeagueOfficialNames().outros){
      champions = {
        2021: [],
        2020: [],
        2019: [],
        2018: [],
        2017: [],
        2016: [],
        2015: [],
        2014: [],
        2013: [],
        2012: [],
        2011: [],
        2010: [],
        2009: [],
        2008: [],
        2007: [],
        2006: [],
        2005: [],
        2004: [],
        2003: [],
        2002: [],
        2001: [],
        2000: [],
      };
    }
    return champions;
  }
