import 'package:fifa/values/club_names.dart';
import 'package:fifa/values/league_names.dart';


ClubName _clubName = ClubName();

  Map mapChampions(String leagueName){
    Map champions = {};
    if(leagueName == LeagueOfficialNames().inglaterra1){
      champions = {
        2021: [_clubName.manchestercity,_clubName.manchesterunited,_clubName.liverpool,_clubName.chelsea,_clubName.leicester,_clubName.westham,_clubName.tottenham,_clubName.arsenal,_clubName.everton,_clubName.leedsunited,_clubName.astonvilla,_clubName.newcastle,_clubName.wolves,_clubName.crystalpalace,_clubName.southampton,_clubName.brighton],
        2020: [_clubName.liverpool,_clubName.manchestercity,_clubName.manchesterunited,_clubName.chelsea,_clubName.leicester,_clubName.tottenham,_clubName.wolves,_clubName.arsenal,_clubName.sheffieldunited,_clubName.burnley,_clubName.southampton,_clubName.everton,_clubName.newcastle,_clubName.crystalpalace,_clubName.brighton,_clubName.westham],
        2019: [_clubName.manchestercity,_clubName.liverpool,_clubName.chelsea,_clubName.tottenham,_clubName.arsenal,_clubName.manchesterunited],
        2018: [_clubName.manchestercity,_clubName.manchesterunited,_clubName.tottenham,_clubName.liverpool,_clubName.chelsea,_clubName.arsenal],
        2017: [_clubName.chelsea,_clubName.tottenham,_clubName.manchestercity,_clubName.liverpool,_clubName.chelsea,_clubName.arsenal],
        2016: [_clubName.leicester,_clubName.arsenal,_clubName.tottenham,_clubName.manchestercity,_clubName.manchesterunited,_clubName.tottenham],
        2015: [_clubName.chelsea,_clubName.manchestercity,_clubName.arsenal,_clubName.manchesterunited,_clubName.tottenham,_clubName.liverpool],
        2014: [_clubName.manchestercity,_clubName.liverpool,_clubName.chelsea,_clubName.arsenal,_clubName.everton,_clubName.tottenham],
        2013: [_clubName.manchesterunited,_clubName.manchestercity,_clubName.chelsea,_clubName.arsenal,_clubName.tottenham,_clubName.everton],
        2012: [_clubName.manchestercity,_clubName.manchesterunited,_clubName.arsenal,_clubName.tottenham,_clubName.newcastle,_clubName.chelsea],
        2011: [_clubName.manchesterunited,_clubName.chelsea,_clubName.manchestercity,_clubName.arsenal,_clubName.tottenham,_clubName.liverpool],
        2010: [_clubName.chelsea,_clubName.manchesterunited,_clubName.arsenal,_clubName.tottenham,_clubName.manchestercity,_clubName.astonvilla],
        2009: [_clubName.manchesterunited,_clubName.liverpool,_clubName.chelsea,_clubName.arsenal,_clubName.everton,_clubName.astonvilla],
        2008: [_clubName.manchesterunited,_clubName.chelsea,_clubName.arsenal,_clubName.liverpool,_clubName.everton,_clubName.astonvilla],
        2007: [_clubName.manchesterunited,_clubName.chelsea,_clubName.liverpool,_clubName.arsenal,_clubName.tottenham,_clubName.everton],
        2006: [_clubName.chelsea,_clubName.manchesterunited,_clubName.liverpool,_clubName.arsenal,_clubName.tottenham,_clubName.blackburn],
        2005: [_clubName.chelsea,_clubName.arsenal,_clubName.manchesterunited,_clubName.everton,_clubName.liverpool,_clubName.bolton,_clubName.middlesbrough,_clubName.manchestercity,_clubName.tottenham,_clubName.astonvilla],
        2004: [_clubName.arsenal,_clubName.chelsea,_clubName.manchesterunited,_clubName.liverpool,_clubName.newcastle,_clubName.astonvilla,_clubName.charlton,_clubName.bolton,_clubName.fulham,_clubName.birmigham],
        2003: [_clubName.manchesterunited,_clubName.arsenal,_clubName.newcastle,_clubName.chelsea,_clubName.liverpool,_clubName.blackburn,_clubName.everton,_clubName.southampton,_clubName.manchestercity,_clubName.tottenham],
        2002: [_clubName.arsenal,_clubName.liverpool,_clubName.manchesterunited,_clubName.newcastle,_clubName.leedsunited,_clubName.chelsea,_clubName.westham,_clubName.astonvilla,_clubName.tottenham,_clubName.blackburn],
        2001: [_clubName.manchesterunited,_clubName.arsenal,_clubName.liverpool,_clubName.leedsunited,_clubName.ipswichTown,_clubName.chelsea,_clubName.sunderland,_clubName.astonvilla,_clubName.charlton,_clubName.southampton],
        2000: [_clubName.manchesterunited,_clubName.arsenal],
        1999: [_clubName.manchesterunited,_clubName.arsenal],
        1998: [_clubName.arsenal,_clubName.manchesterunited],
        1997: [_clubName.manchesterunited,_clubName.newcastle],
        1996: [_clubName.manchesterunited,_clubName.newcastle],
        1995: [_clubName.blackburn,_clubName.manchesterunited],
        1994: [_clubName.manchesterunited,_clubName.blackburn],
        1993: [_clubName.manchesterunited,_clubName.astonvilla],
        1992: [],
        1991: [],
      };
    }
    if(leagueName == LeagueOfficialNames().inglaterra2){
      champions = {
        2021: [_clubName.norwich,_clubName.watford],
        2020: [_clubName.leedsunited,_clubName.westbromwich],
        2019: [_clubName.norwich,_clubName.sheffieldunited],
        2018: [_clubName.wolves],
        2017: [_clubName.newcastle,_clubName.brighton],
        2016: [_clubName.burnley,_clubName.middlesbrough],
        2015: [_clubName.bournemouth,_clubName.watford],
        2014: [_clubName.leicester,_clubName.burnley],
        2013: [],
        2012: [_clubName.reading,_clubName.southampton],
        2011: [_clubName.qpr,_clubName.norwich],
        2010: [_clubName.newcastle,_clubName.westbromwich],
        2009: [_clubName.wolves,_clubName.birmigham],
        2008: [_clubName.westbromwich,_clubName.stoke],
        2007: [_clubName.sunderland,_clubName.birmigham],
        2006: [_clubName.reading,_clubName.sheffieldunited],
        2005: [_clubName.sunderland],
        2004: [_clubName.norwich,_clubName.westbromwich],
        2003: [_clubName.portsmouth,_clubName.leicester],
        2002: [_clubName.manchestercity,_clubName.westbromwich],
        2001: [_clubName.fulham,_clubName.blackburn],
        2000: [],
        1999: [],
        1998: [],
        1997: [],
        1996: [],
        1995: [],
        1994: [],
        1993: [],
        1992: [],
        1991: [],
      };
    }
    if(leagueName == LeagueOfficialNames().espanha1){
      champions = {
        //2022: [_clubName.realmadrid,_clubName.sevilla],
        2021: [_clubName.atleticomadrid,_clubName.realmadrid,_clubName.barcelona,_clubName.sevilla,_clubName.realsociedad,_clubName.realbetis,_clubName.villareal,_clubName.athleticbilbao],
        2020: [_clubName.realmadrid,_clubName.barcelona,_clubName.atleticomadrid,_clubName.sevilla,_clubName.villareal,_clubName.realsociedad],
        2019: [_clubName.barcelona,_clubName.atleticomadrid,_clubName.realmadrid,_clubName.valencia,_clubName.getafe,_clubName.realsociedad],
        2018: [_clubName.barcelona,_clubName.atleticomadrid,_clubName.realmadrid,_clubName.valencia,_clubName.villareal,_clubName.realbetis],
        2017: [_clubName.realmadrid,_clubName.barcelona,_clubName.atleticomadrid,_clubName.sevilla,_clubName.villareal,_clubName.realsociedad],
        2016: [_clubName.barcelona,_clubName.realmadrid,_clubName.atleticomadrid,_clubName.villareal,_clubName.athleticbilbao,_clubName.celtavigo],
        2015: [_clubName.barcelona,_clubName.realmadrid,_clubName.atleticomadrid,_clubName.valencia,_clubName.sevilla,_clubName.villareal],
        2014: [_clubName.atleticomadrid,_clubName.barcelona,_clubName.realmadrid,_clubName.athleticbilbao,_clubName.sevilla,_clubName.villareal],
        2013: [_clubName.barcelona,_clubName.realmadrid,_clubName.atleticomadrid,_clubName.realsociedad],
        2012: [_clubName.realmadrid,_clubName.barcelona,_clubName.valencia,_clubName.malaga,_clubName.atleticomadrid,_clubName.levante],
        2011: [_clubName.barcelona,_clubName.realmadrid,_clubName.valencia,_clubName.villareal,_clubName.sevilla,_clubName.athleticbilbao],
        2010: [_clubName.barcelona,_clubName.realmadrid,_clubName.valencia,_clubName.sevilla,_clubName.mallorca,_clubName.getafe],
        2009: [_clubName.barcelona,_clubName.realmadrid,_clubName.sevilla,_clubName.atleticomadrid,_clubName.villareal,_clubName.valencia],
        2008: [_clubName.realmadrid,_clubName.villareal,_clubName.barcelona,_clubName.atleticomadrid,_clubName.sevilla],
        2007: [_clubName.realmadrid,_clubName.barcelona,_clubName.sevilla,_clubName.valencia,_clubName.villareal,_clubName.zaragoza],
        2006: [_clubName.barcelona,_clubName.realmadrid,_clubName.valencia,_clubName.osasuna,_clubName.sevilla,_clubName.celtavigo],
        2005: [_clubName.barcelona,_clubName.realmadrid,_clubName.villareal,_clubName.realbetis,_clubName.espanyol,_clubName.sevilla],
        2004: [_clubName.valencia,_clubName.barcelona,_clubName.lacoruna,_clubName.realmadrid,_clubName.athleticbilbao,_clubName.sevilla],
        2003: [_clubName.realmadrid,_clubName.realsociedad,_clubName.lacoruna,_clubName.celtavigo,_clubName.valencia,_clubName.barcelona],
        2002: [_clubName.valencia,_clubName.lacoruna,_clubName.realmadrid,_clubName.barcelona,_clubName.celtavigo,_clubName.realbetis],
        2001: [_clubName.realmadrid,_clubName.lacoruna,_clubName.mallorca,_clubName.barcelona,_clubName.valencia,_clubName.celtavigo],
        2000: [_clubName.lacoruna,_clubName.barcelona,_clubName.valencia],
        1999: [_clubName.barcelona,_clubName.realmadrid,_clubName.mallorca],
        1998: [_clubName.barcelona,_clubName.athleticbilbao,_clubName.realsociedad],
        1997: [_clubName.realmadrid,_clubName.lacoruna,_clubName.zaragoza],
        1996: [_clubName.atleticomadrid,_clubName.valencia,_clubName.barcelona],
        1995: [_clubName.realmadrid,_clubName.lacoruna,_clubName.realbetis],
        1994: [_clubName.barcelona,_clubName.lacoruna,_clubName.zaragoza],
        1993: [_clubName.barcelona,_clubName.realmadrid,_clubName.lacoruna],
        1992: [_clubName.barcelona,_clubName.realmadrid,_clubName.atleticomadrid],
        1991: [_clubName.barcelona,_clubName.atleticomadrid,_clubName.realmadrid],
        1990: [_clubName.realmadrid,_clubName.barcelona,_clubName.valencia],
      };
    }
    if(leagueName == LeagueOfficialNames().italia1){
      champions = {
        2021: [_clubName.inter,_clubName.milan,_clubName.atalanta,_clubName.juventus,_clubName.napoli,_clubName.lazio,_clubName.roma,_clubName.sassuolo,_clubName.sampdoria],
        2020: [_clubName.juventus,_clubName.inter,_clubName.lazio,_clubName.atalanta,_clubName.roma],
        2019: [_clubName.juventus,_clubName.napoli,_clubName.atalanta,_clubName.inter,_clubName.milan],
        2018: [_clubName.juventus,_clubName.napoli,_clubName.roma,_clubName.inter,_clubName.lazio],
        2017: [_clubName.juventus,_clubName.roma,_clubName.napoli,_clubName.atalanta,_clubName.lazio],
        2016: [_clubName.juventus,_clubName.napoli,_clubName.roma,_clubName.inter,_clubName.fiorentina],
        2015: [_clubName.juventus,_clubName.roma,_clubName.lazio,_clubName.fiorentina,_clubName.napoli],
        2014: [_clubName.juventus,_clubName.roma,_clubName.napoli,_clubName.fiorentina,_clubName.inter],
        2013: [_clubName.juventus,_clubName.napoli,_clubName.milan,_clubName.fiorentina,_clubName.udinese],
        2012: [_clubName.juventus,_clubName.milan,_clubName.udinese,_clubName.lazio,_clubName.napoli],
        2011: [_clubName.milan,_clubName.inter,_clubName.napoli,_clubName.udinese,_clubName.lazio],
        2010: [_clubName.inter,_clubName.roma,_clubName.milan,_clubName.sampdoria],
        2009: [_clubName.inter,_clubName.juventus,_clubName.milan,_clubName.fiorentina,_clubName.genoa],
        2008: [_clubName.inter,_clubName.roma,_clubName.juventus,_clubName.fiorentina,_clubName.milan],
        2007: [_clubName.inter,_clubName.roma,_clubName.lazio,_clubName.milan],
        2006: [_clubName.inter,_clubName.roma,_clubName.milan],
        2005: [],
        2004: [_clubName.milan,_clubName.roma,_clubName.juventus,_clubName.inter,_clubName.parma],
        2003: [_clubName.juventus,_clubName.inter,_clubName.milan,_clubName.lazio,_clubName.parma],
        2002: [_clubName.juventus,_clubName.roma,_clubName.inter,_clubName.milan],
        2001: [_clubName.roma,_clubName.juventus,_clubName.lazio,_clubName.parma,_clubName.inter],
        2000: [_clubName.lazio,_clubName.juventus,_clubName.milan,_clubName.inter],
        1999: [_clubName.milan,_clubName.lazio],
        1998: [_clubName.juventus,_clubName.inter],
        1997: [_clubName.juventus,_clubName.parma],
        1996: [_clubName.milan,_clubName.juventus],
        1995: [_clubName.juventus,_clubName.lazio],
        1994: [_clubName.milan,_clubName.juventus],
        1993: [_clubName.milan,_clubName.inter],
        1992: [_clubName.milan,_clubName.juventus],
        1991: [_clubName.sampdoria,_clubName.milan],
        1990: [_clubName.napoli,_clubName.milan],
        1989: [_clubName.inter,_clubName.napoli],
        1988: [_clubName.milan,_clubName.napoli],
        1987: [_clubName.napoli,_clubName.juventus],
        1986: [_clubName.juventus,_clubName.roma],
        1985: [_clubName.hellasVerona,_clubName.torino],
        1984: [_clubName.juventus,_clubName.roma],
      };
    }
    if(leagueName == LeagueOfficialNames().alemanha1){
      champions = {
        2021: [_clubName.bayernmunique,_clubName.rbleipzig,_clubName.borussiadortmund,_clubName.wolfsburg,_clubName.eintrachtfrankfurt,_clubName.bayerleverkusen],
        2020: [_clubName.bayernmunique,_clubName.borussiadortmund,_clubName.rbleipzig,_clubName.moenchengladbach,_clubName.bayerleverkusen,_clubName.hoffenheim],
        2019: [_clubName.bayernmunique,_clubName.borussiadortmund,_clubName.rbleipzig,_clubName.bayerleverkusen,_clubName.moenchengladbach,_clubName.wolfsburg],
        2018: [_clubName.bayernmunique,_clubName.schalke04,_clubName.hoffenheim,_clubName.borussiadortmund,_clubName.bayerleverkusen,_clubName.rbleipzig],
        2017: [_clubName.bayernmunique,_clubName.rbleipzig,_clubName.borussiadortmund,_clubName.hoffenheim,_clubName.colonia,_clubName.herthaberlim],
        2016: [_clubName.bayernmunique,_clubName.borussiadortmund,_clubName.bayerleverkusen,_clubName.moenchengladbach,_clubName.schalke04,_clubName.mainz05],
        2015: [_clubName.bayernmunique,_clubName.wolfsburg,_clubName.moenchengladbach,_clubName.bayerleverkusen,_clubName.augsburg,_clubName.schalke04],
        2014: [_clubName.bayernmunique,_clubName.borussiadortmund,_clubName.schalke04,_clubName.bayerleverkusen,_clubName.wolfsburg,_clubName.moenchengladbach],
        2013: [_clubName.bayernmunique,_clubName.borussiadortmund,_clubName.bayerleverkusen,_clubName.schalke04,_clubName.freiburg,_clubName.eintrachtfrankfurt],
        2012: [_clubName.borussiadortmund,_clubName.bayernmunique,_clubName.schalke04,_clubName.moenchengladbach,_clubName.bayerleverkusen,_clubName.stuttgart],
        2011: [_clubName.borussiadortmund,_clubName.bayerleverkusen,_clubName.bayernmunique,_clubName.hannover96,_clubName.mainz05,_clubName.nurnberg],
        2010: [_clubName.bayernmunique,_clubName.schalke04,_clubName.werderbremen,_clubName.bayerleverkusen,_clubName.borussiadortmund,_clubName.stuttgart],
        2009: [_clubName.wolfsburg,_clubName.bayernmunique,_clubName.stuttgart,_clubName.herthaberlim,_clubName.hamburgo,_clubName.borussiadortmund],
        2008: [_clubName.bayernmunique,_clubName.werderbremen,_clubName.schalke04,_clubName.hamburgo,_clubName.wolfsburg,_clubName.stuttgart],
        2007: [_clubName.stuttgart,_clubName.schalke04,_clubName.werderbremen,_clubName.bayernmunique,_clubName.hamburgo,_clubName.nurnberg],
        2006: [_clubName.bayernmunique,_clubName.werderbremen,_clubName.hamburgo,_clubName.schalke04,_clubName.bayerleverkusen,_clubName.herthaberlim],
        2005: [_clubName.bayernmunique,_clubName.schalke04,_clubName.werderbremen,_clubName.herthaberlim,_clubName.stuttgart,_clubName.bayerleverkusen],
        2004: [_clubName.werderbremen,_clubName.bayernmunique,_clubName.bayerleverkusen,_clubName.stuttgart],
        2003: [_clubName.bayernmunique,_clubName.stuttgart,_clubName.borussiadortmund,_clubName.hamburgo,_clubName.herthaberlim,_clubName.werderbremen],
        2002: [_clubName.borussiadortmund,_clubName.bayerleverkusen,_clubName.bayernmunique,_clubName.herthaberlim,_clubName.schalke04,_clubName.werderbremen],
        2001: [_clubName.bayernmunique,_clubName.schalke04,_clubName.borussiadortmund,_clubName.bayerleverkusen,_clubName.herthaberlim,_clubName.freiburg],
        2000: [],
      };
    }
    if(leagueName == LeagueOfficialNames().franca1){
      champions = {
        2021: [_clubName.lille,_clubName.psg,_clubName.monaco,_clubName.lyon],
        2020: [_clubName.psg,_clubName.olympiquemarselha,_clubName.rennes,_clubName.lille],
        2019: [_clubName.psg,_clubName.lille,_clubName.lyon,_clubName.saintetienne],
        2018: [_clubName.psg,_clubName.monaco,_clubName.lyon,_clubName.olympiquemarselha],
        2017: [_clubName.monaco,_clubName.psg,_clubName.nice,_clubName.lyon],
        2016: [_clubName.psg,_clubName.lyon,_clubName.monaco,_clubName.nice],
        2015: [_clubName.psg,_clubName.lyon,_clubName.monaco,_clubName.olympiquemarselha],
        2014: [_clubName.psg,_clubName.monaco,_clubName.lille,_clubName.saintetienne],
        2013: [_clubName.psg,_clubName.olympiquemarselha,_clubName.lyon,_clubName.nice],
        2012: [_clubName.montpellier,_clubName.psg,_clubName.lille,_clubName.lyon],
        2011: [_clubName.lille,_clubName.olympiquemarselha,_clubName.lyon,_clubName.psg],
        2010: [_clubName.olympiquemarselha,_clubName.lyon,_clubName.auxerre,_clubName.lille],
        2009: [_clubName.bordeaux,_clubName.olympiquemarselha,_clubName.lyon,_clubName.toulouse],
        2008: [_clubName.lyon,_clubName.bordeaux,_clubName.olympiquemarselha],
        2007: [_clubName.lyon,_clubName.olympiquemarselha,_clubName.toulouse,_clubName.rennes],
        2006: [_clubName.lyon,_clubName.bordeaux,_clubName.lille,_clubName.lens],
        2005: [_clubName.lyon,_clubName.lille,_clubName.monaco,_clubName.rennes],
        2004: [_clubName.lyon,_clubName.psg,_clubName.monaco,_clubName.auxerre],
        2003: [_clubName.lyon,_clubName.monaco,_clubName.olympiquemarselha,_clubName.bordeaux],
        2002: [_clubName.lyon,_clubName.lens,_clubName.auxerre,_clubName.psg],
        2001: [_clubName.nantes,_clubName.lyon,_clubName.lille,_clubName.bordeaux],
        2000: [_clubName.monaco,_clubName.psg,_clubName.lyon,_clubName.bordeaux,_clubName.lens],
        1999: [_clubName.bordeaux,_clubName.olympiquemarselha,_clubName.lyon,_clubName.monaco,_clubName.rennes],
        1998: [_clubName.lens,_clubName.metz,_clubName.monaco,_clubName.olympiquemarselha,_clubName.bordeaux],
        1997: [_clubName.monaco,_clubName.psg,_clubName.nantes,_clubName.bordeaux,_clubName.metz,_clubName.auxerre],
        1996: [],
        1995: [],
      };
    }
    if(leagueName == LeagueOfficialNames().brasil1){
      champions = {
        2021: [_clubName.atleticomg,_clubName.flamengo,_clubName.palmeiras,_clubName.fortaleza,_clubName.corinthians,_clubName.bragantino,_clubName.fluminense,_clubName.americamg,_clubName.atleticogo,_clubName.santos],
        2020: [_clubName.flamengo,_clubName.internacional,_clubName.atleticomg,_clubName.saopaulo,_clubName.fluminense,_clubName.palmeiras,_clubName.gremio,_clubName.santos,_clubName.atleticopr,_clubName.bragantino],
        2019: [_clubName.flamengo,_clubName.santos,_clubName.palmeiras,_clubName.gremio,_clubName.atleticopr,_clubName.saopaulo,_clubName.internacional,_clubName.corinthians,_clubName.fortaleza,_clubName.goias],
        2018: [_clubName.palmeiras,_clubName.flamengo,_clubName.internacional,_clubName.gremio,_clubName.saopaulo,_clubName.atleticomg,_clubName.atleticopr,_clubName.cruzeiro,_clubName.botafogo,_clubName.santos],
        2017: [_clubName.corinthians,_clubName.palmeiras,_clubName.gremio,_clubName.santos,_clubName.cruzeiro,_clubName.flamengo],
        2016: [_clubName.palmeiras,_clubName.flamengo,_clubName.santos,_clubName.atleticomg,_clubName.botafogo,_clubName.atleticopr],
        2015: [_clubName.corinthians,_clubName.atleticomg,_clubName.gremio,_clubName.saopaulo,_clubName.internacional,_clubName.sport],
        2014: [_clubName.cruzeiro,_clubName.saopaulo,_clubName.internacional,_clubName.corinthians,_clubName.atleticomg,_clubName.botafogo],
        2013: [_clubName.cruzeiro,_clubName.gremio,_clubName.atleticopr,_clubName.botafogo,_clubName.vitoria,_clubName.goias],
        2012: [_clubName.fluminense,_clubName.atleticomg,_clubName.gremio,_clubName.saopaulo,_clubName.vasco,_clubName.corinthians],
        2011: [_clubName.corinthians,_clubName.vasco,_clubName.fluminense,_clubName.flamengo,_clubName.internacional,_clubName.saopaulo],
        2010: [_clubName.fluminense,_clubName.cruzeiro,_clubName.corinthians,_clubName.gremio,_clubName.atleticopr,_clubName.botafogo],
        2009: [_clubName.flamengo,_clubName.internacional,_clubName.saopaulo,_clubName.cruzeiro],
        2008: [_clubName.saopaulo,_clubName.gremio,_clubName.cruzeiro,_clubName.palmeiras],
        2007: [_clubName.saopaulo,_clubName.santos,_clubName.flamengo,_clubName.fluminense],
        2006: [_clubName.saopaulo,_clubName.internacional,_clubName.gremio,_clubName.santos],
        2005: [_clubName.corinthians,_clubName.internacional,_clubName.goias,_clubName.palmeiras],
        2004: [_clubName.santos,_clubName.atleticopr,_clubName.saopaulo,_clubName.palmeiras],
        2003: [_clubName.cruzeiro,_clubName.santos,_clubName.saopaulo,_clubName.saocaetano],
        2002: [_clubName.santos,_clubName.corinthians,_clubName.gremio,_clubName.fluminense],
        2001: [_clubName.atleticopr,_clubName.saocaetano,_clubName.fluminense,_clubName.atleticomg],
        2000: [_clubName.vasco,_clubName.saocaetano,_clubName.cruzeiro,_clubName.gremio],
        1999: [_clubName.corinthians,_clubName.atleticomg,_clubName.vitoria,_clubName.saopaulo],
        1998: [_clubName.corinthians,_clubName.cruzeiro,_clubName.santos,_clubName.portuguesa],
        1997: [_clubName.vasco,_clubName.palmeiras,_clubName.internacional,_clubName.atleticomg],
        1996: [_clubName.gremio,_clubName.portuguesa,_clubName.atleticomg,_clubName.goias],
        1995: [_clubName.botafogo,_clubName.santos,_clubName.cruzeiro,_clubName.fluminense],
        1994: [_clubName.palmeiras,_clubName.corinthians,_clubName.guarani,_clubName.atleticomg],
        1993: [_clubName.palmeiras,_clubName.vitoria,_clubName.corinthians,_clubName.saopaulo],
        1992: [_clubName.flamengo,_clubName.botafogo,_clubName.vasco,_clubName.bragantino],
        1991: [_clubName.saopaulo,_clubName.bragantino,_clubName.atleticomg,_clubName.fluminense],
        1990: [_clubName.corinthians,_clubName.saopaulo,_clubName.gremio,_clubName.bahia],
        1989: [_clubName.vasco,_clubName.saopaulo,_clubName.cruzeiro,_clubName.botafogo],
        1988: [_clubName.bahia,_clubName.internacional,_clubName.fluminense,_clubName.gremio],
        1987: [_clubName.sport,_clubName.guarani,_clubName.flamengo,_clubName.internacional],
        1986: [_clubName.saopaulo,_clubName.guarani,_clubName.atleticomg],
        1985: [_clubName.coritiba,_clubName.bangu,_clubName.brasilPelotas,_clubName.atleticomg],
        1984: [_clubName.fluminense,_clubName.vasco,_clubName.gremio,_clubName.corinthians],
        1983: [_clubName.flamengo,_clubName.santos,_clubName.atleticopr,_clubName.atleticomg],
        1982: [_clubName.flamengo,_clubName.gremio,_clubName.guarani,_clubName.corinthians],
        1981: [_clubName.gremio,_clubName.saopaulo,_clubName.pontepreta,_clubName.botafogo],
        1980: [_clubName.flamengo,_clubName.atleticomg,_clubName.internacional,_clubName.coritiba],
        1979: [_clubName.internacional,_clubName.vasco,_clubName.coritiba,_clubName.palmeiras],
        1978: [_clubName.guarani,_clubName.palmeiras,_clubName.internacional,_clubName.vasco],
        1977: [_clubName.saopaulo,_clubName.atleticomg,_clubName.operarioms,_clubName.londrina],
        1976: [_clubName.internacional,_clubName.corinthians,_clubName.atleticomg,_clubName.fluminense],
        1975: [_clubName.internacional,_clubName.cruzeiro,_clubName.fluminense,_clubName.santacruz],
        1974: [_clubName.vasco,_clubName.cruzeiro,_clubName.santos,_clubName.internacional],
        1973: [_clubName.palmeiras,_clubName.saopaulo,_clubName.cruzeiro,_clubName.internacional],
        1972: [_clubName.palmeiras,_clubName.botafogo,_clubName.internacional,_clubName.corinthians],
        1971: [_clubName.atleticomg,_clubName.saopaulo,_clubName.botafogo,_clubName.corinthians],
        1970: [_clubName.fluminense,_clubName.palmeiras,_clubName.atleticomg,_clubName.cruzeiro],
        1969: [_clubName.palmeiras,_clubName.cruzeiro,_clubName.corinthians,_clubName.botafogo],
        1968: [_clubName.santos,_clubName.internacional,_clubName.vasco,_clubName.palmeiras],
        1967: [_clubName.palmeiras,_clubName.internacional,_clubName.corinthians,_clubName.gremio],
      };
    }
    if(leagueName == LeagueOfficialNames().brasil2){
      champions = {
        2021: [_clubName.botafogo,_clubName.goias],
        2020: [_clubName.chapecoense,_clubName.americamg],
        2019: [_clubName.bragantino,_clubName.sport],
        2018: [_clubName.fortaleza,_clubName.csa],
        2017: [_clubName.americamg,_clubName.internacional],
        2016: [_clubName.atleticogo,_clubName.avai],
        2015: [_clubName.botafogo,_clubName.santacruz],
        2014: [],
        2013: [_clubName.palmeiras,_clubName.chapecoense],
        2012: [_clubName.goias,_clubName.criciuma],
        2011: [_clubName.portuguesa,_clubName.nautico],
        2010: [_clubName.coritiba,_clubName.figueirense],
        2009: [_clubName.vasco,_clubName.guarani],
        2008: [_clubName.corinthians],
        2007: [_clubName.coritiba],
        2006: [_clubName.atleticomg,_clubName.sport],
        2005: [_clubName.gremio,_clubName.santacruz],
        2004: [],
        2003: [_clubName.palmeiras,_clubName.botafogo],
        2002: [_clubName.criciuma,_clubName.fortaleza],
        2001: [_clubName.paysandu,_clubName.figueirense],
        2000: [_clubName.parana],
      };
    }
    if(leagueName == LeagueOfficialNames().brasil3){
      champions = {
        2021: [_clubName.ituano],
        2020: [_clubName.vilaNova],
        2019: [_clubName.nautico],
        2018: [_clubName.operarioPR],
        2017: [_clubName.csa],
        2016: [],
        2015: [_clubName.vilaNova],
        2014: [],
        2013: [_clubName.santacruz],
        2012: [],
        2011: [],
        2010: [_clubName.abc],
        2009: [],
        2008: [_clubName.atleticogo],
        2007: [_clubName.bragantino],
        2006: [_clubName.criciuma],
        2005: [_clubName.remo],
        2004: [],
        2003: [_clubName.ituano],
        2002: [],
        2001: [],
        2000: [],
        1999: [_clubName.fluminense],
        1998: [_clubName.avai],
        1997: [_clubName.sampaio],
      };
    }
    if(leagueName == LeagueOfficialNames().argentina){
      champions = {
        2021: [_clubName.riverplate,_clubName.defensayjusticia,_clubName.talleres,_clubName.bocajuniors],
        2020: [_clubName.bocajuniors,_clubName.riverplate,_clubName.velezsarsfield,_clubName.racing],
        2019: [_clubName.racing,_clubName.defensayjusticia,_clubName.bocajuniors,_clubName.riverplate],
        2018: [_clubName.bocajuniors],
        2017: [_clubName.bocajuniors,_clubName.riverplate],
        2016: [_clubName.lanus,_clubName.sanlorenzo],
        2015: [_clubName.bocajuniors,_clubName.sanlorenzo],
        2014: [_clubName.racing,_clubName.riverplate],
        2013: [],
        2012: [],
        2011: [],
        2010: [],
        2009: [],
        2008: [],
        2007: [],
        2006: [],
        2005: [],
        2004: [],
        2003: [],
        2002: [],
        2001: [],
        2000: [],
      };
    }

    if(leagueName == LeagueOfficialNames().estadosUnidos){
      champions = {
        2021: [_clubName.nycity,_clubName.portland],
        2020: [_clubName.columbuscrew,_clubName.seattle],
        2019: [_clubName.seattle,_clubName.torontofc],
        2018: [_clubName.atlantaunited,_clubName.portland],
        2017: [_clubName.torontofc,_clubName.seattle],
        2016: [_clubName.seattle,_clubName.torontofc],
        2015: [_clubName.portland,_clubName.columbuscrew],
        2014: [_clubName.lagalaxy,_clubName.nerevolution],
        2013: [],
        2012: [_clubName.lagalaxy],
        2011: [_clubName.lagalaxy],
        2010: [],
        2009: [],
        2008: [_clubName.columbuscrew],
        2007: [],
        2006: [],
        2005: [_clubName.lagalaxy,_clubName.nerevolution],
        2004: [_clubName.dcunited],
        2003: [],
        2002: [],
        2001: [],
        2000: [],
      };
    }
    if(leagueName == LeagueOfficialNames().asia){
      champions = {
        2021: [_clubName.alhilal,_clubName.pohang,_clubName.alnassr],
        2020: [_clubName.ulsan,_clubName.persepolis,_clubName.alnassr],
        2019: [_clubName.alhilal,_clubName.urawareddiamonds,_clubName.alsadd],
        2018: [_clubName.kashimaantlers,_clubName.persepolis,_clubName.suwonSamsung],
        2017: [_clubName.urawareddiamonds,_clubName.alhilal,_clubName.shanghaisipg],
        2016: [_clubName.jeonbuk,_clubName.alain],
        2015: [_clubName.ghuagzhouevergrande,_clubName.alahli,_clubName.alhilal],
        2014: [_clubName.sydneyWanderers,_clubName.alhilal,_clubName.alain],
        2013: [_clubName.ghuagzhouevergrande,_clubName.fcSeoul,_clubName.esteghlal],
        2012: [_clubName.ulsan,_clubName.alahli],
        2011: [_clubName.alsadd,_clubName.jeonbuk],
        2010: [_clubName.seognam,_clubName.zobAhan],
        2009: [_clubName.pohang,_clubName.alIttihad],
        2008: [_clubName.gambaOsaka],
        2007: [_clubName.urawareddiamonds,_clubName.sepahan],
        2006: [_clubName.jeonbuk],
        2005: [_clubName.alIttihad,_clubName.alain],
        2004: [_clubName.alIttihad,_clubName.seognam],
        2003: [_clubName.alain],
        2002: [_clubName.suwonSamsung,_clubName.fcSeoul],
        2001: [_clubName.suwonSamsung,_clubName.jubiloIwata],
        2000: [_clubName.alhilal,_clubName.jubiloIwata],
        1999: [_clubName.jubiloIwata,_clubName.esteghlal],
        1998: [_clubName.pohang],
        1997: [_clubName.pohang,_clubName.seognam],
        1996: [_clubName.seognam,_clubName.alnassr],
        1995: [_clubName.thai],
        1994: [_clubName.thai],
        1992: [_clubName.alhilal],
        1991: [_clubName.esteghlal],
      };
    }
    if(leagueName == LeagueOfficialNames().africa){
      champions = {
        2021: [_clubName.alahly,_clubName.kaizer,_clubName.esperance,_clubName.wydad],
        2020: [_clubName.alahly,_clubName.zamalek,_clubName.rajacasablanca,_clubName.wydad],
        2019: [_clubName.esperance,_clubName.wydad,_clubName.mazembe,_clubName.mamelodi],
        2018: [_clubName.esperance,_clubName.alahly,_clubName.agosto],
        2017: [_clubName.wydad,_clubName.alahly],
        2016: [_clubName.mamelodi,_clubName.zamalek],
        2015: [_clubName.mazembe,_clubName.usmAlger],
        2014: [_clubName.esSetif,_clubName.vita],
        2013: [_clubName.alahly,_clubName.orlandoPirates],
        2012: [_clubName.alahly,_clubName.esperance],
        2011: [_clubName.esperance,_clubName.wydad],
        2010: [_clubName.mazembe,_clubName.esperance],
        2009: [_clubName.mazembe,_clubName.heartland],
        2008: [_clubName.alahly,_clubName.cotonsport],
        2007: [_clubName.etoileSahel,_clubName.alahly],
        2006: [_clubName.alahly,_clubName.sfaxien],
        2005: [_clubName.alahly,_clubName.etoileSahel],
        2004: [_clubName.enyimba,_clubName.etoileSahel],
        2003: [_clubName.enyimba,_clubName.ismaily],
        2002: [_clubName.zamalek,_clubName.rajacasablanca],
        2001: [_clubName.alahly,_clubName.mamelodi],
        2000: [_clubName.heartsOfOak,_clubName.esperance],
        1999: [_clubName.rajacasablanca,_clubName.esperance],
        1998: [_clubName.asecMimosas],
        1997: [_clubName.rajacasablanca],
        1996: [_clubName.zamalek],
        1995: [_clubName.orlandoPirates,_clubName.asecMimosas],
        1994: [_clubName.esperance,_clubName.zamalek],
        1993: [_clubName.zamalek],
        1992: [_clubName.wydad],
        1991: [_clubName.africain],
        1990: [_clubName.kabylie],
        1989: [_clubName.rajacasablanca],
        1988: [_clubName.esSetif],
        1987: [_clubName.alahly],
        1986: [_clubName.zamalek],
        1985: [_clubName.farRabat],
        1984: [_clubName.zamalek],
        1982: [_clubName.alahly],
        1981: [_clubName.kabylie],
        1969: [_clubName.ismaily],
        1968: [_clubName.mazembe],
        1967: [_clubName.mazembe],
      };
    }
    if(leagueName == LeagueOfficialNames().outros){
      champions = {
        2021: [],
        2020: [],
        2019: [],
        2018: [],
        2017: [],
        2016: [],
        2015: [],
        2014: [],
        2013: [],
        2012: [],
        2011: [],
        2010: [],
        2009: [],
        2008: [],
        2007: [],
        2006: [],
        2005: [],
        2004: [],
        2003: [],
        2002: [],
        2001: [],
        2000: [],
        1999: [],
        1998: [],
        1997: [],
        1996: [],
        1995: [],
        1994: [],
        1993: [],
        1992: [],
        1991: [],
      };
    }
    return champions;
  }
